// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	replay0 "github.com/TakuyaYagam1/task-per-minute/internal/usecase/game/replay"
	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/tournament/admin/replay"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReplayWorkflowRepository creates a new instance of MockReplayWorkflowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplayWorkflowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplayWorkflowRepository {
	mock := &MockReplayWorkflowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReplayWorkflowRepository is an autogenerated mock type for the ReplayWorkflowRepository type
type MockReplayWorkflowRepository struct {
	mock.Mock
}

type MockReplayWorkflowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplayWorkflowRepository) EXPECT() *MockReplayWorkflowRepository_Expecter {
	return &MockReplayWorkflowRepository_Expecter{mock: &_m.Mock}
}

// CommitOperatorReserve provides a mock function for the type MockReplayWorkflowRepository
func (_mock *MockReplayWorkflowRepository) CommitOperatorReserve(ctx context.Context, command replay.ReserveCommand, requestDigest [32]byte, record replay0.OperatorReserve) (*replay0.OperatorReserve, bool, error) {
	ret := _mock.Called(ctx, command, requestDigest, record)

	if len(ret) == 0 {
		panic("no return value specified for CommitOperatorReserve")
	}

	var r0 *replay0.OperatorReserve
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReserveCommand, [32]byte, replay0.OperatorReserve) (*replay0.OperatorReserve, bool, error)); ok {
		return returnFunc(ctx, command, requestDigest, record)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReserveCommand, [32]byte, replay0.OperatorReserve) *replay0.OperatorReserve); ok {
		r0 = returnFunc(ctx, command, requestDigest, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*replay0.OperatorReserve)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, replay.ReserveCommand, [32]byte, replay0.OperatorReserve) bool); ok {
		r1 = returnFunc(ctx, command, requestDigest, record)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, replay.ReserveCommand, [32]byte, replay0.OperatorReserve) error); ok {
		r2 = returnFunc(ctx, command, requestDigest, record)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReplayWorkflowRepository_CommitOperatorReserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitOperatorReserve'
type MockReplayWorkflowRepository_CommitOperatorReserve_Call struct {
	*mock.Call
}

// CommitOperatorReserve is a helper method to define mock.On call
//   - ctx context.Context
//   - command replay.ReserveCommand
//   - requestDigest [32]byte
//   - record replay0.OperatorReserve
func (_e *MockReplayWorkflowRepository_Expecter) CommitOperatorReserve(ctx interface{}, command interface{}, requestDigest interface{}, record interface{}) *MockReplayWorkflowRepository_CommitOperatorReserve_Call {
	return &MockReplayWorkflowRepository_CommitOperatorReserve_Call{Call: _e.mock.On("CommitOperatorReserve", ctx, command, requestDigest, record)}
}

func (_c *MockReplayWorkflowRepository_CommitOperatorReserve_Call) Run(run func(ctx context.Context, command replay.ReserveCommand, requestDigest [32]byte, record replay0.OperatorReserve)) *MockReplayWorkflowRepository_CommitOperatorReserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 replay.ReserveCommand
		if args[1] != nil {
			arg1 = args[1].(replay.ReserveCommand)
		}
		var arg2 [32]byte
		if args[2] != nil {
			arg2 = args[2].([32]byte)
		}
		var arg3 replay0.OperatorReserve
		if args[3] != nil {
			arg3 = args[3].(replay0.OperatorReserve)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReplayWorkflowRepository_CommitOperatorReserve_Call) Return(operatorReserve *replay0.OperatorReserve, b bool, err error) *MockReplayWorkflowRepository_CommitOperatorReserve_Call {
	_c.Call.Return(operatorReserve, b, err)
	return _c
}

func (_c *MockReplayWorkflowRepository_CommitOperatorReserve_Call) RunAndReturn(run func(ctx context.Context, command replay.ReserveCommand, requestDigest [32]byte, record replay0.OperatorReserve) (*replay0.OperatorReserve, bool, error)) *MockReplayWorkflowRepository_CommitOperatorReserve_Call {
	_c.Call.Return(run)
	return _c
}

// CommitReplayReplacement provides a mock function for the type MockReplayWorkflowRepository
func (_mock *MockReplayWorkflowRepository) CommitReplayReplacement(ctx context.Context, command replay.ReplayCommand, requestDigest [32]byte, record replay0.ReplayReplacement) (*replay0.ReplayReplacement, bool, error) {
	ret := _mock.Called(ctx, command, requestDigest, record)

	if len(ret) == 0 {
		panic("no return value specified for CommitReplayReplacement")
	}

	var r0 *replay0.ReplayReplacement
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReplayCommand, [32]byte, replay0.ReplayReplacement) (*replay0.ReplayReplacement, bool, error)); ok {
		return returnFunc(ctx, command, requestDigest, record)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReplayCommand, [32]byte, replay0.ReplayReplacement) *replay0.ReplayReplacement); ok {
		r0 = returnFunc(ctx, command, requestDigest, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*replay0.ReplayReplacement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, replay.ReplayCommand, [32]byte, replay0.ReplayReplacement) bool); ok {
		r1 = returnFunc(ctx, command, requestDigest, record)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, replay.ReplayCommand, [32]byte, replay0.ReplayReplacement) error); ok {
		r2 = returnFunc(ctx, command, requestDigest, record)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReplayWorkflowRepository_CommitReplayReplacement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitReplayReplacement'
type MockReplayWorkflowRepository_CommitReplayReplacement_Call struct {
	*mock.Call
}

// CommitReplayReplacement is a helper method to define mock.On call
//   - ctx context.Context
//   - command replay.ReplayCommand
//   - requestDigest [32]byte
//   - record replay0.ReplayReplacement
func (_e *MockReplayWorkflowRepository_Expecter) CommitReplayReplacement(ctx interface{}, command interface{}, requestDigest interface{}, record interface{}) *MockReplayWorkflowRepository_CommitReplayReplacement_Call {
	return &MockReplayWorkflowRepository_CommitReplayReplacement_Call{Call: _e.mock.On("CommitReplayReplacement", ctx, command, requestDigest, record)}
}

func (_c *MockReplayWorkflowRepository_CommitReplayReplacement_Call) Run(run func(ctx context.Context, command replay.ReplayCommand, requestDigest [32]byte, record replay0.ReplayReplacement)) *MockReplayWorkflowRepository_CommitReplayReplacement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 replay.ReplayCommand
		if args[1] != nil {
			arg1 = args[1].(replay.ReplayCommand)
		}
		var arg2 [32]byte
		if args[2] != nil {
			arg2 = args[2].([32]byte)
		}
		var arg3 replay0.ReplayReplacement
		if args[3] != nil {
			arg3 = args[3].(replay0.ReplayReplacement)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReplayWorkflowRepository_CommitReplayReplacement_Call) Return(replayReplacement *replay0.ReplayReplacement, b bool, err error) *MockReplayWorkflowRepository_CommitReplayReplacement_Call {
	_c.Call.Return(replayReplacement, b, err)
	return _c
}

func (_c *MockReplayWorkflowRepository_CommitReplayReplacement_Call) RunAndReturn(run func(ctx context.Context, command replay.ReplayCommand, requestDigest [32]byte, record replay0.ReplayReplacement) (*replay0.ReplayReplacement, bool, error)) *MockReplayWorkflowRepository_CommitReplayReplacement_Call {
	_c.Call.Return(run)
	return _c
}

// LoadOperatorReserveAuthority provides a mock function for the type MockReplayWorkflowRepository
func (_mock *MockReplayWorkflowRepository) LoadOperatorReserveAuthority(ctx context.Context, command replay.ReserveCommand) (replay.OperatorReserveAuthority, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for LoadOperatorReserveAuthority")
	}

	var r0 replay.OperatorReserveAuthority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReserveCommand) (replay.OperatorReserveAuthority, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReserveCommand) replay.OperatorReserveAuthority); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(replay.OperatorReserveAuthority)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, replay.ReserveCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadOperatorReserveAuthority'
type MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call struct {
	*mock.Call
}

// LoadOperatorReserveAuthority is a helper method to define mock.On call
//   - ctx context.Context
//   - command replay.ReserveCommand
func (_e *MockReplayWorkflowRepository_Expecter) LoadOperatorReserveAuthority(ctx interface{}, command interface{}) *MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call {
	return &MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call{Call: _e.mock.On("LoadOperatorReserveAuthority", ctx, command)}
}

func (_c *MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call) Run(run func(ctx context.Context, command replay.ReserveCommand)) *MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 replay.ReserveCommand
		if args[1] != nil {
			arg1 = args[1].(replay.ReserveCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call) Return(operatorReserveAuthority replay.OperatorReserveAuthority, err error) *MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call {
	_c.Call.Return(operatorReserveAuthority, err)
	return _c
}

func (_c *MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call) RunAndReturn(run func(ctx context.Context, command replay.ReserveCommand) (replay.OperatorReserveAuthority, error)) *MockReplayWorkflowRepository_LoadOperatorReserveAuthority_Call {
	_c.Call.Return(run)
	return _c
}

// LoadReplayReplacementAuthority provides a mock function for the type MockReplayWorkflowRepository
func (_mock *MockReplayWorkflowRepository) LoadReplayReplacementAuthority(ctx context.Context, command replay.ReplayCommand) (replay.ReplayReplacementAuthority, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for LoadReplayReplacementAuthority")
	}

	var r0 replay.ReplayReplacementAuthority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReplayCommand) (replay.ReplayReplacementAuthority, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, replay.ReplayCommand) replay.ReplayReplacementAuthority); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(replay.ReplayReplacementAuthority)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, replay.ReplayCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadReplayReplacementAuthority'
type MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call struct {
	*mock.Call
}

// LoadReplayReplacementAuthority is a helper method to define mock.On call
//   - ctx context.Context
//   - command replay.ReplayCommand
func (_e *MockReplayWorkflowRepository_Expecter) LoadReplayReplacementAuthority(ctx interface{}, command interface{}) *MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call {
	return &MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call{Call: _e.mock.On("LoadReplayReplacementAuthority", ctx, command)}
}

func (_c *MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call) Run(run func(ctx context.Context, command replay.ReplayCommand)) *MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 replay.ReplayCommand
		if args[1] != nil {
			arg1 = args[1].(replay.ReplayCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call) Return(replayReplacementAuthority replay.ReplayReplacementAuthority, err error) *MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call {
	_c.Call.Return(replayReplacementAuthority, err)
	return _c
}

func (_c *MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call) RunAndReturn(run func(ctx context.Context, command replay.ReplayCommand) (replay.ReplayReplacementAuthority, error)) *MockReplayWorkflowRepository_LoadReplayReplacementAuthority_Call {
	_c.Call.Return(run)
	return _c
}

// ReadReplayTime provides a mock function for the type MockReplayWorkflowRepository
func (_mock *MockReplayWorkflowRepository) ReadReplayTime(ctx context.Context, commandID uuid.UUID) (time.Time, error) {
	ret := _mock.Called(ctx, commandID)

	if len(ret) == 0 {
		panic("no return value specified for ReadReplayTime")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (time.Time, error)); ok {
		return returnFunc(ctx, commandID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) time.Time); ok {
		r0 = returnFunc(ctx, commandID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commandID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReplayWorkflowRepository_ReadReplayTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadReplayTime'
type MockReplayWorkflowRepository_ReadReplayTime_Call struct {
	*mock.Call
}

// ReadReplayTime is a helper method to define mock.On call
//   - ctx context.Context
//   - commandID uuid.UUID
func (_e *MockReplayWorkflowRepository_Expecter) ReadReplayTime(ctx interface{}, commandID interface{}) *MockReplayWorkflowRepository_ReadReplayTime_Call {
	return &MockReplayWorkflowRepository_ReadReplayTime_Call{Call: _e.mock.On("ReadReplayTime", ctx, commandID)}
}

func (_c *MockReplayWorkflowRepository_ReadReplayTime_Call) Run(run func(ctx context.Context, commandID uuid.UUID)) *MockReplayWorkflowRepository_ReadReplayTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReplayWorkflowRepository_ReadReplayTime_Call) Return(time1 time.Time, err error) *MockReplayWorkflowRepository_ReadReplayTime_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockReplayWorkflowRepository_ReadReplayTime_Call) RunAndReturn(run func(ctx context.Context, commandID uuid.UUID) (time.Time, error)) *MockReplayWorkflowRepository_ReadReplayTime_Call {
	_c.Call.Return(run)
	return _c
}
