-- name: CreateDraftCategoryRevision :one
INSERT INTO category_revisions (
    id,
    series_id,
    roster_id,
    revision,
    source_pool_revision_id,
    mode,
    category_pool,
    selected_categories,
    created_at
)
VALUES (
    sqlc.arg(id),
    sqlc.arg(series_id),
    sqlc.arg(roster_id),
    sqlc.arg(revision),
    sqlc.arg(source_pool_revision_id),
    'draft',
    sqlc.arg(category_pool),
    '[]'::JSONB,
    sqlc.arg(created_at)
)
RETURNING id,
    series_id,
    roster_id,
    revision,
    source_pool_revision_id,
    mode,
    category_pool,
    selected_categories,
    selector_actor_id,
    selection_reason,
    decision_evidence_id,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at;

-- name: CreateDraft :one
INSERT INTO drafts (
    id,
    series_id,
    roster_id,
    category_revision_id,
    first_participant_id,
    second_participant_id,
    format,
    created_at
)
VALUES (
    sqlc.arg(id),
    sqlc.arg(series_id),
    sqlc.arg(roster_id),
    sqlc.arg(category_revision_id),
    sqlc.arg(first_participant_id),
    sqlc.arg(second_participant_id),
    sqlc.arg(format),
    sqlc.arg(created_at)
)
RETURNING id,
    series_id,
    roster_id,
    category_revision_id,
    first_participant_id,
    second_participant_id,
    format,
    created_at;

-- name: CreateInitialDraftRevision :one
INSERT INTO draft_revisions (
    id,
    draft_id,
    series_id,
    roster_id,
    revision,
    previous_revision_id,
    command_id,
    service_epoch,
    state,
    turn_number,
    current_actor_id,
    current_action,
    absolute_deadline,
    paused_remaining_ms,
    recovery_reason,
    recovery_evidence,
    selected_categories,
    decision_evidence_id,
    decision_purpose,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at
)
VALUES (
    sqlc.arg(id),
    sqlc.arg(draft_id),
    sqlc.arg(series_id),
    sqlc.arg(roster_id),
    1,
    NULL,
    sqlc.arg(command_id),
    sqlc.arg(service_epoch),
    'active',
    1,
    sqlc.arg(current_actor_id),
    sqlc.arg(current_action),
    sqlc.arg(absolute_deadline),
    NULL,
    NULL,
    NULL,
    '[]'::JSONB,
    sqlc.arg(decision_evidence_id),
    'draft_order',
    sqlc.arg(decision_algorithm_version),
    sqlc.arg(decision_inputs),
    sqlc.arg(decision_seed),
    sqlc.arg(decision_result),
    sqlc.arg(decision_replay_digest),
    sqlc.arg(decision_owner_id),
    sqlc.arg(decided_at),
    sqlc.arg(created_at)
)
RETURNING id,
    draft_id,
    series_id,
    roster_id,
    revision,
    previous_revision_id,
    command_id,
    service_epoch,
    state,
    turn_number,
    current_actor_id,
    current_action,
    absolute_deadline,
    paused_remaining_ms,
    recovery_reason,
    recovery_evidence,
    selected_categories,
    decision_evidence_id,
    decision_purpose,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at;

-- name: AppendDraftRevisionCAS :one
INSERT INTO draft_revisions (
    id,
    draft_id,
    series_id,
    roster_id,
    revision,
    previous_revision_id,
    command_id,
    service_epoch,
    state,
    turn_number,
    current_actor_id,
    current_action,
    absolute_deadline,
    paused_remaining_ms,
    recovery_reason,
    recovery_evidence,
    selected_categories,
    decision_evidence_id,
    decision_purpose,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at
)
SELECT sqlc.arg(id),
    current_revision.draft_id,
    current_revision.series_id,
    current_revision.roster_id,
    current_revision.revision + 1,
    current_revision.id,
    sqlc.arg(command_id),
    sqlc.arg(service_epoch),
    sqlc.arg(state),
    sqlc.arg(turn_number),
    sqlc.arg(current_actor_id),
    sqlc.narg(current_action)::VARCHAR,
    sqlc.narg(absolute_deadline)::TIMESTAMPTZ,
    sqlc.narg(paused_remaining_ms)::INTEGER,
    sqlc.narg(recovery_reason)::VARCHAR,
    sqlc.narg(recovery_evidence)::JSONB,
    sqlc.arg(selected_categories),
    sqlc.arg(decision_evidence_id),
    sqlc.narg(decision_purpose)::VARCHAR,
    sqlc.narg(decision_algorithm_version)::VARCHAR,
    sqlc.narg(decision_inputs)::JSONB,
    sqlc.arg(decision_seed),
    sqlc.narg(decision_result)::JSONB,
    sqlc.arg(decision_replay_digest),
    sqlc.arg(decision_owner_id),
    sqlc.narg(decided_at)::TIMESTAMPTZ,
    sqlc.arg(created_at)
FROM draft_revisions AS current_revision
WHERE current_revision.id = sqlc.arg(expected_revision_id)
    AND current_revision.draft_id = sqlc.arg(draft_id)
    AND current_revision.revision = sqlc.arg(expected_revision)
    AND current_revision.service_epoch = sqlc.arg(expected_service_epoch)
RETURNING id,
    draft_id,
    series_id,
    roster_id,
    revision,
    previous_revision_id,
    command_id,
    service_epoch,
    state,
    turn_number,
    current_actor_id,
    current_action,
    absolute_deadline,
    paused_remaining_ms,
    recovery_reason,
    recovery_evidence,
    selected_categories,
    decision_evidence_id,
    decision_purpose,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at;

-- name: CreateDraftAction :one
INSERT INTO draft_actions (
    id,
    draft_id,
    result_revision_id,
    command_id,
    turn_number,
    actor_id,
    action,
    category,
    scheduled_deadline,
    occurred_at,
    automatic,
    created_at
)
VALUES (
    sqlc.arg(id),
    sqlc.arg(draft_id),
    sqlc.arg(result_revision_id),
    sqlc.arg(command_id),
    sqlc.arg(turn_number),
    sqlc.arg(actor_id),
    sqlc.arg(action),
    sqlc.arg(category),
    sqlc.arg(scheduled_deadline),
    sqlc.arg(occurred_at),
    sqlc.arg(automatic),
    sqlc.arg(created_at)
)
RETURNING id,
    draft_id,
    result_revision_id,
    command_id,
    turn_number,
    actor_id,
    action,
    category,
    scheduled_deadline,
    occurred_at,
    automatic,
    created_at;

-- name: GetDraft :one
SELECT id,
    series_id,
    roster_id,
    category_revision_id,
    first_participant_id,
    second_participant_id,
    format,
    created_at
FROM drafts
WHERE id = sqlc.arg(id);

-- name: GetDraftCategoryRevision :one
SELECT id,
    series_id,
    roster_id,
    revision,
    source_pool_revision_id,
    mode,
    category_pool,
    selected_categories,
    selector_actor_id,
    selection_reason,
    decision_evidence_id,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at
FROM category_revisions
WHERE id = sqlc.arg(id);

-- name: GetCurrentDraftRevision :one
SELECT id,
    draft_id,
    series_id,
    roster_id,
    revision,
    previous_revision_id,
    command_id,
    service_epoch,
    state,
    turn_number,
    current_actor_id,
    current_action,
    absolute_deadline,
    paused_remaining_ms,
    recovery_reason,
    recovery_evidence,
    selected_categories,
    decision_evidence_id,
    decision_purpose,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at
FROM draft_revisions
WHERE draft_id = sqlc.arg(draft_id)
ORDER BY revision DESC
LIMIT 1;

-- name: ListDraftRevisions :many
SELECT id,
    draft_id,
    series_id,
    roster_id,
    revision,
    previous_revision_id,
    command_id,
    service_epoch,
    state,
    turn_number,
    current_actor_id,
    current_action,
    absolute_deadline,
    paused_remaining_ms,
    recovery_reason,
    recovery_evidence,
    selected_categories,
    decision_evidence_id,
    decision_purpose,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at
FROM draft_revisions
WHERE draft_id = sqlc.arg(draft_id)
ORDER BY revision;

-- name: ListDraftActions :many
SELECT id,
    draft_id,
    result_revision_id,
    command_id,
    turn_number,
    actor_id,
    action,
    category,
    scheduled_deadline,
    occurred_at,
    automatic,
    created_at
FROM draft_actions
WHERE draft_id = sqlc.arg(draft_id)
ORDER BY turn_number;
