version: 2

updates:
  - package-ecosystem: gomod
    directory: /backend
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /frontend
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
      - /test-data/importer
    target-branch: dev
    schedule:
      interval: daily
    open-pull-requests-limit: 10
