version: 2

multi-ecosystem-groups:
  dependencies:
    target-branch: dev
    schedule:
      interval: daily

updates:
  - package-ecosystem: gomod
    directory: /backend
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: /frontend
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    open-pull-requests-limit: 1

  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
      - /test-data/importer
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    open-pull-requests-limit: 1
