// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/tournament/admin/observability"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationObserver creates a new instance of MockOperationObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationObserver {
	mock := &MockOperationObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationObserver is an autogenerated mock type for the OperationObserver type
type MockOperationObserver struct {
	mock.Mock
}

type MockOperationObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationObserver) EXPECT() *MockOperationObserver_Expecter {
	return &MockOperationObserver_Expecter{mock: &_m.Mock}
}

// ObserveTournamentAdminOperation provides a mock function for the type MockOperationObserver
func (_mock *MockOperationObserver) ObserveTournamentAdminOperation(ctx context.Context, event observability.OperationEvent) {
	_mock.Called(ctx, event)
	return
}

// MockOperationObserver_ObserveTournamentAdminOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveTournamentAdminOperation'
type MockOperationObserver_ObserveTournamentAdminOperation_Call struct {
	*mock.Call
}

// ObserveTournamentAdminOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event observability.OperationEvent
func (_e *MockOperationObserver_Expecter) ObserveTournamentAdminOperation(ctx interface{}, event interface{}) *MockOperationObserver_ObserveTournamentAdminOperation_Call {
	return &MockOperationObserver_ObserveTournamentAdminOperation_Call{Call: _e.mock.On("ObserveTournamentAdminOperation", ctx, event)}
}

func (_c *MockOperationObserver_ObserveTournamentAdminOperation_Call) Run(run func(ctx context.Context, event observability.OperationEvent)) *MockOperationObserver_ObserveTournamentAdminOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 observability.OperationEvent
		if args[1] != nil {
			arg1 = args[1].(observability.OperationEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationObserver_ObserveTournamentAdminOperation_Call) Return() *MockOperationObserver_ObserveTournamentAdminOperation_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOperationObserver_ObserveTournamentAdminOperation_Call) RunAndReturn(run func(ctx context.Context, event observability.OperationEvent)) *MockOperationObserver_ObserveTournamentAdminOperation_Call {
	_c.Run(run)
	return _c
}
