#!/usr/bin/env python3
"""Merge per-domain OpenAPI schema YAMLs into one YAML mapping.

Inputs:  api/components/schemas/*.yml (any number of files,
         each providing a top-level mapping of schema names -> definitions).
Output:  the explicit path passed with --output.

Duplicate schema names across files are a hard error: name collisions silently
dropped by a "last writer wins" merge are exactly the bug class this script
exists to prevent.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("merge-schemas.py: PyYAML is required\n")
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parent.parent


class DuplicateKeyError(yaml.YAMLError):
    """Raised when a YAML mapping repeats a key."""


class UniqueKeyLoader(yaml.SafeLoader):
    """Safe YAML loader that rejects ambiguous mappings."""


def construct_unique_mapping(
    loader: UniqueKeyLoader, node: yaml.nodes.MappingNode, deep: bool = False
) -> dict[object, object]:
    mapping: dict[object, object] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        try:
            duplicate = key in mapping
        except TypeError as error:
            raise yaml.constructor.ConstructorError(
                "while constructing a mapping",
                node.start_mark,
                "found an unhashable key",
                key_node.start_mark,
            ) from error
        if duplicate:
            raise DuplicateKeyError(
                f"duplicate key {key!r} at line {key_node.start_mark.line + 1}"
            )
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


UniqueKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, construct_unique_mapping
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    args = parse_args()
    source_dir = args.source_dir.resolve()
    destination = args.output.resolve()

    if not source_dir.is_dir():
        sys.stderr.write(f"merge-schemas.py: source dir not found: {source_dir}\n")
        return 1

    sources = sorted(source_dir.glob("*.yml")) + sorted(source_dir.glob("*.yaml"))
    if not sources:
        sys.stderr.write(f"merge-schemas.py: no schema YAML files in {source_dir}\n")
        return 1

    merged: dict[str, object] = {}
    origins: dict[str, Path] = {}
    for path in sources:
        try:
            with path.open("r", encoding="utf-8") as fh:
                doc = yaml.load(fh, Loader=UniqueKeyLoader) or {}
        except yaml.YAMLError as error:
            sys.stderr.write(
                f"merge-schemas.py: invalid YAML in {display_path(path)}: {error}\n"
            )
            return 1
        if not isinstance(doc, dict):
            sys.stderr.write(
                f"merge-schemas.py: {path} must be a mapping, got {type(doc).__name__}\n"
            )
            return 1
        for name, schema in doc.items():
            if name in merged:
                sys.stderr.write(
                    f"merge-schemas.py: duplicate schema '{name}' "
                    f"(first in {origins[name].name}, also in {path.name})\n"
                )
                return 1
            merged[name] = schema
            origins[name] = path

    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as fh:
        fh.write("# generated by scripts/merge-schemas.py - do not edit by hand\n")
        yaml.safe_dump(merged, fh, sort_keys=True, allow_unicode=True)

    sys.stdout.write(
        f"merge-schemas.py: merged {len(sources)} file(s), "
        f"{len(merged)} schema(s) -> {display_path(destination)}\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
