// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminPlayerEventSubscriber creates a new instance of MockAdminPlayerEventSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminPlayerEventSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminPlayerEventSubscriber {
	mock := &MockAdminPlayerEventSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminPlayerEventSubscriber is an autogenerated mock type for the AdminPlayerEventSubscriber type
type MockAdminPlayerEventSubscriber struct {
	mock.Mock
}

type MockAdminPlayerEventSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminPlayerEventSubscriber) EXPECT() *MockAdminPlayerEventSubscriber_Expecter {
	return &MockAdminPlayerEventSubscriber_Expecter{mock: &_m.Mock}
}

// SubscribeAdminPlayerChanges provides a mock function for the type MockAdminPlayerEventSubscriber
func (_mock *MockAdminPlayerEventSubscriber) SubscribeAdminPlayerChanges(ctx context.Context) (<-chan struct{}, func(), error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeAdminPlayerChanges")
	}

	var r0 <-chan struct{}
	var r1 func()
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan struct{}, func(), error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan struct{}); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) func()); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeAdminPlayerChanges'
type MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call struct {
	*mock.Call
}

// SubscribeAdminPlayerChanges is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminPlayerEventSubscriber_Expecter) SubscribeAdminPlayerChanges(ctx interface{}) *MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call {
	return &MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call{Call: _e.mock.On("SubscribeAdminPlayerChanges", ctx)}
}

func (_c *MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call) Run(run func(ctx context.Context)) *MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call) Return(valCh <-chan struct{}, fn func(), err error) *MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call {
	_c.Call.Return(valCh, fn, err)
	return _c
}

func (_c *MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call) RunAndReturn(run func(ctx context.Context) (<-chan struct{}, func(), error)) *MockAdminPlayerEventSubscriber_SubscribeAdminPlayerChanges_Call {
	_c.Call.Return(run)
	return _c
}
