// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayerService creates a new instance of MockPlayerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPlayerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPlayerService is an autogenerated mock type for the PlayerService type
type MockPlayerService struct {
	mock.Mock
}

type MockPlayerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerService) EXPECT() *MockPlayerService_Expecter {
	return &MockPlayerService_Expecter{mock: &_m.Mock}
}

// GetCurrentPlayer provides a mock function for the type MockPlayerService
func (_mock *MockPlayerService) GetCurrentPlayer(ctx context.Context, sessionToken uuid.UUID) (*domain.Player, error) {
	ret := _mock.Called(ctx, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentPlayer")
	}

	var r0 *domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Player, error)); ok {
		return returnFunc(ctx, sessionToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Player); ok {
		r0 = returnFunc(ctx, sessionToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerService_GetCurrentPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentPlayer'
type MockPlayerService_GetCurrentPlayer_Call struct {
	*mock.Call
}

// GetCurrentPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken uuid.UUID
func (_e *MockPlayerService_Expecter) GetCurrentPlayer(ctx any, sessionToken any) *MockPlayerService_GetCurrentPlayer_Call {
	return &MockPlayerService_GetCurrentPlayer_Call{Call: _e.mock.On("GetCurrentPlayer", ctx, sessionToken)}
}

func (_c *MockPlayerService_GetCurrentPlayer_Call) Run(run func(ctx context.Context, sessionToken uuid.UUID)) *MockPlayerService_GetCurrentPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerService_GetCurrentPlayer_Call) Return(player *domain.Player, err error) *MockPlayerService_GetCurrentPlayer_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *MockPlayerService_GetCurrentPlayer_Call) RunAndReturn(run func(ctx context.Context, sessionToken uuid.UUID) (*domain.Player, error)) *MockPlayerService_GetCurrentPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockPlayerService
func (_mock *MockPlayerService) Logout(ctx context.Context, sessionToken uuid.UUID) error {
	ret := _mock.Called(ctx, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayerService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockPlayerService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken uuid.UUID
func (_e *MockPlayerService_Expecter) Logout(ctx any, sessionToken any) *MockPlayerService_Logout_Call {
	return &MockPlayerService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionToken)}
}

func (_c *MockPlayerService_Logout_Call) Run(run func(ctx context.Context, sessionToken uuid.UUID)) *MockPlayerService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerService_Logout_Call) Return(err error) *MockPlayerService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayerService_Logout_Call) RunAndReturn(run func(ctx context.Context, sessionToken uuid.UUID) error) *MockPlayerService_Logout_Call {
	_c.Call.Return(run)
	return _c
}
