package admin

import (
	configurationusecase "github.com/TakuyaYagam1/task-per-minute/internal/usecase/tournament/admin/configuration"
)

type ConfigurationQuery = configurationusecase.ConfigurationQuery
type ConfigurationUpdateCommand = configurationusecase.ConfigurationUpdateCommand
type UnstartedSeriesUpdateCommand = configurationusecase.UnstartedSeriesUpdateCommand
type SwissRoundRevisionCommand = configurationusecase.SwissRoundRevisionCommand
type ConfigurationStageDefault = configurationusecase.ConfigurationStageDefault
type ConfigurationReservation = configurationusecase.ConfigurationReservation
type ConfigurationArtifact = configurationusecase.ConfigurationArtifact
type ConfigurationSeries = configurationusecase.ConfigurationSeries
type ConfigurationRound = configurationusecase.ConfigurationRound
type ConfigurationAuthority = configurationusecase.ConfigurationAuthority
type ConfigurationLoadQuery = configurationusecase.ConfigurationLoadQuery
type ConfigurationCommandRecord = configurationusecase.ConfigurationCommandRecord
type ConfigurationMutation = configurationusecase.ConfigurationMutation
type ConfigurationSeriesChange = configurationusecase.ConfigurationSeriesChange
type ConfigurationRoundChange = configurationusecase.ConfigurationRoundChange
type ConfigurationMutationResult = configurationusecase.ConfigurationMutationResult
type TournamentConfigurationRepository = configurationusecase.TournamentConfigurationRepository
type TournamentConfigurationWorkflow = configurationusecase.TournamentConfigurationWorkflow
type ConfigurationRevisionConflictError = configurationusecase.ConfigurationRevisionConflictError

const (
	ConfigurationArtifactPlanned  = configurationusecase.ConfigurationArtifactPlanned
	ConfigurationArtifactLocked   = configurationusecase.ConfigurationArtifactLocked
	ConfigurationArtifactActive   = configurationusecase.ConfigurationArtifactActive
	ConfigurationArtifactTerminal = configurationusecase.ConfigurationArtifactTerminal
)

var ErrCutoff = configurationusecase.ErrCutoff

func NewTournamentConfigurationWorkflow(repository TournamentConfigurationRepository) *TournamentConfigurationWorkflow {
	return configurationusecase.NewTournamentConfigurationWorkflow(repository)
}
