package admin

import executionusecase "github.com/TakuyaYagam1/task-per-minute/internal/usecase/tournament/admin/execution"

type ExecutionTransactionManager = executionusecase.ExecutionTransactionManager
type ExecutionAuthorityProvider = executionusecase.ExecutionAuthorityProvider
type PairingCommandRecord = executionusecase.PairingCommandRecord
type WaveGraph = executionusecase.WaveGraph
type WaveAuthority = executionusecase.WaveAuthority
type WaveMutation = executionusecase.WaveMutation
type WaveCommandRecord = executionusecase.WaveCommandRecord
type NormalPauseExecutionRepository = executionusecase.NormalPauseExecutionRepository
type ExecutionWorkflowRepository = executionusecase.ExecutionWorkflowRepository
type ExecutionWorkflowDependencies = executionusecase.ExecutionWorkflowDependencies
