// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAttemptClock creates a new instance of MockAttemptClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttemptClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttemptClock {
	mock := &MockAttemptClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttemptClock is an autogenerated mock type for the AttemptClock type
type MockAttemptClock struct {
	mock.Mock
}

type MockAttemptClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttemptClock) EXPECT() *MockAttemptClock_Expecter {
	return &MockAttemptClock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockAttemptClock
func (_mock *MockAttemptClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockAttemptClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockAttemptClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockAttemptClock_Expecter) Now() *MockAttemptClock_Now_Call {
	return &MockAttemptClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockAttemptClock_Now_Call) Run(run func()) *MockAttemptClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAttemptClock_Now_Call) Return(time1 time.Time) *MockAttemptClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockAttemptClock_Now_Call) RunAndReturn(run func() time.Time) *MockAttemptClock_Now_Call {
	_c.Call.Return(run)
	return _c
}
