// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/TakuyaYagam1/task-per-minute/config"
	"github.com/TakuyaYagam1/task-per-minute/internal/adapter/inbound/websocket"
	"github.com/TakuyaYagam1/task-per-minute/internal/adapter/outbound/postgres"
	"github.com/wahrwelt-kit/go-logkit"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

func initializeApp(runtime *RuntimeContext, cfg *config.Config, log logkit.Logger) (*App, func(), error) {
	objectstorageConfig := provideSeaweedConfig(cfg)
	seaweedStorage, err := provideSeaweedStorage(objectstorageConfig)
	if err != nil {
		return nil, nil, err
	}
	migrator := provideMigrator(cfg)
	context := provideRuntimeContext(runtime)
	postgresConfig := providePostgresConfig(cfg)
	pool, cleanup, err := providePostgres(context, postgresConfig)
	if err != nil {
		return nil, nil, err
	}
	txManager := postgres.NewTxManager(pool)
	duelPostgres := postgres.NewDuelPostgres(txManager)
	playerPostgres := postgres.NewPlayerPostgres(txManager)
	redisConfig := provideRedisConfig(cfg)
	client, cleanup2, err := provideRedis(context, redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	matchmakingRedis := provideMatchmakingRedis(client)
	taskPostgres := postgres.NewTaskPostgres(txManager)
	historyPostgres := postgres.NewHistoryPostgres(txManager)
	bootstrapClockFunc := provideClock()
	matchmakingUseCase := provideMatchmakingUseCase(txManager, matchmakingRedis, playerPostgres, taskPostgres, historyPostgres, duelPostgres, seaweedStorage, bootstrapClockFunc, log)
	leaderboardRedis := provideLeaderboardRedis(client)
	leaderboardPostgres := postgres.NewLeaderboardPostgres(txManager)
	useCase := provideLeaderboardUseCase(leaderboardRedis, leaderboardPostgres, bootstrapClockFunc)
	timerRegistry := provideTimerRegistry(context, txManager, duelPostgres, playerPostgres, bootstrapClockFunc, log)
	flagSubmitUseCase := provideFlagSubmitUseCase(txManager, duelPostgres, playerPostgres, historyPostgres, useCase, bootstrapClockFunc, timerRegistry, log)
	hubRegistry := provideHubRegistry()
	hintScheduler := provideHintScheduler(bootstrapClockFunc)
	bootstrapWsHandshakeRateLimiter := provideHandshakeRateLimiter(context, cfg)
	arenaTournamentPostgres := postgres.NewArenaTournamentPostgres(txManager)
	arenaProductionSnapshotSource := websocket.NewArenaProductionSnapshotSource(arenaTournamentPostgres, arenaTournamentPostgres)
	arenaParticipantFlow, err := websocket.NewArenaParticipantFlow(arenaProductionSnapshotSource)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	publicRealtimeConfig := provideArenaPublicRealtimeConfig()
	arenaPublicFlow, err := websocket.NewArenaPublicFlow(arenaProductionSnapshotSource, publicRealtimeConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	arenaOperatorFlow, err := websocket.NewArenaOperatorFlow(arenaProductionSnapshotSource)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := provideArenaCancellationCoordinators()
	arenaTerminalRegistry, err := websocket.NewArenaTerminalRegistry(v)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	arenaTerminalFlow, err := websocket.NewArenaTerminalFlow(arenaTerminalRegistry)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authConfig := provideAuthConfig(cfg)
	revocationRedis := provideRevocationRedis(client)
	authUseCase := provideAuthUseCase(authConfig, bootstrapClockFunc, revocationRedis)
	arenaOperatorPrincipalResolver := provideArenaOperatorPrincipalResolver(authUseCase)
	bootstrapArenaWebSocketOptions := provideArenaWebSocketOptions(arenaParticipantFlow, arenaPublicFlow, arenaOperatorFlow, arenaTerminalFlow, arenaOperatorPrincipalResolver)
	bootstrapRawWebSocketServer := provideRawWebSocketServerWithArena(context, cfg, log, playerPostgres, matchmakingUseCase, flagSubmitUseCase, hubRegistry, hintScheduler, timerRegistry, duelPostgres, seaweedStorage, bootstrapWsHandshakeRateLimiter, bootstrapArenaWebSocketOptions)
	broadcaster := provideDuelBroadcaster(bootstrapRawWebSocketServer)
	duelTimer := provideDuelTimers(timerRegistry, hintScheduler)
	reconnectManager := provideReconnectManager(context, txManager, duelPostgres, playerPostgres, duelTimer, broadcaster, bootstrapClockFunc, useCase, log)
	startupRecoverer := provideStartupRecoverer(txManager, duelPostgres, duelPostgres, playerPostgres, playerPostgres, matchmakingRedis, broadcaster, reconnectManager, hintScheduler, bootstrapClockFunc, log)
	bootstrapArenaCore := provideArenaCore(arenaTournamentPostgres, arenaTournamentPostgres, arenaTournamentPostgres, arenaTournamentPostgres, bootstrapClockFunc)
	playerUseCase := providePlayerUseCase(cfg, txManager, playerPostgres, duelPostgres, bootstrapClockFunc)
	taskUseCase := provideAdminTaskUseCase(taskPostgres)
	adminPlayerUseCase := provideAdminPlayerUseCase(txManager, playerPostgres, useCase, bootstrapClockFunc)
	adminPlayerEventsPostgres := postgres.NewAdminPlayerEventsPostgres(pool)
	uploadUseCase := provideUploadUseCase(taskPostgres, seaweedStorage, log)
	readUseCase := provideReadUseCase(duelPostgres)
	schemaVersionPostgres := postgres.NewSchemaVersionPostgres(pool)
	healthChecks := provideHealthChecks(pool, client, seaweedStorage, schemaVersionPostgres)
	loginRateLimiter := provideLoginRateLimiter(context, cfg)
	bootstrapAdminRefreshRateLimiter := provideRefreshRateLimiter(context, cfg)
	joinRateLimiter := provideJoinRateLimiter(context, cfg)
	bootstrapLeaderboardRateLimiter := provideLeaderboardRateLimiter(context, cfg)
	server := provideRESTServerWithClock(playerUseCase, authUseCase, taskUseCase, adminPlayerUseCase, adminPlayerEventsPostgres, uploadUseCase, useCase, readUseCase, healthChecks, bootstrapClockFunc, loginRateLimiter, bootstrapAdminRefreshRateLimiter, joinRateLimiter, bootstrapLeaderboardRateLimiter, log)
	websocketServer := provideWebSocketServer(bootstrapRawWebSocketServer, reconnectManager)
	bootstrapRestMiddlewareStack, err := provideRESTMiddlewares(context, log, cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler := provideHTTPHandler(cfg, server, websocketServer, authUseCase, playerPostgres, bootstrapRestMiddlewareStack, log)
	httpServer := provideHTTPServer(cfg, handler)
	app := provideArenaApplication(cfg, log, runtime, seaweedStorage, migrator, startupRecoverer, bootstrapArenaCore, httpServer, websocketServer, revocationRedis)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
