// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/port/inbound"
	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/audit"
	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/tournament/admin/inbound"
	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/tournament/preflight"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminService creates a new instance of MockAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAdminService is an autogenerated mock type for the AdminService type
type MockAdminService struct {
	mock.Mock
}

type MockAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminService) EXPECT() *MockAdminService_Expecter {
	return &MockAdminService_Expecter{mock: &_m.Mock}
}

// ApplyTournamentAction provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ApplyTournamentAction(ctx context.Context, command inbound.TournamentActionCommand) (usecase.TournamentView, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ApplyTournamentAction")
	}

	var r0 usecase.TournamentView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.TournamentActionCommand) (usecase.TournamentView, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.TournamentActionCommand) usecase.TournamentView); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(usecase.TournamentView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.TournamentActionCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_ApplyTournamentAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyTournamentAction'
type MockAdminService_ApplyTournamentAction_Call struct {
	*mock.Call
}

// ApplyTournamentAction is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.TournamentActionCommand
func (_e *MockAdminService_Expecter) ApplyTournamentAction(ctx any, command any) *MockAdminService_ApplyTournamentAction_Call {
	return &MockAdminService_ApplyTournamentAction_Call{Call: _e.mock.On("ApplyTournamentAction", ctx, command)}
}

func (_c *MockAdminService_ApplyTournamentAction_Call) Run(run func(ctx context.Context, command inbound.TournamentActionCommand)) *MockAdminService_ApplyTournamentAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.TournamentActionCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.TournamentActionCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ApplyTournamentAction_Call) Return(tournamentView usecase.TournamentView, err error) *MockAdminService_ApplyTournamentAction_Call {
	_c.Call.Return(tournamentView, err)
	return _c
}

func (_c *MockAdminService_ApplyTournamentAction_Call) RunAndReturn(run func(ctx context.Context, command inbound.TournamentActionCommand) (usecase.TournamentView, error)) *MockAdminService_ApplyTournamentAction_Call {
	_c.Call.Return(run)
	return _c
}

// AssignReserve provides a mock function for the type MockAdminService
func (_mock *MockAdminService) AssignReserve(ctx context.Context, command inbound.ReserveCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for AssignReserve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.ReserveCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminService_AssignReserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignReserve'
type MockAdminService_AssignReserve_Call struct {
	*mock.Call
}

// AssignReserve is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.ReserveCommand
func (_e *MockAdminService_Expecter) AssignReserve(ctx any, command any) *MockAdminService_AssignReserve_Call {
	return &MockAdminService_AssignReserve_Call{Call: _e.mock.On("AssignReserve", ctx, command)}
}

func (_c *MockAdminService_AssignReserve_Call) Run(run func(ctx context.Context, command inbound.ReserveCommand)) *MockAdminService_AssignReserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.ReserveCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.ReserveCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_AssignReserve_Call) Return(err error) *MockAdminService_AssignReserve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminService_AssignReserve_Call) RunAndReturn(run func(ctx context.Context, command inbound.ReserveCommand) error) *MockAdminService_AssignReserve_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigurePairings provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ConfigurePairings(ctx context.Context, command inbound.PairingCommand) (inbound.SwissRoundView, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ConfigurePairings")
	}

	var r0 inbound.SwissRoundView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.PairingCommand) (inbound.SwissRoundView, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.PairingCommand) inbound.SwissRoundView); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(inbound.SwissRoundView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.PairingCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_ConfigurePairings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigurePairings'
type MockAdminService_ConfigurePairings_Call struct {
	*mock.Call
}

// ConfigurePairings is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.PairingCommand
func (_e *MockAdminService_Expecter) ConfigurePairings(ctx any, command any) *MockAdminService_ConfigurePairings_Call {
	return &MockAdminService_ConfigurePairings_Call{Call: _e.mock.On("ConfigurePairings", ctx, command)}
}

func (_c *MockAdminService_ConfigurePairings_Call) Run(run func(ctx context.Context, command inbound.PairingCommand)) *MockAdminService_ConfigurePairings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.PairingCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.PairingCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ConfigurePairings_Call) Return(swissRoundView inbound.SwissRoundView, err error) *MockAdminService_ConfigurePairings_Call {
	_c.Call.Return(swissRoundView, err)
	return _c
}

func (_c *MockAdminService_ConfigurePairings_Call) RunAndReturn(run func(ctx context.Context, command inbound.PairingCommand) (inbound.SwissRoundView, error)) *MockAdminService_ConfigurePairings_Call {
	_c.Call.Return(run)
	return _c
}

// ControlWave provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ControlWave(ctx context.Context, command inbound.WaveCommand) (inbound.WaveView, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ControlWave")
	}

	var r0 inbound.WaveView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.WaveCommand) (inbound.WaveView, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.WaveCommand) inbound.WaveView); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(inbound.WaveView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.WaveCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_ControlWave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ControlWave'
type MockAdminService_ControlWave_Call struct {
	*mock.Call
}

// ControlWave is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.WaveCommand
func (_e *MockAdminService_Expecter) ControlWave(ctx any, command any) *MockAdminService_ControlWave_Call {
	return &MockAdminService_ControlWave_Call{Call: _e.mock.On("ControlWave", ctx, command)}
}

func (_c *MockAdminService_ControlWave_Call) Run(run func(ctx context.Context, command inbound.WaveCommand)) *MockAdminService_ControlWave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.WaveCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.WaveCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ControlWave_Call) Return(waveView inbound.WaveView, err error) *MockAdminService_ControlWave_Call {
	_c.Call.Return(waveView, err)
	return _c
}

func (_c *MockAdminService_ControlWave_Call) RunAndReturn(run func(ctx context.Context, command inbound.WaveCommand) (inbound.WaveView, error)) *MockAdminService_ControlWave_Call {
	_c.Call.Return(run)
	return _c
}

// CorrectGameResult provides a mock function for the type MockAdminService
func (_mock *MockAdminService) CorrectGameResult(ctx context.Context, command inbound.CorrectionCommand) (inbound.CorrectionEvidence, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for CorrectGameResult")
	}

	var r0 inbound.CorrectionEvidence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.CorrectionCommand) (inbound.CorrectionEvidence, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.CorrectionCommand) inbound.CorrectionEvidence); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(inbound.CorrectionEvidence)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.CorrectionCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_CorrectGameResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CorrectGameResult'
type MockAdminService_CorrectGameResult_Call struct {
	*mock.Call
}

// CorrectGameResult is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.CorrectionCommand
func (_e *MockAdminService_Expecter) CorrectGameResult(ctx any, command any) *MockAdminService_CorrectGameResult_Call {
	return &MockAdminService_CorrectGameResult_Call{Call: _e.mock.On("CorrectGameResult", ctx, command)}
}

func (_c *MockAdminService_CorrectGameResult_Call) Run(run func(ctx context.Context, command inbound.CorrectionCommand)) *MockAdminService_CorrectGameResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.CorrectionCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.CorrectionCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_CorrectGameResult_Call) Return(correctionEvidence inbound.CorrectionEvidence, err error) *MockAdminService_CorrectGameResult_Call {
	_c.Call.Return(correctionEvidence, err)
	return _c
}

func (_c *MockAdminService_CorrectGameResult_Call) RunAndReturn(run func(ctx context.Context, command inbound.CorrectionCommand) (inbound.CorrectionEvidence, error)) *MockAdminService_CorrectGameResult_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTournament provides a mock function for the type MockAdminService
func (_mock *MockAdminService) DeleteTournament(ctx context.Context, command inbound.TournamentDeletionCommand) (inbound.TournamentDeletionRecord, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTournament")
	}

	var r0 inbound.TournamentDeletionRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.TournamentDeletionCommand) (inbound.TournamentDeletionRecord, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.TournamentDeletionCommand) inbound.TournamentDeletionRecord); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(inbound.TournamentDeletionRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.TournamentDeletionCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_DeleteTournament_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTournament'
type MockAdminService_DeleteTournament_Call struct {
	*mock.Call
}

// DeleteTournament is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.TournamentDeletionCommand
func (_e *MockAdminService_Expecter) DeleteTournament(ctx any, command any) *MockAdminService_DeleteTournament_Call {
	return &MockAdminService_DeleteTournament_Call{Call: _e.mock.On("DeleteTournament", ctx, command)}
}

func (_c *MockAdminService_DeleteTournament_Call) Run(run func(ctx context.Context, command inbound.TournamentDeletionCommand)) *MockAdminService_DeleteTournament_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.TournamentDeletionCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.TournamentDeletionCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_DeleteTournament_Call) Return(tournamentDeletionRecord inbound.TournamentDeletionRecord, err error) *MockAdminService_DeleteTournament_Call {
	_c.Call.Return(tournamentDeletionRecord, err)
	return _c
}

func (_c *MockAdminService_DeleteTournament_Call) RunAndReturn(run func(ctx context.Context, command inbound.TournamentDeletionCommand) (inbound.TournamentDeletionRecord, error)) *MockAdminService_DeleteTournament_Call {
	_c.Call.Return(run)
	return _c
}

// ExportIncident provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ExportIncident(ctx context.Context, query inbound.IncidentQuery) (audit.IncidentBundle, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ExportIncident")
	}

	var r0 audit.IncidentBundle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.IncidentQuery) (audit.IncidentBundle, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.IncidentQuery) audit.IncidentBundle); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(audit.IncidentBundle)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.IncidentQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_ExportIncident_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportIncident'
type MockAdminService_ExportIncident_Call struct {
	*mock.Call
}

// ExportIncident is a helper method to define mock.On call
//   - ctx context.Context
//   - query inbound.IncidentQuery
func (_e *MockAdminService_Expecter) ExportIncident(ctx any, query any) *MockAdminService_ExportIncident_Call {
	return &MockAdminService_ExportIncident_Call{Call: _e.mock.On("ExportIncident", ctx, query)}
}

func (_c *MockAdminService_ExportIncident_Call) Run(run func(ctx context.Context, query inbound.IncidentQuery)) *MockAdminService_ExportIncident_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.IncidentQuery
		if args[1] != nil {
			arg1 = args[1].(inbound.IncidentQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ExportIncident_Call) Return(incidentBundle audit.IncidentBundle, err error) *MockAdminService_ExportIncident_Call {
	_c.Call.Return(incidentBundle, err)
	return _c
}

func (_c *MockAdminService_ExportIncident_Call) RunAndReturn(run func(ctx context.Context, query inbound.IncidentQuery) (audit.IncidentBundle, error)) *MockAdminService_ExportIncident_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperatorSnapshot provides a mock function for the type MockAdminService
func (_mock *MockAdminService) GetOperatorSnapshot(ctx context.Context, query inbound.SnapshotQuery) (inbound.OperatorSnapshotView, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorSnapshot")
	}

	var r0 inbound.OperatorSnapshotView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.SnapshotQuery) (inbound.OperatorSnapshotView, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.SnapshotQuery) inbound.OperatorSnapshotView); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(inbound.OperatorSnapshotView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.SnapshotQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_GetOperatorSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperatorSnapshot'
type MockAdminService_GetOperatorSnapshot_Call struct {
	*mock.Call
}

// GetOperatorSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - query inbound.SnapshotQuery
func (_e *MockAdminService_Expecter) GetOperatorSnapshot(ctx any, query any) *MockAdminService_GetOperatorSnapshot_Call {
	return &MockAdminService_GetOperatorSnapshot_Call{Call: _e.mock.On("GetOperatorSnapshot", ctx, query)}
}

func (_c *MockAdminService_GetOperatorSnapshot_Call) Run(run func(ctx context.Context, query inbound.SnapshotQuery)) *MockAdminService_GetOperatorSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.SnapshotQuery
		if args[1] != nil {
			arg1 = args[1].(inbound.SnapshotQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_GetOperatorSnapshot_Call) Return(operatorSnapshotView inbound.OperatorSnapshotView, err error) *MockAdminService_GetOperatorSnapshot_Call {
	_c.Call.Return(operatorSnapshotView, err)
	return _c
}

func (_c *MockAdminService_GetOperatorSnapshot_Call) RunAndReturn(run func(ctx context.Context, query inbound.SnapshotQuery) (inbound.OperatorSnapshotView, error)) *MockAdminService_GetOperatorSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoster provides a mock function for the type MockAdminService
func (_mock *MockAdminService) GetRoster(ctx context.Context, query inbound.RosterQuery) (inbound.RosterView, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetRoster")
	}

	var r0 inbound.RosterView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.RosterQuery) (inbound.RosterView, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.RosterQuery) inbound.RosterView); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(inbound.RosterView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.RosterQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_GetRoster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoster'
type MockAdminService_GetRoster_Call struct {
	*mock.Call
}

// GetRoster is a helper method to define mock.On call
//   - ctx context.Context
//   - query inbound.RosterQuery
func (_e *MockAdminService_Expecter) GetRoster(ctx any, query any) *MockAdminService_GetRoster_Call {
	return &MockAdminService_GetRoster_Call{Call: _e.mock.On("GetRoster", ctx, query)}
}

func (_c *MockAdminService_GetRoster_Call) Run(run func(ctx context.Context, query inbound.RosterQuery)) *MockAdminService_GetRoster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.RosterQuery
		if args[1] != nil {
			arg1 = args[1].(inbound.RosterQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_GetRoster_Call) Return(rosterView inbound.RosterView, err error) *MockAdminService_GetRoster_Call {
	_c.Call.Return(rosterView, err)
	return _c
}

func (_c *MockAdminService_GetRoster_Call) RunAndReturn(run func(ctx context.Context, query inbound.RosterQuery) (inbound.RosterView, error)) *MockAdminService_GetRoster_Call {
	_c.Call.Return(run)
	return _c
}

// ListAudit provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ListAudit(ctx context.Context, query inbound.AuditQuery) (audit.AuditPage, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListAudit")
	}

	var r0 audit.AuditPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.AuditQuery) (audit.AuditPage, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.AuditQuery) audit.AuditPage); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(audit.AuditPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.AuditQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_ListAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAudit'
type MockAdminService_ListAudit_Call struct {
	*mock.Call
}

// ListAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - query inbound.AuditQuery
func (_e *MockAdminService_Expecter) ListAudit(ctx any, query any) *MockAdminService_ListAudit_Call {
	return &MockAdminService_ListAudit_Call{Call: _e.mock.On("ListAudit", ctx, query)}
}

func (_c *MockAdminService_ListAudit_Call) Run(run func(ctx context.Context, query inbound.AuditQuery)) *MockAdminService_ListAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.AuditQuery
		if args[1] != nil {
			arg1 = args[1].(inbound.AuditQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ListAudit_Call) Return(auditPage audit.AuditPage, err error) *MockAdminService_ListAudit_Call {
	_c.Call.Return(auditPage, err)
	return _c
}

func (_c *MockAdminService_ListAudit_Call) RunAndReturn(run func(ctx context.Context, query inbound.AuditQuery) (audit.AuditPage, error)) *MockAdminService_ListAudit_Call {
	_c.Call.Return(run)
	return _c
}

// LockRoster provides a mock function for the type MockAdminService
func (_mock *MockAdminService) LockRoster(ctx context.Context, command inbound.LockRosterCommand) (inbound.RosterView, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for LockRoster")
	}

	var r0 inbound.RosterView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.LockRosterCommand) (inbound.RosterView, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.LockRosterCommand) inbound.RosterView); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(inbound.RosterView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.LockRosterCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_LockRoster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockRoster'
type MockAdminService_LockRoster_Call struct {
	*mock.Call
}

// LockRoster is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.LockRosterCommand
func (_e *MockAdminService_Expecter) LockRoster(ctx any, command any) *MockAdminService_LockRoster_Call {
	return &MockAdminService_LockRoster_Call{Call: _e.mock.On("LockRoster", ctx, command)}
}

func (_c *MockAdminService_LockRoster_Call) Run(run func(ctx context.Context, command inbound.LockRosterCommand)) *MockAdminService_LockRoster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.LockRosterCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.LockRosterCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_LockRoster_Call) Return(rosterView inbound.RosterView, err error) *MockAdminService_LockRoster_Call {
	_c.Call.Return(rosterView, err)
	return _c
}

func (_c *MockAdminService_LockRoster_Call) RunAndReturn(run func(ctx context.Context, command inbound.LockRosterCommand) (inbound.RosterView, error)) *MockAdminService_LockRoster_Call {
	_c.Call.Return(run)
	return _c
}

// RecordForfeit provides a mock function for the type MockAdminService
func (_mock *MockAdminService) RecordForfeit(ctx context.Context, command inbound.ForfeitCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for RecordForfeit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.ForfeitCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminService_RecordForfeit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordForfeit'
type MockAdminService_RecordForfeit_Call struct {
	*mock.Call
}

// RecordForfeit is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.ForfeitCommand
func (_e *MockAdminService_Expecter) RecordForfeit(ctx any, command any) *MockAdminService_RecordForfeit_Call {
	return &MockAdminService_RecordForfeit_Call{Call: _e.mock.On("RecordForfeit", ctx, command)}
}

func (_c *MockAdminService_RecordForfeit_Call) Run(run func(ctx context.Context, command inbound.ForfeitCommand)) *MockAdminService_RecordForfeit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.ForfeitCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.ForfeitCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_RecordForfeit_Call) Return(err error) *MockAdminService_RecordForfeit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminService_RecordForfeit_Call) RunAndReturn(run func(ctx context.Context, command inbound.ForfeitCommand) error) *MockAdminService_RecordForfeit_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceRoster provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ReplaceRoster(ctx context.Context, command inbound.ReplaceRosterCommand) (inbound.RosterView, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceRoster")
	}

	var r0 inbound.RosterView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.ReplaceRosterCommand) (inbound.RosterView, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.ReplaceRosterCommand) inbound.RosterView); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(inbound.RosterView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.ReplaceRosterCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_ReplaceRoster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceRoster'
type MockAdminService_ReplaceRoster_Call struct {
	*mock.Call
}

// ReplaceRoster is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.ReplaceRosterCommand
func (_e *MockAdminService_Expecter) ReplaceRoster(ctx any, command any) *MockAdminService_ReplaceRoster_Call {
	return &MockAdminService_ReplaceRoster_Call{Call: _e.mock.On("ReplaceRoster", ctx, command)}
}

func (_c *MockAdminService_ReplaceRoster_Call) Run(run func(ctx context.Context, command inbound.ReplaceRosterCommand)) *MockAdminService_ReplaceRoster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.ReplaceRosterCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.ReplaceRosterCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ReplaceRoster_Call) Return(rosterView inbound.RosterView, err error) *MockAdminService_ReplaceRoster_Call {
	_c.Call.Return(rosterView, err)
	return _c
}

func (_c *MockAdminService_ReplaceRoster_Call) RunAndReturn(run func(ctx context.Context, command inbound.ReplaceRosterCommand) (inbound.RosterView, error)) *MockAdminService_ReplaceRoster_Call {
	_c.Call.Return(run)
	return _c
}

// ReplayGame provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ReplayGame(ctx context.Context, command inbound.ReplayCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ReplayGame")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.ReplayCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminService_ReplayGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayGame'
type MockAdminService_ReplayGame_Call struct {
	*mock.Call
}

// ReplayGame is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.ReplayCommand
func (_e *MockAdminService_Expecter) ReplayGame(ctx any, command any) *MockAdminService_ReplayGame_Call {
	return &MockAdminService_ReplayGame_Call{Call: _e.mock.On("ReplayGame", ctx, command)}
}

func (_c *MockAdminService_ReplayGame_Call) Run(run func(ctx context.Context, command inbound.ReplayCommand)) *MockAdminService_ReplayGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.ReplayCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.ReplayCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ReplayGame_Call) Return(err error) *MockAdminService_ReplayGame_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminService_ReplayGame_Call) RunAndReturn(run func(ctx context.Context, command inbound.ReplayCommand) error) *MockAdminService_ReplayGame_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveNoShow provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ResolveNoShow(ctx context.Context, command inbound.NoShowCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ResolveNoShow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.NoShowCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminService_ResolveNoShow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveNoShow'
type MockAdminService_ResolveNoShow_Call struct {
	*mock.Call
}

// ResolveNoShow is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.NoShowCommand
func (_e *MockAdminService_Expecter) ResolveNoShow(ctx any, command any) *MockAdminService_ResolveNoShow_Call {
	return &MockAdminService_ResolveNoShow_Call{Call: _e.mock.On("ResolveNoShow", ctx, command)}
}

func (_c *MockAdminService_ResolveNoShow_Call) Run(run func(ctx context.Context, command inbound.NoShowCommand)) *MockAdminService_ResolveNoShow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.NoShowCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.NoShowCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_ResolveNoShow_Call) Return(err error) *MockAdminService_ResolveNoShow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminService_ResolveNoShow_Call) RunAndReturn(run func(ctx context.Context, command inbound.NoShowCommand) error) *MockAdminService_ResolveNoShow_Call {
	_c.Call.Return(run)
	return _c
}

// RunPreflight provides a mock function for the type MockAdminService
func (_mock *MockAdminService) RunPreflight(ctx context.Context, command inbound.PreflightCommand) (preflight.ReportRevision, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for RunPreflight")
	}

	var r0 preflight.ReportRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.PreflightCommand) (preflight.ReportRevision, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.PreflightCommand) preflight.ReportRevision); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(preflight.ReportRevision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.PreflightCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_RunPreflight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunPreflight'
type MockAdminService_RunPreflight_Call struct {
	*mock.Call
}

// RunPreflight is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.PreflightCommand
func (_e *MockAdminService_Expecter) RunPreflight(ctx any, command any) *MockAdminService_RunPreflight_Call {
	return &MockAdminService_RunPreflight_Call{Call: _e.mock.On("RunPreflight", ctx, command)}
}

func (_c *MockAdminService_RunPreflight_Call) Run(run func(ctx context.Context, command inbound.PreflightCommand)) *MockAdminService_RunPreflight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.PreflightCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.PreflightCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_RunPreflight_Call) Return(reportRevision preflight.ReportRevision, err error) *MockAdminService_RunPreflight_Call {
	_c.Call.Return(reportRevision, err)
	return _c
}

func (_c *MockAdminService_RunPreflight_Call) RunAndReturn(run func(ctx context.Context, command inbound.PreflightCommand) (preflight.ReportRevision, error)) *MockAdminService_RunPreflight_Call {
	_c.Call.Return(run)
	return _c
}

// UnlockRoster provides a mock function for the type MockAdminService
func (_mock *MockAdminService) UnlockRoster(ctx context.Context, command inbound.UnlockRosterCommand) (inbound.RosterView, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for UnlockRoster")
	}

	var r0 inbound.RosterView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.UnlockRosterCommand) (inbound.RosterView, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, inbound.UnlockRosterCommand) inbound.RosterView); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(inbound.RosterView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, inbound.UnlockRosterCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_UnlockRoster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlockRoster'
type MockAdminService_UnlockRoster_Call struct {
	*mock.Call
}

// UnlockRoster is a helper method to define mock.On call
//   - ctx context.Context
//   - command inbound.UnlockRosterCommand
func (_e *MockAdminService_Expecter) UnlockRoster(ctx any, command any) *MockAdminService_UnlockRoster_Call {
	return &MockAdminService_UnlockRoster_Call{Call: _e.mock.On("UnlockRoster", ctx, command)}
}

func (_c *MockAdminService_UnlockRoster_Call) Run(run func(ctx context.Context, command inbound.UnlockRosterCommand)) *MockAdminService_UnlockRoster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 inbound.UnlockRosterCommand
		if args[1] != nil {
			arg1 = args[1].(inbound.UnlockRosterCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_UnlockRoster_Call) Return(rosterView inbound.RosterView, err error) *MockAdminService_UnlockRoster_Call {
	_c.Call.Return(rosterView, err)
	return _c
}

func (_c *MockAdminService_UnlockRoster_Call) RunAndReturn(run func(ctx context.Context, command inbound.UnlockRosterCommand) (inbound.RosterView, error)) *MockAdminService_UnlockRoster_Call {
	_c.Call.Return(run)
	return _c
}
