// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/correction/stage"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStageRepository creates a new instance of MockStageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStageRepository {
	mock := &MockStageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStageRepository is an autogenerated mock type for the StageRepository type
type MockStageRepository struct {
	mock.Mock
}

type MockStageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStageRepository) EXPECT() *MockStageRepository_Expecter {
	return &MockStageRepository_Expecter{mock: &_m.Mock}
}

// CommitCorrectionStage provides a mock function for the type MockStageRepository
func (_mock *MockStageRepository) CommitCorrectionStage(ctx context.Context, commit stage.StageCommit) (bool, error) {
	ret := _mock.Called(ctx, commit)

	if len(ret) == 0 {
		panic("no return value specified for CommitCorrectionStage")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, stage.StageCommit) (bool, error)); ok {
		return returnFunc(ctx, commit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, stage.StageCommit) bool); ok {
		r0 = returnFunc(ctx, commit)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, stage.StageCommit) error); ok {
		r1 = returnFunc(ctx, commit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStageRepository_CommitCorrectionStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitCorrectionStage'
type MockStageRepository_CommitCorrectionStage_Call struct {
	*mock.Call
}

// CommitCorrectionStage is a helper method to define mock.On call
//   - ctx context.Context
//   - commit stage.StageCommit
func (_e *MockStageRepository_Expecter) CommitCorrectionStage(ctx interface{}, commit interface{}) *MockStageRepository_CommitCorrectionStage_Call {
	return &MockStageRepository_CommitCorrectionStage_Call{Call: _e.mock.On("CommitCorrectionStage", ctx, commit)}
}

func (_c *MockStageRepository_CommitCorrectionStage_Call) Run(run func(ctx context.Context, commit stage.StageCommit)) *MockStageRepository_CommitCorrectionStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 stage.StageCommit
		if args[1] != nil {
			arg1 = args[1].(stage.StageCommit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStageRepository_CommitCorrectionStage_Call) Return(b bool, err error) *MockStageRepository_CommitCorrectionStage_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStageRepository_CommitCorrectionStage_Call) RunAndReturn(run func(ctx context.Context, commit stage.StageCommit) (bool, error)) *MockStageRepository_CommitCorrectionStage_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCorrectionStage provides a mock function for the type MockStageRepository
func (_mock *MockStageRepository) LoadCorrectionStage(ctx context.Context, tournamentID uuid.UUID) (stage.StageSnapshot, error) {
	ret := _mock.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for LoadCorrectionStage")
	}

	var r0 stage.StageSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (stage.StageSnapshot, error)); ok {
		return returnFunc(ctx, tournamentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) stage.StageSnapshot); ok {
		r0 = returnFunc(ctx, tournamentID)
	} else {
		r0 = ret.Get(0).(stage.StageSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStageRepository_LoadCorrectionStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCorrectionStage'
type MockStageRepository_LoadCorrectionStage_Call struct {
	*mock.Call
}

// LoadCorrectionStage is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockStageRepository_Expecter) LoadCorrectionStage(ctx interface{}, tournamentID interface{}) *MockStageRepository_LoadCorrectionStage_Call {
	return &MockStageRepository_LoadCorrectionStage_Call{Call: _e.mock.On("LoadCorrectionStage", ctx, tournamentID)}
}

func (_c *MockStageRepository_LoadCorrectionStage_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockStageRepository_LoadCorrectionStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStageRepository_LoadCorrectionStage_Call) Return(stageSnapshot stage.StageSnapshot, err error) *MockStageRepository_LoadCorrectionStage_Call {
	_c.Call.Return(stageSnapshot, err)
	return _c
}

func (_c *MockStageRepository_LoadCorrectionStage_Call) RunAndReturn(run func(ctx context.Context, tournamentID uuid.UUID) (stage.StageSnapshot, error)) *MockStageRepository_LoadCorrectionStage_Call {
	_c.Call.Return(run)
	return _c
}
