// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb3XbbNvJ/lTn898I+pST6q2nUK8eOE7dJ479lt90mXgUiRxJiEmAAULKaowfY99hz",
	"9j32UfZJ9gAgxQ+RkuzGdk43dzIJAoOZ33yPPzk+j2LOkCnpdD850h9jRMzPQ1/RCR4nGJ6yIddPYsFj",
	"FIqieR8gCULKUP8echER5XSdgChsKRqh4zpqFqPTdaQSlI2cuevQoLQ2SWhQt0wqIhQGfb1o062lIiox",
	"ZCFLIqf71iGGfOdqafHcdQR+TKjAQK8zNKSfl8528xvmm/DBB/SVPvEwiCh7xUeUnePHBKVa5lBMpJxy",
	"YW6tFyMbqbHT3amS5DpTQRW+YeHM6SqRYJXGxUaNhJzjUKAcN5Ii7Pu+4tfI9IPVTCkvbzz1Qr8+Rxlz",
	"JnH5UOL7KGXjma6DNzEVKPuUWUBJX9BYUc6crtNDn7NAQsIUDaG4FaSftR03Rwdlam83RwZlCkcoHHOv",
	"1Vd3HfOmbx/nAHqGRKBYD6DSLavHlTYvXbiOqUcCicILIq8bBekThSMuZvr3NwKHTtf5v06uw51UgTt6",
	"k6Ns7dwtM7eGBwEdDqmfhGqjnY/z1XPXGYZkZDBObjKM7x4cuCsxP3edMU2NDlUYyXVKMnf1/qd26Z7Z",
	"PP8jXUqEIIYiReR1PxFh2d4I6rgOS8KQDEK0mlZzijYx/ZBGtGx+MoBFlNFII2SnDmyKqhBvzYsKouwm",
	"ZZm5ueRLwirRm4oiY20dxLQ9P0ZFaNist0GC4ToU6H0WO8xdJw7JDEVfM74s03WbnJkPLebz7coCrfDH",
	"0Fc5sumuNdsv22m70abuiYcTDApKNOA8RMLyd6s813r4aehuRErVSSxukW+yoLaJPStAcGv3PqSMyvGf",
	"vP6GQrCX3enfavlu/0EikHWI79mVc9eZUsYagbeGVXVhTIErpTsXApyFWEu3bIJHrymsyqVd4yBd5yWS",
	"UI1XgGtQ3JNfa9coBBe1mwkMqLzFesvr/gSFTL1d0Yh/t1804l6dEZdIpojB8FaHLnHKfBDgSJCglksV",
	"AeYSGjjZnYukLN2rTmY/8hXhaCJRMBLZIOeGRLHGlqPIdTIjjlv0WAdeyWHtuk5MlEKh47K/vyWtPw5b",
	"v3utp/3W1bffrLVLi2ObCf5MhhmlZkwe6N3dfpa3qiP8FZIAxYATETxnysZjlZCbsOu7RBDanfVzJ9P8",
	"eS12FVcktJ/3TWRgvfAtNaAIlTWZgr5l4YPKBeoJWsPQZkAgUyL9uVGAsSSlUhR54K0JNLLj6ui1gcVr",
	"XJX+aFPZ3ySaquTaC4+17jtLRB441UJ6BfnNxPsmFbmdC9zcu27gKS2Bua8sQnKlqdrATxbQujC7hQs3",
	"82vZH9LAhOofE0wM3CmzAq/zEWeCD0KMbPgtl1Pe85MjePK99wSMmwFkEwx5jJBIDGAwA5ygmMH+zU3n",
	"4OYGRCo7nQZXQzd9QNnMZ1eGKJEKBgi77faBB/6YCOIrFLJWoEwqwvyKx+iQmHYmOx2LLtn5wClzav22",
	"cUSp+c6/93Ze/na0+9PTk/3fX3z3t192Dg+fPbl49v9PDs/WVHayHfY9rybzj8iNtWgHT58W7JtZvCJR",
	"y+n6hYQ0IFoWcEJoiLXgXVQJFp+RAU9UdxBaQ1jJNtckerYqkOV76VXr4FdK5wvwm+LAYHcWK25PRyap",
	"L00IoSMFvW88ZcbiS78WlpWEvrA7EqkzzAgDmkQ6rSQiaNyiaEvKuDa1IphQnAIfAgHtIdpwMUZ4r/PV",
	"9zCkGAZAJXAWWpiDQJUIhgEoDkR/L11g5o3ikCJvGfl3rY7cxdo9RkXlIWsoG6fDifCxP6Qh3rni8tmq",
	"NWXcnaFo6b1BLwKzCCgDaSuLteXDO1Z3NvA5n6uos9ZTXcbB1yLi/2YRsQYLISdBz6hoc6y3XoXXpK6V",
	"75dRabIzPxFUzXoaAfZcW2E/TPR9PjkD89dJdvCPv15UtCVzJLbgDrYXsPWyt3vw3XYbTqVMbJh09qZ3",
	"AVmQYnxHJ+QjytpZDm2Kdra6v6B0rFSsOdazmZ/pbGSUlYl4E5OPCcLl5ekx0PpDi5FR2wSF+gSTi2jw",
	"mCjW+a2VntW6yFoFKQBj+hPqZMREYLb1VgkUn/cuQCZiSHyEIRegxghHFyfwGlFdxmAyD6pmbfgVBz3u",
	"X6OCWHDFfR7C1vsXzy+gM5Xvt98xKiHgfhIhUxho43h2fgz//tde+wAIMy5Z45Lpc0kYzoAnStIAQY2p",
	"hDcxssOzU5Ax+u137J1hmF7smyiq+44BtMBGzhIksgDeV27dhXeJ5+352ruYX/getqpcLbJzu213NVDI",
	"NtXnckH/sMeCxVW684epaty4AA6978JKd43ut2IUrYiyRCE8I/61Purw7NRxnUVpydlpe21P44bHyEhM",
	"na6z1/bae44pmYwNzGugaHSQW9OsNdEQfhpkEDdtRWcRQT/jgTGoPjeyMLllHIcpmzsfpDXH1rauTTWX",
	"+pbzsj6bBqR+YM2FucKu531eAsqdQ0NBGeKGQnjzU1szd9/bWXF8bNOqb29HRiUZqyHhlE10RgBZ97Vt",
	"7VgSRUS7Tuf5jT8mbIRG++SYCAxsqLr4wugmSS1VTKixN2QkTSFVr3Su9JZlgKQNxDUQSRu+9wmSSk/5",
	"i4TJzzgtsPcRwZIyKyWGWui4aas6cIHrlGbCr3EJRudcEWVBZD1bhoBb4mbRehthDWheUakuzIo/KbON",
	"6m5r2nlL3DsMQ5MVykeU4GsqJWUjLalUfGCDBCuHdimKcbpvy/HL26v5VVGqmt9AsmvBFlnkwC5Q5odJ",
	"gBJ0zLtdI1u3QfPz+YB70vvlAYSNtH7nsxFQBs6ykCyBQQoT7xFgUqgSmTLdXwaxlrVpeWZjg9P5RIO5",
	"jVBDVDXFn3NTyJGw7z0FOjRmzuTkVILAIQpkvg3JCLNxK0KQYKjD5jL4j80BC/CXALi/fK5dHnzR4tGU",
	"7T8CZZqJwLiCIU9YxqKnj0WISTIgkViHgltB2Mq8GcJuvW98gaoeVt6D2TX9/itUN4HqbfBwjiRI0aCx",
	"lY7GLPlaIkiEpgeiNzTJuk7e8lTdfFh2gm7hhuv6zFeuEyc1uMsrdffkzpdLgQ8cxK+DvSUwsB2Brz79",
	"r6uJVtCZLm7FRChKQkjsYyp1qMynGMCEEjg7vDh6CRIjwhT15fbtgpGOLUfaAewH0OzaSN0WXjXLbPF1",
	"pYJHSaioZklHn9cKiCJlwZXLtUMalqfyBpQR00JYXaY139XUZh/UItRWpGvQ1lNcYNCGLHzUcePl+StQ",
	"HAYIGA0wCGzF0pTpiZR0xDCAX3uAE2TqEa3Jz1wBgd9Pz1yIUm02DU5TBOBqjAImXw3O3aLUnb1HIOSE",
	"hgh44yMGFog7ngevn9mO4q0NocY/ELBWqqWVUmMFtv7zj3+mG2+b2rvUGgC2ZdmzY4AnvdWmUIfMeUaW",
	"xrqV7gULZzYJm3IwZtinMWFKArfJmd4DIjIDoYMnqn6wkJUwQgX73t5yYvYC1XE6kf0A9vbeLFPNZHwd",
	"FpIwtDyyUzZfluamc4sl1X0MjTkiYYhC+3VmjGEBaBZnVGb53WNZFy3uleHMciewIb0waJCmiLs1NHVe",
	"nzOGvioGLiMzAVtU1jCfTWzU1h4XylZHilOVcPy8d+RCzWQlHPaO2nBE/DHa5sOOl407mMhqxFu+fnlN",
	"Fbw6P7k0K23na0mnC7OT95kZ18191jkDHsOBl03+aI5MKZPVWvoFj1sHHoQl0ptFUJpgK/RbqkmKRKGk",
	"hrFZrw9fjNPZLqlMUL9nOIXS6DBsXV6eHm+34fkNlUora/paLtq2Uu+Sb6dNPkvDg2L8UyifpVRQCX4i",
	"BDIVzrSPqFROaoT6I6fMdmPvKd8sjp8/cFxZGiSvwY+998JApjM0ti1jui1fYlH5MUpyZ7XoMkOtP4BP",
	"mDaZAu1kQ6WRhSMqFYoCU3OdSRlfUMdsOLlOIe2Yb61JLCYE6d5aBwmbFeGvX8+MNi1cj1E/O4+xZOte",
	"432auKVR8dr+YWrb7Z2+7LDiLq7SXM9ILcXVhsgYm38lauxr2v80Ohqjf6/128o/NDW0MAOMkQXIfIoS",
	"LOEzI8mDlVHY5yblDUMtvUjnDyWStD4kLCdsXu5YTpChlPBt/pHNAqh+XJCPnEmFkZaPAYKYZAF/dYTD",
	"J5onZoo90vd2HTNeZoatup1OqBeMuVTd773vPWfuLg1wCh4kfjoqmX8qux1tMNqVIZ12NpOtoZfS+ilL",
	"PFJM6TPSJyYcKPxt86nCg/Sa86v5fwMAAP//DU0t9SZBAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
