// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes       = "BearerAuth.Scopes"
	SessionTokenAuthScopes = "SessionTokenAuth.Scopes"
)

// Defines values for ActiveDuelInfoStatus.
const (
	ActiveDuelInfoStatusActive ActiveDuelInfoStatus = "active"
)

// Defines values for AdminTokenResponseTokenType.
const (
	Bearer AdminTokenResponseTokenType = "Bearer"
)

// Defines values for DuelStatus.
const (
	DuelStatusActive   DuelStatus = "active"
	DuelStatusFinished DuelStatus = "finished"
)

// Defines values for HealthResponseDb.
const (
	HealthResponseDbError HealthResponseDb = "error"
	HealthResponseDbOk    HealthResponseDb = "ok"
)

// Defines values for HealthResponseRedis.
const (
	HealthResponseRedisError HealthResponseRedis = "error"
	HealthResponseRedisOk    HealthResponseRedis = "ok"
)

// Defines values for HealthResponseSeaweedfs.
const (
	HealthResponseSeaweedfsError HealthResponseSeaweedfs = "error"
	HealthResponseSeaweedfsOk    HealthResponseSeaweedfs = "ok"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Defines values for PlayerStatus.
const (
	Idle   PlayerStatus = "idle"
	InDuel PlayerStatus = "in_duel"
	Queued PlayerStatus = "queued"
)

// Defines values for TaskCategory.
const (
	Crypto    TaskCategory = "crypto"
	Forensics TaskCategory = "forensics"
	Misc      TaskCategory = "misc"
	Pwn       TaskCategory = "pwn"
	Reverse   TaskCategory = "reverse"
	Web       TaskCategory = "web"
)

// Defines values for TaskDifficulty.
const (
	Easy   TaskDifficulty = "easy"
	Hard   TaskDifficulty = "hard"
	Medium TaskDifficulty = "medium"
)

// ActiveDuelInfo defines model for ActiveDuelInfo.
type ActiveDuelInfo struct {
	Deadline  time.Time            `json:"deadline"`
	Id        openapi_types.UUID   `json:"id"`
	StartedAt time.Time            `json:"started_at"`
	Status    ActiveDuelInfoStatus `json:"status"`
}

// ActiveDuelInfoStatus defines model for ActiveDuelInfo.Status.
type ActiveDuelInfoStatus string

// AdminLoginRequest defines model for AdminLoginRequest.
type AdminLoginRequest struct {
	Password *string `json:"password,omitempty"`
}

// AdminLogoutRequest defines model for AdminLogoutRequest.
type AdminLogoutRequest struct {
	// RefreshToken Refresh token to revoke. Access token is taken from the Authorization header.
	RefreshToken string `json:"refresh_token"`
}

// AdminRefreshRequest defines model for AdminRefreshRequest.
type AdminRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// AdminTokenResponse defines model for AdminTokenResponse.
type AdminTokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until access_token expires.
	ExpiresIn    int32                       `json:"expires_in"`
	RefreshToken string                      `json:"refresh_token"`
	TokenType    AdminTokenResponseTokenType `json:"token_type"`
}

// AdminTokenResponseTokenType defines model for AdminTokenResponse.TokenType.
type AdminTokenResponseTokenType string

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Category    TaskCategory   `json:"category"`
	Description string         `json:"description"`
	Difficulty  TaskDifficulty `json:"difficulty"`
	Flag        string         `json:"flag"`
	Hints       []string       `json:"hints"`

	// TaskUrl Task endpoint. Accepts http(s) URLs or host:port targets for pwn/nc tasks.
	TaskUrl   *string `json:"task_url"`
	TimeLimit int32   `json:"time_limit"`
	Title     string  `json:"title"`
}

// DuelDetailResponse defines model for DuelDetailResponse.
type DuelDetailResponse struct {
	Duel        DuelResponse             `json:"duel"`
	PlayerTasks []DuelPlayerTaskResponse `json:"player_tasks"`
}

// DuelPlayerTaskResponse defines model for DuelPlayerTaskResponse.
type DuelPlayerTaskResponse struct {
	PlayerId openapi_types.UUID `json:"player_id"`
	Solved   bool               `json:"solved"`
	SolvedAt *time.Time         `json:"solved_at"`
	TaskId   openapi_types.UUID `json:"task_id"`
}

// DuelResponse defines model for DuelResponse.
type DuelResponse struct {
	Deadline   time.Time           `json:"deadline"`
	FinishedAt *time.Time          `json:"finished_at"`
	Id         openapi_types.UUID  `json:"id"`
	Player1Id  openapi_types.UUID  `json:"player1_id"`
	Player2Id  openapi_types.UUID  `json:"player2_id"`
	StartedAt  time.Time           `json:"started_at"`
	Status     DuelStatus          `json:"status"`
	WinnerId   *openapi_types.UUID `json:"winner_id"`
}

// DuelStatus defines model for DuelStatus.
type DuelStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Db            HealthResponseDb        `json:"db"`
	Redis         HealthResponseRedis     `json:"redis"`
	SchemaVersion int64                   `json:"schema_version"`
	Seaweedfs     HealthResponseSeaweedfs `json:"seaweedfs"`
	Status        HealthResponseStatus    `json:"status"`
}

// HealthResponseDb defines model for HealthResponse.Db.
type HealthResponseDb string

// HealthResponseRedis defines model for HealthResponse.Redis.
type HealthResponseRedis string

// HealthResponseSeaweedfs defines model for HealthResponse.Seaweedfs.
type HealthResponseSeaweedfs string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JoinRequest defines model for JoinRequest.
type JoinRequest struct {
	Username string `json:"username"`
}

// JoinResponse defines model for JoinResponse.
type JoinResponse struct {
	PlayerId     openapi_types.UUID `json:"player_id"`
	SessionToken openapi_types.UUID `json:"session_token"`
}

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	Rank             int32  `json:"rank"`
	TasksSolved      int32  `json:"tasks_solved"`
	TotalSolveTimeMs int64  `json:"total_solve_time_ms"`
	Username         string `json:"username"`
}

// LeaderboardResponse defines model for LeaderboardResponse.
type LeaderboardResponse struct {
	Entries []LeaderboardEntry `json:"entries"`
}

// PlayerMeResponse defines model for PlayerMeResponse.
type PlayerMeResponse struct {
	ActiveDuel *ActiveDuelInfo `json:"active_duel,omitempty"`
	Player     PlayerResponse  `json:"player"`
}

// PlayerResponse defines model for PlayerResponse.
type PlayerResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Status    PlayerStatus       `json:"status"`
	Username  string             `json:"username"`
}

// PlayerStatus defines model for PlayerStatus.
type PlayerStatus string

// ProblemDetails RFC 7807 error envelope used by every 4xx/5xx response.
type ProblemDetails struct {
	Detail    *string `json:"detail,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
	Status    int32   `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// TaskCategory defines model for TaskCategory.
type TaskCategory string

// TaskDifficulty defines model for TaskDifficulty.
type TaskDifficulty string

// TaskResponse Admin view of a task. The `flag` field is only ever returned to admins, never to players.
type TaskResponse struct {
	Category      TaskCategory       `json:"category"`
	CreatedAt     time.Time          `json:"created_at"`
	Description   string             `json:"description"`
	Difficulty    TaskDifficulty     `json:"difficulty"`
	Flag          string             `json:"flag"`
	Hints         []string           `json:"hints"`
	Id            openapi_types.UUID `json:"id"`
	SourceFileUrl *string            `json:"source_file_url"`

	// TaskUrl Task endpoint. Accepts http(s) URLs or host:port targets for pwn/nc tasks.
	TaskUrl *string `json:"task_url"`

	// TimeLimit Per-task time limit in seconds.
	TimeLimit int32  `json:"time_limit"`
	Title     string `json:"title"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Category    *TaskCategory   `json:"category,omitempty"`
	Description *string         `json:"description,omitempty"`
	Difficulty  *TaskDifficulty `json:"difficulty,omitempty"`
	Flag        *string         `json:"flag,omitempty"`
	Hints       *[]string       `json:"hints,omitempty"`

	// TaskUrl Task endpoint. Accepts http(s) URLs or host:port targets for pwn/nc tasks.
	TaskUrl   *string `json:"task_url"`
	TimeLimit *int32  `json:"time_limit,omitempty"`
	Title     *string `json:"title,omitempty"`
}

// UploadSourceResponse defines model for UploadSourceResponse.
type UploadSourceResponse struct {
	SourceFileUrl string `json:"source_file_url"`
}

// UploadTaskSourceMultipartBody defines parameters for UploadTaskSource.
type UploadTaskSourceMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// AdminLoginJSONRequestBody defines body for AdminLogin for application/json ContentType.
type AdminLoginJSONRequestBody = AdminLoginRequest

// AdminLogoutJSONRequestBody defines body for AdminLogout for application/json ContentType.
type AdminLogoutJSONRequestBody = AdminLogoutRequest

// AdminRefreshJSONRequestBody defines body for AdminRefresh for application/json ContentType.
type AdminRefreshJSONRequestBody = AdminRefreshRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// UploadTaskSourceMultipartRequestBody defines body for UploadTaskSource for multipart/form-data ContentType.
type UploadTaskSourceMultipartRequestBody UploadTaskSourceMultipartBody

// JoinPlayerJSONRequestBody defines body for JoinPlayer for application/json ContentType.
type JoinPlayerJSONRequestBody = JoinRequest
