// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/domain/game"
	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/game/settlement"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSettlementRepository creates a new instance of MockSettlementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettlementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettlementRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSettlementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSettlementRepository is an autogenerated mock type for the SettlementRepository type
type MockSettlementRepository struct {
	mock.Mock
}

type MockSettlementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettlementRepository) EXPECT() *MockSettlementRepository_Expecter {
	return &MockSettlementRepository_Expecter{mock: &_m.Mock}
}

// CommitConcurrentWinnerSettlement provides a mock function for the type MockSettlementRepository
func (_mock *MockSettlementRepository) CommitConcurrentWinnerSettlement(ctx context.Context, settlement1 settlement.SettlementRecord) (*settlement.SettlementRecord, bool, error) {
	ret := _mock.Called(ctx, settlement1)

	if len(ret) == 0 {
		panic("no return value specified for CommitConcurrentWinnerSettlement")
	}

	var r0 *settlement.SettlementRecord
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, settlement.SettlementRecord) (*settlement.SettlementRecord, bool, error)); ok {
		return returnFunc(ctx, settlement1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, settlement.SettlementRecord) *settlement.SettlementRecord); ok {
		r0 = returnFunc(ctx, settlement1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settlement.SettlementRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, settlement.SettlementRecord) bool); ok {
		r1 = returnFunc(ctx, settlement1)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, settlement.SettlementRecord) error); ok {
		r2 = returnFunc(ctx, settlement1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSettlementRepository_CommitConcurrentWinnerSettlement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitConcurrentWinnerSettlement'
type MockSettlementRepository_CommitConcurrentWinnerSettlement_Call struct {
	*mock.Call
}

// CommitConcurrentWinnerSettlement is a helper method to define mock.On call
//   - ctx context.Context
//   - settlement1 settlement.SettlementRecord
func (_e *MockSettlementRepository_Expecter) CommitConcurrentWinnerSettlement(ctx any, settlement1 any) *MockSettlementRepository_CommitConcurrentWinnerSettlement_Call {
	return &MockSettlementRepository_CommitConcurrentWinnerSettlement_Call{Call: _e.mock.On("CommitConcurrentWinnerSettlement", ctx, settlement1)}
}

func (_c *MockSettlementRepository_CommitConcurrentWinnerSettlement_Call) Run(run func(ctx context.Context, settlement1 settlement.SettlementRecord)) *MockSettlementRepository_CommitConcurrentWinnerSettlement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 settlement.SettlementRecord
		if args[1] != nil {
			arg1 = args[1].(settlement.SettlementRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettlementRepository_CommitConcurrentWinnerSettlement_Call) Return(settlementRecord *settlement.SettlementRecord, b bool, err error) *MockSettlementRepository_CommitConcurrentWinnerSettlement_Call {
	_c.Call.Return(settlementRecord, b, err)
	return _c
}

func (_c *MockSettlementRepository_CommitConcurrentWinnerSettlement_Call) RunAndReturn(run func(ctx context.Context, settlement1 settlement.SettlementRecord) (*settlement.SettlementRecord, bool, error)) *MockSettlementRepository_CommitConcurrentWinnerSettlement_Call {
	_c.Call.Return(run)
	return _c
}

// LoadConcurrentWinnerAuthority provides a mock function for the type MockSettlementRepository
func (_mock *MockSettlementRepository) LoadConcurrentWinnerAuthority(ctx context.Context, scope game.SubmissionScope) (settlement.SettlementAuthority, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for LoadConcurrentWinnerAuthority")
	}

	var r0 settlement.SettlementAuthority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, game.SubmissionScope) (settlement.SettlementAuthority, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, game.SubmissionScope) settlement.SettlementAuthority); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(settlement.SettlementAuthority)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, game.SubmissionScope) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettlementRepository_LoadConcurrentWinnerAuthority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConcurrentWinnerAuthority'
type MockSettlementRepository_LoadConcurrentWinnerAuthority_Call struct {
	*mock.Call
}

// LoadConcurrentWinnerAuthority is a helper method to define mock.On call
//   - ctx context.Context
//   - scope game.SubmissionScope
func (_e *MockSettlementRepository_Expecter) LoadConcurrentWinnerAuthority(ctx any, scope any) *MockSettlementRepository_LoadConcurrentWinnerAuthority_Call {
	return &MockSettlementRepository_LoadConcurrentWinnerAuthority_Call{Call: _e.mock.On("LoadConcurrentWinnerAuthority", ctx, scope)}
}

func (_c *MockSettlementRepository_LoadConcurrentWinnerAuthority_Call) Run(run func(ctx context.Context, scope game.SubmissionScope)) *MockSettlementRepository_LoadConcurrentWinnerAuthority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 game.SubmissionScope
		if args[1] != nil {
			arg1 = args[1].(game.SubmissionScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettlementRepository_LoadConcurrentWinnerAuthority_Call) Return(settlementAuthority settlement.SettlementAuthority, err error) *MockSettlementRepository_LoadConcurrentWinnerAuthority_Call {
	_c.Call.Return(settlementAuthority, err)
	return _c
}

func (_c *MockSettlementRepository_LoadConcurrentWinnerAuthority_Call) RunAndReturn(run func(ctx context.Context, scope game.SubmissionScope) (settlement.SettlementAuthority, error)) *MockSettlementRepository_LoadConcurrentWinnerAuthority_Call {
	_c.Call.Return(run)
	return _c
}
