// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3tehs3sjB4K3i458fMGVKWHTtz4vd5fyj+SDzHjrWSMpk9Yy8DdoMkoibQA6ApM3l8AXsfe2V7Jfug",
	"AHSju9GfJCXZoz+TMYUGCoVCob7rj0nENylnhCk5ef7HJMUCb4giAv51Fm8oe3F58fqKXxOmf4mJjARN",
	"FeVs8nzygvNrSmYLnrEY6XFI6YFIkH9lVJAYLblAak0lwnomtMkU1p+eTKYTqidYExwTMZlOGN6QyfPJ",
	"P2Z6lplZbjpx80yeK5GR6URGa7LBGo4N/vSWsJVaT54/e/xkOtlQ5v79eDpRu1TPJpWgbDX5/Hk6OZOS",
	"rtiGMPUm1t/D6ilW62JtnA+Z07h18SUXG6wmzydZBiMDy2UxVWeR4sJb7l8ZETtvPf1ns9S4qf+bso7J",
	"r/UIf/r/EGQ5eT75Px4Vp/7I/FU+uiAyS7yZ88VeZEJyoT8nn9KEx8RhJLRwZAb3XdRf4PN0ItUu0bPE",
	"hKTvF7+RSE0cFK+YomrXjE4Cfx+JTzN5G0Lt9IMwWp26WG5LmLoCUBpW0wPmAGwD1X/7tHEz76MoE4LE",
	"rwXfNC3A7Zj5Ug8KYizGiswU3ZBJ50pXvHMdxUevco5X5JL+3oisFK/IXOoB/goxWeIsUZPnz06nxXKU",
	"qW+eTKYak3STbSbPn5yeAvcw/yp4B2WKrIgooDDX44JgyVkTJALGzIUZ1HByT08bd3rFM6GnKnGpyhoq",
	"H7M/m/oBb0gjP1zhDTnAEjyJCTtTimzSFt5r/r7/cm9iskm5Iiza/TfZ5atV3xlv2EyP22/R9ykRWHFx",
	"QSK+JWJXMMzyc/kWS4W4HYyEHY1usCJig8U1WpMkRosdUmuCooQSpk7Q+yQmAnGByL8ynKAtTjIikSAq",
	"EwxhtBRErtEySxIkGU7lmqv/hbAZhrDeN+JLmBBnas0F1S/wluSDEdWTaU5LYoQlwkiQLZWUMxRxtkxo",
	"pPRrfXjO34C0xkfgHAtFI5pipup4Pjx4zcs1Q5jgHREt4tKFE4tu1oTBmWiqI1KhCAtBiUSYIfKJSkXZ",
	"CqUwHZJE2tPQslZfyanYZJ1cz7NFQqMuYn0P/wcnKIXhIXK9oWqNUsE1Aihn85xyMIuRecKk3iCLyAl6",
	"R6WkbDVFmiGIaRNFc0ZCNH2C3iwRoWpNhKVtLVT65B1nAi8SgiQRWyIKKKclRJtVJPrx6uocPT397gRd",
	"afH04tXlFTIUoieWRMvBSkPCN+gXsrjk0TXRX8sMmOJxrkTwYBrJzVFTJ9ldGgrqI6Zbmrs7Of2S6HvQ",
	"+E5I+PP+z0TwoS0vdch3tljuLZWePN2TZjwkPj598rSKxVS/nkJP9X//82z2P3j2++nsu/ns41/+owOY",
	"OxesClAuFVbkNU0UaUSM1EN636XK1LDcL3jbLO7c4O3e4s5n/bFMOZME9OfXXCxoHBN2LvgiISCNR5wp",
	"wpT+vzhNExrBTXuUmhF/+c2Klz05hvnqJVGYJtJAUL78V/bl1/pLhPUjT2Ojy6AER9cS4SgiUp6gd/bO",
	"SxRhhnAiOVpimhRvVcE4NPOmKwr/RYIsiSDANinb4kQzx1zuu8iYlu1fWEniWGhoXawBKeYbJMxHudQz",
	"RYLgeIduKIv5zRQpLFZEwU4jvtnoly1HoH4pFE6I+aNZlbIV7P+NwcWFeXfu9vwd4CneJRzHaEt5gpUW",
	"N5AkG6wpo3ggs4TABn7i6rV+MO4WdAsWiVHBj/UzzDMREXSDJWJcoaUGFKA+z6WRC3ugx6a9+oodhEc+",
	"pUba9nZUCFGF+O2oC/Z1gRV5SzdUkfg+8ZK0kJIR+RQREut9eSQHUlSiAdeyhBEjgDVeECV2s7OlZfhV",
	"iSXiLJZI380E5vMX2uCdluPEzl/pJGxeyJ+ltofos5WmiLTWmivO3+p7fy9oHy14vLPYlXbLbElXmZbc",
	"/nb5/iekn2iH5NKrelt3oL7iiDsQJvyfmdVbf79flO/UMirRxmk29v0zus2nVMsQdg9uv5egnNzdPt4w",
	"LSnixGlJ+oXPBDHvuKE2/RryTAFf5VrfuqGSoJhHmT6lfEcyS1MuFInfkZjiq116Ty6LXRrpS442mb4+",
	"BPlA6MVPQBy0C+SOjrd8RZnlAwB6HFOjA58LnhKhqJbqljiRZDpJvZ/+mKRYyhsu4oq0/uTZt90qTyFu",
	"/rOY52M+khdmcA2kVeYurJgJi5dAMYQn55T14avGL2NkwJym7RSapTYz0tOgRO9vxoMkuB2h6BJHylnd",
	"CdPT/tPYHY0lVfN0o/HJiAtS/LP4s8IspmwlJ9PJCiS6+UrwLNXCOU/nS55pVWohsNbfJ9NJtMabVCPj",
	"Y+0oppMzpQiLMYuI0Rk8oCjb6rcXtIMVlYoI+Ee0JtE1ifUWp5MbqtaxwDcNk5ddKZWDUWC7uCY7SZQz",
	"RHAR62XQYoesGZ1FBO7nFGE9m7GxoDcvp2BxoRutt+t5DHoKjvrmpT7LMp3ADHNjpaFxD+1mWhjzsepr",
	"w9f4MkD0XcRZfOZgrgjZpfC/MoJirPACS8+QacwbqSCat1G20tKtQYdBltZmEY4El1JzCYNQBfIDVUDs",
	"JSP9dwOvro+caRW7ZTTUNhm8HnW/VOmGWJN5fieaiQ68TSFrZIzhDS7oxiIqF0ZP0AW+QdQ9Gk5/oBIx",
	"op8PyqIki0kcoC7n3AwcOcuSRC/n9GutcL1nyc79u7YLz5k51Ic57UHnnetHgug3v43sO+co3JNjIPC9",
	"j0OdjlPfm1h3InauTeXc3hX9dcPwBecJwcyOl1lKhNTKQL9P+jCWTjj5ckkjipN57oVrZTyd8wl7P+aW",
	"7Fu2Utxau/Ze5Fb2Itadh30nkO4RG/69xRzLNgujn/lywLdPKwpVw4S5XDCdCK6fzLEIKay+Y74uG3LH",
	"zHBDGSMH4maVV6P2TtTMzjnmphXrd5nQpuWQDy+4pBRLUCPqaeXh8nhdhZCmNfd2gZf22zetRE/4oRpV",
	"WivxmyozaXwnz/EqJApvXVgTVWQj+3FOeCw/gzDwxnwFlmy7LhYC7/SfGfmk5lEuzuEkeb+cPP/ngGiX",
	"j3XaqWyuKk+b7ZTXDqHkBVZkxcXOlxluyAJOd5dCJMaSC8IkjaQ5Ao1g/YbfgO9QkRVmfCVwut7pX9NI",
	"H7CkcCIbvqCJHrzGIr7BIJVvqIzq8sd08mmml59tMZC01HA42H4BeNy/Xji43A+vPfjcbxc5nO6Xc4DX",
	"/euyAnc+CuB3/3pv9+H+/c7tx/3wY7GvfAzs77P/UVxSDwRmMcTRgD41mU5igZcqKJK9sMYb0EadDjRQ",
	"3ewpSjtxoT1sSE9OtpRncj5YVlf23jk8yBsqC1UMWNaGLinDiaY5+G8IJzIDBZSLgRBULohlL4ZXAmgN",
	"e2taMXiZ/PPyogLOMRUDj21JhVRzz5TZG8+gtw//soKf4PpNs3fi4meW8Oj6TWHpaUNEWfV49QlHoHml",
	"WJAZZvFMq71kS2NQcZdgjkoIlqDGMYSXS2MuNMpd7psuo3dBwRQwj+nKWnAqhO+pc/qfvt/0dPYdni0/",
	"/vHt08//EToBB9txJrfWwXlMZZRwacTmupicj3M02ymZ1SWxfI6scRl+0yzthGRNdyK9qRmcN/td9cqy",
	"HtDB+UO4q+IieA71k59W6Sx8UYQwKvQr+3ld/36Tq91RPhqibER8gs6SxHcKYRajDO5bcUsgcEthyoyJ",
	"CKJi6pfCukfGir5LSpK4vwhV7Pu1/rAsR30DtGn/0aw25CKWC0AcA7eLshuvgznlq992bVyopVLwWO6l",
	"zO6n8liRGay5Yw6v8GleejNZvLSe2f7KliHzOYV3ZQzwpXepRIDGqNe1BfDhGM5yAGY/TB30bmtdFfTV",
	"vyI416f0nG7zi1uhx9DuquRSO4J2Bmcuuq9pgFYYUBclT7ZkviEKx1jhBuE4J0GsonVdpet3L3/AG1KK",
	"1/5cW703OV3q7965z4zQa8wqXRDYwKOB9oN2AilU8YAO3ojg0LkVd7wQ4coP1Eugjxlnyc5/i1xwIDL0",
	"YWzE3t99KzFXiHxK9Utaf5liEg1SNoLSz7DIjFxxH6ro2D0dQfqr+8xqYkoN4mkJdzXo+p57ibfXbhq2",
	"qmlfFOXjexmpfd+fr4F2EMVg10Ff1baHQJAmOCLAjTuA7PE891R3B9oSSycwLZ3gQEW44USa0dBOc0XW",
	"TG4oiLgg14SkWpAmQkDE65YIuqQknstsAUEVQP75AyeyRG+7/d0os+uASfCIehzw31a5r4PZ6+NwOz/M",
	"c5FDVJ26rti0H2FV268mgm7ShCgyQKfPWK5lTVHGtAp2a+p9t7/tgGTSvdiD+n8Mt85AA0JV2r5nBgVw",
	"y1xheT0uQCnyXAKtkXxYXufug2qg1R/tARHTSUyXSxplieq1zstiNLi4NVuLSxkGTf7iZYJXtVCrZ9Mu",
	"8Na0qlF28uOS9aKkKU4nn2YrPrO//fPjf3peD/v7TF7TdMZtItUs5RBJYdbyzPP9fEcaY0Zc+jgtMDRh",
	"muoTuBBYXs8zkdS5s/4UERYDACfoLIpIqiRaK5X+Sf4Z/XzxViIu0JpL9TzlQtmgdwlMO71hj1iE9OwQ",
	"JNOJMv3UzSEadXAkrv5YJWTw0VbutpmkTLzT4gqU6LQEr6WslgvoBbqOuoYmOvEgHLzfHKehOUzKSzmx",
	"6Mlp5/1JE8yYXtn4pKVNHWrOAXr8rQfJ0xAkEK6l+scXn5vx+ktIlrO8v/lxruRHmeSoj3/50yz/v3/+",
	"z3FqmQXdYtMHKIypaf30g4RmfN8mq685zNNk6nWqwOVZauGmZpIQGC9JQrdE7C5IRGiqAvphqVxGLw2x",
	"SPLuMzw2EOxpSO2t4A93yrkYvp7jgT+PEVVMdEelOkkpY77u0vNgK1au4DR87ClhWjzZXSqsMhlwW7DY",
	"jnG57FqgXxOcqDX4KZTAmrtCHhVlRJpnhDPiB/vH+Tp1Qd/M5WuL5hfg3GQlcAxy1BLTpBQT0hZ2UN3X",
	"jzDjj/m84b+/LFYLD3htYbCWcdhuKS6A4BhSGDnYQeH/Q27DSLAv3CIXdrLGAT9x1Tnm0kBSpTeLf39L",
	"QVIpCXtuxwRLveaGxDTb2CiRvpvNJ3xlJil+eOemK376ESbWcECoRZ0/gdra34EA05zBRxWvQd1FMNqR",
	"7wa0g2KSoF+bsQN4GOdJf3+JJ+QXe33mu+jqEm/G6L8yYv9spdg9RJmxYQ36y8S8x1aoc3Ex43feb7Ot",
	"brlQeEy3pwDoLncVqEywMWJzJtg8JjhOKCNjrU+hZ6cccpjLPnb66bCQEkui09yLAbutQj/Nr274nIO8",
	"yLu8DZxgwP2Hykyfp61B7PUg8Z4atk9+B4l7PirJDLNA2/P0gk8t7kvaVzngtAxHx+G6mlnutVlgkMRp",
	"dB00C3t3y/tIw7Q18rixWsbBj18L/jthLz0MVaK54O97HV0fV8k5ziRxUDh/icm/x8neBzjY3LfBlFG2",
	"mhs+26p39ggLh3oqgyzmvYLf9ZyDuWHvsPi94+HDYYuewbF+vFOP3CrHUEJjYP8e4KHb9YO1BVSyrBhB",
	"VsVAlBWpVEY0QTLh6gRdEK1ASrQiCmHEyA3Sk6E3L0EPMMFJkGWoh9uqORXWbLUYxkdwsP4m6nI6RT97",
	"Wz2G4GMP41e/3JPBpGcReDip41jxCeb1T3hFS2Xce/Xb0ggC+Gsi2mpBvty1CD4vcHgJoRUf4TsRl1ws",
	"CZj6GJ/DUKcg21xo8y5sOJunCVYaG95fYiojzpiGYjohn0iUgQOBpDxazxeC4Gs78ZrfFNJThFlEkoRU",
	"3Az+zzERdOvZl8JZD8Uhw/klPKT3GJT3l4eBAXyuKzljBJremoqkKsBJy9bDbzr1h4gLMl+QJRekn051",
	"CWnEAwX5Lrk4301JyikBNy2OpYmca2KKtSHaN3xnhSmg1xRbB1MhwUwnWw7Q+FTVRUQQpf8+JSOz3nOr",
	"aKAG3F6WbVOTZ7yFu8l6G4Kzbd3gWTmkAT/5AZLNh6FtsB300IIMZMj3Xd4M3tdbuyGbha380o8p+RWd",
	"3sHHZX3duhZciladfblbaSrcDpcu8u/VGNkEruzcFJEaHXI06Br0ysOUCgt1YIG7n7zhn2dRkc2/pTlV",
	"hmiuYvDORYkqiuqYr1JC+WRLKPHuWkGx3TzAd9IMYAOwyaE3osx3Aq82X0Bplz1NCvvFVlRDKexOy8A1",
	"47VUenUUao/NYW+Box7CQ9VPzCo5aR83brbK3MLBQ18P3zscn7Ohd0o1RVxp9WOAYuovcaU/7ZFKfPA7",
	"XTPtHo19536zHIklkbuJfwNSm5kMOMfGib0DuctIsfZx682zSoI+64/TcfewKz7OYL0Z+mm1ant5xRbU",
	"NxYF7XcBqgXBplUV2JYPmLcfVOeFd9P0wGX/ufZVbbwT2XN7XkzL/vs7qO5WoZuPPcq35rVZvZKsgmTS",
	"1FSnRbl/dE12pnA5RjFdLkleBMov7VovYWt1kKFl4e7oze5jerecpLs6T+n16hpeK2hXeSZauXknz6gb",
	"SQRJsQhbSRSJ1oxGOJmDvaRiLhlsJ/Ff3GHp7p5AO5N4SbyKW5aMi+ieE/Q6wSu0wYoIipOi1paEf9Pf",
	"g9W2Bsdi+ca9gDw8Puh37zApG2y9pAmZ4y2mlq6rDopf1gSaAah1KzrRGnpa2HrBWERruiUonxepteDZ",
	"al2rMRvzGwZZbHnY7GTaILkNiv+y8bkDgmjnxpfuhxU9/q/Tj4HSjC3RtLX5t0TIRi7TXrS9lHJUiUpr",
	"ijtzy01Hx+bmaGiikGbecaklxD0tnIeS3fYRydpEsf7S12WeBvRlSr+DMOi9M/NRSQPVfKrybAcWj01M",
	"YXPMb7zwnz5+rdeH1Ll+8XXl6V8u3usJqj++MhOa+ndUHnDBCz1fYE34vVjWSPnzBgbVQz6WBN8QEi8P",
	"CfulmzMAf/43bw957Gxp/Tx4dRQIMGdoffhDHqr6sazru65PnW68WuRveZ4o4dH1nnPwTC34pz0nKXw4",
	"e04kNBbphuw9jWnXs+c0XsrrfhPBo2vjvEcAFag3kOlHN15MHEvwr1jtvjYQX9NeW0APkU74AJvoI0DA",
	"4aMLMeM3LAJt8PuMxQkZKPG/wIyD6oFcwUVTqd8U2F3AlFCq3ITxIKzQhkuFnp5+962p6iwhhgYz9OO7",
	"sxdF7XmqdoiwLUl4Gij2g5OVRvd6Uwqe3+BoJtf4ybNvZ9vHeq/dBW8d+HOvknt5h99jSb59OiMs4jGJ",
	"Uf6F2ae3NcbRhgstaWNm9pejxCtiXS42vtipXn6KGpxzgEf/tRQkqEEdt/F5YkWDvU3Q9alVJZixWqW+",
	"F8QrwojYuzrxNdkNzaTKO019LP7vyXz28T975TxvcHTcpOoxIQk9/AhwjY4L+b4llLoM98EYiBIZhRhA",
	"IwG33sKWG5Ujc+qxrZwSDYWE+PLfOGUurW2M/pJJIlz+I/mENym01lP4Otvhcg34Z+WMyCe1TMKz2f+0",
	"dlrzjyFftmtP7Ql/oxTH4tPQ4m+hKc+CYxG/YsrIDJVnZUsEtIKD+kKg5vQI/w3ob5hdj4il8E8sVJtZ",
	"ts/ZHR8EcHnr2FmnDRvvQGJLaw6mBmWq1E6mnKtTq0pctRfY5YLw8uj6ApJTRyYy540v5jl1lTfWqZk3",
	"xfI87ZWJc+DYs1SQZUJXa7VfWcqOSLPwKtMGbIbO7R1mGU7OMRVvWJqpf7cCtO9tlXEX+1ucd1NtTVeX",
	"vNYTxSWlQsg6Fzayfb9OFoftXLFn6c6W8pnd8SymB89tRMzDUnlsRf+VbHBFnyXG1hAVMVSs7nqxusXG",
	"vlXIRqSkRFzE+9YahUjlgaANq1jaNHooiZlLOpzIXBepYWRmY8b7E5r1TASY//hSccD7erGQMnO8NF86",
	"ZjI0/OfwWSENBejcLZuWi5+WNt63FmpTCwyPx5R5W4UyqnRZKa9ZuyddJ16+oN0Pmn9mlX5P7X2eXFio",
	"X3JvZH2aJRWbzgpkBwv4TzDDuZ95SK/w45amrgWTu2q0Pesnw/CyFWJ8QeNapdZA2O/4etVHr7fcrqO0",
	"C8wFPXolb32y8QodmzMKXjJ7O16b3C8tPbyCdXPSG+H/HJWy2CKT3WrOX9XKnyfseby0nrrXA7cjfcrD",
	"exEusCx7J0WWkLnpbN3U37GLu7nCfAdTZR8PU2Vzd8lBsqhW1mTST9bpuCO9QoxtbiVlqzE6ptf3c29h",
	"1LiLhlFUf6mtpVvAoOavU0O0Yw3vJ/PnYdNjT5H+UCJ8nxM7doqJLw82k2Hzg9J4AasXynGe4uwqjKOZ",
	"kBskyEY0BrqIVum6kWrbWPVP/HLNb44rIB6WlVXVt95KmzfHDd4OvxHF1yZwZ+j3DaQw+nn5ZvjrEuRN",
	"feTrr4+HTCdABP3137GRelXu5Jb1Jy3zrH34Uo2y2+m26V61UOtQztXGfS5s0EXRCntAXMUvWBGxweIa",
	"RThVmSAxWgq+AUOuQxJWdEuQK/iAXJBH3ii6qRW21Awx2KnpJ2hNifgS4TQlLDYtMbxqhn4gA9JoWCQE",
	"udon3rID/WVhJlqG7S1WRCqU16LI0bBDCcGS5AbvKeImWtqDOzeGmzIF8Gew0ddmIZ+oVLJ9Dw2OlaCl",
	"oBIuY3txx5kwUdkFiF5jEff9YCiq7tCgqhm8YxXK6EPXl/a8Bz6slX6ifUT1yk36bOtCzKEB5oB0Kv3R",
	"D/BNLynf1LTt9GeYUTmP721YMO93yMZRUEX/esGO6fdf/xe8DZRDaWTweYveiVso33H5PLrbthbnmiZ4",
	"bG5iEZA/MFB7RA7JnciCUcJlNkIwMeVi50MsMDyxj2t/NXBwfHrpm4PonX1kO7+NyxCM+N8Nw0zluyOL",
	"lQNMZwdWRH2aKYt4XlWsStZMhTT3kwZD92PawBfChBA+5o5DbMzcDtF2O/eDGhFfPvsrjALDVM28bdMh",
	"uGVtsuHgFIg5CECHfQxs3thxJhuMK/JpjTMJkmV78EbzFGsq1aE2VJ1rMDAp58lBIClNNKLhX9Gr5zCd",
	"M+rzDQZqaF7rUGFCMzYuRyyUfzgkOTX/aGxi6D6Gpq/5bW96ePd54sNspoNnt93GxivfwUza+FbXI9T6",
	"4vW4rF38oYuxt74igVsUuCMNl7SBSZRFgpAIdI6ppsNSl/2+clDZoGLCRNGGxwRZipbIVT9AG/jrPDXL",
	"5ZlG5FOa0Igq5EwAaLEjUOWXYEVipMdLhIWe8jfYX6Dd+J71+Acat/OT0zvtu9A7Pfbw0SwWq4sdCXg/",
	"y8dzYZkMBKFihngcI2NFgLPYZFIhyyDAJhcTRYReXSoaoSWmYrbYEWSq40Mwq+AbZGvMIKkw9JMrm+v6",
	"uk4rxNH7GKuRySW/xX91FWs0q+XHmKdEZYpvsKLRxAEWdOwLnrF4zjJXoqW5cMrTQZbCjuiU0rKVTVRp",
	"czrpaGHgFQkJF/VlMbbW6dbOuvnI3AUWQeuy22mjNCBJxRnO+psASDysKk6gIMZgj1GWxnsiLxQLWey8",
	"HtpY4NDueeoff+k4S+B1ENVZLhMM1amhnk7+lHX3K8iXvMLyOjeHD28A1tu2lHcoa091Ljc0g9C3vC+n",
	"lSHIPOIZU+1k9mRQclG9+l0VoW2AFNvrfbxja2aW6KPnCXtENTLncv87Oirf0dttB2K97iMjbVJj28+M",
	"KcBedJzV8x1Gdz9sce9R7WpGFvSuIKEKRag9TQc1vOWLxW7kDTsMIu3TkfDousn0ONDjVt1esweuVwBO",
	"4XwrulodONjLxis0SWU+ggJh880He5kjbkhS3aiebjw1I+YxlfrFnwd6sn77dH9ryYiQqf5WqmoYsW8R",
	"sWeUdwoLb7hYreN8zrlULvtnPy5ctIG6ZvwmIfHKBb1MzHaIVHPw1XqPxHSSEA1ooskkqIMclF8O43d2",
	"bwMwOE5CgL7RWtg8Ni4Pwyn36PFRau/RgPMyMjqQv0e54QM/xI3FuwfqvjBN564HxXpV9g1Brn5U1sDw",
	"Kd8Ks6XkZr/88INf6oYU8Uagp1WM9ET+yICksj7QN5QoqBn0iSqKXRfXfiuZpq+9ZjZsZqAMVLTMng4J",
	"zWqm/QNztaFJrMepEW9e7/6wmNiqbkhGqXTmnL3oK4DNUVZJ5euOxfIO8hJSPF/ThIx8N8mnlAoi98vR",
	"9mqe2hqyZZPya0HkGimySbnAYod+vniL9H5JjPAKUyYVWJIj61sgMTL96pFUXOAVQabnYNlkLGj3S1kB",
	"bOpvtwuze5YiPfDL2Foq1OQytnkyp5MbQRUpjnHgi1pZfgDu7lAb7V+20Ac44iLu+R56C3RixLb7+xJS",
	"n5ud5XsVmCk20YGskmn2YNXMFZbXRcA7esMUEQwned3thJvydnKKln6V8ym4vTwrKLJWUONuJJ+iJItb",
	"3I2DTGSV6uYd9cxbhZBi5OfpZE2r+dP1eISKPaVPVQd9Uq6Iw63WUneLffkl1Md0xz525fTuSumu8sXI",
	"gukTR5FDCqbXm037GdZeOKfNFsrFq5AWbxILrFmrUsn68D0N8Yb07XRqWiQfuejQIatOHsaQYQ/Mey5K",
	"PaI9nDSSxg8utaTMQF7avB3Id/AeANsyA+n/ESbOJBU8IlLO9FOQ2A+KZKN2bm8dZyarYmwjHp7pV2mI",
	"dTyTRIss0Pb3hfk8xMwdMuVcZmkqiJT9OqYcU/e1TcNz0HrvutL8PrDdlSlTPgSLTZ2GIUHmkGVaTX/c",
	"g3a51Afq7FD9duw+CFZrcV2k+86WEyDIVFucBKcdGE8x0EuUSdKSnAUBSjix9tD+/Z+6T3O8VaLbFtFh",
	"afDjNKw5ITcvmAtQ2BdyCvHP12M4gds4rbE0n3YbWErtvrQgv5GR1xha7YnuITmd9ruLw3tgtTD4Y76z",
	"w+5PJpvikQbgp9YuK6cDn/RqZSychGfbgHefd+HZDLfKG1AsskdRwjHi1eBiewcXsPpmpgZFrLJgVUVr",
	"H/kKwr7OspjaMBBf9DZhXsARElKaoK2BSG3Kn900tb+8tPOWAXm1JcFoxF4RLfUN5QVRf1M0qFuZv9rS",
	"f+ERS30penm1vfVz17bJcx//fY9QytsInQyGmJVw52PaC3PxYwtLuChjtrTRDmLNW/Idp2a4IfimQBeF",
	"lZzzLRGCxjFh4VFHrx/et3B4AOBig81ofocZXkHa5d8puTkeqscQt4V+r8bKA0JZhh32wWr5H4ZMYFse",
	"rZQCeYcSTjO5NNefPyL36o32HpwsjKLghl099RdrYrpTVW363VkhxRwuLcRm6Qwz5VZqmQZkWmcP6Ii7",
	"iEy2gB1frXaZA9eOjkoaRaHWnOQl6E+kElmkMkFOrKjp8oNKMenBD0rx6B1jfdkVTDvSdmft+ExrU6p7",
	"nJdV0QMUm9PSOXKx6zOfvY7NQxWW1/IEUuoiP6mrfTxlWuzilRZYtWHgFgPRr2VQTKXmvXH7qIytoaVc",
	"14rGM9CxW3ArJ7s5+QSpce2jbwRnK0g6bBpnGyue9EKgG1yqBTW3Lu6ujxrakgVGNjcqCwwOtikLbRCn",
	"OKr2SguNqzUyCwyKXWO3louR7ztakzhLSNiI74ZfkJQL1dZqIZ/Z9VrQ2inC0qa2zTTcyDGwluZlfg5y",
	"nYPN8mVmAkCabR+XdhgY8KRf8y/9iMghBj7/8almLzYsVzwYW5xkR8rL6vyM6Q+gmfScsjTr8lt27aV4",
	"3LqN3angfDlfY7k+bhstp42POFAT8ZN3Fxl6sgdu4BVMEqtflgpFhc7YR0rpIHLaz4+yVby4B9E6Q8Ii",
	"WvdSOeuaCGl8p2FPME6y0F+CEVITN74Bmty5UItKYTZJfg8uEVPZa6LBpr7eBt3hNmCLkjlJeXSI/ot3",
	"Zic+QsKGo5fRCTbHymtt85+UYuprLaDylJ7SsZeNqj4J14m6Oxm2hDVPuMinqczaIBDxRUI2L4nCNJGB",
	"3P7XL9Bf/+v0rwi6TefNWo0wtNihi1eXV2iLExpjU6+TxbZYqf4XfBToQhXDcuWehU5PNvUCFgQ9OTl5",
	"doqiNRY4si6n+o1lUrk88mKqRzilj7aPHxn7oHz0G6cs7GwxKR2GyIrvTx//+I8XT/77u9dP/+eHb/+v",
	"vz8+O/v+r1ff/59/PTtvonHbHtvN8PT0dNqScvvsu++8SwqDW2J2Crj+XuD5NRRZC0YVuT6s+Wd4wTP1",
	"fJGYvoCD4mFtT0wXtWO3GiZH91T16WOWl2rdEIVjrLCpHYFiIuiWxOjKq0Zry6kERGxXaGWk2Jh/3ydw",
	"7cwOztuZHa0MQbfzHu8SjuN5TFdWbjlm49mj9fqy8/XoPHIAp/ohhNQSuUxL5FfeT+2Iepj+qrfHMuYB",
	"2SplTv552uQc3SPO100xNnPWq3F0YEk54K1skZg/VqOAL217xVTRDZSlmUWcmYmiHTLPlURqjRWKMEM4",
	"0vvFbIcwenr6HRLWSH0CZwkmo+8Fjq6JeudaLQ3uazk0kzblkqpxtc6gHHrPtFoYWvTQHJzvq/CqJK1I",
	"sqFL2zLN/PfjQRJ/653/wWSWY2kaQnN4Ww5BbY2DSoc+Modho2llSAxTndCq7RVqpo0vp6aFw0Yztr0i",
	"E7dVxMK4oYcS/Zi4fh4B+xnm3jpENYqilkR1p6ECE2VAm8/qLd0SwOfobG01zPpVo5ByL7f61RhX+ABs",
	"/aNqwxWdr491TU1BtaIi4Ogydm0c5Qj2ADi1o1Xb6MyFz2s85Fq88ec4Egwjtp30e5biKAslZ0nCbxIq",
	"FYlRQrcEGdiRvZRI603/q5SkorVvyFoClaoj2cgP6moXHpze+k1XzMU4yWXczesltJgTOJDocuRSJS25",
	"DjWSHCy7NJNnuWfrHiSa9ya3ZGrdZj61ohuq1jxTJaJ981IiLlAq6BZDOU+TRVen2IO0hx5cqn8PMjt6",
	"aRvTzncYIVfILNgEqWTEdMJvV/Nfg4S9GiK9T81Al82ddzu6cZ2STtAZsqECU8STmAjoBET+leGkGIUE",
	"0WKMhE5KS8glX2ZJ4uXynIVa8eiZXNMeqE6BXHUKhNcEaxI3TZCI2BLhLUdlXkQWSBz9eHV1rjXDOhHv",
	"Xwfktmp39KnPETjyF5wtExqp4xkwehavCJFjYfTVr/ce89RuUWXSaRXaHkaIq7UpbwwT1a6AmUeTWokW",
	"Hb3m+a3FVamf0MjiKQujYg7SR/2SI1p4mQ9MC2tSG/oVSYE4mYEZQVVhLRAWN6R2SgP5uVfSFpYaCl/l",
	"tQ5VtdPsesGxiHu+Wvl4/8j6d6cysxTGvmKWti5THpTTnL7KBxfAVYmUepQ9qWzwFVNGCR9C+1m0XvPk",
	"98HhsuB8GyRgkuWSmASq8VHPkJouRwArMLve13QgjIepIoBakKYFKkNb7XN+YyvWMDWCE1TJptYY+wu2",
	"rTmMtCDdk2UHFtSwhXj0p8i0s0dyjYUTjSpNG38hi0uubz/aUnJTl5eMptMcsN6zjHGuHe09UwXhHnzl",
	"NZpxG+CVQx0EjMr1nnkKNiS5txPn3Iw/GKHbYApJfycD6qA/DR6twmLftI17Ugw2DxR32pePptJOpyUy",
	"CJ9KiAYvCI4pI1I2pMMNbPXUx07dw6M9OKLKhTm0p5n7W3U2/FvqmlzqZRNumVyLG7LhFl0m9cC+qoVN",
	"tAKSEM11g/40KOD5i6l9EorSk9nmwLF1nTVSDhWdx1PCjmsj6i5v14eXeEewf63iCpFVjDqWlRSYKdVK",
	"8Y+7idpKgHq0pqf0psjr5cGyWUqEJHEjCVZrQDQWYskLECBqx56gF5wpyjIS579JlNo6W1rGoALp/eEV",
	"QTgSXEqES42YcSYDUfu2a8EhCT8ygJp+Tm1NXQbVIYjc9udLwTeHCsrZ/5IOab/ac1gfnPUKEjoAZzh2",
	"+YeHOOE+VWNyfikzCYlB8XyxG1RIqfOgjxNQ3FAQo1rWqkE6qEUT572aQjwmxCOaMNb9RuR8sRTD3BGi",
	"XDmw+ruRM/bK0xFhFpEkaXw5oHOv6cl+L2qtekfV38xg4PfqTwY6jVndpylqYVg5zRKU4fMCxHpazg2V",
	"8oJnLB7Vxe+wzfT8gInBnfX8cqiWCPWfPk6PXxy1iFGEBmvH6sl3a63xSqTgd2TAVAzrkzemzeHovqwZ",
	"S3h0PdfoHHJLS7v9GeZ4A1NUAoqgoPI+t7OJTBqaq1a2Y5HZ2ZfP+A3OIsVFtSCm8WqaNwB6l4eZL3Ct",
	"QMXuLEl8Adu8byfo1ScSZeBljTBDYL9AnCU7dLOmCdTQvSaxqZiLkTVvuO6REWaMQy6I2W0wjOUAcfjE",
	"wTi3ANS3dyUy4uAmzIINzrhEcqTnPWleqcRbKkvdRQJb0W2pG2Az9rDFB8e8ln5DyU5T/AGl3nubi9bw",
	"ruenGyLrYe0WGwSUgYGb+/T6HNaAc/+WmtW4iNbelSGUdRWmM47MgyfT5HkZERfk4LMbF8cI1XdcYN8h",
	"A7PCkX8jtiITPoBZQXHlhKvu6NkRUV8jCoiaOLFRcmIfXhQkkCZsB6IZXYRZAadDeBtpT9tuVfPlfJ0T",
	"pRN8FvzxZDpZ8G+CAk/eZCxL1EUufOZCE4Dl1RpywtM84kIQFy9vNfxCry0hsV3drbhiQ+5RH8WHc5Ue",
	"dNag27S2QvPazQdaMy6kCWYMcJw/hS5ixPlGTKFa+AFCFXLQphNFojWjEWhGmTQGcnO63ZaJWleQfb1r",
	"erjporKPfBtx0BJuJWHUkn3P6ikjGHHEux1/xTlcwnCg6T4Rl+E8ioF9Kvr3gKiGfAOw07LrMMBW7U4q",
	"5FHgftrYj6FCCcFLVcFdvUBj3nmqL0KGOAUG2o2TAccyqvD2qIMsPHFt6ScOeN/oW0Zu8HxuqJTf21Cq",
	"y6L2gGN+gptXsCOj0kyzC5yvq2l1YDfOGNcJRI7N8Q0Wcado392jaD+nrjHLjHbO5p+HDPvlfVb9t/6B",
	"NFLEuTHj7X+co6X9vv55W2ZwbjIMRxov81kKe2CPEtspKL/GurPEkO5ildb62zTgvMcrFh2UMlCwHkIo",
	"r7y6oJWSLzbPA8UkMmkRbl5TpCNTfIMVjZCzHIPxbrEj8gRdrUmeyJN/rlVnRCViXCFbRnFgvbz1Bkcz",
	"ucZPnn0707CJ2fZxryJ4Gob4iyhKN6gmG79p1ue6zW+Z0GdQejQs8/jYKzgGJObbkCVFnpJ2ELwFPbIW",
	"GeEadOGic3lDaB8R3qGUyK75HgLTf4sXJBn9foNrrs7yF7shnQqcINArsyLXhQ4bI3O0Yjr3z/YNN23u",
	"l2XuPJ0qyy7m6W+SKgkJzV66x0c1ptugh/LDVd5D5wH2dY6HHcHmcW0LKXIC5dNOtVBhFg8/g0v72SBH",
	"/6gY505ivL919rxDKrk6GgjIuw/+uXgGoCF+j/IxBfqF2F75wzoUNLBWj6D2SDVyn86LYnTdPL+sQx4o",
	"AWlNcDxXfA7/xWma0KZ2F6WRo/OWRquVY9Yyelri3uxufuu98Z0lmvo6qYDCFwmZH97fVVdM82pJeRZX",
	"CQmlpK4qEYaPuIFEQtRX3mnoql5hef3Cq67jpKgbsoBLv0sVNx4HwiSNbNFgIkDiS2/ANK/ICjMOXcj0",
	"q5GmkRbmJIU8xQ1fUCh9uMYivsHgpthQGfXsWeTD9wvA5P/ywsHn//jag9X//SKH2//1HPbg/3JZ2U9p",
	"NOzN/+W93af/2zu3Z//HH4v9l8YCLuxJNFYRPYs3lEGCF+JLhKFGiVEWf10mePWryRPTOiKEWOid2hR+",
	"EiPFEdbfyyli8BfFka3sOb6FcolwRneLKbVe7og/6t+IGVBZasZMmGl7EOSjgfbuT549C0BQb+ncI0bM",
	"c14W8sk3NVnr02zFZ/a3f378z8Fi+eDe0ZVG/aU1oLBpd0dlr/1yJdgHy+uizzM6gwdforVS6Z/kn9HP",
	"F2+hYsmaS/U85UIhhcWKKAn2kfSGPWIRMg0hesFR6uxcSaYkYgYFfaDxLAxClCFjAILpx3aC7qCWoJg2",
	"vncz0GjeBNqRc9HTuaM8ZuVGeIyeYKkX25CYZhvLpgfw5mLSV2ai8o/v3LTln3+ERSxc1TA6YzOYTCcr",
	"npRbG3UBo2f6yX3tfvjBzmJXMwXef04TjuPm1kjdt6NPkffi++CZlCoE1DLI1L6lRg9gEhiTJ3soO0Mg",
	"6f/xk9POKFXbLxUC9ge2nKwlp/ZpO2l95fMDZuPukVgM6dFWjG82Kz6utTs7nX338S9/muX/98//+R/3",
	"qrnqOOyeHijX+TD5ioHc5+NYA0qtYl06tKslkVNImHSnddbjpVLX7AjumwHGgQINZ9H4XAhc64nKU8Lm",
	"gqyoVHlTKDjrudSaZP4v+6q4f2pBmC+X0iUX5b1Z81iVoPW4lA9x9AyI5pj9dnLoiJgvqpHmu2k/sVIs",
	"/7jslR109+pv8mtYPFfIOE/KcvaTjpyJUuOwQ3aZB1fDPPeLjtrWaz3HSzvFZycC7TnppcIr4k06hiZ7",
	"NPauz7pXpMDeJGJ8O6ECT65i9oHxOrBeVtOsjcWzgI8dGOZ96/4f4Q3rUYGnrTRPw/2eVhlQFZ+1yxYi",
	"lOot9/r/W6Id8P41M7RhBYOKriBui0hvsajKiLeYgkCDFPdTjKCme7MN6MCJht90uJfD/qZDhsD3rlux",
	"NzsMimWBCskdyWZ9XomxtAKEjL5//w1a0i2Z5aQDkb7IEvht0cazUbSxqfS1NUHKH4cynH6Jfw1n8S5T",
	"8F8/HGiIHAs2e80timYoA/25IxBXW3VkOqfr6dOnKWR74HZ3NBCUKjyW7JYnHYwNCXJdfo4GYd+03R48",
	"bpHRRN0uwRXlXfcxRxUFcW4X+gMISbeQO911AYsmc7cQe9ZWy6sq4PmXz0vQLtFMCPzua9fONqYN3LeZ",
	"0BpuT5Ch1g59wKOSh6UNeNlfmFwu5LCJXNPrHXhVOCOIxNS8/eBbRyCx1l/4cdURukPU7rZ6hSmv1Stq",
	"LabSlGvpN3wkSxgSRzemzsPBy1IcNaxtZFBZ99ReQYJuPB+DTQ8PqW2O3qpLqqXArcDN9SK4vBz2otpc",
	"Qev78KtR3VleuXCVnGXN9EZLemyJc+d8zCx3W7pJTxbjWxcOKfiFJx4riPw7csI7Z1SnPRlVpbGfdVsU",
	"DotQp78+vqkvjQG6XoPDGGHzRWm8nbfEHX2b65dT8mv4VTukXcVH2piyKf9umNNUeQlt1fq45up9U2wp",
	"iGRn+qbINYmRdQUj6eYtGrguCFro2wnBhYiRmw+sUOtMZKJr8lYxRtOYMEWXlAgJDdZobpHk0CfInwhR",
	"iaxv+QSdoQSbolYKJ3xl+7sYySDmxKTHCXIjqIIcOi5KUy2oCWo/+cDqgkMg3KaMonecccUZjQLoybem",
	"OJKExShj0RqzFYlNrSvYAWWrUgHdauhZDy+w9U+E5IBKM16HeRP7ZDralU+hfHhNcDXG5kCQ1RBIzBeH",
	"h8QjgiAAhb3bJxdDg1YzVmtNZZWz7L+4Fx9V3Ts0uVJ0Q6TCmxRhhW7WNFqbFX14FiTCm/wOltZuCaCt",
	"2VhqgRsV7FQgbj7HZlpr50NvqRzbkiHn0AN9pxXn/+lpZ9MhP6Ds9MnTwQV8YKXu3jm1+CxPtPMsYCYP",
	"t0+AY2W+vz82MY1eL4yHxuf96+ccqvH5xesX6K//dfrXptbnRAguisYtdolSocec5ZSOs1aVpyjBU4px",
	"spFYhSBbVRu8CKfRpXk6KBJgfWnhq/x8UQa3+leA/q0DvvLXS7uXys8/uK1Vfj8vdlr5y5Xb+Lndd+Xv",
	"Lzw0VP9UYOXzdGKUm30qJ9+XyLHWONphcWSB+qohjvgzBEacQ+bJyKi/LRF4RQYmDtaxkkkiAvHFz8rh",
	"xU9qYbJns/85nX03n338y380lIkbnhVXQXUOmp1u2rDpZgRfYXm9V4Hp4bk/CcFi7sW8h4QhBcEnIoMg",
	"lJjo2+ZzxGSHMgjKJzEyMyE90wkyofoSZdKMt3/Ms0smQcPV/c4s6oBn3zyjvqlFQ3OG7kXCT3k/P9mx",
	"l7U/zuQ1TWfcNsSdAWREuDk/zThO6SziMVkRNiOflMAzhY275Ddgmfl2p3yjDyJVxlxVTjc6VPpQFztu",
	"uuwNDsT9n6beRd5Hhjy01Hm/06fvOPGheWuCQwdx5hN/MeXZmwM0e5Vpr0Zt1k/rY4/bYlxID00Z9r+s",
	"tiDfPl0ZHroYBK5JFa+HbWPwC94G0h57ZmNtyGZBRH/k6cXewTflglOB7AybvnfI5CwoWTu/yXv19TOK",
	"+A3+ehV2Omis397t8+4mxU0f9KEae7YW7a+V8Hcpao40K8deafxZUFnT3XjBmRI8OXByWh2iYNpZUQz7",
	"IQMtPxHLQGo8a0T9GuHafx44QDfe9fOyl0r01pwGlMiygyLFGpvIkvYJ0jqPqfNh3Bcunm+xI8jDRsiF",
	"MczUXYslctW/AwhsOraW4uL+fZjnDc0q9cXNVa1YKktf9myYaYqMZoKq3aVmV4Z6oLDKBVkKIteXBKo2",
	"n2VqXT+YH5VK9amaUipImE+QNN+giPNrShCVMiMxWuzQ+fvLK/QIp/TR9vEj+OZRwleUaTU48Dc73wmy",
	"sEBJ0ISveKaQDYSVaJNJZfrlgJsRrCew7sw40V5cXrxGil8ThihD/5jpf8+u9L+N05PqjZgvXEbw84lK",
	"N3OAYW5hKG4MTul/E3iWAU1D8IOjiEh5ePT8zCRekvwQmhHTgosQjp11yfssd0xCw/UqlvItMWOVwhuC",
	"1gTHRPTCtcFPCNXGPtoP1zzF/8oI+vnnNy97otrW/Xn0G6eswGam1prfaJkxtqWB0MWry6tGDPv4RBus",
	"ojVlK0CEvpom1SzdzG3/l0iKpYXLhAb4hyORpCtGYlME18d5vk0LUXmHNshA4z2fyRbHrZ44EtYnaU/I",
	"mJ1kmlA1i/kGU4YWgt9IIhBOU9lxgHZTFpr6EWpOQ9mSBwoDa5TKTCyxLQWsdwmms3Mi0DvKMkWQJGJL",
	"I70930WEEyhgkzf7/8Ccta2wjBpv79R/A0xfsDwkvNS/V62h8PAHBlEYoD+AeKPpKlOSxsQ4qt+nhJ2d",
	"v0EyJdHJB/aBhQDLJJEII1c2fwaFl1Gc9x/Wog3Sqklygt6LmGie/IFRiRYYGoEtdrAF90FKxMwDlmdq",
	"wT8hV7h/av3oG7xDC4J+J4J/YHqjXhiIaZQG9ZYhrsD2yaScnaBXOFp7PyBBIkK3egMfWMSZpBJiAZb6",
	"nXU7QliVHHg3WBGxweIaLciSC4LIVovCxtPHyA0RH5iD1wS6xCShWyJMKEvRkVlvAmrWxgRhJHhCZtDG",
	"ILZYm9P4AzO93qiSOYZkttCktYBCXxEXUPxLEIUp0yu8WTqkLzFN5FTD/oFFCTWnZhc34Jo3xq5lGslZ",
	"+y1GhteVMHHygV0RsYH0wQIKU8Ta9I0GfKYeZTqTD2zKEtoHZt5vd5jWeiP17f/rk1O05pkWdt6bo7fY",
	"LdZwbgCbdmepOI/2gF0IAsSQikzjRJPuWcHpKGfPPzCEZshw3ALanO/8Wr/uvw7hr2Z6eDubZvdfg18B",
	"6l9rT41bUxaL6plR8yOq5xn5igJ7/9Xnnr+emNXsq/moKpXkT657GctPb22uyXSS0IjYEBHLWN+9uZpM",
	"J+BbmKyVSuXzR4+0SGiO+YSL1SP70aMNVZ4lHaz0M80vNoZ/fq8ZCovR2fmbyXSS10KfPD45PTl1Xaxx",
	"SifPJ9+cnJ58AzKmWoM0GMAlqBhcBuN7lCxOs3qYhlQbpAbZegSaUkrPVx49YKcuEByUZToOpC4XmveB",
	"cvYmnjyfwLaBaIskrO+50W1sjBEouWnqYose/WZ1Q2MH6OxTp+d+q1dx6vXnsuaRJw2aVxuO5snp6WEB",
	"sBJWHq4EMJRPGGBE7//7xNbctDavf8xggplFvYfOOpE0yZMBuimTyAm09XK7qesy/zjUspam+qyq133a",
	"eg6pCSX6y7DzqAYg1U/iDYP0P3dR0ILHO4iXeXr6+A7BSbGUN1zEFpRv7gAUe4UQF9SqT4IsiSDCNYzA",
	"ScJviAXx8V2CqA8NkU8RIbEEavzb5fufkKS/28KMFsRndwiiCwPVlG+Y8YKgKqMxcD757g7gvOIcbTDb",
	"IfvOK/BLS7QUfFPooVbMe3NeYVwXRInd7GwZ7D98aUpioowpmsBcZg2BFUFGVEMQeCi7mUSHezNn7I9+",
	"Zs5AaKJlXeyib62ZPP/nx+lEZpsNFrvJ88mrTya62ux3jbVUaZ5Rdx2N2M/sr56iBv79f07g98lHvUjt",
	"xecm0yD85F+QLb8mhnidNpqjvpOlI8kRhfD5D4xxlHC2IkITmB2m5far4pV3C7geyQIWtzHlVEmtq1hR",
	"FEGZN6ZO0FsjAniKEDyqoNnkgTaGeZWXmWroMEPWmpYrxLnSDc2naZJ8YAYQ0EaqZjAthUA0ENgUcmnn",
	"g3vpfSFzLwmFZ8qJKCkWeEMU0HiDU6cYYt5+Pb15OT9/rMkZT0N3w2zPHoFl93fxEL6jUlK20nye2kcI",
	"cGdNT3f3JF5UKGFjAJ06MKeOsqbmjfIReRePkkdx+WUBQ1aJLvPLYY01Yshre2gu2GKt/ufHzyUeaRiV",
	"0RmGMkGrwmqwVyZsvXL7qFRWZa7fPrCa/SsjUM7Y6naURUkWk7kJ+otLr0dXG7HA/RymB/TrjQ7beYcZ",
	"XpENYervlNzUU97rRHRm8pctxoBKcJK4f1tOXd69JhTT7f7OhekqZHBsKD/QO2QmAS5XIuNjXq/We/WW",
	"SlUcr1bL86YLKAEWvOBYxEgqDMEY7rKZT1pu2yNj4PIuXSiZaHap5bpXxhYmlSB4k9uRrQhkTOUxlmuA",
	"xFrJzVCyAbHhV3Cf/YroZkNiihVJdghrodCZ82BRY4yy4M1tQtuvQNOmicCafGB2Oc0SprmZHppXmMsA",
	"MPmIcW0HJTIznnxgPxIs1IJgZcykWo5BWKLLy1co4puNsaqC/dOaEp3ZlkpE44SEJASzYXOtDbomnXxE",
	"kU/KHMPMfF6m6JqcWyVaDbD58MQdkd6PccHq+4Ulqq3xcMnql+zSUGuJoDWFOTBNzhxxx9r/jv1B48/m",
	"akF4Rf2S8aWamT8aGd98ODUirXSWZyvhgPBgHCxroGi1JhujDvjLlshfb8OIwyoTTKKnp9852vadKhEX",
	"sTTithUwWEQ8iEIkb+A2JH87UvFL827cg5fMYprGmpjvhzzc63bdR9E35L8fJ/8+NURzy7szNwCAWZoC",
	"VwDKd3cHCjjm7CU2ns7aXb87XluwPITtPQrx1LCgn2K19uT8eFK14vuiflf438fpxJZ5KGPxF0E1Pza2",
	"iYRGVLXIFSAO3VBm/C82dQpB6hRkYp98YJdEwYj/feqPKadX/e9TpDgSZMO3Pt8tjD3G1+6DEOLJmZfx",
	"dhiefHhvTCgr75b9MWH1q36fDKiO3d/hu/N3TwwRgj+8Mw/vzF2+Mz/bnFFjKgbtDil8TdiD0+ewTp+7",
	"eKEvCByte5xNQJd77YxGsp/lQWtFj3AWm3zGDpPfmR6Xa9Q9jH+ugVnA5PfsdNpSQA1KebT23rxF02Cx",
	"7T5mwZ/IDZEuBg4w6+KXnLHmzl+woOb0hRkA7xHfv2NbZInI7kp8rzEYF0/e7E7lCqvx7lTNCZ3rVKIF",
	"V2tUiULPo62uPJniEB5I+5V/SEewudx+xFPu6ISTiY8Q+JT7uu8qBKoVgC8iGOrBB/zl+IDvOEzI7eG4",
	"gUJulfsQKjTESQ5MbpyTHIqVtMrLVzDiNkRUv3N4H6d1krhaKw++p6BQhR2G0J9w3nh96vzlEi0TvPqz",
	"RyV6rBGyrJhTpgZTwVSf0n21Ab7IIRxkAXx8MABKJBxg1LYG7IPF78Hi92DS+uJNWuY6IwxMts5Hw49t",
	"p/fe96nTZanPoc1cgxpkWEq6YiaspOxb18ucNPjVD8e9vxyvOhRrfvCpP/g6THm/++DpAEDusz/9pXOl",
	"h1nbNKwvrIiyDOZoFqAOCesKeN99YTkPlueet/BuHFI4tgSuL58xBtc0oduLFgmFXNxnZatepfeWwy06",
	"WIGLslB3yxIeNK4HuSMkdzyofl+y6meYi3s+/gSlanCCDNc28StAdGhLMTo/u3rxI5Jkg5mikfzzIFXx",
	"kSkd0WijjfkNSziONY1dmqEVnvvN6ZOQlhlTAaVToGWNIpuUCyx26JLgG0Li15eQjGlKGv188bZiWX/L",
	"zSmYQnHdj5+ggbfv84Ocdu/lNC78Mvb3QmwzhFulWwPlDKD8nzfnyN0LTbx3JtkF7eimP0Dpvh5RwNtk",
	"iaKaPz3SAM9irHCZSMplKF3bg3x3C8owBEK111iE7+rFE29fIjQ4Nd0WWkMEFIcaVs7cBklZmHFor1Ki",
	"JuB+d8aqftISjKboqfNDoyUlifE9c7UmAm0fRMwHEfO+iJiv9ZXxRcvHp6fo3feeXHk38hq8Bbj2TPzp",
	"//t//l8L4p8hEktqvoCoQpQVslAfiS033s2qQaiBLpW2CCyCgMzXNFGGlvAW08Q2kUx28MQx1wD/d63L",
	"erUEbTHEuqUfvPb5QFhh+BOjvyomeRNDO7U+H72Cgr+21cqQT4assSVMXemXpu8XZ5HiYhBQ8MUAmC6I",
	"zBJ1YepL9/3ofQTVTOLXgm8Gf3TFe3/ywvT36zv8HK/IJf2dHDmYzy0VVgNjDB03TUhoilfEJKpjJE1p",
	"xGuyk0Qh07rQf/K6mEpxn3KGkr9J7d++5mJB45iw0odPuz/8iavXmi97391JlhzBIo8Ks/j1WIpFdV7h",
	"3Od6RaPKj9PJp5nGoanvOXnu/fH5BpKfJq3s0SOeIIP0JbK2Jr5exy0JFLHkwmtSW+3kS6X/ranT7i1i",
	"W5jqJ6DU2FV+YNAt2MaWFNi6oUkC3XgR+YQjlexO0JtSxaI0wZGfEP2BpYIsE7paKxStSXRt4uhN40MU",
	"4RRHVO20dJHgjEVrlJcnh5qfb5b6MeBJDNWMkqJ4QFGDyeBhmgeyQd3bH15dwa5s4c4PTAB+SezN4uL5",
	"TYiPk3dO0LlBv2n6C+VnTdPiDyzYtThPbCdGRjI9jPXERUVTd462j/EHxpcmJ5JKODfv0AIByyuiau2i",
	"j+puau5NHRIxbVHdFqqt2FFe4GhNZrZLQ4OsYCctTgusYRrfC2LEFfAe2kpX0sjeigioiiF2KNJrVEIY",
	"XRV7xmcwQ6jQ/Oc7Y6lPntyJolXnKG3sByhW+tGx7Tu9wIq81UIwuetn4CWVEbe1T3LyKrbqvQi1XR/n",
	"SeiIQPXGDZVjK01QjaTdRw4qN4PuLz957Y1vRYhqaFodoO/3werpK3J3otOdBcZ6lFfUHSo1D3Da1R70",
	"Pm3IFsrPIW+OEvEN8ULay5A4wwm6gsrnlebo+v03aSFWCHHpIdJ1rK+xMCh8SG0dQCsJLHYgJnSJbCBH",
	"aImDbKEuPE1cx9OVwLGt145RqhfgmUx2BRg+wDWBRYPkJBascolFECV2RdXoutxSF1A+MCuhoKCA4lXc",
	"zOUQl1TjJBBfbpQn6Cy4nTXBiVrvAEzbOrXAdAnDGwxVHKASvSnpDiWqsCmuX27n7xkAQsJPVBFBB3PD",
	"NzHZpFwRFu1Ml457Frjt9YC/m/Btrx1/KBuleBfrgdztHMw6nOy+SszzTnTWHvJKvSP/C86WCY1K4D/u",
	"AYLdtTHzXHH+FosVKU3yrA8OZJamXCgSv9OC7dUuJXcuM175nNZxFJ/VbQp7eJXr3YOwZZ+THEOse/RH",
	"qfHd50emT5rrdzZKjnsTT3zXWkUBgz5zUwTdtqa2G4ipbaZcrw8LQ15SOK/GY20C2KlpZearyWnnmVWd",
	"OPyVcODqzu4qpquVA+chXYWN4IvlwOOshr0493luwfsSOPddsMAzfZlLHBAldEmiXZSQos0UPqbKW+ON",
	"pX7SvYyjliQVhrqtvtpuuwyDJVNatxZekbw5kakkAO2mUWldKEaa2+q+f/+NM7ov6ZbM8nljgZfKlSOw",
	"PcmcXjDMJNVu3vMQcltGPm/Jnkp0CYHD7Hul9b5+u95Ypmdku7H8/csyzkFYur7dvIvU9rNN7Cl+YRUF",
	"OjqaB1pa7/WaIMdJTGdXYESuz33RKQ26LZRYls+fNBMKcJ8SpzLjI77ZGLsBiCu2lgqkxHkmr/xxNOuW",
	"bmDu9EFpksmwaGicKdCuPG/bdtJQMrGZmX0lYuPPbdu8cxmyBM27TMF/X9kzC8aF5k+fO9ncPth0C4HE",
	"VRHa9CCKDhdF/534u40cDzFEj8Qcb7wt4XPFk5iwRjfMiqgfYISTfy5tn/qjXeLycr38GuYTqBxIHi5j",
	"4DuDoIuMKbohwXv4ZUpKqeBxZp50SwPkE4ky+EFaQr0jSWnEJXzkihw9+sP+P/gjNALe13DWLTcYBJ6Z",
	"hSu2tmpvCixUafjXI9aYbV3qHd6RENOf/wGUJH5gf/9m7A/OHXFmetXv3Pnj/C7eouAAPY4PaNUvcxo9",
	"udndK8fXvzZW8z4l7N5zmndYEUFxAqHoD+zm34vdeIffIHQ5ueW2WA9lEYTQzMinlIvmqt/mzx6vsd8d",
	"U31xa3yfsTgJmxrsCLSAIcbOviLMQg5dPqbo8sez2ZNn39p44WxjfJk/vjt7UYQJUbVDhG1JwlPyEAff",
	"h5ZfAUUg7CX8heLhafmIvhAtIsVUULY6npN9YACbX8AsAhKtxTVZexrxgyftJr6ad97u6D4YSMH2dKHv",
	"YTCI3Z1GbI1UwiuW9fDEPzjaB8UaOWJC2KcmE0iqpO/2SWi0uy3RweTctJk7veg3M/aI99Gu0B5yaEB+",
	"eN/H+VBtktVBctv2d55mt/Gq2gS0ACF/JS/qhdmg2dYdPaXNV9fFqpXu7cPz+fB8DmNk1SRSx8kIU4IS",
	"iRZkyQVBCY+ub/fxfARLfjE6hob262WFb3l0fU/5oAbtgQ0+sMG9kvZ4dG3yykz6/AynqeDb8sUX7k7f",
	"JhPMQfpyOKHIWJURnue7+HrMLW5Ld9ULuFgfjNOtwWZFXQgBox/Y5AObHGPW3uIkg/odRkaEWFjjf0LV",
	"0iO3zCdNvOzRmCRUd4m4EJpAtsRmbhSBwOEcL9TKWzUaAnG97OuWJH+G/d1XnRqAe5AmH9jkXhG4JnYf",
	"OzZpVWhPciqFD4rb82hLonX6R3+Y/5qM2aLNz6M/in/A35x1cyaI1EiRxw8PvATIepbFy6Ht4N3E1CMX",
	"JCVY2UqsNpUDMGvCpE0V4jxDo5l7Q/JJCws3WPQCXjTuvh4OXtnYICb+tEX/sERmG0+RB4/gA/cdlXoL",
	"5AOl7Bz78orEWBKDEink0xpn8jZTcAP8t5aVe1v8tTvJTvNJslxakTf3pG54TPyUOkpMkSPMUMakDRY2",
	"65TT5qAf1W/mJMwJ6BXMSPsQoiHpdXkdDGx7lNup3O/dSXPmg3+T1LnAZr+qBDp7+g/Jcw/Jc3u3Xamz",
	"soOlRu/7YKzwRv+i/2MfEGOVOEDZm8OK5z/gDekUzAvoC7bfz4bSJYXbmYsdanhMEe2vTxZ/kaPxjlh6",
	"AUA/7u2de5Hj/sCiH+T9ERGAQEkg8C+XNKI4QfqqQ3GuxJSUjElKWFwWH+U94uEQSrX7Evl3zbCyxDQh",
	"sTmBwriSCq5vuUSmCqcNHTNB8Iatg7Ywltcb/JVZ/ddocNG73NfeYmYpHQFPyYO95YH/7hdChktX31b1",
	"sgaXuNbm+ZYZbm4KWnKxJFTJ27a07GWZJkol5qbmstIerDLiIi4289og5OvjlnZjBzNPW8qxndMf2OUD",
	"uxzJLjX5IOy0XK8WvCOxW+OTDKdyzVVbmkpej8eNHconCuEFWkLsXKeDY/YsqK6ZA99W3UfYwcihBXiv",
	"K4G5+2L7QB3u3t7VdXGdRJZZkgSrFt6HrJthN++GSvkIMtXkoz/gv3OWbRZEfD6AYBJoNesv0a/pLGXq",
	"myeT6WSDP9FNtpk8fzqdbCgz//9xXvSTMkVWEEzTlHdk5UPXALXBibTTUg6Y8jkjpbzQugvJEOgM32BB",
	"yg6jPeop1rKZiiTWr9Q/dNFzx1+Xk8jLEX3wFD14ivZWeyvs6m7cRDd4qxVe/Z9DtkHoZlW/4G27jVAP",
	"gMYVAloedvLpcJekXMkN1nbQcxeA6xW/Hiatd2Ore98RHwZ8tuSf6r8/8MwHXXgED32fEjY1kT+1liqu",
	"gzX0SI+g7QrCyF7uO2GqjM/kmt/cB67a03CYB0gdwmwoebL1hMWf+OWa33x9ZkOzr32thj8ZWkEWbQ/G",
	"wgcGOU7IBPIpWQuhGOfshrKY3yDLkw7DEhNoK7LgWMSN7WHOVitBVvDwA7fQTIeqSmKo8bybYE4uYmIb",
	"jdxQJtHLV5cvpghvicArMoftzRXdkPlGojP9Jy3/oUwSmEz/1NCm+a0H7RHFH2+ZttKVVzxFz05RmuAd",
	"EVLvVvmdvFmpj+9tN5HjHG0w2yHvgF0Lbi/PV2p8RwnVEL85r/SZuSBK7GZnS1vVqFIhmEScxRJlTNEE",
	"5iqthBVBll4FkURVWsqE2scc+rKVbtUVT2fPTn0Yvfvj//rRvx32aB/9xqmJ0w43iIPedxJhSwqmT3mU",
	"YLrRP+Z0De+tCYKmSuYtQF03Vq0haU3JXgcqZaYnZehHpdL3+ls7vRsfcX5NyQk6A/4Atg/7p5ltQJpu",
	"5uabeSTF0n4AV/QfM/28zuB9LdotmcNHWBCzfIxwwtlK0pggakx1GZN4SRwoF68ur3KyOkFnDLIktzkg",
	"RQMna2sDpnDN+E1C4hVBfGlQAQ1Lc0yFbr8+gnNYdHIcYeBv+QJ3pHT5ADQznfMKDZimoYbkINBGCx6l",
	"a+wfdYB4Ly9eIwVkkHetheb65vw7aK/zUj9tRdCxuN/ftThlDAxEiNyD880dgGKJCXFBV5TZcyJC8wDT",
	"PhgnCb/JpcW7eCt+dgwKJ6bq9xoD3ylf5RNPMrsjHIL6Qz5FhMRG/fnb5fufkKS/E5TQDbUlDozcd0cg",
	"un6t+i6Y3msLgqo84T7IBZqf5tWVjyMQwBL3ThJwnWpZ0Re7wtw8ycD8ISwUJHzFjfOrQSxICBaGTtu5",
	"qClcaXTAPAkryoSAgiuwsRk8wZWvb7SYgBF856aiIFdIwtQJunDiHjRAj7AQu0JGqYAApCpJVTLYYBVB",
	"I3TTK91KGWG5IvRqGxzl7/Ywu4H5rGoG6FLDqw+kPoWcvd4F9/JeWCrdObvsOdcg3sELpi+D7AHvxnEv",
	"jMZgiSaDJNTz1mxIrzakdomSSFJcCfMgIa+SaYqFohFN84aj5FPKpRE3VWAYU4iwOOUU+vG/WfYhcK/3",
	"9tSOt3KzE70koraDaQVWK5CXSQEnkiMBmyaaAZSvniYQmSZUzWK+wZS5np0oJmnCd2C/1CxAEPQ3vMWX",
	"gEgUYaaJQ7hipWfnb9Caw8PUdEdXRL0w0Hry9bFSRvyF2sRcawWJLSEcRKR1Z7K/TPv4DtjIu6Lru+Mh",
	"DnDY65Fav5uj6mWxamYRHbyhxSLfFqd2Dlrjld9w/niltyprtdHumebMCZVaL7OarceClpQksTUN3ZPy",
	"xw0d0Gqgx1RCHsFesVeaNR0y8qrNnbMQOLomqpuIvrcDj05BdqG+5GM3EMD8F0lAeg98uXTbuufUk9At",
	"mUFf4G4Ceku35CUMPToJ5Uv1JSLT2tiRUIwVhlQNnimUCroFbaioCPTlEJY+n8rmvhjO5AmibeWYGmXl",
	"KyyvUUw0CsTOvilgt83lSc/a7Eu9/IYRIdc0BQk0dxwG2+afF98VdZeOSuChBVutoZZ+/R0WGHxobNBT",
	"fsMxVMI1uFSatAok5mGU5TAtD+Mjrlqhru0dhT24Zthhb+gjU0NstqRJt2aLbS6sZWCm5hX6+eJtjuS8",
	"+7w5hiIvAS6yy0zApiBlcUYQT9P/Dl8CzK9pQm7pNhcLtjpUySblAotd6T7bIm1YRGtThjMiUj5c7V5X",
	"2xo7VY7YIDKdMapAVAND/fpvet+e5T5t307bcm/F1hexGDYDT+1DT82vqadm3+e89cHOm2vek4s9/qI+",
	"Aofl0ZoEy8B1v4AVjx8DeWEDD8JekGP1DIbd3WnT4J58zoWiB8j6gdX9u7C6d1hcB1idpQOfNIS9tXtx",
	"ufFsSmYL8BwdIEGnmVnpNSy/ep3g1VfLoy5zZD4wqgdG9UUwKiBZpfX/BK8aLCoHF8pGsKuELxa7RjOG",
	"R/FFLgkknZii9xuyWVjjYsRdwGtDT6E8qqzdZvEWALodIwWs1VO3QoAptKXk5sEUcSi1xPMUJfbcvzCt",
	"JFCGChwUt5ed27MElfPTG/cJjhQX1T41eYntOBNgkTRjVSYCt9YIH94FAQ/VWXRL5RNuWxAJb/SOxBHj",
	"d+wpephD9PjWg+Dx5eanfaliEGt5BHKONM6Ju68E1KNy6wGVuTuo3ipJJIhCVKIbQRWZaSHtBDWKdr6T",
	"CZKMQbKrPxIpDqUQ156Fr1Qx9d0Bd62dNsDSFmsZY2jQURC2Ted8eCIenoi70pQtn+qMPkC28PM9eCg0",
	"052Zf98LQT/I1ENSvkspiCKSKhOLrmy5iUCrszRNdt7U51zaPjP/DuJ+sdu7Z+8+LC2hgO5UgTxtZxMc",
	"PdQ9e+Dvd8DfzzT3QLhEjKVgk3sk+EswksQm2/HOufmlg0az65hIJTLbmLizHOYJOouGtSTOt+5Lk+Zl",
	"+8qld7vvO+Lu7207E9O0yDGgYBFj1/gkPyrX/aTohffA3R+4+y1L744W22X2nJXcOpev1z8PmEhc1O0G",
	"7yCjH1PmBUh7JpHOIHvTGL/LyzW60nrJB317xdYDy7bVWz8vBWKESq4/FFq/I59cUWm9l1tuS8nNl+eV",
	"q1Z1PEjQ4AFKOu6rnwuvLkpAhCuxmK81bLG6xTuS2/TalBEpX231XEErq+khA6FoMBSRbZGk9CClPUhp",
	"tyalEeVR4dHzu3pybBlxQaqVKBvSbS+LsUfPty3W6p1wa7NR9eZMRUy9N8pWX3Lyv/RRfp9TaztF/Eo2",
	"3tQ0mcH1qg25iEpZlGSxPsDEVEQzNlQWF+1Hbf3TE3RW1IjhSUwEVPQh/8pwYqVcSLy1L7kebn/Fa417",
	"yoLd7rnIo3Dg0UBSszUWuXxfiX68ujpHT0+/O0HnFeBtcjCUcvLP9heyuORQXUBLdaZnKgc5w2y3nFX7",
	"5qWc+mniU5OgaO+ZhF3iLKYKEszDCo+5TqN1Hfj8VtWc0oqtGo5BaVi5sfgu6Th7vZ2HrTwTQGvtsW0s",
	"eFdclnzvHpUDSfNlKYosR80NVkRssLg+uQW2Vug5zWVNRio3B+Nta4IT/Vw3PH7mzy/WJLo+5qP3IyzT",
	"8dTl3ZUjzQgNZDtfkr2j8osbojAUuKCa4SVLLja2RNqz1tpve6JoeiubfM+I5rIbLkgZ/1gQlDF7CrUK",
	"copCw8FMHf+evaVbAjLlXwoAd4Wo6V0uuZOKbCYfP5vp9ALm2lRKedkw1bPzN7YS3mQ6yUQyeT55BLzf",
	"zlcrWR5vKMvrYyV0SaJdlBCU3ygwydlGadAWAnTbtkqC01xFn5qX37WXNVXV47z4c2gJW/Wqvsb76izw",
	"qgbngHa69Rm8IniwESqV+XZaer9tpwg59Z8krzO6v1DB+AJIqbHPcoVxHPtT+ZW163NpwqIRsfwjvGtL",
	"KJ8/fv7/AwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
