// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y923YbN9Yw+CpYnO8imSZl2bHTHX/rv3BkO3HaiTWS8qWn4wwNVm2SiIpABUBRYrL8",
	"APMe82TzJP/CBqoKdT6QOtitq8QiCoeNjX0+/DUJxCYWHLhWk+d/TWIq6QY0SPzXCwmcvgg3jJ+cn72+",
	"EJfAzZ9DUIFksWaCT55PzuCPhEkIieDRjiyFJIEQlwxmNNFr4JoFVENIFlJcKZCEmumIhD8SUFodTaYT",
	"ZmZZAw1BTqYTTjcweT7518wsObNrTicqWMOGmsU39Pot8JVeT54/e/xkOtkwnv778XSid7H5WmnJ+Gry",
	"8ePUnUEptuIb4PpNaCbBJWOq1/mCNBsyZ+FkOpHuWJPnWibg72Ap5IbqyfNJkuDIpjWTkOkXgRbSW/OP",
	"BOTOW9T8bNfbY/5/Mt6xwqUZ4a/xXxKWk+eT/+NRfv2P7K/qEc5+BiqJvOmLy54kUglpJoLrOBIhpFCq",
	"20JgBw9a3l/l43Si9C4yU4UA8bvF7xDoSWE/r7hmetcMZ8Df9wG0XaEN0m6N4aAuz19aeAtcX+DOGtY1",
	"A+a494Z38vXT9rO9C4JESghfS7FpWkW4MfOlGVQLxZBqmGm2gUm/5S5E52Ja7LfUKV3BOfuzEXYxXcFc",
	"mQH+MiEsaRLpyfNnx9N8Tcb1V08mUwNYtkk2k+dPjo+R/Nh/5cSHcQ0rkKWt2Ad1BlQJ3rQdiWPm0g5q",
	"uM2nx+1nvhCJNPMVaF1pIZ2NORCxK/CHPgS9ecVRBP47uoFG0r6iGzjQOd+EsImFBh7s/gm7xsN6w2Zm",
	"3AFWfheDpFrInPQeitamM59BILYgdynZLa/8lik9eHXvNh8fP3naeTyzyP14temO8vd0rqlu3JTCHwcB",
	"vjxztvQplZoFLKZcH/66vcmbbvw0WUQsuIGlcd6mVc9BMlCNr1jhzwd6x7VEsrjewWnkL3TbTKOu6HZv",
	"GvXRfKxiwRXk4vtrIRcsDIGfuZ/ML4HgGrg2/0vjODIiOhP8USzFIoLN3353PKrf1Z7ar16CpixSdh9F",
	"FeFiDaSoDaBYSiIaXCpCgwCUIloQvWbmvynciZBEigiOMmHvDd/SiIVnVnu44xPhjkggNhvKQxLTXSRo",
	"SLZMRFSDIpQo2FBz4lTbITLxD/OT0K9FwsM7PobbHITuQBKUSGQA5IoqwoUmS7PJfNtnVMNbtmEawnuF",
	"UnFO1whcBwAhhERX7klSDSQy+ze6p2Xc+FrOQMvd7MVSg6wquecQCB4qknDNIpzVX25Dd0Saz/EXt9JR",
	"veiaMaQ2FpTRjDPYMsUEPxF8GbGgD8oPg3TtKk0Ah+sYghxTYimMKsaE0eftDIQpojT10fxnbu5JSPbn",
	"PUMYBSrd8oYpxfhqSpglMFNDeuA6NnT4CCm4WwjJaqDZFl4mEL3hS9RhYilikJpZshsCDSPGoa/GMp2w",
	"sAd5N1owlRrCOdX9pzZiSYLbAm6w7dcJxe1PfqvjUznv+XVilWX7eWHtaX7CfBKRa+WhkdjFinFHpqsQ",
	"iqlSV0KGJQHxybOv28X96eRKMg3veLSz3LG852zito2JRDfuTMJSglrPdZOtC38m+LPhWBK24hKOyLfO",
	"uhVEzOClowjRjgiONOF7rWOzbaLjzRxNYHO3lLOW/Tfhgs8WpWkCyonSLIrMW9uyEHAyWdgFsyv8cP7u",
	"J7IQ4e7oPZ903W3xmI3AOo3oDmRqaGL2QaZ4lMShlXhDiEDXIVR1FjRm+ESgCH2aLdJKsuq39nHqjF2/",
	"a2amqGzG/qoSe8baEYb4z1Uq5g/ZhJPgp5MFLIWEPScJJNChL70nEYlxuXmv0XUUoQhFH+bT9P78RUoA",
	"KcK4cNA+WJhpYCW82YJEnVBEW5gbAM03qsx1v37qc93jKtdNMTn0cGMhRASUp5RUzY3mIlGebh5l6W0r",
	"u8IjnduxH6eTRIG0ikANVl4xrtpFiONaLda/umwBj6TjvNMG4NWcN4dPx1W1PPADXdSY9+E23/YNT6KI",
	"LqLMmr0Ho74VVPFNZccF1vlkavRLDdJwrf/nVzr788Xs38ezb+az3/72X3VbPgSSITDqMM27ruFo14hs",
	"jhn35+UH4YlowGxjYUaZbZIfvgUqQeYar+HfSyHJggaXV1SGamYwgGq2iKBOIPAEDetjS2XYTO8nibJC",
	"gojpHwmQ+dyOdEKHGz+fkw2VlyAJ40oDDYlYEkoSZbCf/PDLRa0QMZ1YkVjNGe9SkXw4OEkanX0V/Ko+",
	"7g4ZzMGwKAR9SkDEHVuHjSdO2WN1i+UFBCsDqzB54bpq8Rl9BlKzJQ106tpK94NGc+uQMK/SGt9UICTk",
	"/8x/1pSHjK/MA16JKAQ+X0mRxLiheL4UiTSSgKTBJZjxwZpuYnOdtUIjbktr4CHlAWQ8P90Z41tmuJA5",
	"/IopDRL/EawhuITQHNYQGb0OJb1qW6HoyCwhs8ZLvISdAk2srZMIGZq1yGJHnIeKB0AM6ZoSamYj6Isj",
	"b15OCeUhYZtNYuexgMq15DcvzVsoUQ4zw9x683rymcxPNoQPppsYJQL6K07LWy7O3YxxVX9qAekM39rE",
	"OdZ1XCHqFHWqWkjRVpHfgr2j3GpxRM7oFTGUR3IaZRY8pgiHLT7rIEpCCGvuKvXb1wCwLERIoGGusU6b",
	"9JJLB4rhnvlpD9Tp3EQPiapzjtzLPmYHvv98lNt86rvCqx7wzg0wNbePWlvpoXa4J78xNVdJDFJBaHWG",
	"7k/6PNjOfYrlkgWMRvPMXdz6oDvnk+6lzN0DaDlK/pLd2nvhXNHdXfVy950g07WHf+8gx5PNwpp9mxWR",
	"x40T+rKLMPxoLEByF9eYr4sOqzEzXDHO4UB0rSy2lFlFxb2WQW5acvUVEW1aDGnyIqgKgTAVpJ6WeFdB",
	"Jykg0rQSh5HDpf31TUtBQH7YURnXCvSmTEzaeecpXdVoHnh8/D+mYaMG0FBkoB/RR/7GfopOcrcDKiXd",
	"mZ85XOt5kAlMNIreLSfPfx0azfVbGZXKqOIOUlywESInVMNKyJ0vRlzBAm94F2MA0VJI4IoFyl6DAbLh",
	"6FcYYqNhRblYSRqvd+avcWAuWTG8lY1YsMgMXlMZXlGUfTdMBVWRZDq5npnlZ1uKaK3MPgob/AU3VfjT",
	"SbrDwl9fe9st/HCW7b3w51M8SOFP56VTFcfjEQt/eufOW/jjj+nhC3/9PodEcTSC5WNljrAgu0vKQ4wf",
	"Q01qMp2Eki51s4R3IqS0wtqrLQuNvF2V9N5kAl6QjSYSAiHDI/LC2s5TP5URyxMeieCSgJvQyHsSNGXc",
	"ivZbGiVQFfmcV28saV0yiMKBrzM//GvzdfGJfoWsyf2jmTdlrzcNghqzeeFCYcYz+pTDDzizC5VzxAE9",
	"1HuJTfsxV0ecUfEffY2nGSKee9M5CLXe3v683WL9nKHTdfQJfsZZ3ljPbQEfnx5/83X3OdC7io7eechW",
	"zmxXEtQ9M6b5p2/HPJ59Q2fL3/76+unH/5oMFUG8F1wVP3yRI48X9BE/Q+PsMZcws+50ZcSp3EMzXys9",
	"fp+9oThSI6dYW+oGNA2ppn2o6inVwbrOdNr7wX5HN1CIbf1Y2ccwFDs3H/+Yfuvs5NB7L5kPbZAw2445",
	"uVxYIxA2Ar3xQnMy8CYLgSiytJeIPTPMqPC4l+Fz+D8We6z9wvvdt2AITeA6FqrOfBFCMMAEhHZEjPvI",
	"hN1+0X7ZxtL4kkyKHGaDMjQAD3YImtF+09WT1ux4WgBgZXeDMKDACKreBGec7QunbHx/K4pv/jWQNgcV",
	"iZp34MhgK1c28f7mijiiASDp7thkD66O1nQh99xVWdktXMO0cI0NkGjaS8ONNIOhB/blSQgpR0G7/iVA",
	"zPhqDlJiYO8WJFsyCOcqWWCAFL6GjCXKJDJn78FkihS9RnG1gvgNvG5Hnfdz+ubHPwwzyXZUnnpaAUWP",
	"yyxIZBVGciI2cQQagxJjKmFGeThToHPtZykkkRABVYyvCOUk4SFTQWQ4x5QkPFEQEgkK5BZ5T5WbLBj6",
	"fm5BoJseFFe6F0uZQQaQekd+LXtsNSRWDYfZHEnjMuKK9w3cQdEwvbG+n9iw373pc6eq0uWGL2y8Kqln",
	"YKjd8bSWhRehW3uzVdyaljG7+TWiLTHPKfBCEmgYMnMWGp16j2ZJIwXld5RtKpfoemJUbYxMbCCpe0pq",
	"ODS3XyuXfdOcRvP4a2/9p52hIa1ny/ZaXL8R3C8hYluQuzMIgMU1kR/FXN5egpP1OfYdHtod7GmR6C38",
	"ZpHmvZ8yp7Fai97jNVWXe4QEllKnPWBWdl/cW75yCabNd8+WSxYkkS4YfIGqncFOCFmycebaITbafNZX",
	"dqbSX39MJy79/XtcJ9sb2jIboloHmlxwrjyy1bOzVI0qSyaVno9Ak3RAj/3Y5KzX9oMBuCtENNDWlNrz",
	"C6d+5ls7vyqBYDpJOPsjAfcz+hRyh8sIZqwwlGkMRBVEls4F9hgOBfY9fr8Tt1o4a4MUoT8uZnYVnUg+",
	"OKPFfjbvTI0YJkrXOAszluKmb3gdTXfsMHaamXzwtOXdT7M3XX/jzdTLe9Vjo99L82BpgI/T1pCUarSH",
	"5zQbhJIHCWC4UQwapqm76/W8yFkMewajsue4uI8+d31RivVbUBR6WHDZrD57j66avDPFsi3lYOzSDK+l",
	"+BP4Sw9gRXxb4u973WRvM9MpTRSkW0ltTUKyFeM02vtSB+tGG8q4Eex7BJ/3iPkAlWyG2Rh6RbaYOQcT",
	"zN4xL3sHu5RekjN1edpZ9XqnHs6VrqEAxprzextvfHHfubD4ognkHQfiJFLCOKFEWWexlWiIioQ+ImcQ",
	"R3SnyAo0oYTDFTGTkTcv0WNs3cMYEWyGz1ldSKATerkYQdr6K/XFgKkBMRhVP001EMNbYXtQ46+D2oHl",
	"kpty91j5IBIldYYLTy5oCxGqAWIrzpZLw2RWWbQUoplQSuC2wkhmf10KuQRmHgsXNosiVaeWlEWJdFxi",
	"I/g8jqg2IPF+CZkKBOc2hwuuIUhQJ4dYBOv5QgK9dBOvxVUuZAWUBxBFULLL+H8OQbKtZ32pD2sqsSq8",
	"yUjUKU8W+AOlaKQEH6ua0mi5p7e6o5iuIa5F28lXnfpHICTMbeLcAO3sHKPzByoCXSJ1dqSCRFTY4TS/",
	"pVY8r0gzcUQ5h9SquHPSFyJyTJ2pLhd0ppOtwC356NYHu97wgIXA9bcJD6MaDnFCueAsoBFJowZtNq2N",
	"F1/gVyQQXFt2RagmG6E0eXr8zdc25F/VxAulk869RPdSJgtV8PXTGfBAhBCS7Au7urcgF2QjJBC9ptyu",
	"mm3Uyzso5tcsdrqX5FTZ5xz3Y34tSKxmqwbEIyaMnD1+7+ja6tTlLJpKIYQ+O14BNzR1T61msNW215HV",
	"mj559vXN+jn2DS4q61Qlg329ybcA9JqrnTRedyvOtuBfBsxGIvVWBJdnaIEeZ8HPU5DmWQZ0kXN1cpDc",
	"5uMs7A1mv3oL0HgXwuMGF8IyYqv10ICNwcb/mlWmDdBsvLwfKU9odEqZfMPjZOjVjbahjrUVlmA0yErV",
	"CIN3Ljg9lSjzm28KmU3D2SspakshieBg9SAhnbq0XyrUDaQ+7RmW2xIV27l5lyF5Y7oYzp9pQwOnd3pR",
	"3bxjg4BlaLT5Tu22m6f1DQUaYdsIhAz3jRNG0Xbg1oZFGzeNHoVM9mF2o1OawjsCoZx60YxSzhFfQ9/H",
	"R2YhZetPG4qk79x+nlKJoTEJhzcnNAR9pY9qWoxOLpy+b7ByU16UR0eKRKuEE2U0LIW5Vp5F17UX32NP",
	"nuVfXCkxuEdCcFYk1Yt1GyXICb5kctMZ8HMYMQuujSJMU8PBoAK4t5BZUjaixGnM+JDMB/ymqCXtmYpQ",
	"iaKusffsmXhyOzkTxU0Pk51zRPWi03188pIV7L01v0P3dl5bu6IRIl7h4hliDnhAe1nDW4Sy27csl6M3",
	"M7OwR3irBuK+UB5HnkaUilhQxQplAGUSwdwWK20qxNFFBdN4uYMpuY+HKbmurqTeHSTwcuW8RwPkoo4n",
	"UysqObM946sx2qZXlWVvEVUkeiGuh6FRfwmvJQlwSMlH86HBVBa228AeF01gL2b/prM/j2ffHM2fN5W8",
	"6iXoH0qw73Njhw6lbRMbm9Gwmak0vrryK0rJTX53JWrRjMgNgmYjGGuK0JTxuhFrO4n0T+J8La5uVoQ8",
	"LBErK3nDVDtvIqxHPhRf868ZD8XV4O8bkGI0d/lqOHOppVJ9xPDPj5pMs6L0PRVmc+WHoFN5Lfx80iL1",
	"2odCVTC7HW+bHlcLtg6lYZ10qNQxYYywqAwRc+UTBiYSHIRCHUJTLhd7rtWIai+/BIPeAD93seoDQV6q",
	"lDK6A4tzg8+xjsdA2RQj7r7DD+sjfdDP1c/sbodmBGiYImw5TJ12nr/7ge1SUto0cCe/0G1NVEgjMcrS",
	"USbpahkAihfTs1JNfstxRHcjNb881WJgysrwnJi7kWCCSKhkBCddUhY5+bN3+cTIcYP+Gky4mw9hdKVv",
	"DqIy9RFG/OTgIRDxvxsGmdJ3NywHDTD6HFiH8nGmKJN4AYOlfKgSau4nvtS9j2kDXahHhPpr7rjEKva3",
	"4HYPEqhAbuHTp4G5UjtMQcoqAhyCZFYmG76dHDAH2dBhOYILO7yZyQbDCq7XNFEodrYHHzRPsWZKH+pA",
	"5bkGbyYWIjrITgoTjSgtk+d9H2I3dfMN3tTQPNqhEoUhbEKNWCj7sH/mrvfRFqRqjFJuBe9488jnzOCb",
	"uO8+fL6ezHTQ7LbX2PjkO4hJG93qYkKtHK/HY+2iD12EvZWL1LyimjfS8EgbiERRJOiUg3KV9i0bLAdl",
	"im9/DbioQg+r91rp5DowCgZX6qkqn1JmJjkx72eVSDokkqMY6WijQslGhLbTIZOgSJpTQDb46zy2yylM",
	"9qLYryJiAdMkPSJZ7ACTxMC1GmRSpdMRiX9OW5ZAVlqnLifgAEnhAw3aGd5vXCnW3qth7dbDR7s4mC92",
	"0MMB2unELN3gMLiWQ4YLb+IfPqyf1IXB4JIZXLMUhESLDdUsmKS7q3Wul7CmZxYtLmnx8J37Mn0XaNNL",
	"eNhQzLyYgvR0kKW1IwilsGwJMGUEnE765Mm3HvSgfriRAk2ltGiF0becLUP6+nQ32/akX/W+UpeUAzVy",
	"uIFWch2l8WvkRQgHVCCqLxgw2OFlexruA7y62E+/tH0lOcbrlIdnnvo4UCpT722vD3q9yCTEoRYWzMLL",
	"BJt+ogVVl5m7ZHhFpd6GxqzkU3eRjFKZKAzoywp+OYES5oFIuG5HtSfD26AV9IAyPNs2kp9x2BX7LclG",
	"GdOGNo/3sOtA/r2D63INHsJ8431A7NXxGGmv3Kuuy+iU5bzGnZn0MBaeQ4U72+lG1YEZJpo0AaG8i7q6",
	"L32Q461YLHYjn95hoOmYSySCy8bOpSO8tuUzNntx+8ca5dpnXkzqwBFuLjSjSU71QVWTTdBxz+cZHIck",
	"Fo6vsSZiO2weMmXkhHlN38+vn+5vbBsbLNbf0lkOovatau7Ksnpd9afOV+tzXadC6TQvaj+SnRdeuuTi",
	"KoJw5XVFdOX/52jT8NjKdBKB2W1ksKZW+zsoSR1GEt3ZhoJxnHQRBBCjxHrTAD0MMd2jcEahZkYD4IvA",
	"6HMDZ0DD3W2Xk22y/Ie7Ov4y0FaA0/Q7+h5Bbzb4d4+gN980tWVw9UnEvjVvelqGyJAbGBkFV1QtBoWu",
	"1SoZdVFsYVpydcD0tkxr7XSWvoyRjzICWTWcD5mrJgLwgIRtVNpvPaTGBRMP3IAN2OtsGNdP7bN364Xw",
	"4YZSFCqohb29FNm9nWeF/O8Fsca+AtrMt4zoqtIa85uOpJvp5EoyDbmZayCRLy0/FIB3qE15rS56CcTe",
	"rgMhw5502lulH2xc+bdPIZm52aC+V5GY/BAtECvXGPXTHb1YNRe739190MZQO6Wr3ELp0IU50/zD3sXt",
	"bI3Mm6gQcsj6VYeRqN19eQhRqAzqAaIdPb5LI+lL/bYSiW5ejOomqZ32iJwl3Fwn9niX1j0cSxGAUrNI",
	"BNgz3HyQRXIQKoHAdUvbcLaFuY0dH+nwRCsxyMHmnESBoVFY8vHEzlFnzUnBiu1oYwlK9e1tfWBRzFWK",
	"zfYz7Lyl2scf6/thjgFiU2lJTAU4ZOU3WwHxoFWFsc2G04cGHDv9qrbAQlpFdNCUGSa+MXi4pVHt3AMd",
	"hmOMnImClvwUkBssYEwHNmPpvtzx4nNPoblDRPZdkk4OzuRi+zJywTjDGv+6PUJU81anFVLn43MDlam8",
	"oZYbaKfyFUJXYd8R2zDd7ns47vdIB6fwt1H/m6vWPfQ5pW2o9oJPWRjOkcHHv0r+ub0ct4c+hb/9d1y5",
	"atdjfT6g1FvP8uw3U0vr4MLXoCy9WhmsKHmVAdpbAEvrPJ6sIbisuai+AWr5RGmEmtcbPKP+1UDhEnkv",
	"lV2qeaiqoRdbJfontCWLVdZdzKu/k22uB2DKoWTm16OsPuaR0jIJdCLhyL2fNJARe0w2jS3EkzQP858h",
	"irDKVmJu+SLt2tU8xAv2al/bhe+1DVrsOmZJY+nqRmmqLtURBj4HflRp41DGt8C1rXZdPwJVeLSW1P8e",
	"MmUedtg4IOFroJFetyxhq3Q2nydZRCyIdnPX6rdx4JUUfDV3vW3KQ6TVco66AJOOS9UdaqNatJB0BS3j",
	"C/1DmwZhCLbrAbZrGScNyKz823gOGtOA6bZZgkgEly2/hxADN8+2HnOzkwVrCJMIWkwI6TdnEAup20qx",
	"ZtOntVix9SZVxD52o3FetgQX08g8NL3e+OkdBUoyy1aYSdzNbPu4X0lvQ7DVYK3Bp/blyOWuRvGwpVFy",
	"Q4GMnZ9x80HE/sTiw3FSKv1Wm+PbdpackXRr0bEUYjlfU7W+2ZrfKT8fe6vnWPrRb+w96HoPXHK8NrSy",
	"+iBKaFV30T5kCreRvYLsPrv5+T3wBQyxsnYfqHTrFRHOFgStfSQG8HW/VLoj4wzp+LYtZaaMirmbu5Sj",
	"PShH3h/lwDaYm2v6merptonLITTGu1I+byp+KUWa0eFnNxUh3maeKQSWVOrDZwFvhbsv6ms+Hlcxu2dY",
	"eQF0nmSRzVWaulUkco2JC9LJ3AojTd+k5KpPUfusiP3GNZ3HavaUuN5EBKckaUZijSjl9esfIz8U+//3",
	"SuRwX2Rl7W8si6PbSEx3kaDhrXRYv8FK8G6+HgVoD2CtPYS0UsCZaQEHi+epXFEBXZpfMOqK30oaXIL+",
	"Ma3hPLhFxtBY1PaWWN1tsMb1v8KuGYPDZrXRY/0GbLBhS1ef3f73t8PFz5YFH22VaK/fVg3A68+Wgqqz",
	"+nABB0YGWmwM6gz2tFSRr7XB8aeVUZKCpAPupe6/t5ZCYnsBDH0NN9oj+DA9gdua+ZYeSFdb346re8u2",
	"gJAdHQg9ogd8FWs6O8GPTzY4YKf2m3nJt9Ra/fb6qN9cced6KpVlWGRKgzMHj+tlbrHzjqO0byuyunf0",
	"dAEoIwOnF5ZNDmesfhByxLYwHxOT00Twap2Vg0Od65AmFfUWgspwwDTn2Uf+wQdWFbVT5alp+VRthUG9",
	"/U6z+yoAvW8Mcekkr7i2LHcIviTBei2iPzv99dUHNFQogOUSbGSHYeR9+qfXPFrBXDeVgZuVlF/uKyPg",
	"HKVzZ1ua5qCsO2rvSxwpJADXI2KYahGo0mTjE5auU7B0gL/mCQ/VbzlT62Hm3nojrO5vjTxg8rwzGir2",
	"JwyonPG0VtbSVOo9IXGf8oKzSIWsfbsHq8JxpwU0qL+aRkQ8AxoyDkq92kJddZeB9SL7KFI9zHmDHQlp",
	"U+UeYZz+eVN185a6BhSq4tW3DKiYy13/4F6KX83hyvkERp2MgMo2azdmcP5i8w7qfFUq2RzYw9SZmnAo",
	"H5WIge+JnXu3iexNZLx72D+BvYRzpUYPjsbk4ClkK/h33op8hd16qGfm9eaxAWe4s37t8KvB1435EFm8",
	"L2Fu7BE5EVwznkCY/U2R2NWwIXoNTBJzUroCQgMplCKU5PTYZkzUlMaztXAO+Q4Cu1FbMrKtKNqgiN8g",
	"Pf58KcXmUP6K/d/skDLvPYf1gVkv/8kBCMVNB1o/OM9752xk5FMlCqPkwvliNyipqfO2b8bL3hB/Xt9N",
	"tyI7VFzsWcHDOkJTRyiaINbNMjLiWHDs9/Hbl26tykYyEl/iJAHlAURROyPBhgG2Pcy9yHv2Lm2gGm0P",
	"4SXd1lQELTarfLpf59bCVluur9jxvuCclFtENOGKCbddlF32RPBlxIKaKNRzGzghYs02TGkWzALBbaB/",
	"sCMhaMoiRfSaahJQTmhg4Ej5jlDy9PgbIp3GXcPXXbLAHpeaTrGXQunVkT5wJF1NZkQPTTHrvlS8h9dJ",
	"FPnSkqVTR+TVNQSJGYPgR32VCB7tyNWaRUBsSauprV9MnDrrPjZfcKHJAojtZ1yXmXqIeBNI9zh3G6ge",
	"70ImkO4buNs2YYrQSAli5j1qXqmQs15a6i5C9PKSa90btmMPm8w5mtb5FWg7DYUHlGPubbRdA1XOrrgO",
	"t0eUZm3gMcM7a+9XIXhY2d79C/GWHWytFW8bgdeV3jeuKXK3Epkynz7tPQfPbiN8Rug2ezj6+977nsFX",
	"Iw6lIjGUlGEhi0jobp/+2CKHIzK1GeeN72tg04Q6clWLNE1wr3H7p7Fi+T5T0Leh+7TtpXW82tcZtqbC",
	"60I8nkwnC/FVs9CaFR5MIn2WFZXJpF/coJf/mErB80BICWm0j9PtcmWmAM4eOo6P3BXaU72JK8bVXrWk",
	"a+9x71lLaNWw7+a1O+63olvGEeUcoZ1x0NQrnhrObYGAtO3cbp7tbzrREKw5C7CtQ6KszdTec0/FtFKW",
	"aV9PjBluC1rtIyAHgmtb2PTmI6vdK+iZdDaCVgeip5Mov4xz/AZRvE/ET30U2MBGWf37Y5XjcXGz06Kb",
	"qYboupOUcCS/gOKW8w1V0KH5jZUAWG0aMbit4RBj8f3p3LWHwyb31bTFzeUdvnI7YBG4zZd0xZT61kWP",
	"GHqYqAJBlMJyy45Ycm+uXc1ND+03eYPJZhgxM6dXVIadCkJ3zbj9vIC2Ac1oR172eZ3Vt3jOsq+vV7cv",
	"vE/X0mb/Ox2tM/T16roqCnMbRz2yTFk2S14PsPMb6fprWbvRkiaRzpTgms49/S99vFLSgS4DRfHB2PLK",
	"K2xStKRZwQZCEkJgc93SyW2uW9qEihR6my12oI7IxRpILNmWasg/N6o4YYpwoYmrJjGwxsB6Q4OZWtMn",
	"z76emb3JvuUFzB7CTyLTf1COu7hqVgO7rXuJNHdQ4CGOgvzWK64CherbkDRd8fZDwa3WceeAUZ/TX5/E",
	"n1WU9wHhXUoB7ToeI/KAt3QB0X48/cxQjioHWOwGF5FKJYTaoOxMWzpsOMXtNRa7c8u6bWDnl5XqdyVl",
	"sp1PNtCuVRAZmtsSPr5Re71zkhfZWPEgnVfZ13ta37zyYA0N0frFw5EXce6+HeQOHhVF24mb97diQaEH",
	"ZLXrThmLvJfhX45nMRrsXyneVVVNTvtvKBENSGBoEFs91Noj/yL9FJ3byQCULKmaB0rNWAMN51rM8b80",
	"jiPWVDW8MHJ0RsdoxXPMWlaTi1I23pMGe7y/M5u9f2tKhfEW88M716r6a5ZOniW5FCBRyHkpo2P9PTfg",
	"SR0KFk/a+HIvqLosx7dYsW4ynaxEFAJvFq0KnScripJNDiEsKw6iqbr0SnyfOkVoGdEV2VANktEIlSWv",
	"RyNx8a2qo8D36Jzpwp7/qitHtFyyIIl0v6lf5sPNW2W8S7Eps67ehUuymxthm7W1nuZLFsE8kVHxG8n6",
	"mBn6m3fdWLdO98QGgXtUCa5Pi2I6aqiClavN+2SxNZmUc6XIVRGxOyniVyEH3kOswqFTrGl+soU0y8NH",
	"E43Jxjpc8S0sVY1xm2Nq/Fbiz+q0tFGZYncWVXy3yWUHzAOpiQ28+a7P1fyzinzsUtEGC735eQ7To9YP",
	"D55LWDGls4KweHNzZeSi7F+OO6f/jCO6E8ulSsOts+rQnhc3c+LW8vTPol1NXm6ku29NGSO9S8id5oV7",
	"qDQydTeS3YV3C3s703/GoNF9grzvy40O6ejfux1Rd8P/X1znhiJQetLdDRiNeqDRwqz4I35YNL4+qatN",
	"e/AuI4VWS8MYp58sedPF8Q+QeniHbMxc8aGypVuDYishsikLSzFzWu6tVcimzvGr9X2cCK6liA7MvKrb",
	"emBLvdmSR0QqxGuE3Uam6dTzg75h15S220+wRyOyGv9uHjOSxrPVnK8VtC0xcz7izrM0rVLYnH1YJXZe",
	"+LJ3VvAJypxGk/fe3zjDhpmkxa7RyoGHWDnMOkUjR02jyyfPnk27lqzaRjpNA81xxtPJ9WwlZu5vv/72",
	"f2b9NLO/z9Qli2citqRthhY188LStqqejaKUOkPVJQEe4hdH5AUasxVZax1/ob4kP5+9VURIshZKP4+F",
	"1ERTuQKtMBwgvuKPeEBsL4hedpWDmD8G3UW5hMd4y0Vj09GXCUQvMZfNLxFTauyYdJuHzTx+ySmX0oDg",
	"7S2pmUlO8UP78rwKVm0Ocdxfacmms9ZMXyXlw7JBRLRtYoH2t71qxoyO1vSTSnJzmNttE3hakKArHf8g",
	"5qrR5ik87OP5oOFPBmSEd8m1tXJr0gvjc3/VodMkPKgUzpztrpBS7Z2yCT2qUZwZ801vu5adfo9NfVqQ",
	"a1EQVS8n0wlI2ZC/KyFkasB4C+t5g525hwtQAb0CCJeDFq1ACj8IYSVpvdBRLX7sbmgxSc/sb6Vyrro7",
	"+0Ew3ijAJApkWuQOrqkRmSbPJ5peJjtqzZeZlH1cYFRPitFRdPbni9m/j2ffzGe//e2/OulStmzzhg9B",
	"mBupYd2yb4GGIIvVBksK1RYkXcFAR/mBCvZNC3dVl1013PtbXwQwW8fNOm04eAcQm69waEG/ys0UK+se",
	"d1UcaCmUZ0WBH6F5s65jZx/55wUONTTyDV+KnMd0fWc30Vhh003SvP3mzffwOI3ltv14m91gzt18HG4l",
	"Lj04m4enGaHsqPhf2I5Hl1mIQvUfCSSoGTJuL7yOqp9KsYhgYwVmVROC/PqE/P0fx38nyBgI8C1EIgbb",
	"tmyxI7AFuSNPr68fPbu+bikRYatLFAlzemSySRSWLnhydPTsmARrKmngus5WL5QrnSZG51M9ojF7tH38",
	"yGKXevS7YLzeQIGswxHc/Pvjx9//6+TJP795/fTf3339f//P4xcvvv37xbf/199fnLZjSzbD0+PjaYvD",
	"7Nk33/ges+PjVpUq39f/0IiF6BEgrylzuY1Npfzyz+hCJPr5IrIksORv71DJbPW8VDNzR61Dv4IZwEO/",
	"K1gg7u5iLezqwBULXNstkGiYi6+smRFWlAtsCWw0vDgOJtOJUAzr727EguEm1lSGVxTzWTdMBbWIXDIW",
	"ePsBqnZoygxZsnGzNU7hU5/iS3gRbhgnWwZXRCwJRT3bhtl/MLroB7JkEGF0Pda+MCclEnQiOYREC0LN",
	"92pKOP6iBXG4Oj7ApGyHGUMf7952c3BrTe4K6Wu6GcAnDhTNcu+sP6V4KpAzDKEygwgOIowTm/KC0x/K",
	"WtTHabGnkSjFqE5++jN64vGdp6JIg6JxKNm5twAxRDs5jPi8j9xsAflga74xW3M9JSpV+wJtuAy3xaYI",
	"1rAllJMkjoRR2ImdgZgZjshPgs9wKLZktCGQG8rpyop5eg3pePt9TqeqAkb7gYtn+smNPR9kRDfDBI3Z",
	"LBAhrIDP4FpLOtPURv7/jm61MoimYmPuJNZWqboXdPj2gJEetwyFO/EB1FAMg1Rp59EmBbCb+/bpO5p/",
	"X6VdNos0kUzvzg1lsOt+C1SCfJForBm6wH+l5U4mP/xyUWJOqaxIgwCUIlpcAidffH/+5NnXXx6Rb6W4",
	"UiBJEDFDgYhaiyQKjUKFr+x7reN3RoDU8WaOMuPczRMIccmAMKUS+yhP351fkFTzwaGPIrFi3CBnzW8S",
	"lhLU+oj8zBVdgptvRhO9Bq6ZocihlVKJU5OU1cywbpsCHpJ/zU7Oz17PLsyJjsiZndAsKhLtfUR3drg5",
	"j1uVmA8dKBgnwPQaZGE+s+t/zRByMzdzYbUXtiH5n6gNPSf2ToiEDWVckTTvwwrf5iFm27liem32t3CA",
	"fyfZivFHZ7AEM8Ma7TFqSpQgXPBZOgxTaWlweUVlqGZYClGzRQTZxQWUk0uAmCSK8RVh+ug9T42Y6DXB",
	"HeZIaeiHwfVzwDoPeKwUp4rok+GAiOkfCZCff37zkij7WQca+ApwdtPFK7ZDyNmr84teF02w85k5or1P",
	"GtoQ+3gzdzbIQMml25fViPzLVkSxldGBEKAi4agNFVDd7ah4QjuTohvIZ3I5ywaDCjtM7Q7pZSICqDhi",
	"ehYKgyDZ5dM4VvaemIG0XcqQaZTCJt6h3G7y+6Mx+ycYqolWiKWoMZYYkKpELqnL0DanPLl4TX4E0D/H",
	"BK1vTO+OyC+wOBfBJWgSS6FFICLyxYfvXl2QR1fqw5fvOVMkFEGyAa7tcQ3wmMJq3NwyAYMeiVYsNHSD",
	"KfIuBv7i9A1RMQRH7/l7xC136+bFvOeEzIgVbFWV3HyoHv1DE64VkMzOi+9WEQkBsG15Wp+MfcCjeH92",
	"BCJdTJGlFBszKUkx26Ns5lv/rxlN+1BPHt4nx8dfBb9fafwf+GDnTYmGSmLDv/egGkd2wqEUFd/YBx+F",
	"P7iZ9qapdpri3Ia0fmimrR/sg3DcHCWFWQxytmE80UC+pcGlWfnF6Rsv++D55PHR8dFxWvmbxmzyfPLV",
	"0fHRVxi3otfIOWu4E7J1oXRduQOdSK7wiPZUMWUSr6WWEPvUOiXKWBzVkjGtWpipGVfBwRwFzZLFmTPG",
	"PbNSRJjfTYr07vpTMrah8hJkKlAzjuf64fzdT+5waC+yO0GkME+yQNUMCuJHbs/edZsNJo64I35tEo2Y",
	"rypsuQfmDGDDiCm2DBsT/E2YCjtv8WozA+u3woZsufJHqDPHceRo0aPfXdyb1b46PRHZAqk6+bEo2WVx",
	"o5YLIOY9OT4+7Abw/J5bo6yMTnCH5N0/j1zunIvobQZm9QV411LPKZtQ9ijzntZ33//XoZYtyKLtq5p1",
	"nx4/brmF2Dof/jbsNkoui5qbeMO3NGIhialSV0KGR4ZKPX381R1sxWEsWYhwR+A6AAhVTggU+9OZ19wW",
	"n93hFt2yxNxj5pIpP5ojqyMlmw2Vu8nzyavrYE35ygoTak1lxvFS4NtSNdz91ZOqUD/9dYJ/n/xmpq1w",
	"C2Er5zaxi624BAtNw8kjhkTZPguLzUoQZouZc0EiwVcgzaHAbTp8z23PeA5XyGuszFmcw3y98FbwCTne",
	"qpDvuTORdL9TXKCgGDJFEk4xqdZs6AuGpXmYBEU41YlESW/LKGFWWZSaXFy8/fKIvLX0PRRgC/o4ekjo",
	"e1fUXZsP8SH4C6KiQ7lbJMz4XCZ9Y+1xFkXvuUQIFxiH3bPhWc6glOiMbR695yd1ElC6Qo0MVM+T3nMj",
	"A7awoWYV8j0fx7wMpt0s9xKJHsS+ntZhvH8J9nYccbsTOvsjU0b1nRJmCe40RaopQVEa91dEnQdSfGOk",
	"+Cx/rRmxSpUP7wb6kF6n4JkDrWz6avHVvGVKe34Smwgo6QbQa//817+sdv1HAuigcco145hSPw8hDWXP",
	"4dZVCu7jb3vKd/0Sq3zfT2OsbuXaXkQRKiPuYLln965fpnmG7m0W+e9RwdSJN+YbOX/9zcA7Ry1z3+mp",
	"rFqSVYEgUR7PRJSm6Gjri2CPsOWyj2dlH4bcgpydm7eAHfoUUVoC3WTWFSdrWANSSNUaN+JsR3YobJhW",
	"7/kHzJv4QNhmAyGjGqIdoUttOF+yyBa11gm3vbkTEz5gJwvrt1/De+6Wi5jS08x4hYESSPjsnny4pIUS",
	"FbEzHr3n3wOVegFUW1+LMkekipyfvyKB2GzwrLbvhzmma99jNsgUYWEEdczsHA/sIbGF2aTz6Wi41vYu",
	"ZhZoRVysSPZldDO7th8epfdkDmWN82gEUaSyxufzPCzci7hokCOd3AbwQHoZvV/HXyz8aB8Fpq5Vn4dY",
	"akd0LCezH06tbKZco75UsHPSn0HwNeKiXsMGrW3EX7aAuOYURq5LTTNPj78hbOmtZdAxlzZtyJkFK6Ek",
	"TCCqw9OXuGUPTyd9pB/7VXi/0cZs7ekdbM3CEfWApVHh3Va+ubutMFWLDg/y34Hlv95EKicWRv0zPMS9",
	"4RqSVC/PxVSvPXEunJS1GF+i64pm/206cY1xijD4RTJDzqyGGrGA6RaGinLAFToAeUhchArBCBWMXTp6",
	"z89B44j/deyPKUax/K9jogWRsBG2vWlK3JA44r9tgSlvC3V0rRJAdEMqZWOg0l3YRSvx3hWstttNxWJH",
	"mY7v4Hl50bQYzvzASu45K/k5jRDH7nEowBNNH8wId8hGzgAvhKYk0tDUjBq7ztD7aIRG5n1Ek9AGJPWx",
	"PrzAwb0sEGlcaI3d4Vlr/P6T4+OO2m23bZ/AU6OuNcRS8RNcgdIzLGlPEMpOLckU6jsn0qnzBq+OZJf6",
	"QKt70uqRdp0CNtyRRFghCs5w2ewDSmMz3cC5846nYpvvpOnroPGjEDhc7RWJ4OZ22nm2uMWe1GtCOpwm",
	"dnuHjjZoCwkY7X0ZEznght6k98Utca+jB34qoNoNxBCkuBjeVTRB6wY+ibiCov+tzen1IJ/enJtLaKrB",
	"M/4PCCnIirc0ypUXOOI2ZLmOgjC1TiaXVfBZuZVoei7yBc1SLKfEOQsV1uz+sl4gcSJB8RbzQlc3xFKq",
	"lbR6MZTHB9tAEXOqt2Q3GD4YWm4AZS1sXfpvb5LT6cmp8a9g/iVD0RYk8MAGYFNuo8jBWtPJ90xpIVlA",
	"o3ygdb5Za2aYR5FiwnKDLyZ7Lg9OmD22holj98FudtEHd4Yh/kvnOWhC/Gk9T/0OdD1uHd8aObxAvH/A",
	"1374+iCz3oVNlYbuZZl36grc3aFHrs6tdYMSVTVf/JZV9C4SknqwdE5KHsSqT4aqDXmK9qbTx/gFVgWm",
	"EbFNGqwbKhJXEGJE9umLi5PviYIN5ZoF6sth8uAjm0jUqI6+FFc8EjTE1kd2aOkJfHX8pE6UDJmEQCss",
	"OkM0bGIhqdyRc1tp7/U5iSW4nMyfz96WTE1vhb0eW3C5m5TUpl1/fMDLBrwU0q+7MBpN00su37Gde4Zz",
	"//vNKQkdDpmLvjumUqun25T/EnI38ZZNEmlmHuMjs94spJoWr6ZYKMCcv7C5BeMUHYHtBQLwu5qqALfK",
	"jGprIdQFXWohISw6LH4+e2tQYgEENgsIQ5evQtXl3Pa4h5D8cm69PHfIyH4SmlCDoFOycQ8W/RNoQhXo",
	"Wdg+8LpPSYJ/bSiOL7k/Pj4mP36bie3DeDCSLFqhZl/8///v/+cm/hI9Wco8AWKLU2XsrYMLS+D0kSVF",
	"QlYiDUrgxdBrW3qfYFV/dLu/ZpG2EY50SxmWbLEZ5Bozq6hLRce6b2nDDZIuWTXBYDyDmfydG9IQ0VB3",
	"Q/mQR/n+8mZDb8LJx+mAL19xzfTO9fob/N3g1QwZujC0dtBnLwIt5PA94mdDt3iGPcbPbKeOQV++CzAu",
	"OnwtxWbclxdi2HcniVRCDvvmlK7gnP1p29fdnAu0sF69eh3SADMFMAwhpiuwlktKbHNRcgk7BZoEeEif",
	"G9QtnJ3kkWtvlb9J3+fy9PirnjO8FnLBwtD34WY0v8fnPwn92lDoQlnc/qG7QGWwdk5UByecNoVW1gfG",
	"p31mwCylOkaquZ7ZvxlYzFQgrIzjBjzPSdWkhV7mozqyw3x6duF9NIqqVSdK2yIN+97sbOAr8T+9xcdS",
	"PbHZQN3LSUf6vMY8n/vwRAY7Ay1We0iWJ3oVomMytB6P7/jbxHMjNoCVhYDMzQgCrjpNzYYyUXBa644s",
	"d1Md9QrehEbP08CDHRYi6kvnjRB0cn722sZrWNy9gUgbbHdsfaPZQe/IQ1oGd53knL+WoOAvvXOe8k3P",
	"z89cC6oTwZcRC/S4Z5c6NHnl7e3/tnqxkUd/FbrSfXxk+5elLciGPpKi7Ptb0/M+wSZwU4IdtqbE9omz",
	"yXEa5IZxGhG3kaywQpaP4hqrIWZWX/yLOI52tW1bP9tn39Sf9rYj7bqffWbJz0b5ZpAer86FJ7sTFl/u",
	"JyyO3j7hwWdCfIJDIraEYBcYbTrlvvTWxdoKPWI8QBlgBtexkM1pCa/w54L09sZ9OrlppE8X+jbhYQT1",
	"YfV2BFngEKtcrYC7E9hK34b8nX//Yvbk2ddkA5qGVNP/LFXLXiKhJKBccBdXU1C5WBGQB0LN6QF43Tj0",
	"jimTjK9umN8OFKc9ooBgq5GrDQ9eJbIsWp+mx/lcea07YHp+etf89vyKKXVmXlxtLGJ6TSHBgUR6oVEP",
	"PPe2hf30Ngj1r8NWl8WSxrbSPolFxILdnbJd2/++kdt+B0VWa3vX3zijdcu0K5R26/9ZjBNjmAwhz0Q3",
	"C4XDGyenh2FTyW1wqTOIIxqUeVSGq58nh3KHtqe8S9bU/FhTNfBzeam3z0rcJftvwD1416GQLGApJJBI",
	"BJf3gJE8wn18WjLuWxFc/meRDnPi+0w3zP4eyMYeZMMAkFASS1hGbLXWMxrHEvNUKoTkPhCNbJ+fGOU4",
	"S7iHyafZKT5bpTg94V2SDW8TaCiss8JtNokNZ8gwi0gc/UBMRhjrtjRKqIZU8sCSCwlHU2YO32ANwaW6",
	"D9Qk4TcvhFysmSKBkNKVZ7UG9NSHpRqcWKSVAhmwVGnMz3ia/yz5xJ75Xms2uMMHGWUPsmJBSGhKVpwi",
	"43FduIYgwXelNJX6bomLAqNuPfrL/te60DHW2w3P/4G/pXPOJCiQWziM4b/nWz3HPQ4Jwsw230H1wCYP",
	"SoixprItmrzZYJSwgbmNF7apF9KhiWqme7YhVDPxs/sqWiAtPD9b2lc6577NDDLIOzwkaYLCg3Pgjhzy",
	"CH9CeWbCnSmIsC1JfkdYMB2u1zRRd+6YryF8K7oxfzH/wX+ngtCh4oluisx9RzfQSeDyw+TiXD8proua",
	"ndiZs63YqPfPnpKdZAC9S1ku38Wrrbm3ANo1Rw8NwH3wIOWN8YUiGJHeLZcsYDQiBvcxFjDSKC+EEAPH",
	"YI/ci6XuO82TEEd09xnQu4pAt6QsgtDeUi7UxVJssZ9BWigRHRMopzsyiFUWx9JGdHTsCnTjO9sX/3MX",
	"88y5929ZZWYpXIqI4UHKu3O/HS28Jpdq5cS8sFLk5z7QuUwqXQq5BKbviMLtrYOC1pF9CRn73oM4BUKG",
	"hXf72kLns6dP7pwHU0MdVhGJIH0gUHdHoAz8CU1VGy/bK72ju6VMnMZqLXTvyLTz9IO9Uh/TtMVbyzw0",
	"97AFucu235Z7KN1gkkLH9lqx2Gyo2WeStXs3z8E1niPLJIryx+Dne97HGLtxz+uKbg3fN/85eDZYT272",
	"C922KydmABaCkyLq8Kxl76Cau5rx+trgdjN36Qhm2c+WrZvDuWPfpTEGYdwSMGh+fyBjw8nYuxg7T2sq",
	"dSXpMq2wgtV/AkzMJJQ4bL87Rl+mRFzM1Fpc3S9S1FPpSD1eB1E5sHWaw6zztbj67FUNe8x9NY2fLP4Y",
	"tDcAfFAw7kyisv0BfQ0DW4vNrhgPxRVxD/2miI/tJdhGejpVi1OcolBP4oZD20oLttWlexFF4ipiClv+",
	"2b6Jnqhq+9AcHTY1pT4Tpbp4yBSaI1vkZftR4xW7n29GQO7GjEcLSYNL0D0x5Fs3+nbQw63WFzfcUWou",
	"5Taxwyb1mg2I5TLd06eGFRHbwiyUdNkXMd6yLbzE8beDGtl6fZEDD5OhRkg1RRu1SIyyy7ZYsiQPcrpN",
	"hImwgH5he58uOVGBkICdGnsiznn+we1gTr5gb9Rxt2KOaRuemVNmNUbV7VMX5QPt08KPvsZOd1l7mTrt",
	"HLdm6LTL9TFz2pENRk530wUL5/0Shxvtic0C0pbB1b3C1fYKFlKzgMWU67bI1+Yqr1RdkhAMYZe7rFEi",
	"ttDRieQQWp3Yxr55ixFxxUGqNYuxFGymWVV15uyV5B/nga03T0jrVm2jpqeOw/pnzWH5+eW1n9vifWhR",
	"aO3QkYoe2Bwgh0hDkUIPfNW35P3W+KDyMYc2zo+Lvh79KiOxWOwa35+Hn7kxCq1WNv5+A5uFe2eB2IBn",
	"oRpQh7HmCb7FXd3i68MFWx+eBwmEGRLi/9gH1/qkCoXD3E3eqzc2/rnUBL+gwnEXzrCegS9YsdoIEKgY",
	"0UALWc4gs8UV10DCRGIgqx1rWGz1uZ4niw2rvFhUIe+gluKtlXaqO+ldusOsjaDFH+Y/SHufHsV6MG3f",
	"gGm7m3bat5N2Iqgnntk7rTVa7EE4D0n0ypHNyhwMT/8ZRDcrCCRoozlcSaZhZqSaI9IoC3nSpnXroShU",
	"Ja4xrXPa1ZPT1xFdfeZ09DxDmTutDFC/oWZBMGuHkKO8y0t4IK2HI63TydMnvWehGt6yDdMQHoI2p8+/",
	"U3MkLtngflJoQ95m9t/3TCitJaR1EilT2ECJBgHE2vXLckEVbbW9vflPhdJ2R/8Roml+3HtCUv0NtbgI",
	"0gtGnLXjnQD0ENA1lpylRbx9mBashvdbwFSotYa2zOg9Il7n6b4MdQpBaZm4ai4Yy9VeygX7XA2o45It",
	"VhFVLF3/3AVEd/q7JGbvXAJq2m3MPtDaiPs0VTVD3TRfNQ3xexAQP3EBMb3XdrEwe5z3gbJWvcQ1+m7q",
	"NN3QHQbPU8Y9l4qn33Z622xFr142/j090vlEt+eWztfs5Zv2IFTvoH7IvdlPxvE95r28EfXO80/VGVEO",
	"g8dQ2XsVA7+vqufEjAaV77xKVM4QBJ+3XIRnvNMSd0BDxkEp7BJbbySzmboYvY1DC42tH0jdcOEDtAfM",
	"241q8AhUmECkHv3VFrPzDtstr4HoK+FvSRGxdE5GiFDUMOchTP+37SuuyAo0eXr8Va308DKBaHI7TfFv",
	"7PGYM9hG3W3WkNdJFFkYhTj2frVXd1EcRBtUPfIe4y1v7YRGkVXCkW8UxVGDZ0Y9TyC6ww7w5roLHeBH",
	"BzchNihthPEvli6nm3MI9JfeO18Z/C80VI+AhiDLMcQle4aQGPG/I1eMK/Ly1fnJlNAtSLqCOWbjzDXb",
	"wHyjyIvzkyNyQoM1hEiAHh8TZTYSKrJllKzELDA/XjJN3p69/hlHHr3nda/5rbezG3xw3jJtL+5CxOTZ",
	"MWYaGDLkYHHkKZm3jDkXQpAN5Tvi3WAqC3mlxxXdAAkiZiTbN6eGbK5xPMLxDLTczV4sXaee0q27e0u4",
	"ZhHOVVjJIJrLuJKgQKNClx+uTDPxBDnSXoh49uzYn7EVSx3YH/0uGAKxXpL8OVYgtSLUXZO5pUQB8ign",
	"QaoEg8rJ91rHyITcyJRkBUJcMjgiL5DxYJyL+2m2wF5LOt7M7TfzQMml+wBn/9fMyHkzfKokxVdiwY0B",
	"qbh8SGgk+EqxEAizHqSEK7qEdCtnr84vsos8Iq+umdKGwLp95IwdrzY/n1nAEmBsh0vOMPxVkafH3xBm",
	"uapbgak04CfaGSmacrT0bi3brXuOPwjGT/Hjyc3Ir2aBOxJX7dItUX0lDLHthgmSWKxZVswFvWUy8D/2",
	"wjE5WMrMUHAXFOm0FrvmBqf+mwSUGzYnwTxhu8nHdyETnHnaIoHrACC0Wdc/nL/7iSj2J5CIbZjTQh4/",
	"u8MtumWJIaVkk5hNAynjuRMZPGlgxTDsNsfPnB46HPZIrf2hnthGYiVsm62GJswRUGmB105OLe3NaJPL",
	"cnchh1iyTM6QHpa+vloDJ5RYodJNxRSJDb/h2lA4x+30mmoSUCl3lbOm3yH8FJTJ9IbqYG2oq7UkOJJf",
	"T+TrCONbhJFHGrvSyMvUxMAwIyB3IiSfn722kjrZVEV5w2soJ5AyoSJwy8iHGFG43drL6Il/RlVrkEhT",
	"3uYxNYyy4jufk5mfd8gYM8kfD8H4EXmz7HPlBt0cVKZuvGPrKe1XhOkjclFAaF9e8MDLFKGREnleCuNF",
	"ZDTAVnHE9CwUG8o4WUhxpUCSEOJI7NDYZx6FBPID3dJzBEhOWV3I9YvTN2QtkH40Ye13oH+EmxSqLZb/",
	"CO1BUraQgrvA+63CjlHLbJ2C5tfQ9AzWQCMzY0PO3vf488kasDHbjV2hXaYjazMrsRswUMRufIc3+ayV",
	"mB16K+84mNvbCAnFLZnHn/B8YwVy9ZZtAU1lf8s/2uUWNO9+1E5p2Jj7QUQwHMsalyr9xaiByRYiEbvk",
	"sERGk+eTtdbx80ePIjPAPM7n/zj+xzHaj8u5WyJM0qiL/FP1/JGhjkeaqstZDHK2YTzRcATXdBNHgGZl",
	"t9e/UiOXwymzhvsL6lXev2m4Ybzwh2KhjMovvoGw+mOaQJj93UHt428f/3cAAAD//9X+aIHE9gEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
