// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3rdhs30ij6Klg882MupCw7duaLz/p+KL4knrFjHUmZzJnEmwG7QRKjJtADoCkzWX6A/R77yfaT7IUC",
	"0I3uRl9JSrK3/sQRuxsoFAqFutfvk4hvUs4IU3Ly/PdJigXeEEUE/HUWbyh7cXnx+opfE6Z/iYmMBE0V",
	"5WzyfPKC82tKZguesRjp95DSLyJB/pNRQWK05AKpNZUI65HQJlNYf3oymU6oHmBNcEzEZDpheEMmzyf/",
	"nOlRZma66cSNM3muREamExmtyQZrODb441vCVmo9ef7s8ZPpZEOZ+/vxdKJ2qR5NKkHZavLp03RyJiVd",
	"sQ1h6k2sv4fZU6zWxdw4f2VO49bJl1xssJo8n2QZvBmYLoupOosUF950/8mI2Hnz6cdmqnFD/52yjsGv",
	"9Rv+8H8QZDl5Pvl/HhW7/sg8lY8uiMwSb+R8sheZkFzoz8nHNOExcRgJTRyZl/tO6k/waTqRapfoUWJC",
	"0veLf5NITRwUr5iiateMTgLPR+LTDN6GUDv8IIxWhy6m2xKmrgCUhtn0C3MAtoHqv37auJj3UZQJQeLX",
	"gm+aJuD2nflSvxTEWIwVmSm6IZPOma545zyKj57lHK/IJf2tEVkpXpG51C/4M8RkibNETZ4/O50W01Gm",
	"vnoymWpM0k22mTx/cnoK3MP8VfAOyhRZEVFAYY7HBcGSsyZIBLwzF+alhp17etq40iueCT1UiUtV5lD5",
	"O/uzqe/whjTywxXekP2neBOTTcoVYdHu72SXT1Vl/N5rM/3efpO+T4nAiosLEvEtEbuCg5Xvr7dYKsTt",
	"y0jYt9ENVkRssLhGa5LEaLFDak1QlFDC1Al6n8REIC4Q+U+GE7TFSUYkEkRlgiGMloLINVpmSYIkw6lc",
	"c/X/ImxeQ1ivG/ElDIgzteaC6itxS/KXEdWDadZHYoQlwkiQLZWUMxRxtkxopPT1eXhW3IC0Rq58joWi",
	"EU0xU3U8Hx685umaIUzwjogW+eXCySk3a8JgTzTVEalQhIWgRCLMEPlIpaJshVIYDkki7W5o4aevKFMs",
	"sk6u59kiodGtIDE0UyP+HHo68XhpUNJHELRIvDtJ8JLojW3kehIe78/3gqy8PNUhOXkx3VsqPYmtJ814",
	"SHx8+uRpFYspVooIPdT/+Pls9i88++109s189uEvf+gA5s6v7gKUS4UVeU0TRRoRI/Urvc9SZWiY7ie8",
	"bb5Qb/B27wv1k/5YppxJAhraay4WNI4JOxd8kRCQ9yLOFGFK/y9O04RGcNIepeaNv/zbCjA9OYb56iVR",
	"mCbSQFA+/Ff2KtMScoT1rUVjIy2jBEfXEuEoIlKeoHf2zEsUYYZwIjlaYpoUzLdgHFPEBV1R+BcJsiSC",
	"CH0xUrbFCY1PNHd6Y/7/wnDsu11/xDcbzGKU4l3CcYy2lCdY6fsDSbLBGjP51SKyhMACfuDqtWaYdwu6",
	"BYvEqOBHSBDJMxERdIMlYlyhpQYUoD4XXN8PlLMLK5e8sGLJEddRmdHN1LAk8jE14pO3ojQfpJCnqERS",
	"YbsbF1iRt3RDFYnv01lKC7EHkY8RIbFel0dyAiuCEg24vkvNNQqs4YIosZudLS3Dq97YEWexRBlTNIHx",
	"/Ik2eKcFWrHzZzoJK3A5W25jxJ+sNEGk1YevOH+LxYrcC9pHCx7vLHalXTJb0lWmJZe/Xb7/AekryiG5",
	"dKvc1hmozzjiDIQJ/0dmFZHf7hflOzmbSrShUlK2mjr+D9cC+ZjqO9Suwa33kogtEXe3jjdMS0o4QRIA",
	"gRsuE8TcY4baFN0Qningq1ytibihkqCYR5nepXxFMktTLhSJ35GY4qtdek8Oi50a6UOONpk+PgT5QOjJ",
	"T0AcshPkpuS3fEWZ5QMAehxT/QlOzoVWwxXVUs0SJ5JMJ6n30++TFEt5w0VckVafPPu6W+QvxK2fi3E+",
	"5G/ywtCogbTKzIUVs2DyEiiG8OScsj581Vi+jQyU07QdQrPUZkZ6GpRo/cV4kASXIxRd4kg5uyZhetif",
	"jWXH2Ko0Tzcaj4y4IMWfxWOFWUzZSk6mkxVPYsLmK8GzVAunPJ0veaZViYXA0TXR70drvEk1Mj7UtmI6",
	"OVOKsBiziBiZ2QOKsq2+e0E6XlGpiIA/ojWJrkmslzid3FC1jgW+aRi8bKyubIzCi4Sga7KTRCGjAiEu",
	"Yj0NWuyQNVSyiMD5nCKsR0NgiEVvXk6RvmvpRuutehyDnoKjvnmp97JMJzDC3JhyadxDup8W5lKs+lpJ",
	"Nb4MEH0ncZamOajrdVS9T/F/MoJirPACS88yZdT7VBDN2yhbaenWoMMgS2tzCEeCS6m5hEGoAvmBKiD2",
	"khn0m4FH10fOtIrdMhpqiwwej7rlv3RCtNK7SYsj0kx0YM8PmZdiDHdwQTcWUbkweoIu8A2i7tJw+gOV",
	"iBF9fVAWJVlM4gB1OfdRYMtZliR6OqdfCoLj9yzZub9rq/DcRUO9RNMedN45fySIvvPbyL5zjMIBNAYC",
	"378z1K0z9f01dTdN59xUzu1Z0V83vL7gPCGY2fdllhIhtTLQ75M+jKUTTr5c0ojiZJ77OVoZT+d4wp6P",
	"uSX7lqUUp9bOvRe5lf00dfdM3wGku8SGf28xx7LNwuhnvhzw9dOKQtUwYC4XTCeC6ytzLEIKq+eYr8uG",
	"zDEj3FDGyIG4WeXWqN0TNbNrjrlpxfpbJrRp2anuue9L3toaUU8rF5fH6yqENK05EAu8tJ++acU/7TvD",
	"q7RW4jdVZtJ4T57jVUgU3rrAEarIRvbjnHBZfgJh4I35Ciy5dl4sBN7px4x8VPMoF+dwkrxfTp7/PCCe",
	"4EOddiqLq8rTZjnluUMoeYEVWXGx82WGG7KA3d2l4OteckGYpJE0W6ARrO/wG3AGKbLCjK8ETtc7/Wsa",
	"6Q2WFHZkwxc00S+vsYhvMEjlGyqjuvwxnXyc6elnWwwkLTUcDrafAB731wsHl/vhtQef++0ih9P9cg7w",
	"ur8uK3DnbwH87q/3dh3u73duPe6H74t15e/A+j75H8Ul9UBgFkOkAuhTk+kkFnipgiLZCy6Eka5ebWms",
	"Rfq6aPYml8ii/G1wAIv4BJ0liW8v1JJ/xhIeXSNiBzROWoUpM9oDeHfrMpq1nI3liktKkrj/6SrW/Vp/",
	"WD5iX8GFYv9ovlHy0+e8/2Pgdh718dezu5f7LdcGZdjDDMbsveSc/W5Dy01B0R+zeYW5+9IbyeKldc/2",
	"v4cNmc8pWHjGAP8jDPDGGKdKBGj0va4lgHkPzEjzmK6smagiT3s6o/7Td06ezr7Bs+WH379++ukPk6GS",
	"gnda61KCLxkUkTE+ped0mx/cCj2GVlcll9oWBG+fykH3LyEQGAKShOTJlsw3RGGt13fwzXOsonX9tu93",
	"Lr/DG1IKlvpUm703OV3q7965zyBQwUrcXRBYn+xA0bKdQAopLSCeNSI4tG/FGX+T23HLF9RLoI8ZZ8nO",
	"v4tc3AQy9GHMB95z34DAFSIfUy5D1oOYRINsRs68nkudw512uUw31F5l13QIhtC+v/VFBiCelnBXg67v",
	"vpd4e+2kYWu57Yui/P1e9gvfLKzxq5fHMznvIIrBVqV84P0NBWmCIwLcuAPIHtczmOK52BOqqppZ2oFp",
	"aQcbMNEES8OONKOhneaKkFV3SYCp/5qQlLLVnAgBwUBbIuiSknguswX424D88wtOZIledvu9UWbXAW3R",
	"SM9HOMmW/7bKfR3MXm+HW/lhroscourQ0xoq2rewJFUFsjA2aUIUOOpTLMgMs3gmiSq0lSV4HxOCJVjt",
	"GcpYTGWU6LthijKWSRIjY9bPo/LKW7eg4AS6BaFselAy6Z7M8fwcIV6MpmdADV6ArTa7uo0uHyNrnIbf",
	"NAsrISuk27Hevh8I69mbIXdqGu0nowJ4XdrO0RCEeBq8qcvYDe5snbamVcoOHkSw2F1heT3Odx151qLW",
	"IA8sr3PLUtUH/3u7r2w6ielySaMsUb3meVm8Dd4PzdbiUvBlkythmeBVzQv/bNoF3ppWNcpOflyyXpQ0",
	"xenk42zFZ/a3nz/82TOI2d9n8pqmM56aPZqlHJxsZq5P04kTlPqZFTXGjLj0YVpgaMI01SdwILC8nmci",
	"qXNn/SkiLAYATtBZFJFUSbRWKv2j/BP68eKtRFygNZfqecqFQgqLFVESmHZ6wx6xCOnRwX/aiTJ91c0h",
	"UGlwkJb+WCVk8NZWzrYZpEy80+IIlOi0BK+lrJYD6MVAjTqGJnDlIBy83xinoTFMNHA55vrJaef5SRPM",
	"mJ7ZuCukjapuDo9+/LUHydMQJODJV/1Dz87N+/pLyCOwvL/5cq6Ejpu48Q9/+eMs/98//XmcWmZBt9j0",
	"AQpjalrf/SChGbeISXhojgAySQydKnB5lFokkhkkBMZLktAtEbsLEhGaqoB+WMpV7aUhmmCGvq/HBoI9",
	"Dam9Ffw89HRwDEvP94E/jxFVjOOvkhrsIbMGfRm2YuYKTsPbnhKmxZPdpcIqkwG3BYvtOy5vTQv0a4IT",
	"tQY/hRJYc1ekt4YyIs01whnx40DjfJ66oG/G8rVF8wtwbrISOAY5aolpUnIXtnmkquv6Hkb8Ph83/Pxl",
	"MVv4hdcWBmsZh+WWXEYEx5DdwcEOCv8PYa8jwb5wk1zYwRpf+IGrzncuDSRVerP495cUJJWSsOdWTLDU",
	"c25ITLONdSD2XWw+4CszSPHDOzdc8dP3MLCGA7xwdf4Eamt/BwIMcwYfVbwGdRfBkgqp5iN4hnuhHRST",
	"H/bavDuAh3Ge9PeXeEJ+sdZnvouuLvFmjP4nI/axlWL3EGUkRKqOwaMkibmPrVBn93yPlfdbbKtbrg5l",
	"H08B0F3uKlCZYGPE5kyweUxwnFBGxlqfQtdOORoll33s8A0noWlnLYlOcy8GrLYK/TQ/uuF9DvIi7/A2",
	"cIIB5x/KInyatsY31uMHe2rYPvkdJCTuqCQzzAJt99OLS7K4L2lf5VikMhwdm+sKVrjbZoFBEqfRddAs",
	"7J0t7yMN09bI48ZqGQc/fi34b4S99DBUJqslPN9r6/q4Ss5xJomDwvlLTGoiTvbewMHmvg2mjLLV3PDZ",
	"Vr2zR8QgkdlmmMW8V1ykHnMwN+wdMbl3qGTl1Fh3jWdwrG/v1CO3yjaU0BhYvwd46HR9Z20BlQB8RpBV",
	"MRBlRZS9EU2QTLg6QRdEK5ASrYhCGDFyg/Rg6M1L0ANMcBIkoOjX5zQUQW61GMZHcLD+JupypG0/e1s9",
	"huBDD+NXv7DkwaRnEXg4qeNY8Qnm9k94RUtl3Lv12yJMA/hrItpqNZzctQg+L3B4CaEVH+E7EZdcLAmY",
	"+hifw6tOQbZpcuZe2HA2TxOsNDa8JzGVEWdMQzGdkI8kysCBQFIerecLQfC1HXjNbwrpKcIsIklCKm4G",
	"/+eYCLr17EvhgNhik2H/Eh7SewzK+8vDwAA+1ZWcMQJNb01FUhXgpGXr4Ved+kPEBZkvyJIL0k+nuoQM",
	"s4GCfJdcnK+mJOWUgJsW29JEzjUxxdoQ7R2+s8IU0GuKrYOpkGCmky0HaHyq6iAiY8NotjHGCx8ermnb",
	"uOr76fPl4V8u3usBqj++MgOaVAwqDzjhhR4vMCf8XkxrCGS+JWKkMV0SfENIvDwk7JduzAD8+TNvDbmt",
	"rjR/biwbBQKMGZofHuSmsQ9lX6yrKNXJNmqWxvI4UcKj6z3H4Jla8I97DlJEtu05kNBYpBuy9zCmctKe",
	"w3ghNvsNBHentSuPACoQ35hpmTZeTBxL8I9Y7bw2EF/TWltAD5FOeAOb6CNAwOGtC90Bb1gERWu+zVhs",
	"XKCtfsVK/A1mnNEIJ8jl/piiESbXcwFDQta8URsQVmjDpUJPT7/52iQYS5DZMUPfvzt7UZRBoGqHCNuS",
	"hKeB5AKcrDS615uSsX6Do5lc4yfPvp5tH+u1dudeOvDnXlGB8gq/xZJ8/XRGWMRjEqP8C7NOb2mMow0X",
	"BKk1ZmZ9OUq8fOpy3vtip3rpyjU45wCPfloySmhQxy18nli/5d7ZePWhVcV4Ui2Y0AviFWFakt7TZnVN",
	"dkM9t3nRrw/F/57MZx/+3CvGaoOj4wZxFWxgfjA7wXRijtFxId83ZaNqA6zEUYUQUyGjEANoJODWU9hy",
	"onJkTj22lVOioZAQX/4bp8y50ceEfGSSCBdvQT5iLa9Pnk8Uvs52uFyO4Fk5AuNJLXLhbPav1qJ3/jbk",
	"03atqT3AYJSGVHwamvwt1IdacCziV0wZmaFyrWyJgKp8kM8A8Tk9zI0B8yJm1yPsSv6OhdKEZfuY3TVT",
	"AC5vHjvqtGHhHUhsqRLD1CDPWG1nyr7BWoJsNUjGTheEl0fXFxAMMzJwKq/BMs+pq7ywTqNDsRIbltTg",
	"3w17/vIIoDGMPhj3tEzoaj00FaUpLinMZcOzTBuwGdq3d5hlODnHVLxhaTZ010b7ycd6hivoGeSdDC3/",
	"vU14d7bGYr+bcnldinytPI8LggETORfWkr5fUZXDFlHZM1W4JV23E25bDuo2LPQwVW4j7z+TtZb3mWJs",
	"zrKIKcNJ543VLTb2zXoa4QKLuIj3zW0Gy+hA0IZlSDe9PZTEzCEdTmSuoNkwMrM26v6EZhMTAsx/fGoa",
	"8L5eLKTMHC/Nl46ZDE3POLwXqiHhzZ2yaTnZurTwvrnXTdVYPB5T5m0VyqjSZSWdt3ZOuna8fEC7LzR/",
	"zyqlx9pLjrlC/X6K38h4+CUVm86Mp8MIXeRjmmCG82SWIWXbj1sKo+p7S132e896DfB62QoxvoBCLTM8",
	"4BwcXx/j6PUd2nWUdoG5oEcvxd4nG6+wgtmj4CGzp+O18TVr6eEVzJuT3oAjsleIRItMdqsxBlUrfx4g",
	"4PHSeqhAD9yOYzsjymIusCx7J0WWkLkpst5UarSLu7lEwIOpso+HqbK5u+Qg+UgrazLpJ+t0nJEehbPA",
	"fq+/pWw1Rsf0StDuLYwad9EwiuovtbVUJxpUh3hqiHas4f1k/jxseuwp0h9KhO+zY4dOF26TB5vJsPlC",
	"aTyA1QPlOE+xdxXG0UzIDRJkIxoDBW2rdN1ItW2s+gd+ueY3xxUQD8vKqupbb6XNGwNarQyl0uJrymJ+",
	"M/j7BlIYfb18Nfx2CfKmPvL1l8dDpnm/nZ76r97yQ3Cnos1PMWiZZ+3Dl2qU3U63TeeqhVqHcq427lPv",
	"aTYgruKnvA1fhFMFzTiWgm/AkFvunVdv4edyMJuqskvNEIOVIX+AKqmILxFOU8JiU4LLy570AxmQRsMi",
	"IcjFWnvTDvSXhZlotV+hIlKhPPY1R8MOJQRLkhu8oUGGBijU/cOERcJjsNHXRoGOd7J9DQ2OlaCloBIu",
	"Y8vCx5kAo317k57BUFTdoUFVM3jGKpTRh64v7X4PvFgrpW3HdWWEONQ51GLtL/lDQst38E0vKd/k0Hf6",
	"M8xbOY/vbVgw93fIxlFQRf/6BI7p95//J7wNhF83Mvi8WvTETZSvuLwf3RWEi31NE7wbqUkXaekD0/uH",
	"1w+4G1kwSrjMRggmJj19PsQCwxN7ufZXA+PdfIjcUPnmIHpnH9nOLxs3BCP+d8MwU/nuyGLlANPZgRVR",
	"n2bKIp6XhVOpHVEhzf2kwdD5mDbwhTAhhLe5YxPr1N9C2+3cD9pkff7srzAKDFM18zKRh+CWtcGGg1Mg",
	"5iAAHfYysPk9xxlsMK7IxzXOJEiW7cEbzUOsqVSHWlB1rMHApJwnB4GkNNCIAsNFbcDDVOqqjzcYqKHl",
	"hoYKE5qxcTliovzD/gWOvI8a8q56+LbGG5q+5Lu96eLd54oPs5kOnt12GhuPfAczaeNbXZdQ643X47B2",
	"8Ycuxt56iwROUeCMNBzSBiZRFglCItA5ppoOX9hOs3hIHEfZoGLCRNGGx8Q13JfIJaeiDTydp2a6PNOI",
	"fEwTGlGFnAkALXYEqgoQ23eYCumGQwJ+nvMtEYLGJK8sHGh5smdNoIEG73w3N7ZfTJ+JoLfM4SNcLKYX",
	"OxLwiFY7AxrGA4GpmCEex8hYFmB/oKuqZRpgp4uJIkLPLhWN0BJTMVvsCDIVeiDAVfANcg0X85adJeNZ",
	"X3dqhWB6b2M1Wrnky/gvf2ufhGJuYLZ8G/M0qUzxDVY0mjjAgs7+Cn12l3WB2Qyxv7cfucMHVq+MxQ29",
	"2cpp8k8HGSM7AmBK01ZwUiX16aSjKlPrGg/qBxwpC9S6r9TuyPCy8pMVLr9g2st29kCoNKI9UA/KvgLY",
	"gPSejtZ+AQGLxAMKw4bLUw32tWVpvCfyQlGkfmu+WmpbjkO75qm//ZU2ex54HUR1lktTQ60RUB8iFwL6",
	"1ODOvQfD67P2NsXlBWTbM8PL9WYhUjAvm25FLjKPeMZUO209GZSLVS+mWsViGyDF8nrvqZ+uNcrS1H2z",
	"hChpZIrq/gdzVHqot9oOxHrF4Uaa8MZWBxxTH6doCKDHO4yp41Ch0Wa4UdUEh8kYTUioQhGqHthBDW/5",
	"YrEbecIOg0h7XyQ8um4SVgY6KKvLa3ZY9opXKnyVRdHRA8fG2fCOJgnTR1Agy6B5Yy9zxA3JQRxVcpen",
	"5o15TKW+5ueBkvlfP93fuDQiwqy/Ua8ade0bkOwe5YVcwwsuZuvYn3MulUuW2o8LF1U6rxm/SUi8cjFC",
	"RTPDObi2vUtiOkmIBjTRZBJUzw7KL4fxO7u2ARgcJyFAWw8tYR4bl4fhlHuUYCtVX2vAeRkZHciHUunj",
	"KPfAF7Gp9Ra4Nwbq8TBM56oHhcYF+m6XgtgGRpv5BqotJTf7pdMf/FA3ZNQ3Aj2tYqQn8kfGb5X1gb6R",
	"V0HNoE8QVuyK7PebydTk7zWyYTMDZaCio8l0SCRbM+0fmKsNzfnth6px8cf9YTGhaINb1vdT6cw+e8Fq",
	"AJujrJLK1x265m3kZV7c7V7wb6g1p/R4gSZlJkGxzSQ5ndwIqkhhpBrI9yvTD8DdHepM/WsR+gBHXMQ9",
	"ubY3QSdGbM3gzyGfudnqvVfVmGIRYWRV69FX+93YCCwb4J8f8ZAkaWKBrWpVbQ996PrtLkGxTzFkU0X9",
	"yHVCDlko7jDCtN0wjxhKZeQ9nDSSxncuGrzSTNyG2kOIcpGkgC4ypvcT6f8I4xpOBY+IlLOERzixHxT5",
	"AVgQRD5GSRaHmopb460JhB6ZzAmmXSKGWGgySTRDgsrgL8znIQONQ6acyyxNBZG2CWvD/nqc43jyl+0r",
	"kIPWe9WV/hiB5a5MZeEhWGwqRg4x7YesrGhKaB+08wQ0BLS6UL8Vuw+CBRZcofm+o+UE+EaT39Y2Ba0O",
	"O9CRN9BSmUnSkk8B8QM4sTp5/waW3bs5XjLuloc7pF3fQWhF2lzENQegkHFzCvH312M4gdM4rbE0n3Yb",
	"WErtvLQgv5GR1xha7Yru0eT1tN9ZHJy838bgj3nPDjs/rsn2XvipSrgFHfikV8s8dx1tbaeA7v0urOsV",
	"mdaE9MwH1Hfr2aTn6PWxDi5g9U0mC4pYZcGqitY+8hXEG5xlMfV6nTnR28QXmB6fRPVtMFkb8kc3TO3J",
	"SztuGZBXW8LU2J5r9QXlNQz/rWiw/qp5aqt1hd9YQsvdPp4Vb/7cvWJSU8d/3yOG5zZidoJhDiXc+Zj2",
	"XK1+UEsJF2XMlhbaQax5a5PjlPk1BN/kbFVYSReVFxMWfuvoJX/71voNAFwssBnN7zDDK8iU+gclN8dD",
	"9RjittAPEbXHHpDhm32w8tuHIRNYlkcrpQiyoYTTTC7NJaOPyL16o70HJwujKLhgVwL5xZqYhjJVi12P",
	"WN18DBe1bWPPS5pRPRukov9Uyg8GZFpnD+jw/UUm+ta+Xy1QlwPXjo5KlHOh1pzkVaNPpBJZpDJBTqyo",
	"6UL6S8GQwQ9KgZAd7/qyK5h2pGlz1fWZa8Df8Z4XpdwDFBty3vnmYtdnPBcO3viqwvJankAWTOTnYbS/",
	"T5kWu3ila03tNTB6g+jX8lJMpea9cftbGSuasLfNaMpgd6w2WyQ0SnZz8hGyWdrfvhGcrea2c3DwPWFs",
	"iCe9EOheLpVvmUvFNVPt+qihk1DgzebeQoGXg52FQgvEKY6q7Y1C79V6DwVeylvwtxyMfN3RmsRZqG29",
	"z1MuSMqFaquOno/syqNr7RRhaTNPZhrulsyevHGHnzZY52CzfJqZAJB69yHSd4QcYr/z75Zq7lDDdMV9",
	"sMVJdqR4/87PmP4gob9BF4A0q1RiDZaNaFtLcXd127JTwflyvsZyfdzGNk7ZHrGhl1BmOa/3P3RnD9xS",
	"J5h8UD8LFYoK7bGPlNJG5LSfb2Wr9HAPXO1DfJqta6nsdU1CNCW3g6dCozv0pGr+MSO49xugyX0HNZcy",
	"s2mre3CJonHtgZ0eve21w028FiWmu+4hbLd3ZQY+Qkywo5fRMdzHypdqc4+UwjZrTVnyqPHStpdtpj4J",
	"14m6O8mqhDVPdsiHqYzaIO/wRUI2L4nCNJGBzNrXL9Bf/+v0rwj6v+btE42ss9ihi1eXV2iLExpjU0GP",
	"xbZ8oP4LPgr0hYlhunIXMacGm2zdBUFPTk6enaJojQWOrEepfmKZVC4/sRjqEU7po+3jR8b8Jx/9m1MW",
	"9qWYqGFDZMX3p4+//+eLJ3//5vXTf3339f//j8dnZ9/+9erb/++vZ+dNNG4b1roRnp6eTluyup598413",
	"SOHlgBuQqqSyrn8UeH4NZY+CdRtcZ8T8M7zgmXq+SEynruIsCdqdDmG61BlY8qWGydFdVX06C+XFEzdE",
	"4RgrbDK3kW0djq68+pC2wEFAgnalD0aKjfn3fRqEnNmX8wZDR0tv7fbN413CcTyP6crKLcdsBXm07jt2",
	"vB69AA7gMz+EkFoil2mJ/MrrqW1RD8te9fRYxjwgILrMyT9Nm3yfewTpuSHGJmd5VUcOLCkHnJEtEvOH",
	"as2PS9vwLFV0A0UhZhFnZqBoh8x1JZFaY4UizBCO9Hox2yGMnp5+g4S1QZ/AXoJF6FuBo2ui3rnmJ4M7",
	"zQ1N1so79w+vPgQFintmbsGrRVe7wSllCq9K0ookG7q0TYzMvx8OkltW78UNFrEcS9MQmsPLcghqa+VR",
	"2vSRAcgbTStDQpTqhFYteF4zbXw+adMOG83Y9vKYbytP2niZhxL9mOxqHgH7Gea9OkTCc5GuXF1pKIe5",
	"DGjzXr2lWwL4HJ0QqIZZv2oUUu6uVD8a43JrwZQ/qjJT0Yv2WMfUlDMqanSNLiLVxlGOYA+AXTtaQndn",
	"umWeRpxr8cZd40gwjNhm0r/jzMTbyibskzFYwsfIZMGFue8GXY5+il1Ct2Q+MAS9iYf1CkofktMXIhgn",
	"oEEv634jXObv+yvvXwPejFII8MUobbXcPSin+TaVEN4jGa4Cf95VfQiFZNF6zZPfBgewgL1s0M1Olkti",
	"QprHxyGlnNrmgQOBHdUSPty+vXLPW5CmBSpDS+2zfyOv+6Hd3sNkU+su9xmLw20N6RuP61C9k1G53jO6",
	"zQay9LYNnJv3D7YZ1kYv6W9kQNm2p0H5SWGxb7DfPSljk4cXOZnGR1NppdMSGYR3JUSDFwTHlBEpG4Ko",
	"B9b07qP+9DCUDnbUOet5e3KSv1SnGt5Se6xS0eJwb6yaO8pa8bs0tcC6qumwWvVLCBYN3iQoPfKTyZgN",
	"OX9ltjmwy7Yzs/ZQTl+eErYnOe7dz7wPL/G2YP8qSxUiq7Qws6ykwEwpw9bf7iZqKwHq0Zoe0hvChIUC",
	"UNOJzFIiJIkbSbCaOdiYvpunrSFq3z1BLzhTlGUkzn+TKLV1EpFaEyqQXh9eEYQjwaVEuNRxC2cyVMXZ",
	"1Fs8JOFHBlBTuLuttO6g7LXILX++FHxzKF/P/od0SJ+dnq/1wVkv39MBOMOxkwYfwk/65Brn/FJmEsJJ",
	"4/liNyj9vnOjjxOn0pBGWS2G0CAd1IJU8orZIR4T4hFNGOu+I3K+WAqN6Yh8qWxY/d7IGXvl6ogwi0iS",
	"NN4c0KLJNN+7F/V3vK3qrwob+L0yMIHy8eVO6087GvZ1lFgpQRneL5kl6ixSXFRrrMC9KgyBQAer8M7k",
	"XRPLF/nrLElKLTnhvRP0Km/oGWGGQLlB0Hb0Zk0Tgky5zqlp3YCs7uP6BUSYMQ7xRxkzLwau8wPEfuRN",
	"R+cWgPryrkRGHNyEWbARlQgnkiM97knzTKVKPZWp7iJosigi2w2wefew9SzGHCW/OH6nLemAV+K9jX9s",
	"OPT57obIeljp+AbuNdBZuE/fgmHNBPZvD1B1rrTW4Q+hrKvWQb8G4cMVEBcL1KfV+eDRTXDGCLl4nBu3",
	"726PD5QZsRSZ8AHMCup1JVx1e2xH1GkeUZOGMtZ4jDrMpn14UZBAmrAdcOq6kJ4CTofwNtKetp2q5sP5",
	"OidKJ/gs+OPJdLLgXwUFnrx2cpaoi7wwXi40AVhe+qoTnuYRF4K4GA0r/hdCbwmJ7bKwT8M1xlJHfXO6",
	"eM9GFsGN23vUCh01wN08d/OG1jSPNMGMAY7zq9C5PJ3h1NQ+cr1gd/MctOlEkWjNaARtojJprGdmd7vV",
	"lloZyX1N7/p1U3ZzH/lWa4mmBPvxg5Qt2ffM2BvBiCPe7RUo9uESXgea7hO2EY7dGdi4sn+/ympgJAA7",
	"LfsVAmzVrqRCHgXuyyAXANUoIXioKrir1/wY3GF4iMXw/jTR3MNWX5jp20KeimabhUWojNzg/txQKb+1",
	"sQCXRb6LY36Cm1uwI4rXDLML7O/Qhs9HzNSD0Ic5vsEi7hTtu4va7ufxMR3sRntu8s9DVr/yOqvOna52",
	"m7CVtife/ts5Wtrv67yzlSvmJqp1ZC3VfJSiVnGPqm2mAaix7ixxlqhcaQ20/uu/3+MViw5KGShYDyGU",
	"V16pmWoDTy26kBjFJDKJYW5ckxjm2laiUt/VxY7IE3S1JigVdIsVKT7XqjOiEjGukK3MMbAEw3qDo5lc",
	"4yfPvp5p2ETfwgsahvizKIQwqA4Av2nW57rNb5nQe1C6NCzz+NDLcw4S823IkralzKHwFnTXWGSE6x6E",
	"Cx3kfW58RHibUiK75nMITP8tXpBk9P19oVlFneUvdkOKXzpBoFcAba4LHdaBfnv9Se/c9m0a3/qVvjp3",
	"p8qyi3H6m6RKQkJz/+LHRzWmW49o+eIqr6FzA/t6zsJNtQ/W/hisV6YV9bA9uLSfDfICjgqA7CTG+1vb",
	"odQsut7kr0pA3nnw98UzAA3xe5S3KVCC1rYAG1b0soG1egS1R6y8+3ReFEDo5vllHfJAEfRrguO54nP4",
	"F6dpQpsqqJbeHB14P1qtHDOX0dMSd2d381vvju9MC+7fw1pChvT88P6uumKaZ+jmaQglJJSyEqpEGN7i",
	"BhIJUV95paGjeoXl9Qsvo9NJUTdkAYd+lypuPA6ESRrZQlVEgMSX3oBpXpEVZhwK2+tbI00jLcxJCnk0",
	"G76gUG5jjUV8g8FNsaEy6lkG24fvJ4DJ/+WFg8//8bUHq//7RQ63/+s5rMH/5bKyntLbsDb/l/d2nf5v",
	"79ya/R+/L9ZfehdwYXeisXLNWbyhDG0puUF8iTBSWF4bZfHXZYJXv6IlJQnoiBBioVeKBFGZYCRGiiOs",
	"v5dTxOCJ4shWkwmEg/RM7y0RzugCxN4af29tvwXpTMsljbJE9YLtZfG2ZszMVNIM8tFAP7Anz54FIFjT",
	"asBFp8mk5Lws5JOvarLWx9mKz+xvP3/482CxvE/ZF40XV/LFlD6bL2lC5plIynNAMZ3OtYFV3H5bCfbB",
	"8hoRFgPHOkFncOFLtFYq/aP8E/rx4q1EXKA1l+p5yoVCCosVURLsI+kNe8QiZGqM9oJDc7u85UUZknMi",
	"ZnokaGOE4CVEGTIGIBh+YHmJvJJRB7UExTRbecgHsZR+7pF4aVmWRu0uF+TsSLKzJEvlRHiMnmCpJ9uQ",
	"mGYby6YH8OZi0FdmoPKP79yw5Z+/h0ksXNUwOmMzmEwnK56Uq2V3AaNH+sF97X74zo5iZ/MTdSukAoln",
	"iOZ1nYBuioZY59Ysp7cCbbAiguIETHcZi6k04Z/IhtfLjnZYY6ooVNjlHgyyzBzrbK2zYvZgbjPQA3go",
	"7jTE4WjnGchuxrKPesnKwmq7Tw5sk+OysMlZHrIHMzIE08RnTNnOH9OE47i5nn33Dvcp3Vl8H4SmlCNe",
	"S+BS+xaQOoDRbUya6qEseYG88MdPTqddcphtcgXx8gP7BNVyQ/v0CrLRKPMDJsPukdcLl4TlK82G+8e1",
	"HhWns28+/OWPs/x///TnP9yrjljjsHt6oFTjw6QLBlKPj2NvK/X3ctnIrtxATiFh0p3WWY+XyVyz1Llv",
	"BpjfCjSc2Sp8Y9I/cK2RFU8JmwuyolLllfxhr+fyhkqZ/2XlNvenVjX5cildbk/eUCuPBgv6Z76Ijr1F",
	"janW1r3Fjr2lcmzFg1x662VK9+7Gkpr6xCvgmot7laov/oVx+uTp4BBYmKm7fEqN/wZ7CsyNJ7uPilAZ",
	"7x+PjVbglZp4KFfZPwL1UOUq86rMDQUrTbHmG6rWSK0JslOUUqXsbCdlqqnFtRZBrCUeZjlt7upw3Czn",
	"Yx4HGx3c2kGRAOtLC1/l54syuNWnAP1bB3zl6aVdS+Xn79zSKr+fFyutPLlyCz+36648f+GhofqowMqn",
	"6eRHyETbJzHxvtwMrXLy2M7u+YQhjmh6QLpWYaNu9QP1m7vHrdr6dvRrRrDWYkeS5ljreUKwmHs6bd08",
	"dUk0z4NMSf2vad7nc8RkhzJQukmMzEhIj3SCjCouUSbN+/Zhbp+dBPua32/bfAc8+1rq+xrnh9rB7oXJ",
	"vLyeH+y7l7WHM3lN0xlPDe3PADIi3JgfZxyndBbxmKwIm5GPSuCZwiaa49/AMvPlTvlGb0SqTBDZYSxo",
	"g0jiU+Cw/2Q7jVfE6H768oZsFkT0l7f1ZO/gm3LQ3ZNQy6aDd8CHtJ35TV7MqJ9Y61dA6hXcdkjrxf71",
	"he7GCKE3+lCVz1oTl2tpzM6I4Eizsu2VymgFlX1oOBsvOFOCJwc2H9QhChoGioTABxtBviOWgdR41ogY",
	"HuHqo80PemhxvOsXGlpKU6pKOvoRojFhiqqdueGwxiaypH2C9K1lYh30Uy3VgKaDFjuCPGyUHLyj8nVr",
	"IT0uAzKAwKZta0mw9M/DPK/4UsmxNEe1omuWvuxZUcwkWmSCqt2lZleGeiC45IIsBZHrSwKZa2eZWtc3",
	"5nulUr2rJpwECfMJkuYbFHF+TQmiUmamn9L5+8sr5PoXwTePEr6iTAsygWd2vBNkYQHfasJXPNMqPjAh",
	"aRoqQc0QSVhs5F+Yd7bgGYvRi8uL10jxa8IQZeifM/337Er/ffKLRi7VCzFfOJvt84lKN3OAYW5hKE4M",
	"TunfCVzLgKYh+MFRRKQ8PHp+ZBIvSb4JzYhpwUUIx04/8D4zONVqx5qgGpbyJTGjV+ANQWuCYyJ64drg",
	"J4Rqo+H2wzVP8X8ygn788c3Lnqj2O2kV2MzUWvMbrcHFNjzKNARrwrCPTwQNHihbASL00TQRBOlmbmtg",
	"RFIsLVwmcMvfHIkkXTESm0QgH+f5Mi1E5RWakQDv+Ug2Qai643lbF7tDRnGQaULVLOYbTBlaCH4jiUA4",
	"TWXHBtpFWWjqW/gJ2pkteSA5SqNUZmKJbTqUXiUoP+dEoHeUZYogScSWRnp5vpHPtOJFP5HFJY+uifqF",
	"OX2p0G2N92Xq3wFTr4+bns8vcKjWkHz1C8OCQJFEZsQbTVeZkjTWo1KJ3qeEnZ2/QTIl0ckv7BcgSksu",
	"lLPnvzCEZsiQbQFMvnm/1nH26xAiNcMDA2oa3T9Sv8KKf62dVzenLCbVI6NmTqTHGcmK4Iz86pPgrydm",
	"Nst6HlVZe863HHsp86/aWFCOPSLWU2Kp892bq8l0Air2RCvP8vmjR/peNUaPEy5Wj+xHj7T+WSiUoKzO",
	"UiJmG0OE3+LoWkN0dv7Gi594Pnl8cnpy6mol4pROnk++Ojk9+QouarWGKzWAS5DTuFRBy44sdrO6mbAH",
	"TaxXtm6BppQSD8iN6HboAsHBC6FjQ+qXa94s8U08eT6BZQPRTvL2hN9yIyBaHyhoCmma2HP06N9WwDbK",
	"VGfBIz32Wz2L01E+lcU3l7NiWR9szZPT08MCYK8pr61A1Xw2ARjR+7+f2OBtazj45wwGmFnUe+isE0nT",
	"pRygmzKJnEB9GLeaukD4z0NNa2mqz6x63qet+5Aaj9pfhu1H1Q9X34k3DPp7uoOCFjzegdvo6enjOwQn",
	"xVLecBFbUL66A1DsEUJcUCuDCrIkggiXeYyThN8QC+LjuwRRbxoiHyNCYgnU+LfL9z8gSX+zEb4WxGd3",
	"CKKdFmnKz5vAVhmNgfPJN3cA5xXnaIPZDtl7XoF5VqKl4JtCmI8Sqhfx5rzCuC6IErvZ2TJYyPLSxFaj",
	"jCmawFhmDoEVQUZfhShZJbuZRF5lILzenLE/+pE5K8slVOF0Lnxf5Z08//mDVpA3Gyx2k+eTVx+jNWYr",
	"6xRZY6EFcLhG3XE0+frM/upJu2Dm/nkCv08+6ElqNz43lf7CV/4F2fJrYojXifQ56jtZOpIcUWje+Atj",
	"HCWcrYjQBGZfI7FRDCoKqCu2KWDy2BTipEr+wnJR1JQHZ+oEvTUiQMyJOf32UkX4F1b4mwzzKk8z1dBh",
	"hqxJItcqcs0FqpjSJPmFGUA0CDVbgpZCwCkGilku7fzibnpfyNxLQuGZciJKigXeEOjO3GQZL14xd78e",
	"3tycnz7U5IynobNhlme3wLL7u7gI31Eptb7KBaL2EgLcWf397q7EiwolbAygUwfm1FHW1NxRPiLv4lLy",
	"KC4/LGANKNFlfjisxiuG3LaH5oItJr+fP3wq8UjDqIzOMJQJWhVWg70y0VuV00elsipz/fSB6eE/GYFQ",
	"dKvbUQbpFHPj+45Lt0dXPZrA+RymB/QrsgvLeYcZXpENYeoflNzU8yfqRHQGpl6XlQdUgpPE/W05dXn1",
	"mlBM2eQ7F6arkMG2oXxD75CZBLhciYyPebxaz9VbKlWxvVotz7N3UQIsGFp/Iakw5He5w2Y+aTltj6B1",
	"oX/oas6VLRGzSy3XQWsciaQSBG9yY5wVgYy9McZyDZBYU6N5lWxAbPgVfBC/IrrZkJhiRZIdwlooRDJb",
	"5JMaY5QFb25ErvhXoGmTjbomvzA7nWYJ09zWCVnQ5jAATD5iXP0qicyIJ7+w7wkWakGwMslXEhruS3R5",
	"+QpFfLOBtZqi6cZrAFX1rWBE44SEJASzYHOsDbomnXxEkY/KbMPMfF6m6JqcW+vfffnKIvrEbZFej/Fj",
	"6fOFJarN8XDI6ofs0lBriaA1hTkwAS2IuG3tf8Z+p/Enc7TAR10/ZHypZuahkfHNh1Mj0krbe8dJOCA8",
	"GCv1GiharcnGqAP+tCXy18sw4rDKBJPQuN3Stm8yj7iIpRG3rYDBIuJBFCJ5A7ch+duRil+ae+Me3GQW",
	"0zTWxHw/5OFep+s+ir4hJ+g4+fepIZpbXp05AQDMkmfMgfLN3YFCZXGIwWNUP+t3x2sLloewPUchnhoW",
	"9FOs1p6cH0+qVnxf1O+Kofowndg2C2Us/iSo5sfGNpHQiKoWuQLEoRvKjP/FRhAjiCCGWgInv7BLouCN",
	"/z713ylHGf/3KVIcCbLhW5/vFsYe47D0QQjx5MwL/D4MTz68NyYUnH7L/piw+lU/TwZUx+7v8N75hyeG",
	"CMEf7pmHe+Yu75kfbeqEMRWDdocUvibswelzWKfPXdzQFwS21l3OJirG3Xa2G+helgetFT3CWWzC+jtM",
	"fmf6vVyj7mH8c8UnAia/Z6fTtr4ap6cdFTRu0TRYLLuPWfAHckOkmkEVawSYtdpqbqy58xssqDl9ZgbA",
	"e8T379gWWSKyuxLfawzGBeU2u1O5wmq8O1VzQuc6lWjB1RpVQnnzaKsrT6Y4hAfSfuVv0hFsLrcf8ZQ7",
	"OmFn4iMEPuW+7rsKgWoF4LMIhnrwAX8+PuA7DhNyazhuoJCb5T6ECg1xkgOTG+ckh5zdVnn5Ct64DRHV",
	"L0Hbx2mdJC7l+MH3FBSqsMMQ+iPOK/hOnb9cQinJP3lUot81QpYVc8rUYIpA6V26rzbAFzmEgyyAjw8G",
	"QImEA4zalNF6sPg9WPweTFqfv0nLHGdbD73OR8OXbaf33vep06XvZHPFVaEUR9FpUFZ861CdvcGvfjju",
	"/fl41aGQ8oNP/cHXYarc3AdPBwByn/3pL50rPczapmF9YUWUZTBHswB1SFhXwPvuC8t5sDz3PIV345DC",
	"sSVwffhswfKqJnR70SKhkIv7rGzVi9XdcrhFBytwURbqblnCg8b1IHeE5I4H1e9zVv0Mc3HXxx+h3gdO",
	"kOHaJn4FiA5tKUbnZ1cvvkeSbDBTNJJ/GqQqPjKlIxpttDG/YQnHcdH7oip+fXX6JKRlxlSQSEnoz4UU",
	"2aRcYLFDlwTfEBK/voRkTFMX5seLtxXL+ltudsFU2+q+/IItNT49yGn3Xk7jwq/mei/ENkO4Vbo1UM4A",
	"yn+9OUfuXGjivTPJLmhHN2VyS+f1iALeJksU1fzpkQZ4FmOFy0RSruXnqv/mq1tQhiEQqr1QHXxXr0B3",
	"+xJhsP9PKERAcUHiE+TMbZCUhRmHKuMlagLud2es6gctwWiKnjo/tOm2CPIPV2si0PZBxHwQMe+LiPla",
	"HxlftHx8eorefevJlXcjr8FdgGvXxB//9//8XxbEP0EkltR8AZk+jbks1Ediy413s2oQamWnIPvTVNJE",
	"EJD5mibK0BLeYgrVQU1xUQWlLHCm1lzQ36CXam4hdBXl6pZ+8NoXTXgAmMFXjP6qGORNDF1F+nz0Cqqm",
	"2orjQz4ZMseWMHWlb5q+X5xFiotBQMEXA2C6IDJL1IUp0tv3o/cRVDOJXwu+GfzRFe/9yQvT5qbv6+d4",
	"RS7pb+TIwXxuqrAaGOMIso0hJDTFK2IS1TEyTaXRNdlJopDp4ONfeV1MpThPOUPJ76T2b19zsaBxTFjp",
	"w6fdH/7A1WvNl73v7iRLjmCRR4VZ/HosxaI6LxPtc72iX9OH6eTjTONwJiMOwl7x8PkGkp8mbeyxI9zI",
	"e28o06o0fjFstQ/Rlxtg9T8sXkunWzkxDY26AsfnfbDe6Irc3Tm5sygoj/KKIhOlcrvuKt2D3qcNoeH5",
	"PuTlxCO+IV78YhmSXEqehmOvCqiGno03sdaUFWHRzlQ5vmcxW14XtLuJ3PIa0oUCUfNTFNVjuNrp2dqa",
	"7LpKR+lOrqtvuj+s96R7wdkyoVEJ/Mc9QLCrNhLeFedvsViR0iDP+uBAZmnKhSLxOxJTrCW/O+YsReiP",
	"fySPcVs++r3UgePTI9OwwTVeGHU9arH2QxPLMv3SpgjK/k+R6Ylh6oMoIjaU4QRZGPKyfHlGu20iASew",
	"zsX08dxV+4N+OaysqfPpbVvBWllZ7hbN3/p8Wdk4ybsXCzzPpeAHFhhmgWf6MJc4IErokkS7KCFFvXt8",
	"TE2ixhspi0DQmpGPGlmNmoZ57DFE+90xI5fcHN9mLE5I2Ctl3kALeMXouyvCLORQ+GOKLr8/mz159jWK",
	"1iS6ltnGsObv3529KIRJLWgStiUJT8mDatyHml8BRSDs+QBCKjItb9F+GsM+t/egY5FiKihbHU9mGKjm",
	"+DHNEZBoTd/RcsQqE8RXse0ivhh5wa7ohV0rvkOZAdpXXehzGHSduN2IbZ8r4cXPPsgND3LDINXJERPC",
	"PjXBLUaVRK6JLUp5QqPdbYkOpg13o8SwIp64YNpHH1NYsDO0myIMyA/3e+9oX30T5ZKpwd5hzN3Tva/V",
	"7DZuVUHSBEckQMhfyI16YRZYbu9+y1dp89F1qnfp3D5cnw/X5zBGBiReShYynIwwBZ1LF2TJBUEJj65v",
	"9/J8BFN+NjqGhvbLZYVveXR9T/mgBu2BDT6wwb1cuzy6RhilgiwTulqrGU5Twbflgy/cmb5NJpiD9Plw",
	"QpGxKiM8z1fx5Zhb3JLuqjxwMT8Yp0MW4M0mM9FNORUhAW8/sMkHNjnGrL3FSYYVcTIi1BrMGHQyLkjM",
	"uBJumU9m7Kji4tWaShRxIWxbG+OIch5r2eCyRq28VaOhzj3NQr5cSfJHWN991akBuAdp8oFN7pUeAFSE",
	"sGOTVoX2JCfykUQZcBCpsFC3xiwl0Tr9o9/NvyYAqKj88+j34g945qybM0GkRsreLr9uLnQJkPWMlM+h",
	"7eDdxKQoC5JCQy3TMWuzgQQNjVmTqmESE4UlatnMvSGbooWFGyy6ry8M7r4cDl5Z2CAm/rRF/7BEZmtR",
	"kQeP4AP3HRVJBOSDMMudMzNJEhi7IDFo7Ec+rnEmbzOiKMB/V3ijf9H/wN9OyDxAUOZhue13eEM6+WwB",
	"fSEb9xOJu5iqHblYoYbHpEl9eaz1RY7GOxKRCwBebfVGRaTdwODtO7EfPLDvB/Y9KqADKAn493JJI4oT",
	"pI86hI4nCkS1mKSEQeBc4W+X94iHg2d89zny75qcvMQ0IbHZgUJWTgXfQndPW+LceBFNTKNh69BgYiyv",
	"N/grs/ovUX7Wq9xXfDajlLaAp+RBfH7gv/tFBODS0bfJ0lZ+jmuFPG+Z4eaS/ZKLJaHqVlnt3oYGolRi",
	"TmouK+3BKiMu4mIxrw1CvjxuaRd2MGuDpRxbG/eBXT6wy5HsUpMPwk7L9RLAHYndGp+0Bd3boo4d+V+6",
	"d4fyiUJ4ifiWiJ0rb3DMQgXVOXPg20oVCPtyXufe9DU2Z0+z18+00sfhzu1dHZctMWUTllmSFIfFLy1x",
	"D4KoB528G7zVAor+55BJ1d138E94267T6Reg+KngSYe3Oj8f9VIWuVASTK3SYxeA6xm/HOlDr+aFWeId",
	"WeIAny3h3/r5g+zyILuMYMbvU8KmxgNdK9DgaspB1cIIijggjOzhvhVxpspUGZ/JNb+5D1y1p6LnXMkH",
	"UfMkT7Zers0P/HLNb748Nc+sa18t7wdDK8ii7UG5e2CQ46RVIJ+SdicIjncz28/T8qTDsESvYX1juc+z",
	"1UqQFVz8wC0006GqEpdtPCXSNMUXMRGmIdANZRK9fHX5Yorwlgi8InNY3lzRDZlvJDrTj7T8hzJJYDD9",
	"U6jT84qotx60RxR/vGnaKtRd8RQ9O7WNv2Wl/ZFe+H3oO+ttsCsCfKTes6WZ7kH/2dKpuuLp7NmpD6N3",
	"fvxfS3Vx7dY++jenrLl5uqmkJRF2PeCNJSDBdKN/zOka7lsTBUKVRKm+qnmW12q2LZmlPQ5UykwPyoru",
	"2HZ4977tjY3OgD+AS9w+mtk+2+lmbr6ZR1Is/W7tfsdu5FBr+8ohLIiZPkY44WwlaQz1hJdcoIxJvCQO",
	"lItXl1c5WZ2gMwZBytuiiTyViBGtfFtfETCFa8ZvEhKvCOJLg4pskdAox1To9OstMA3/J8cRBv6WT3BH",
	"SpcPQDPTOa/QgKnlZwt6m3bqtV7xY5qz2/3voL172pe9oWPRXfar6Vl4/S7uih8dg8IJCBpojYHvlI/y",
	"Q8+fw/b8uWO5QPPTIzejhynunSTg6l4yr1R9mbl5koF5EBYKEr7ipuZFg1iQECwMnbZzUVM3htkeGMRq",
	"9pkQkO8IC5vBFVz5+kaLCdj0znBDUZArJGHqBF04cU+tsUIRFmJXyCgVEIBUJalKBtBdgrKVLbhtpYyw",
	"XBG6tQ2O8nt7mN3AfDa0a2/1gtS7kLPXO+7aQWXeU0TLUljLfFQqjeC9GnYc98BoDJZoMkhCPU/NhjTq",
	"mX4fGztFSSQpjoS5kNCVXxlcKBrR1Fz6FNwNXNaa0uavMYUIi1NOmZZb3yz7ELge1jawmdr3rdzsRC+J",
	"qDpBV3VYrUBeJgWcSI4ELJpoBlA+eppAZJpQNYv5BlOGFoLfSCJQTNKE70w18Js1EQT9DW/xJSASRZhp",
	"4hCuVtDZ+Ru05nAxNZ3RFVEvDLSefH2sEF9/ojYx11pBYksIBxFp3Z7sL9Pek75EDnBY65Ea05it6mWx",
	"amYRHbyhxSLfFldwDlpjqaL88TLfK3O10e6Z5swJlVovs5qtx4Kg9ZU8uU/Vx8Jlxuqgx1RC3OdevnLN",
	"mg7pKW9z5ywEjq6J6iaib+2LR6cgO1Ff8rELCGD+syQgvQa+XLpl3XPqSeiWzGKBlz0I6C3dkpfw6tFJ",
	"KJ+qLxHBEnISirHCEFrLM4VSQbegDRUJuZ8PYen9qSzus+FMniDalg3d3IINy2sUE40CsbN3Cthtc3nS",
	"szb7Ui+/YUTINU1BAs0dhychsfC8+K5Iez4qgYcmbLWGWvr1V1hg8KGuaE/5DfoKOl4AHYULJDZ0HPIw",
	"PuKoFera3lFzg1P2R5zQhC8Wu8az6FFtEWIBsRimFMOGbBb2zEXc+YGGtk8qH8e3ANDtnESYq/UQeusH",
	"TKEtJTcPh6//4Ws9XqX2FHbf7/C8jTk/gWwauLdvL2i1ZyaNU1+NVIEjxUW1epJpI7QmKM4EGIvMu/rW",
	"rZ9amS021D+4ILjdWtegC+u8DFtSj9EOILTQO/KnGnG8JYrVP2NmEz2+9RC29fmGbVnXWgcgWJG3dEMV",
	"ufM74BK4hGuUHL4Eco40TrcpXQCH4eDVBHTgdbDKzzEJXZJIEKWVohtBFZlpIe0ENYp2nnxsYm9Bsqtf",
	"EikORdbWroXXCV592ffBZU4dd1W7NAxLmwvCNk8qCNtGOT5cEQ9XxB1dEY5PdSrlyNavuAcXhWa6M/P3",
	"vRD0g0w9JOU7T3sUkVQZF62yWRgNnUG9oc+5VAaY/xvE/WK1d8/efVhaLORuV4E8zftWvnrg7w/8/Zb5",
	"u2tF6hNjyah9jwR/CUaS2AQB3jk3v3TQaHYdE6lEZstls7izVvZZNKxQdr50X5o0N9sXLr3bdd8Rd39v",
	"q7KZ2ouOAQVrMbj6bflWuSJuLjPygbs/cPdbl94dLbbL7DkruXUuXy/jEjCRuKImG7yDQHdMmec39Ewi",
	"nb5n066hy8s1umCMN8Zt1owJTNtWNsbXQ8KVYx7qxdyRT64oGNPLLbel5Obz88pVix1A8s89qHSwr34u",
	"vHShgAhXYjEXsOYvWnaDJd5V1xOCY8qIlK+2eqygldWUwoOQdXgVkW0Ru/MgpT1IabcmpRHlUeHRw556",
	"cmwZcUGqBRoaolAvi3ePHoZazNU7DtUGaerFmUIRem2UrT7nmHjpo/w+R5z2qdRod3a02A2f36rEXZqx",
	"Vdg2OxeWs+22lsTtL03ybZRwm/M8Roq1B6PqNcGJZtQNBGsev9Cq5DHZ3fcwTQeTy9sDRJRIZCDb+TLM",
	"HeWjb4jCEPFPJdrgZMnFxuaMPmtNht0TRdNbWeR7RhAXaMMFKeMfC4IyZnehllKrKFTMzdTxc2ff0i0B",
	"aeIvBYC7QsjwDpfcSUU2kw+fzHB6AnNsKrmNNkDx7PyNTQ2eTCeZSCbPJ4+A1drxajWc4g1lecJgQpck",
	"2kUJQfmJAmOMPn+T5xOokwdaTVtq9TRXzqam6pOrj27KTMV5NZzQFDYNsD7H++ooEI4eHAPqwddH8LKC",
	"YSFUKvPttKS+29J5curfAF5rD3+igvEFkFJjn+WSSzj2h/JLDdXH0oRFI2L5R3jVllA+ffj0fwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
