// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/game/reconnect"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObserver creates a new instance of MockObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver struct {
	mock.Mock
}

type MockObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObserver) EXPECT() *MockObserver_Expecter {
	return &MockObserver_Expecter{mock: &_m.Mock}
}

// Observe provides a mock function for the type MockObserver
func (_mock *MockObserver) Observe(ctx context.Context, event reconnect.ReconnectEvent) {
	_mock.Called(ctx, event)
	return
}

// MockObserver_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockObserver_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
//   - event reconnect.ReconnectEvent
func (_e *MockObserver_Expecter) Observe(ctx any, event any) *MockObserver_Observe_Call {
	return &MockObserver_Observe_Call{Call: _e.mock.On("Observe", ctx, event)}
}

func (_c *MockObserver_Observe_Call) Run(run func(ctx context.Context, event reconnect.ReconnectEvent)) *MockObserver_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 reconnect.ReconnectEvent
		if args[1] != nil {
			arg1 = args[1].(reconnect.ReconnectEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObserver_Observe_Call) Return() *MockObserver_Observe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObserver_Observe_Call) RunAndReturn(run func(ctx context.Context, event reconnect.ReconnectEvent)) *MockObserver_Observe_Call {
	_c.Run(run)
	return _c
}
