// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/game/start"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStartRepository creates a new instance of MockStartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStartRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStartRepository is an autogenerated mock type for the StartRepository type
type MockStartRepository struct {
	mock.Mock
}

type MockStartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStartRepository) EXPECT() *MockStartRepository_Expecter {
	return &MockStartRepository_Expecter{mock: &_m.Mock}
}

// CommitWaveStart provides a mock function for the type MockStartRepository
func (_mock *MockStartRepository) CommitWaveStart(ctx context.Context, record start.StartRecord) (*start.StartRecord, bool, error) {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CommitWaveStart")
	}

	var r0 *start.StartRecord
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, start.StartRecord) (*start.StartRecord, bool, error)); ok {
		return returnFunc(ctx, record)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, start.StartRecord) *start.StartRecord); ok {
		r0 = returnFunc(ctx, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*start.StartRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, start.StartRecord) bool); ok {
		r1 = returnFunc(ctx, record)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, start.StartRecord) error); ok {
		r2 = returnFunc(ctx, record)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStartRepository_CommitWaveStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitWaveStart'
type MockStartRepository_CommitWaveStart_Call struct {
	*mock.Call
}

// CommitWaveStart is a helper method to define mock.On call
//   - ctx context.Context
//   - record start.StartRecord
func (_e *MockStartRepository_Expecter) CommitWaveStart(ctx any, record any) *MockStartRepository_CommitWaveStart_Call {
	return &MockStartRepository_CommitWaveStart_Call{Call: _e.mock.On("CommitWaveStart", ctx, record)}
}

func (_c *MockStartRepository_CommitWaveStart_Call) Run(run func(ctx context.Context, record start.StartRecord)) *MockStartRepository_CommitWaveStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 start.StartRecord
		if args[1] != nil {
			arg1 = args[1].(start.StartRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStartRepository_CommitWaveStart_Call) Return(startRecord *start.StartRecord, b bool, err error) *MockStartRepository_CommitWaveStart_Call {
	_c.Call.Return(startRecord, b, err)
	return _c
}

func (_c *MockStartRepository_CommitWaveStart_Call) RunAndReturn(run func(ctx context.Context, record start.StartRecord) (*start.StartRecord, bool, error)) *MockStartRepository_CommitWaveStart_Call {
	_c.Call.Return(run)
	return _c
}

// LoadWaveStartAuthority provides a mock function for the type MockStartRepository
func (_mock *MockStartRepository) LoadWaveStartAuthority(ctx context.Context, scope start.StartScope) (start.StartAuthority, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for LoadWaveStartAuthority")
	}

	var r0 start.StartAuthority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, start.StartScope) (start.StartAuthority, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, start.StartScope) start.StartAuthority); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(start.StartAuthority)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, start.StartScope) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStartRepository_LoadWaveStartAuthority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadWaveStartAuthority'
type MockStartRepository_LoadWaveStartAuthority_Call struct {
	*mock.Call
}

// LoadWaveStartAuthority is a helper method to define mock.On call
//   - ctx context.Context
//   - scope start.StartScope
func (_e *MockStartRepository_Expecter) LoadWaveStartAuthority(ctx any, scope any) *MockStartRepository_LoadWaveStartAuthority_Call {
	return &MockStartRepository_LoadWaveStartAuthority_Call{Call: _e.mock.On("LoadWaveStartAuthority", ctx, scope)}
}

func (_c *MockStartRepository_LoadWaveStartAuthority_Call) Run(run func(ctx context.Context, scope start.StartScope)) *MockStartRepository_LoadWaveStartAuthority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 start.StartScope
		if args[1] != nil {
			arg1 = args[1].(start.StartScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStartRepository_LoadWaveStartAuthority_Call) Return(startAuthority start.StartAuthority, err error) *MockStartRepository_LoadWaveStartAuthority_Call {
	_c.Call.Return(startAuthority, err)
	return _c
}

func (_c *MockStartRepository_LoadWaveStartAuthority_Call) RunAndReturn(run func(ctx context.Context, scope start.StartScope) (start.StartAuthority, error)) *MockStartRepository_LoadWaveStartAuthority_Call {
	_c.Call.Return(run)
	return _c
}

// ReadWaveStartTime provides a mock function for the type MockStartRepository
func (_mock *MockStartRepository) ReadWaveStartTime(ctx context.Context) (time.Time, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadWaveStartTime")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (time.Time, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStartRepository_ReadWaveStartTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadWaveStartTime'
type MockStartRepository_ReadWaveStartTime_Call struct {
	*mock.Call
}

// ReadWaveStartTime is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStartRepository_Expecter) ReadWaveStartTime(ctx any) *MockStartRepository_ReadWaveStartTime_Call {
	return &MockStartRepository_ReadWaveStartTime_Call{Call: _e.mock.On("ReadWaveStartTime", ctx)}
}

func (_c *MockStartRepository_ReadWaveStartTime_Call) Run(run func(ctx context.Context)) *MockStartRepository_ReadWaveStartTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStartRepository_ReadWaveStartTime_Call) Return(time1 time.Time, err error) *MockStartRepository_ReadWaveStartTime_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockStartRepository_ReadWaveStartTime_Call) RunAndReturn(run func(ctx context.Context) (time.Time, error)) *MockStartRepository_ReadWaveStartTime_Call {
	_c.Call.Return(run)
	return _c
}
