// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/golden/plan"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlanRepository creates a new instance of MockPlanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanRepository {
	mock := &MockPlanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlanRepository is an autogenerated mock type for the PlanRepository type
type MockPlanRepository struct {
	mock.Mock
}

type MockPlanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanRepository) EXPECT() *MockPlanRepository_Expecter {
	return &MockPlanRepository_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockPlanRepository
func (_mock *MockPlanRepository) Commit(ctx context.Context, plan1 plan.ExactPlan) (*plan.ExactPlan, bool, error) {
	ret := _mock.Called(ctx, plan1)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *plan.ExactPlan
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, plan.ExactPlan) (*plan.ExactPlan, bool, error)); ok {
		return returnFunc(ctx, plan1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, plan.ExactPlan) *plan.ExactPlan); ok {
		r0 = returnFunc(ctx, plan1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plan.ExactPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, plan.ExactPlan) bool); ok {
		r1 = returnFunc(ctx, plan1)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, plan.ExactPlan) error); ok {
		r2 = returnFunc(ctx, plan1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPlanRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockPlanRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - plan1 plan.ExactPlan
func (_e *MockPlanRepository_Expecter) Commit(ctx interface{}, plan1 interface{}) *MockPlanRepository_Commit_Call {
	return &MockPlanRepository_Commit_Call{Call: _e.mock.On("Commit", ctx, plan1)}
}

func (_c *MockPlanRepository_Commit_Call) Run(run func(ctx context.Context, plan1 plan.ExactPlan)) *MockPlanRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 plan.ExactPlan
		if args[1] != nil {
			arg1 = args[1].(plan.ExactPlan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlanRepository_Commit_Call) Return(exactPlan *plan.ExactPlan, b bool, err error) *MockPlanRepository_Commit_Call {
	_c.Call.Return(exactPlan, b, err)
	return _c
}

func (_c *MockPlanRepository_Commit_Call) RunAndReturn(run func(ctx context.Context, plan1 plan.ExactPlan) (*plan.ExactPlan, bool, error)) *MockPlanRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPlanRepository
func (_mock *MockPlanRepository) Get(ctx context.Context, scope plan.Scope, planID uuid.UUID) (*plan.ExactPlan, error) {
	ret := _mock.Called(ctx, scope, planID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *plan.ExactPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, plan.Scope, uuid.UUID) (*plan.ExactPlan, error)); ok {
		return returnFunc(ctx, scope, planID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, plan.Scope, uuid.UUID) *plan.ExactPlan); ok {
		r0 = returnFunc(ctx, scope, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plan.ExactPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, plan.Scope, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, scope, planID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPlanRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - scope plan.Scope
//   - planID uuid.UUID
func (_e *MockPlanRepository_Expecter) Get(ctx interface{}, scope interface{}, planID interface{}) *MockPlanRepository_Get_Call {
	return &MockPlanRepository_Get_Call{Call: _e.mock.On("Get", ctx, scope, planID)}
}

func (_c *MockPlanRepository_Get_Call) Run(run func(ctx context.Context, scope plan.Scope, planID uuid.UUID)) *MockPlanRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 plan.Scope
		if args[1] != nil {
			arg1 = args[1].(plan.Scope)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanRepository_Get_Call) Return(exactPlan *plan.ExactPlan, err error) *MockPlanRepository_Get_Call {
	_c.Call.Return(exactPlan, err)
	return _c
}

func (_c *MockPlanRepository_Get_Call) RunAndReturn(run func(ctx context.Context, scope plan.Scope, planID uuid.UUID) (*plan.ExactPlan, error)) *MockPlanRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LoadAuthority provides a mock function for the type MockPlanRepository
func (_mock *MockPlanRepository) LoadAuthority(ctx context.Context, scope plan.Scope) (plan.Authority, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for LoadAuthority")
	}

	var r0 plan.Authority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, plan.Scope) (plan.Authority, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, plan.Scope) plan.Authority); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(plan.Authority)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, plan.Scope) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanRepository_LoadAuthority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAuthority'
type MockPlanRepository_LoadAuthority_Call struct {
	*mock.Call
}

// LoadAuthority is a helper method to define mock.On call
//   - ctx context.Context
//   - scope plan.Scope
func (_e *MockPlanRepository_Expecter) LoadAuthority(ctx interface{}, scope interface{}) *MockPlanRepository_LoadAuthority_Call {
	return &MockPlanRepository_LoadAuthority_Call{Call: _e.mock.On("LoadAuthority", ctx, scope)}
}

func (_c *MockPlanRepository_LoadAuthority_Call) Run(run func(ctx context.Context, scope plan.Scope)) *MockPlanRepository_LoadAuthority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 plan.Scope
		if args[1] != nil {
			arg1 = args[1].(plan.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlanRepository_LoadAuthority_Call) Return(authority plan.Authority, err error) *MockPlanRepository_LoadAuthority_Call {
	_c.Call.Return(authority, err)
	return _c
}

func (_c *MockPlanRepository_LoadAuthority_Call) RunAndReturn(run func(ctx context.Context, scope plan.Scope) (plan.Authority, error)) *MockPlanRepository_LoadAuthority_Call {
	_c.Call.Return(run)
	return _c
}
