// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminPlayerAuditEvent struct {
	ID           uuid.UUID
	ActorSubject string
	ActorJti     string
	Action       string
	PlayerID     uuid.UUID
	BeforeState  []byte
	AfterState   []byte
	CreatedAt    pgtype.Timestamptz
}

type Duel struct {
	ID         uuid.UUID
	Player1ID  uuid.UUID
	Player2ID  uuid.UUID
	Status     string
	WinnerID   uuid.NullUUID
	Deadline   pgtype.Timestamptz
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type DuelPlayerTask struct {
	DuelID   uuid.UUID
	PlayerID uuid.UUID
	TaskID   uuid.UUID
	Solved   bool
	SolvedAt pgtype.Timestamptz
}

type Player struct {
	ID           uuid.UUID
	Username     string
	SessionToken uuid.NullUUID
	Status       string
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type PlayerLeaderboardOverride struct {
	PlayerID           uuid.UUID
	Wins               int32
	AverageSolveTimeMs int64
	UpdatedAt          pgtype.Timestamptz
}

type PlayerTaskHistory struct {
	PlayerID uuid.UUID
	TaskID   uuid.UUID
	SolvedAt pgtype.Timestamptz
}

type Task struct {
	ID            uuid.UUID
	Title         string
	Description   string
	Category      string
	Difficulty    string
	TimeLimit     int32
	Flag          string
	Hint1         *string
	Hint2         *string
	Hint3         *string
	TaskUrl       *string
	SourceFileUrl *string
	CreatedAt     pgtype.Timestamptz
}
