// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: player_task_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSolvedTask = `-- name: AddSolvedTask :exec
INSERT INTO player_task_history (player_id, task_id, solved_at)
VALUES ($1, $2, $3) ON CONFLICT (player_id, task_id) DO NOTHING
`

type AddSolvedTaskParams struct {
	PlayerID uuid.UUID
	TaskID   uuid.UUID
	SolvedAt pgtype.Timestamptz
}

func (q *Queries) AddSolvedTask(ctx context.Context, arg AddSolvedTaskParams) error {
	_, err := q.db.Exec(ctx, addSolvedTask, arg.PlayerID, arg.TaskID, arg.SolvedAt)
	return err
}

const listSolvedTaskIDs = `-- name: ListSolvedTaskIDs :many
SELECT task_id
FROM player_task_history
WHERE player_id = $1
ORDER BY solved_at DESC
`

func (q *Queries) ListSolvedTaskIDs(ctx context.Context, playerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSolvedTaskIDs, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAnyTaskByDifficulty = `-- name: SelectAnyTaskByDifficulty :one
SELECT id,
  title,
  description,
  category,
  difficulty,
  time_limit,
  flag,
  hint_1,
  hint_2,
  hint_3,
  task_url,
  source_file_url,
  created_at
FROM tasks
WHERE difficulty = $1
  AND btrim(hint_1) <> ''
  AND btrim(hint_2) <> ''
  AND btrim(hint_3) <> ''
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) SelectAnyTaskByDifficulty(ctx context.Context, difficulty string) (Task, error) {
	row := q.db.QueryRow(ctx, selectAnyTaskByDifficulty, difficulty)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.TimeLimit,
		&i.Flag,
		&i.Hint1,
		&i.Hint2,
		&i.Hint3,
		&i.TaskUrl,
		&i.SourceFileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const selectUnsolvedTaskByDifficulty = `-- name: SelectUnsolvedTaskByDifficulty :one
SELECT id,
  title,
  description,
  category,
  difficulty,
  time_limit,
  flag,
  hint_1,
  hint_2,
  hint_3,
  task_url,
  source_file_url,
  created_at
FROM tasks
WHERE difficulty = $2
  AND btrim(hint_1) <> ''
  AND btrim(hint_2) <> ''
  AND btrim(hint_3) <> ''
  AND id NOT IN (
    SELECT task_id
    FROM player_task_history
    WHERE player_id = $1
  )
ORDER BY RANDOM()
LIMIT 1
`

type SelectUnsolvedTaskByDifficultyParams struct {
	PlayerID   uuid.UUID
	Difficulty string
}

func (q *Queries) SelectUnsolvedTaskByDifficulty(ctx context.Context, arg SelectUnsolvedTaskByDifficultyParams) (Task, error) {
	row := q.db.QueryRow(ctx, selectUnsolvedTaskByDifficulty, arg.PlayerID, arg.Difficulty)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.TimeLimit,
		&i.Flag,
		&i.Hint1,
		&i.Hint2,
		&i.Hint3,
		&i.TaskUrl,
		&i.SourceFileUrl,
		&i.CreatedAt,
	)
	return i, err
}
