// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (username)
VALUES ($1)
RETURNING id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
`

func (q *Queries) CreatePlayer(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const getAdminPlayer = `-- name: GetAdminPlayer :one
WITH base_stats AS (
    SELECT d.winner_id AS player_id,
        COUNT(*)::INT AS wins,
        FLOOR(
            AVG(
                (
                    EXTRACT(
                        EPOCH
                        FROM dpt.solved_at - d.started_at
                    ) * 1000
                )::BIGINT
            )
        )::BIGINT AS average_solve_time_ms
    FROM duels d
        JOIN duel_player_tasks dpt ON dpt.duel_id = d.id
            AND dpt.player_id = d.winner_id
            AND dpt.solved = TRUE
            AND dpt.solved_at IS NOT NULL
    WHERE d.status = 'finished'
        AND d.winner_id IS NOT NULL
    GROUP BY d.winner_id
)
SELECT p.id,
    p.username,
    p.session_token,
    p.status,
    p.created_at,
    p.deleted_at,
    p.session_expires_at,
    COALESCE(o.wins, b.wins, 0)::INT AS wins,
    COALESCE(o.average_solve_time_ms, b.average_solve_time_ms, 0)::BIGINT AS average_solve_time_ms,
    (o.player_id IS NOT NULL)::BOOLEAN AS stats_overridden
FROM players p
    LEFT JOIN base_stats b ON b.player_id = p.id
    LEFT JOIN player_leaderboard_overrides o ON o.player_id = p.id
WHERE p.id = $1
    AND p.deleted_at IS NULL
`

type GetAdminPlayerRow struct {
	ID                 uuid.UUID
	Username           string
	SessionToken       uuid.NullUUID
	Status             string
	CreatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	SessionExpiresAt   pgtype.Timestamptz
	Wins               int32
	AverageSolveTimeMs int64
	StatsOverridden    bool
}

func (q *Queries) GetAdminPlayer(ctx context.Context, id uuid.UUID) (GetAdminPlayerRow, error) {
	row := q.db.QueryRow(ctx, getAdminPlayer, id)
	var i GetAdminPlayerRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
		&i.Wins,
		&i.AverageSolveTimeMs,
		&i.StatsOverridden,
	)
	return i, err
}

const getAdminPlayerIncludingDeleted = `-- name: GetAdminPlayerIncludingDeleted :one
WITH base_stats AS (
    SELECT d.winner_id AS player_id,
        COUNT(*)::INT AS wins,
        FLOOR(
            AVG(
                (
                    EXTRACT(
                        EPOCH
                        FROM dpt.solved_at - d.started_at
                    ) * 1000
                )::BIGINT
            )
        )::BIGINT AS average_solve_time_ms
    FROM duels d
        JOIN duel_player_tasks dpt ON dpt.duel_id = d.id
            AND dpt.player_id = d.winner_id
            AND dpt.solved = TRUE
            AND dpt.solved_at IS NOT NULL
    WHERE d.status = 'finished'
        AND d.winner_id IS NOT NULL
    GROUP BY d.winner_id
)
SELECT p.id,
    p.username,
    p.session_token,
    p.status,
    p.created_at,
    p.deleted_at,
    p.session_expires_at,
    COALESCE(o.wins, b.wins, 0)::INT AS wins,
    COALESCE(o.average_solve_time_ms, b.average_solve_time_ms, 0)::BIGINT AS average_solve_time_ms,
    (o.player_id IS NOT NULL)::BOOLEAN AS stats_overridden
FROM players p
    LEFT JOIN base_stats b ON b.player_id = p.id
    LEFT JOIN player_leaderboard_overrides o ON o.player_id = p.id
WHERE p.id = $1
`

type GetAdminPlayerIncludingDeletedRow struct {
	ID                 uuid.UUID
	Username           string
	SessionToken       uuid.NullUUID
	Status             string
	CreatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	SessionExpiresAt   pgtype.Timestamptz
	Wins               int32
	AverageSolveTimeMs int64
	StatsOverridden    bool
}

func (q *Queries) GetAdminPlayerIncludingDeleted(ctx context.Context, id uuid.UUID) (GetAdminPlayerIncludingDeletedRow, error) {
	row := q.db.QueryRow(ctx, getAdminPlayerIncludingDeleted, id)
	var i GetAdminPlayerIncludingDeletedRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
		&i.Wins,
		&i.AverageSolveTimeMs,
		&i.StatsOverridden,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const getPlayerBySessionToken = `-- name: GetPlayerBySessionToken :one
SELECT id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
FROM players
WHERE session_token = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetPlayerBySessionToken(ctx context.Context, sessionToken uuid.NullUUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerBySessionToken, sessionToken)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
FROM players
WHERE username = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const listAdminPlayers = `-- name: ListAdminPlayers :many
WITH base_stats AS (
    SELECT d.winner_id AS player_id,
        COUNT(*)::INT AS wins,
        FLOOR(
            AVG(
                (
                    EXTRACT(
                        EPOCH
                        FROM dpt.solved_at - d.started_at
                    ) * 1000
                )::BIGINT
            )
        )::BIGINT AS average_solve_time_ms
    FROM duels d
        JOIN duel_player_tasks dpt ON dpt.duel_id = d.id
            AND dpt.player_id = d.winner_id
            AND dpt.solved = TRUE
            AND dpt.solved_at IS NOT NULL
    WHERE d.status = 'finished'
        AND d.winner_id IS NOT NULL
    GROUP BY d.winner_id
)
SELECT p.id,
    p.username,
    p.session_token,
    p.status,
    p.created_at,
    p.deleted_at,
    p.session_expires_at,
    COALESCE(o.wins, b.wins, 0)::INT AS wins,
    COALESCE(o.average_solve_time_ms, b.average_solve_time_ms, 0)::BIGINT AS average_solve_time_ms,
    (o.player_id IS NOT NULL)::BOOLEAN AS stats_overridden
FROM players p
    LEFT JOIN base_stats b ON b.player_id = p.id
    LEFT JOIN player_leaderboard_overrides o ON o.player_id = p.id
WHERE ($1::BOOLEAN OR p.deleted_at IS NULL)
ORDER BY p.created_at DESC,
    p.username ASC
`

type ListAdminPlayersRow struct {
	ID                 uuid.UUID
	Username           string
	SessionToken       uuid.NullUUID
	Status             string
	CreatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	SessionExpiresAt   pgtype.Timestamptz
	Wins               int32
	AverageSolveTimeMs int64
	StatsOverridden    bool
}

func (q *Queries) ListAdminPlayers(ctx context.Context, dollar_1 bool) ([]ListAdminPlayersRow, error) {
	rows, err := q.db.Query(ctx, listAdminPlayers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminPlayersRow{}
	for rows.Next() {
		var i ListAdminPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.SessionToken,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.SessionExpiresAt,
			&i.Wins,
			&i.AverageSolveTimeMs,
			&i.StatsOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetQueuedPlayers = `-- name: ResetQueuedPlayers :execrows
UPDATE players
SET status = 'idle'
WHERE status = 'queued'
    AND deleted_at IS NULL
`

func (q *Queries) ResetQueuedPlayers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetQueuedPlayers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteIdlePlayer = `-- name: SoftDeleteIdlePlayer :one
UPDATE players
SET username = $2,
    session_token = NULL,
    session_expires_at = NULL,
    status = 'idle',
    deleted_at = $3
WHERE id = $1
    AND status = 'idle'
    AND deleted_at IS NULL
RETURNING id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
`

type SoftDeleteIdlePlayerParams struct {
	ID        uuid.UUID
	Username  string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SoftDeleteIdlePlayer(ctx context.Context, arg SoftDeleteIdlePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, softDeleteIdlePlayer, arg.ID, arg.Username, arg.DeletedAt)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const updatePlayerSessionToken = `-- name: UpdatePlayerSessionToken :one
UPDATE players
SET session_token = $2,
    session_expires_at = $3
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
`

type UpdatePlayerSessionTokenParams struct {
	ID               uuid.UUID
	SessionToken     uuid.NullUUID
	SessionExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdatePlayerSessionToken(ctx context.Context, arg UpdatePlayerSessionTokenParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerSessionToken, arg.ID, arg.SessionToken, arg.SessionExpiresAt)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const updatePlayerStatus = `-- name: UpdatePlayerStatus :one
UPDATE players
SET status = $2
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
`

type UpdatePlayerStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatus, arg.ID, arg.Status)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const updatePlayerStatusIfCurrent = `-- name: UpdatePlayerStatusIfCurrent :one
UPDATE players
SET status = $3
WHERE id = $1
    AND status = $2
    AND deleted_at IS NULL
RETURNING id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
`

type UpdatePlayerStatusIfCurrentParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) UpdatePlayerStatusIfCurrent(ctx context.Context, arg UpdatePlayerStatusIfCurrentParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatusIfCurrent, arg.ID, arg.Status, arg.Status_2)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const updatePlayerUsername = `-- name: UpdatePlayerUsername :one
UPDATE players
SET username = $2
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
`

type UpdatePlayerUsernameParams struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) UpdatePlayerUsername(ctx context.Context, arg UpdatePlayerUsernameParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerUsername, arg.ID, arg.Username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const upsertPlayerLeaderboardOverride = `-- name: UpsertPlayerLeaderboardOverride :one
INSERT INTO player_leaderboard_overrides (
    player_id,
    wins,
    average_solve_time_ms,
    updated_at
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (player_id) DO UPDATE
SET wins = EXCLUDED.wins,
    average_solve_time_ms = EXCLUDED.average_solve_time_ms,
    updated_at = EXCLUDED.updated_at
RETURNING player_id,
    wins,
    average_solve_time_ms,
    updated_at
`

type UpsertPlayerLeaderboardOverrideParams struct {
	PlayerID           uuid.UUID
	Wins               int32
	AverageSolveTimeMs int64
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertPlayerLeaderboardOverride(ctx context.Context, arg UpsertPlayerLeaderboardOverrideParams) (PlayerLeaderboardOverride, error) {
	row := q.db.QueryRow(ctx, upsertPlayerLeaderboardOverride,
		arg.PlayerID,
		arg.Wins,
		arg.AverageSolveTimeMs,
		arg.UpdatedAt,
	)
	var i PlayerLeaderboardOverride
	err := row.Scan(
		&i.PlayerID,
		&i.Wins,
		&i.AverageSolveTimeMs,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlayerSessionByUsername = `-- name: UpsertPlayerSessionByUsername :one
INSERT INTO players (username, session_token, session_expires_at)
VALUES ($1, $2, $3) ON CONFLICT (username) DO
UPDATE
SET session_token = EXCLUDED.session_token,
    session_expires_at = EXCLUDED.session_expires_at,
    status = 'idle'
WHERE players.status <> 'in_duel'
    AND players.deleted_at IS NULL
RETURNING id,
    username,
    session_token,
    status,
    created_at,
    deleted_at,
    session_expires_at
`

type UpsertPlayerSessionByUsernameParams struct {
	Username         string
	SessionToken     uuid.NullUUID
	SessionExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpsertPlayerSessionByUsername(ctx context.Context, arg UpsertPlayerSessionByUsernameParams) (Player, error) {
	row := q.db.QueryRow(ctx, upsertPlayerSessionByUsername, arg.Username, arg.SessionToken, arg.SessionExpiresAt)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SessionToken,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}
