// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/domain/authority"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRecoveryAuthorityProvider creates a new instance of MockRecoveryAuthorityProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecoveryAuthorityProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecoveryAuthorityProvider {
	mock := &MockRecoveryAuthorityProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecoveryAuthorityProvider is an autogenerated mock type for the RecoveryAuthorityProvider type
type MockRecoveryAuthorityProvider struct {
	mock.Mock
}

type MockRecoveryAuthorityProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecoveryAuthorityProvider) EXPECT() *MockRecoveryAuthorityProvider_Expecter {
	return &MockRecoveryAuthorityProvider_Expecter{mock: &_m.Mock}
}

// RecoveryAuthorityFor provides a mock function for the type MockRecoveryAuthorityProvider
func (_mock *MockRecoveryAuthorityProvider) RecoveryAuthorityFor(ctx context.Context, tournamentID uuid.UUID) (authority.Identity, bool, error) {
	ret := _mock.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for RecoveryAuthorityFor")
	}

	var r0 authority.Identity
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (authority.Identity, bool, error)); ok {
		return returnFunc(ctx, tournamentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) authority.Identity); ok {
		r0 = returnFunc(ctx, tournamentID)
	} else {
		r0 = ret.Get(0).(authority.Identity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = returnFunc(ctx, tournamentID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, tournamentID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoveryAuthorityFor'
type MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call struct {
	*mock.Call
}

// RecoveryAuthorityFor is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockRecoveryAuthorityProvider_Expecter) RecoveryAuthorityFor(ctx interface{}, tournamentID interface{}) *MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call {
	return &MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call{Call: _e.mock.On("RecoveryAuthorityFor", ctx, tournamentID)}
}

func (_c *MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call) Return(authority1 authority.Identity, owned bool, err error) *MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call {
	_c.Call.Return(authority1, owned, err)
	return _c
}

func (_c *MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call) RunAndReturn(run func(ctx context.Context, tournamentID uuid.UUID) (authority.Identity, bool, error)) *MockRecoveryAuthorityProvider_RecoveryAuthorityFor_Call {
	_c.Call.Return(run)
	return _c
}
