// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/TakuyaYagam1/task-per-minute/internal/usecase/golden/state"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStateRepository creates a new instance of MockStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStateRepository is an autogenerated mock type for the StateRepository type
type MockStateRepository struct {
	mock.Mock
}

type MockStateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateRepository) EXPECT() *MockStateRepository_Expecter {
	return &MockStateRepository_Expecter{mock: &_m.Mock}
}

// CommitGoldenState provides a mock function for the type MockStateRepository
func (_mock *MockStateRepository) CommitGoldenState(ctx context.Context, commit state.GoldenStateCommit) (*state.GoldenState, bool, error) {
	ret := _mock.Called(ctx, commit)

	if len(ret) == 0 {
		panic("no return value specified for CommitGoldenState")
	}

	var r0 *state.GoldenState
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.GoldenStateCommit) (*state.GoldenState, bool, error)); ok {
		return returnFunc(ctx, commit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.GoldenStateCommit) *state.GoldenState); ok {
		r0 = returnFunc(ctx, commit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.GoldenState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.GoldenStateCommit) bool); ok {
		r1 = returnFunc(ctx, commit)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, state.GoldenStateCommit) error); ok {
		r2 = returnFunc(ctx, commit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStateRepository_CommitGoldenState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitGoldenState'
type MockStateRepository_CommitGoldenState_Call struct {
	*mock.Call
}

// CommitGoldenState is a helper method to define mock.On call
//   - ctx context.Context
//   - commit state.GoldenStateCommit
func (_e *MockStateRepository_Expecter) CommitGoldenState(ctx any, commit any) *MockStateRepository_CommitGoldenState_Call {
	return &MockStateRepository_CommitGoldenState_Call{Call: _e.mock.On("CommitGoldenState", ctx, commit)}
}

func (_c *MockStateRepository_CommitGoldenState_Call) Run(run func(ctx context.Context, commit state.GoldenStateCommit)) *MockStateRepository_CommitGoldenState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.GoldenStateCommit
		if args[1] != nil {
			arg1 = args[1].(state.GoldenStateCommit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateRepository_CommitGoldenState_Call) Return(goldenState *state.GoldenState, b bool, err error) *MockStateRepository_CommitGoldenState_Call {
	_c.Call.Return(goldenState, b, err)
	return _c
}

func (_c *MockStateRepository_CommitGoldenState_Call) RunAndReturn(run func(ctx context.Context, commit state.GoldenStateCommit) (*state.GoldenState, bool, error)) *MockStateRepository_CommitGoldenState_Call {
	_c.Call.Return(run)
	return _c
}

// LoadGoldenState provides a mock function for the type MockStateRepository
func (_mock *MockStateRepository) LoadGoldenState(ctx context.Context, scope state.GoldenStateScope) (state.GoldenState, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for LoadGoldenState")
	}

	var r0 state.GoldenState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.GoldenStateScope) (state.GoldenState, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.GoldenStateScope) state.GoldenState); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(state.GoldenState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.GoldenStateScope) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateRepository_LoadGoldenState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadGoldenState'
type MockStateRepository_LoadGoldenState_Call struct {
	*mock.Call
}

// LoadGoldenState is a helper method to define mock.On call
//   - ctx context.Context
//   - scope state.GoldenStateScope
func (_e *MockStateRepository_Expecter) LoadGoldenState(ctx any, scope any) *MockStateRepository_LoadGoldenState_Call {
	return &MockStateRepository_LoadGoldenState_Call{Call: _e.mock.On("LoadGoldenState", ctx, scope)}
}

func (_c *MockStateRepository_LoadGoldenState_Call) Run(run func(ctx context.Context, scope state.GoldenStateScope)) *MockStateRepository_LoadGoldenState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.GoldenStateScope
		if args[1] != nil {
			arg1 = args[1].(state.GoldenStateScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateRepository_LoadGoldenState_Call) Return(goldenState state.GoldenState, err error) *MockStateRepository_LoadGoldenState_Call {
	_c.Call.Return(goldenState, err)
	return _c
}

func (_c *MockStateRepository_LoadGoldenState_Call) RunAndReturn(run func(ctx context.Context, scope state.GoldenStateScope) (state.GoldenState, error)) *MockStateRepository_LoadGoldenState_Call {
	_c.Call.Return(run)
	return _c
}
