// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDuel = `-- name: CreateDuel :one
INSERT INTO duels (player1_id, player2_id, deadline)
VALUES ($1, $2, $3)
RETURNING id,
  player1_id,
  player2_id,
  status,
  winner_id,
  deadline,
  started_at,
  finished_at
`

type CreateDuelParams struct {
	Player1ID uuid.UUID
	Player2ID uuid.UUID
	Deadline  pgtype.Timestamptz
}

func (q *Queries) CreateDuel(ctx context.Context, arg CreateDuelParams) (Duel, error) {
	row := q.db.QueryRow(ctx, createDuel, arg.Player1ID, arg.Player2ID, arg.Deadline)
	var i Duel
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Status,
		&i.WinnerID,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishDuel = `-- name: FinishDuel :one
UPDATE duels
SET status = $4,
  winner_id = $2,
  finished_at = $3
WHERE id = $1
  AND status = 'active'
RETURNING id,
  player1_id,
  player2_id,
  status,
  winner_id,
  deadline,
  started_at,
  finished_at
`

type FinishDuelParams struct {
	ID         uuid.UUID
	WinnerID   uuid.NullUUID
	FinishedAt pgtype.Timestamptz
	Status     string
}

func (q *Queries) FinishDuel(ctx context.Context, arg FinishDuelParams) (Duel, error) {
	row := q.db.QueryRow(ctx, finishDuel,
		arg.ID,
		arg.WinnerID,
		arg.FinishedAt,
		arg.Status,
	)
	var i Duel
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Status,
		&i.WinnerID,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getActiveDuelByPlayerID = `-- name: GetActiveDuelByPlayerID :one
SELECT id,
  player1_id,
  player2_id,
  status,
  winner_id,
  deadline,
  started_at,
  finished_at
FROM duels
WHERE status = 'active'
  AND (
    player1_id = $1
    OR player2_id = $1
  )
LIMIT 1
`

func (q *Queries) GetActiveDuelByPlayerID(ctx context.Context, player1ID uuid.UUID) (Duel, error) {
	row := q.db.QueryRow(ctx, getActiveDuelByPlayerID, player1ID)
	var i Duel
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Status,
		&i.WinnerID,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDuelByID = `-- name: GetDuelByID :one
SELECT id,
  player1_id,
  player2_id,
  status,
  winner_id,
  deadline,
  started_at,
  finished_at
FROM duels
WHERE id = $1
`

func (q *Queries) GetDuelByID(ctx context.Context, id uuid.UUID) (Duel, error) {
	row := q.db.QueryRow(ctx, getDuelByID, id)
	var i Duel
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Status,
		&i.WinnerID,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listActiveDuels = `-- name: ListActiveDuels :many
SELECT id,
  player1_id,
  player2_id,
  status,
  winner_id,
  deadline,
  started_at,
  finished_at
FROM duels
WHERE status = 'active'
ORDER BY started_at ASC,
  id ASC
`

func (q *Queries) ListActiveDuels(ctx context.Context) ([]Duel, error) {
	rows, err := q.db.Query(ctx, listActiveDuels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Duel{}
	for rows.Next() {
		var i Duel
		if err := rows.Scan(
			&i.ID,
			&i.Player1ID,
			&i.Player2ID,
			&i.Status,
			&i.WinnerID,
			&i.Deadline,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDuelDeadline = `-- name: UpdateDuelDeadline :one
UPDATE duels
SET deadline = $2
WHERE id = $1
  AND status = 'active'
RETURNING id,
  player1_id,
  player2_id,
  status,
  winner_id,
  deadline,
  started_at,
  finished_at
`

type UpdateDuelDeadlineParams struct {
	ID       uuid.UUID
	Deadline pgtype.Timestamptz
}

func (q *Queries) UpdateDuelDeadline(ctx context.Context, arg UpdateDuelDeadlineParams) (Duel, error) {
	row := q.db.QueryRow(ctx, updateDuelDeadline, arg.ID, arg.Deadline)
	var i Duel
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Status,
		&i.WinnerID,
		&i.Deadline,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
