// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duel_player_tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDuelPlayerTask = `-- name: CreateDuelPlayerTask :exec
INSERT INTO duel_player_tasks (duel_id, player_id, task_id)
VALUES ($1, $2, $3)
`

type CreateDuelPlayerTaskParams struct {
	DuelID   uuid.UUID
	PlayerID uuid.UUID
	TaskID   uuid.UUID
}

func (q *Queries) CreateDuelPlayerTask(ctx context.Context, arg CreateDuelPlayerTaskParams) error {
	_, err := q.db.Exec(ctx, createDuelPlayerTask, arg.DuelID, arg.PlayerID, arg.TaskID)
	return err
}

const getDuelPlayerTask = `-- name: GetDuelPlayerTask :one
SELECT duel_id,
    player_id,
    task_id,
    solved,
    solved_at
FROM duel_player_tasks
WHERE duel_id = $1
    AND player_id = $2
`

type GetDuelPlayerTaskParams struct {
	DuelID   uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) GetDuelPlayerTask(ctx context.Context, arg GetDuelPlayerTaskParams) (DuelPlayerTask, error) {
	row := q.db.QueryRow(ctx, getDuelPlayerTask, arg.DuelID, arg.PlayerID)
	var i DuelPlayerTask
	err := row.Scan(
		&i.DuelID,
		&i.PlayerID,
		&i.TaskID,
		&i.Solved,
		&i.SolvedAt,
	)
	return i, err
}

const getPlayerTask = `-- name: GetPlayerTask :one
SELECT t.id,
    t.title,
    t.description,
    t.category,
    t.difficulty,
    t.time_limit,
    t.flag,
    t.hint_1,
    t.hint_2,
    t.hint_3,
    t.task_url,
    t.source_file_url,
    t.created_at
FROM duel_player_tasks dpt
    JOIN tasks t ON t.id = dpt.task_id
WHERE dpt.duel_id = $1
    AND dpt.player_id = $2
`

type GetPlayerTaskParams struct {
	DuelID   uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) GetPlayerTask(ctx context.Context, arg GetPlayerTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getPlayerTask, arg.DuelID, arg.PlayerID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.TimeLimit,
		&i.Flag,
		&i.Hint1,
		&i.Hint2,
		&i.Hint3,
		&i.TaskUrl,
		&i.SourceFileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const markDuelPlayerTaskSolved = `-- name: MarkDuelPlayerTaskSolved :exec
UPDATE duel_player_tasks
SET solved = TRUE,
    solved_at = $3
WHERE duel_id = $1
    AND player_id = $2
`

type MarkDuelPlayerTaskSolvedParams struct {
	DuelID   uuid.UUID
	PlayerID uuid.UUID
	SolvedAt pgtype.Timestamptz
}

func (q *Queries) MarkDuelPlayerTaskSolved(ctx context.Context, arg MarkDuelPlayerTaskSolvedParams) error {
	_, err := q.db.Exec(ctx, markDuelPlayerTaskSolved, arg.DuelID, arg.PlayerID, arg.SolvedAt)
	return err
}
