// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution_authority.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExecutionAuthorityLease = `-- name: CreateExecutionAuthorityLease :one
INSERT INTO execution_authority_leases (
    tournament_id,
    command_id,
    holder_id,
    lease_id,
    epoch,
    process_kind,
    revision,
    previous_revision,
    previous_lease_id,
    previous_epoch,
    acquired_at,
    renewed_at,
    expires_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING tournament_id,
    command_id,
    holder_id,
    lease_id,
    epoch,
    process_kind,
    revision,
    previous_revision,
    previous_lease_id,
    previous_epoch,
    acquired_at,
    renewed_at,
    expires_at,
    created_at
`

type CreateExecutionAuthorityLeaseParams struct {
	TournamentID     uuid.UUID
	CommandID        uuid.UUID
	HolderID         uuid.UUID
	LeaseID          uuid.UUID
	Epoch            int64
	ProcessKind      string
	Revision         int64
	PreviousRevision *int64
	PreviousLeaseID  uuid.NullUUID
	PreviousEpoch    *int64
	AcquiredAt       pgtype.Timestamptz
	RenewedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateExecutionAuthorityLease(ctx context.Context, arg CreateExecutionAuthorityLeaseParams) (ExecutionAuthorityLease, error) {
	row := q.db.QueryRow(ctx, createExecutionAuthorityLease,
		arg.TournamentID,
		arg.CommandID,
		arg.HolderID,
		arg.LeaseID,
		arg.Epoch,
		arg.ProcessKind,
		arg.Revision,
		arg.PreviousRevision,
		arg.PreviousLeaseID,
		arg.PreviousEpoch,
		arg.AcquiredAt,
		arg.RenewedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ExecutionAuthorityLease
	err := row.Scan(
		&i.TournamentID,
		&i.CommandID,
		&i.HolderID,
		&i.LeaseID,
		&i.Epoch,
		&i.ProcessKind,
		&i.Revision,
		&i.PreviousRevision,
		&i.PreviousLeaseID,
		&i.PreviousEpoch,
		&i.AcquiredAt,
		&i.RenewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findExecutionAuthorityCommand = `-- name: FindExecutionAuthorityCommand :one
SELECT tournament_id,
    command_id,
    holder_id,
    lease_id,
    epoch,
    process_kind,
    revision,
    previous_revision,
    previous_lease_id,
    previous_epoch,
    acquired_at,
    renewed_at,
    expires_at,
    created_at
FROM execution_authority_leases
WHERE tournament_id = $1
    AND command_id = $2
`

type FindExecutionAuthorityCommandParams struct {
	TournamentID uuid.UUID
	CommandID    uuid.UUID
}

func (q *Queries) FindExecutionAuthorityCommand(ctx context.Context, arg FindExecutionAuthorityCommandParams) (ExecutionAuthorityLease, error) {
	row := q.db.QueryRow(ctx, findExecutionAuthorityCommand, arg.TournamentID, arg.CommandID)
	var i ExecutionAuthorityLease
	err := row.Scan(
		&i.TournamentID,
		&i.CommandID,
		&i.HolderID,
		&i.LeaseID,
		&i.Epoch,
		&i.ProcessKind,
		&i.Revision,
		&i.PreviousRevision,
		&i.PreviousLeaseID,
		&i.PreviousEpoch,
		&i.AcquiredAt,
		&i.RenewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const loadExecutionAuthority = `-- name: LoadExecutionAuthority :one
SELECT tournament_id,
    command_id,
    holder_id,
    lease_id,
    epoch,
    process_kind,
    revision,
    previous_revision,
    previous_lease_id,
    previous_epoch,
    acquired_at,
    renewed_at,
    expires_at,
    created_at
FROM execution_authority_leases
WHERE tournament_id = $1
ORDER BY revision DESC
LIMIT 1
`

func (q *Queries) LoadExecutionAuthority(ctx context.Context, tournamentID uuid.UUID) (ExecutionAuthorityLease, error) {
	row := q.db.QueryRow(ctx, loadExecutionAuthority, tournamentID)
	var i ExecutionAuthorityLease
	err := row.Scan(
		&i.TournamentID,
		&i.CommandID,
		&i.HolderID,
		&i.LeaseID,
		&i.Epoch,
		&i.ProcessKind,
		&i.Revision,
		&i.PreviousRevision,
		&i.PreviousLeaseID,
		&i.PreviousEpoch,
		&i.AcquiredAt,
		&i.RenewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockExecutionAuthorityScope = `-- name: LockExecutionAuthorityScope :one
SELECT tournament.id
FROM tournaments AS tournament
WHERE tournament.id = $1
FOR UPDATE OF tournament
`

func (q *Queries) LockExecutionAuthorityScope(ctx context.Context, tournamentID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockExecutionAuthorityScope, tournamentID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const readExecutionAuthorityTime = `-- name: ReadExecutionAuthorityTime :one
SELECT clock_timestamp()::TIMESTAMPTZ AS authoritative_at
`

func (q *Queries) ReadExecutionAuthorityTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, readExecutionAuthorityTime)
	var authoritative_at pgtype.Timestamptz
	err := row.Scan(&authoritative_at)
	return authoritative_at, err
}
