// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindWaveReadinessHeads = `-- name: BindWaveReadinessHeads :many
UPDATE wave_readiness
SET ready_window_id = $1,
    revision = revision + 1,
    updated_at = $2
WHERE wave_id = $3
    AND ready_window_id IS NULL
    AND NOT ready
    AND revision = 1
RETURNING ready_window_id,
    wave_id,
    roster_id,
    participant_id,
    ready,
    revision,
    ready_at,
    created_at,
    updated_at
`

type BindWaveReadinessHeadsParams struct {
	ReadyWindowID uuid.NullUUID
	UpdatedAt     pgtype.Timestamptz
	WaveID        uuid.UUID
}

func (q *Queries) BindWaveReadinessHeads(ctx context.Context, arg BindWaveReadinessHeadsParams) ([]WaveReadiness, error) {
	rows, err := q.db.Query(ctx, bindWaveReadinessHeads, arg.ReadyWindowID, arg.UpdatedAt, arg.WaveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaveReadiness{}
	for rows.Next() {
		var i WaveReadiness
		if err := rows.Scan(
			&i.ReadyWindowID,
			&i.WaveID,
			&i.RosterID,
			&i.ParticipantID,
			&i.Ready,
			&i.Revision,
			&i.ReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearWaveReadinessHeads = `-- name: ClearWaveReadinessHeads :many
UPDATE wave_readiness
SET ready = false,
    ready_at = NULL,
    revision = revision + 1,
    updated_at = $1
WHERE wave_id = $2
    AND ready_window_id = $3
    AND ready
RETURNING ready_window_id,
    wave_id,
    roster_id,
    participant_id,
    ready,
    revision,
    ready_at,
    created_at,
    updated_at
`

type ClearWaveReadinessHeadsParams struct {
	UpdatedAt     pgtype.Timestamptz
	WaveID        uuid.UUID
	ReadyWindowID uuid.NullUUID
}

func (q *Queries) ClearWaveReadinessHeads(ctx context.Context, arg ClearWaveReadinessHeadsParams) ([]WaveReadiness, error) {
	rows, err := q.db.Query(ctx, clearWaveReadinessHeads, arg.UpdatedAt, arg.WaveID, arg.ReadyWindowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaveReadiness{}
	for rows.Next() {
		var i WaveReadiness
		if err := rows.Scan(
			&i.ReadyWindowID,
			&i.WaveID,
			&i.RosterID,
			&i.ParticipantID,
			&i.Ready,
			&i.Revision,
			&i.ReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeReadyWindowCAS = `-- name: CloseReadyWindowCAS :one
UPDATE ready_windows
SET state = $1,
    consumed_at = NULL
WHERE id = $2
    AND wave_id = $3
    AND state = $4
RETURNING id,
    wave_id,
    roster_id,
    revision_id,
    state,
    opened_at,
    deadline,
    consumed_at,
    created_at
`

type CloseReadyWindowCASParams struct {
	NextState     string
	ID            uuid.UUID
	WaveID        uuid.UUID
	ExpectedState string
}

func (q *Queries) CloseReadyWindowCAS(ctx context.Context, arg CloseReadyWindowCASParams) (ReadyWindow, error) {
	row := q.db.QueryRow(ctx, closeReadyWindowCAS,
		arg.NextState,
		arg.ID,
		arg.WaveID,
		arg.ExpectedState,
	)
	var i ReadyWindow
	err := row.Scan(
		&i.ID,
		&i.WaveID,
		&i.RosterID,
		&i.RevisionID,
		&i.State,
		&i.OpenedAt,
		&i.Deadline,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const closeWaveCAS = `-- name: CloseWaveCAS :one
UPDATE waves
SET state = 'completed',
    revision_id = $1::UUID,
    revision = revision + 1,
    updated_at = $2::TIMESTAMPTZ,
    paused_at = NULL,
    closed_at = $2::TIMESTAMPTZ
WHERE id = $3
    AND tournament_id = $4
    AND revision = $5
    AND state = 'active'
RETURNING id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at,
    started_at,
    paused_at,
    closed_at
`

type CloseWaveCASParams struct {
	RevisionID       uuid.UUID
	ClosedAt         pgtype.Timestamptz
	ID               uuid.UUID
	TournamentID     uuid.UUID
	ExpectedRevision int64
}

// Closing a Wave is a new immutable result authority identity. Keep this CAS
// separate from transitions which intentionally retain the running identity.
func (q *Queries) CloseWaveCAS(ctx context.Context, arg CloseWaveCASParams) (Wave, error) {
	row := q.db.QueryRow(ctx, closeWaveCAS,
		arg.RevisionID,
		arg.ClosedAt,
		arg.ID,
		arg.TournamentID,
		arg.ExpectedRevision,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.RevisionID,
		&i.Revision,
		&i.State,
		&i.ReplacesWaveID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.PausedAt,
		&i.ClosedAt,
	)
	return i, err
}

const consumeReadyWindowCAS = `-- name: ConsumeReadyWindowCAS :one
UPDATE ready_windows
SET state = 'consumed',
    consumed_at = $1
WHERE id = $2
    AND wave_id = $3
    AND state = 'open'
    AND $1::TIMESTAMPTZ BETWEEN opened_at AND deadline
RETURNING id,
    wave_id,
    roster_id,
    revision_id,
    state,
    opened_at,
    deadline,
    consumed_at,
    created_at
`

type ConsumeReadyWindowCASParams struct {
	StartedAt pgtype.Timestamptz
	ID        uuid.UUID
	WaveID    uuid.UUID
}

func (q *Queries) ConsumeReadyWindowCAS(ctx context.Context, arg ConsumeReadyWindowCASParams) (ReadyWindow, error) {
	row := q.db.QueryRow(ctx, consumeReadyWindowCAS, arg.StartedAt, arg.ID, arg.WaveID)
	var i ReadyWindow
	err := row.Scan(
		&i.ID,
		&i.WaveID,
		&i.RosterID,
		&i.RevisionID,
		&i.State,
		&i.OpenedAt,
		&i.Deadline,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countWaveMembers = `-- name: CountWaveMembers :one
SELECT COUNT(*)
FROM wave_members
WHERE wave_id = $1
`

func (q *Queries) CountWaveMembers(ctx context.Context, waveID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWaveMembers, waveID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaveReadiness = `-- name: CountWaveReadiness :one
SELECT COUNT(*)
FROM wave_readiness
WHERE ready_window_id = $1
    AND ready
`

func (q *Queries) CountWaveReadiness(ctx context.Context, readyWindowID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWaveReadiness, readyWindowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInitialSeriesScoreHead = `-- name: CreateInitialSeriesScoreHead :one
WITH created_head AS (
    INSERT INTO series_score_heads (
        series_id,
        roster_id,
        current_revision_id,
        revision,
        updated_at
    )
    VALUES (
        $1,
        $2,
        $3,
        1,
        $4
    )
    RETURNING series_id,
        roster_id,
        current_revision_id
),
bound_series AS (
    UPDATE series
    SET current_score_revision_id = created_head.current_revision_id
    FROM created_head
    WHERE series.id = created_head.series_id
        AND series.roster_id = created_head.roster_id
        AND series.state = 'planned'
        AND series.current_score_revision_id IS NULL
        AND series.current_result_revision_id IS NULL
    RETURNING series.id
)
SELECT id
FROM bound_series
`

type CreateInitialSeriesScoreHeadParams struct {
	SeriesID               uuid.UUID
	RosterID               uuid.UUID
	InitialScoreRevisionID uuid.UUID
	UpdatedAt              pgtype.Timestamptz
}

// The initial score head is created with the planned Series and is the sole
// allowed planned-state score authority. Binding the Series pointer here
// prevents an orphan head or a mutable zero-score compatibility path.
func (q *Queries) CreateInitialSeriesScoreHead(ctx context.Context, arg CreateInitialSeriesScoreHeadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createInitialSeriesScoreHead,
		arg.SeriesID,
		arg.RosterID,
		arg.InitialScoreRevisionID,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createInitialSeriesScoreRevision = `-- name: CreateInitialSeriesScoreRevision :exec
INSERT INTO series_score_revisions (
    id,
    tournament_id,
    roster_id,
    series_id,
    result_event_id,
    previous_revision_id,
    revision_number,
    operation,
    command_id,
    actor_kind,
    actor_id,
    command_attempt_id,
    source_projection_revision_id,
    source_projection_revision,
    first_participant_wins,
    second_participant_wins,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NULL,
    NULL,
    1,
    'initialize',
    $5,
    'server',
    NULL,
    NULL,
    $6,
    $7,
    0,
    0,
    $8
)
`

type CreateInitialSeriesScoreRevisionParams struct {
	ID                         uuid.UUID
	TournamentID               uuid.UUID
	RosterID                   uuid.UUID
	SeriesID                   uuid.UUID
	CommandID                  uuid.UUID
	SourceProjectionRevisionID uuid.UUID
	SourceProjectionRevision   int64
	CreatedAt                  pgtype.Timestamptz
}

func (q *Queries) CreateInitialSeriesScoreRevision(ctx context.Context, arg CreateInitialSeriesScoreRevisionParams) error {
	_, err := q.db.Exec(ctx, createInitialSeriesScoreRevision,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.SeriesID,
		arg.CommandID,
		arg.SourceProjectionRevisionID,
		arg.SourceProjectionRevision,
		arg.CreatedAt,
	)
	return err
}

const createReadyWindow = `-- name: CreateReadyWindow :one
INSERT INTO ready_windows (
    id,
    wave_id,
    roster_id,
    revision_id,
    state,
    opened_at,
    deadline,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    'open',
    $5,
    $6,
    $5
)
RETURNING id,
    wave_id,
    roster_id,
    revision_id,
    state,
    opened_at,
    deadline,
    consumed_at,
    created_at
`

type CreateReadyWindowParams struct {
	ID         uuid.UUID
	WaveID     uuid.UUID
	RosterID   uuid.UUID
	RevisionID uuid.UUID
	OpenedAt   pgtype.Timestamptz
	Deadline   pgtype.Timestamptz
}

func (q *Queries) CreateReadyWindow(ctx context.Context, arg CreateReadyWindowParams) (ReadyWindow, error) {
	row := q.db.QueryRow(ctx, createReadyWindow,
		arg.ID,
		arg.WaveID,
		arg.RosterID,
		arg.RevisionID,
		arg.OpenedAt,
		arg.Deadline,
	)
	var i ReadyWindow
	err := row.Scan(
		&i.ID,
		&i.WaveID,
		&i.RosterID,
		&i.RevisionID,
		&i.State,
		&i.OpenedAt,
		&i.Deadline,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (
    id,
    tournament_id,
    roster_id,
    first_participant_id,
    second_participant_id,
    format,
    state,
    revision,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    'planned',
    1,
    $7,
    $7
)
RETURNING id,
    tournament_id,
    roster_id,
    first_participant_id,
    second_participant_id,
    format,
    state,
    first_participant_wins,
    second_participant_wins,
    winner_id,
    current_score_revision_id,
    current_result_revision_id,
    revision,
    created_at,
    updated_at,
    started_at,
    finished_at
`

type CreateSeriesParams struct {
	ID                  uuid.UUID
	TournamentID        uuid.UUID
	RosterID            uuid.UUID
	FirstParticipantID  uuid.UUID
	SecondParticipantID uuid.UUID
	Format              string
	CreatedAt           pgtype.Timestamptz
}

type CreateSeriesRow struct {
	ID                      uuid.UUID
	TournamentID            uuid.UUID
	RosterID                uuid.UUID
	FirstParticipantID      uuid.UUID
	SecondParticipantID     uuid.UUID
	Format                  string
	State                   string
	FirstParticipantWins    int16
	SecondParticipantWins   int16
	WinnerID                uuid.NullUUID
	CurrentScoreRevisionID  uuid.NullUUID
	CurrentResultRevisionID uuid.NullUUID
	Revision                int64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	StartedAt               pgtype.Timestamptz
	FinishedAt              pgtype.Timestamptz
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (CreateSeriesRow, error) {
	row := q.db.QueryRow(ctx, createSeries,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.FirstParticipantID,
		arg.SecondParticipantID,
		arg.Format,
		arg.CreatedAt,
	)
	var i CreateSeriesRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.FirstParticipantID,
		&i.SecondParticipantID,
		&i.Format,
		&i.State,
		&i.FirstParticipantWins,
		&i.SecondParticipantWins,
		&i.WinnerID,
		&i.CurrentScoreRevisionID,
		&i.CurrentResultRevisionID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createWave = `-- name: CreateWave :one
INSERT INTO waves (
    id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    1,
    'planned',
    $5,
    $6,
    $6
)
RETURNING id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at,
    started_at,
    paused_at,
    closed_at
`

type CreateWaveParams struct {
	ID             uuid.UUID
	TournamentID   uuid.UUID
	RosterID       uuid.UUID
	RevisionID     uuid.UUID
	ReplacesWaveID uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateWave(ctx context.Context, arg CreateWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, createWave,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.RevisionID,
		arg.ReplacesWaveID,
		arg.CreatedAt,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.RevisionID,
		&i.Revision,
		&i.State,
		&i.ReplacesWaveID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.PausedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createWaveMember = `-- name: CreateWaveMember :exec
INSERT INTO wave_members (
    wave_id,
    roster_id,
    participant_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateWaveMemberParams struct {
	WaveID        uuid.UUID
	RosterID      uuid.UUID
	ParticipantID uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateWaveMember(ctx context.Context, arg CreateWaveMemberParams) error {
	_, err := q.db.Exec(ctx, createWaveMember,
		arg.WaveID,
		arg.RosterID,
		arg.ParticipantID,
		arg.CreatedAt,
	)
	return err
}

const createWaveReadinessHead = `-- name: CreateWaveReadinessHead :one
INSERT INTO wave_readiness (
    wave_id,
    roster_id,
    participant_id,
    ready,
    revision,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    false,
    1,
    $4,
    $4
)
RETURNING ready_window_id,
    wave_id,
    roster_id,
    participant_id,
    ready,
    revision,
    ready_at,
    created_at,
    updated_at
`

type CreateWaveReadinessHeadParams struct {
	WaveID        uuid.UUID
	RosterID      uuid.UUID
	ParticipantID uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateWaveReadinessHead(ctx context.Context, arg CreateWaveReadinessHeadParams) (WaveReadiness, error) {
	row := q.db.QueryRow(ctx, createWaveReadinessHead,
		arg.WaveID,
		arg.RosterID,
		arg.ParticipantID,
		arg.CreatedAt,
	)
	var i WaveReadiness
	err := row.Scan(
		&i.ReadyWindowID,
		&i.WaveID,
		&i.RosterID,
		&i.ParticipantID,
		&i.Ready,
		&i.Revision,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWaveSeries = `-- name: CreateWaveSeries :exec
INSERT INTO wave_series (
    wave_id,
    tournament_id,
    roster_id,
    series_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateWaveSeriesParams struct {
	WaveID       uuid.UUID
	TournamentID uuid.UUID
	RosterID     uuid.UUID
	SeriesID     uuid.UUID
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateWaveSeries(ctx context.Context, arg CreateWaveSeriesParams) error {
	_, err := q.db.Exec(ctx, createWaveSeries,
		arg.WaveID,
		arg.TournamentID,
		arg.RosterID,
		arg.SeriesID,
		arg.CreatedAt,
	)
	return err
}

const getReadyWindow = `-- name: GetReadyWindow :one
SELECT id,
    wave_id,
    roster_id,
    revision_id,
    state,
    opened_at,
    deadline,
    consumed_at,
    created_at
FROM ready_windows
WHERE wave_id = $1
`

func (q *Queries) GetReadyWindow(ctx context.Context, waveID uuid.UUID) (ReadyWindow, error) {
	row := q.db.QueryRow(ctx, getReadyWindow, waveID)
	var i ReadyWindow
	err := row.Scan(
		&i.ID,
		&i.WaveID,
		&i.RosterID,
		&i.RevisionID,
		&i.State,
		&i.OpenedAt,
		&i.Deadline,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWave = `-- name: GetWave :one
SELECT id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at,
    started_at,
    paused_at,
    closed_at
FROM waves
WHERE id = $1
    AND tournament_id = $2
`

type GetWaveParams struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
}

func (q *Queries) GetWave(ctx context.Context, arg GetWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, getWave, arg.ID, arg.TournamentID)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.RevisionID,
		&i.Revision,
		&i.State,
		&i.ReplacesWaveID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.PausedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getWaveReadinessHead = `-- name: GetWaveReadinessHead :one
SELECT ready_window_id,
    wave_id,
    roster_id,
    participant_id,
    ready,
    revision,
    ready_at,
    created_at,
    updated_at
FROM wave_readiness
WHERE wave_id = $1
    AND participant_id = $2
`

type GetWaveReadinessHeadParams struct {
	WaveID        uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) GetWaveReadinessHead(ctx context.Context, arg GetWaveReadinessHeadParams) (WaveReadiness, error) {
	row := q.db.QueryRow(ctx, getWaveReadinessHead, arg.WaveID, arg.ParticipantID)
	var i WaveReadiness
	err := row.Scan(
		&i.ReadyWindowID,
		&i.WaveID,
		&i.RosterID,
		&i.ParticipantID,
		&i.Ready,
		&i.Revision,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWaveMembers = `-- name: ListWaveMembers :many
SELECT wave_id,
    roster_id,
    participant_id,
    created_at
FROM wave_members
WHERE wave_id = $1
ORDER BY participant_id
`

func (q *Queries) ListWaveMembers(ctx context.Context, waveID uuid.UUID) ([]WaveMember, error) {
	rows, err := q.db.Query(ctx, listWaveMembers, waveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaveMember{}
	for rows.Next() {
		var i WaveMember
		if err := rows.Scan(
			&i.WaveID,
			&i.RosterID,
			&i.ParticipantID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaveReadinessHeads = `-- name: ListWaveReadinessHeads :many
SELECT ready_window_id,
    wave_id,
    roster_id,
    participant_id,
    ready,
    revision,
    ready_at,
    created_at,
    updated_at
FROM wave_readiness
WHERE wave_id = $1
ORDER BY participant_id
`

func (q *Queries) ListWaveReadinessHeads(ctx context.Context, waveID uuid.UUID) ([]WaveReadiness, error) {
	rows, err := q.db.Query(ctx, listWaveReadinessHeads, waveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaveReadiness{}
	for rows.Next() {
		var i WaveReadiness
		if err := rows.Scan(
			&i.ReadyWindowID,
			&i.WaveID,
			&i.RosterID,
			&i.ParticipantID,
			&i.Ready,
			&i.Revision,
			&i.ReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaveSeries = `-- name: ListWaveSeries :many
SELECT series.id,
    series.tournament_id,
    series.roster_id,
    series.first_participant_id,
    series.second_participant_id,
    series.format,
    series.state,
    series.first_participant_wins,
    series.second_participant_wins,
    series.winner_id,
    series.current_score_revision_id,
    series.current_result_revision_id,
    series.revision,
    series.created_at,
    series.updated_at,
    series.started_at,
    series.finished_at,
    series.supersedes_series_id,
    series.superseded_by_series_id,
    series.superseded_at,
    series.supersession_reason,
    series.content_configuration_id,
    series.content_configuration_revision,
    series.category_mode,
    series.effective_categories
FROM wave_series AS wave_series
JOIN series AS series ON series.id = wave_series.series_id
WHERE wave_series.wave_id = $1
    AND series.state <> 'superseded'
ORDER BY series.id
`

func (q *Queries) ListWaveSeries(ctx context.Context, waveID uuid.UUID) ([]Series, error) {
	rows, err := q.db.Query(ctx, listWaveSeries, waveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RosterID,
			&i.FirstParticipantID,
			&i.SecondParticipantID,
			&i.Format,
			&i.State,
			&i.FirstParticipantWins,
			&i.SecondParticipantWins,
			&i.WinnerID,
			&i.CurrentScoreRevisionID,
			&i.CurrentResultRevisionID,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SupersedesSeriesID,
			&i.SupersededBySeriesID,
			&i.SupersededAt,
			&i.SupersessionReason,
			&i.ContentConfigurationID,
			&i.ContentConfigurationRevision,
			&i.CategoryMode,
			&i.EffectiveCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWaveMemberReadyCAS = `-- name: MarkWaveMemberReadyCAS :one
UPDATE wave_readiness
SET ready = true,
    ready_at = $1,
    revision = revision + 1,
    updated_at = $1
WHERE wave_id = $2
    AND participant_id = $3
    AND ready_window_id = $4
    AND revision = $5
    AND NOT ready
RETURNING ready_window_id,
    wave_id,
    roster_id,
    participant_id,
    ready,
    revision,
    ready_at,
    created_at,
    updated_at
`

type MarkWaveMemberReadyCASParams struct {
	ReadyAt          pgtype.Timestamptz
	WaveID           uuid.UUID
	ParticipantID    uuid.UUID
	ReadyWindowID    uuid.NullUUID
	ExpectedRevision int64
}

func (q *Queries) MarkWaveMemberReadyCAS(ctx context.Context, arg MarkWaveMemberReadyCASParams) (WaveReadiness, error) {
	row := q.db.QueryRow(ctx, markWaveMemberReadyCAS,
		arg.ReadyAt,
		arg.WaveID,
		arg.ParticipantID,
		arg.ReadyWindowID,
		arg.ExpectedRevision,
	)
	var i WaveReadiness
	err := row.Scan(
		&i.ReadyWindowID,
		&i.WaveID,
		&i.RosterID,
		&i.ParticipantID,
		&i.Ready,
		&i.Revision,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWaveReadinessCAS = `-- name: MarkWaveReadinessCAS :one
UPDATE waves
SET state = CASE
        WHEN $1::BOOLEAN THEN 'ready'
        ELSE 'ready_window_open'
    END,
    revision = revision + 1,
    updated_at = $2
WHERE id = $3
    AND revision = $4
    AND state IN ('ready_window_open', 'ready')
RETURNING id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at,
    started_at,
    paused_at,
    closed_at
`

type MarkWaveReadinessCASParams struct {
	AllReady         bool
	UpdatedAt        pgtype.Timestamptz
	ID               uuid.UUID
	ExpectedRevision int64
}

func (q *Queries) MarkWaveReadinessCAS(ctx context.Context, arg MarkWaveReadinessCASParams) (Wave, error) {
	row := q.db.QueryRow(ctx, markWaveReadinessCAS,
		arg.AllReady,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.RevisionID,
		&i.Revision,
		&i.State,
		&i.ReplacesWaveID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.PausedAt,
		&i.ClosedAt,
	)
	return i, err
}

const openWaveReadyWindowCAS = `-- name: OpenWaveReadyWindowCAS :one
UPDATE waves
SET state = 'ready_window_open',
    revision = revision + 1,
    updated_at = $1
WHERE id = $2
    AND revision = $3
    AND state = 'planned'
RETURNING id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at,
    started_at,
    paused_at,
    closed_at
`

type OpenWaveReadyWindowCASParams struct {
	OpenedAt         pgtype.Timestamptz
	ID               uuid.UUID
	ExpectedRevision int64
}

func (q *Queries) OpenWaveReadyWindowCAS(ctx context.Context, arg OpenWaveReadyWindowCASParams) (Wave, error) {
	row := q.db.QueryRow(ctx, openWaveReadyWindowCAS, arg.OpenedAt, arg.ID, arg.ExpectedRevision)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.RevisionID,
		&i.Revision,
		&i.State,
		&i.ReplacesWaveID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.PausedAt,
		&i.ClosedAt,
	)
	return i, err
}

const startWaveCAS = `-- name: StartWaveCAS :one
UPDATE waves
SET state = 'active',
    revision = revision + 1,
    updated_at = $1,
    started_at = $1
WHERE id = $2
    AND tournament_id = $3
    AND revision = $4
    AND state = 'ready'
    AND started_at IS NULL
RETURNING id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at,
    started_at,
    paused_at,
    closed_at
`

type StartWaveCASParams struct {
	StartedAt        pgtype.Timestamptz
	ID               uuid.UUID
	TournamentID     uuid.UUID
	ExpectedRevision int64
}

func (q *Queries) StartWaveCAS(ctx context.Context, arg StartWaveCASParams) (Wave, error) {
	row := q.db.QueryRow(ctx, startWaveCAS,
		arg.StartedAt,
		arg.ID,
		arg.TournamentID,
		arg.ExpectedRevision,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.RevisionID,
		&i.Revision,
		&i.State,
		&i.ReplacesWaveID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.PausedAt,
		&i.ClosedAt,
	)
	return i, err
}

const transitionWaveCAS = `-- name: TransitionWaveCAS :one
UPDATE waves
SET state = $1,
    revision = revision + 1,
    updated_at = $2,
    paused_at = $3::TIMESTAMPTZ,
    closed_at = $4::TIMESTAMPTZ
WHERE id = $5
    AND tournament_id = $6
    AND revision = $7
    AND state = $8
RETURNING id,
    tournament_id,
    roster_id,
    revision_id,
    revision,
    state,
    replaces_wave_id,
    created_at,
    updated_at,
    started_at,
    paused_at,
    closed_at
`

type TransitionWaveCASParams struct {
	NextState        string
	UpdatedAt        pgtype.Timestamptz
	PausedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	ID               uuid.UUID
	TournamentID     uuid.UUID
	ExpectedRevision int64
	ExpectedState    string
}

func (q *Queries) TransitionWaveCAS(ctx context.Context, arg TransitionWaveCASParams) (Wave, error) {
	row := q.db.QueryRow(ctx, transitionWaveCAS,
		arg.NextState,
		arg.UpdatedAt,
		arg.PausedAt,
		arg.ClosedAt,
		arg.ID,
		arg.TournamentID,
		arg.ExpectedRevision,
		arg.ExpectedState,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.RevisionID,
		&i.Revision,
		&i.State,
		&i.ReplacesWaveID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.PausedAt,
		&i.ClosedAt,
	)
	return i, err
}
