// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const topLeaderboardStats = `-- name: TopLeaderboardStats :many
WITH base_stats AS (
  SELECT d.winner_id AS player_id,
    COUNT(*)::INT AS wins,
    FLOOR(
      AVG(
        (
          EXTRACT(
            EPOCH
            FROM dpt.solved_at - d.started_at
          ) * 1000
        )::BIGINT
      )
    )::BIGINT AS average_solve_time_ms
  FROM duels d
    JOIN duel_player_tasks dpt ON dpt.duel_id = d.id
      AND dpt.player_id = d.winner_id
      AND dpt.solved = TRUE
      AND dpt.solved_at IS NOT NULL
  WHERE d.status = 'finished'
    AND d.winner_id IS NOT NULL
  GROUP BY d.winner_id
),
effective_stats AS (
  SELECT p.id AS player_id,
    p.username,
    COALESCE(o.wins, b.wins, 0)::INT AS wins,
    COALESCE(o.average_solve_time_ms, b.average_solve_time_ms, 0)::BIGINT AS average_solve_time_ms
  FROM players p
    LEFT JOIN base_stats b ON b.player_id = p.id
    LEFT JOIN player_leaderboard_overrides o ON o.player_id = p.id
  WHERE p.deleted_at IS NULL
)
SELECT player_id,
  username,
  wins,
  average_solve_time_ms
FROM effective_stats
WHERE wins > 0
ORDER BY wins DESC,
  average_solve_time_ms ASC,
  username ASC
LIMIT $1
`

type TopLeaderboardStatsRow struct {
	PlayerID           uuid.UUID
	Username           string
	Wins               int32
	AverageSolveTimeMs int64
}

func (q *Queries) TopLeaderboardStats(ctx context.Context, limit int32) ([]TopLeaderboardStatsRow, error) {
	rows, err := q.db.Query(ctx, topLeaderboardStats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopLeaderboardStatsRow{}
	for rows.Next() {
		var i TopLeaderboardStatsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Username,
			&i.Wins,
			&i.AverageSolveTimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
