// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participant_connection.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeExpiredParticipantConnectionLease = `-- name: CloseExpiredParticipantConnectionLease :one
UPDATE participant_connection_leases AS lease
SET state = 'disconnected',
    disconnected_at = GREATEST(clock_timestamp(), lease.connected_at),
    updated_at = GREATEST(clock_timestamp(), lease.updated_at + INTERVAL '1 microsecond'),
    revision = lease.revision + 1
WHERE lease.tournament_id = $1
    AND lease.roster_id = $2
    AND lease.participant_id = $3
    AND lease.player_id = $4
    AND lease.id = $5
    AND lease.revision = $6
    AND lease.connection_id = $7
    AND lease.connection_generation = $8
    AND EXISTS (
        SELECT 1
        FROM execution_authority_leases AS candidate
        WHERE candidate.tournament_id = lease.tournament_id
            AND candidate.holder_id = $9
            AND candidate.lease_id = $10
            AND candidate.epoch = $11
            AND candidate.process_kind = 'authority'
            AND candidate.expires_at <= clock_timestamp()
            AND NOT EXISTS (
                SELECT 1
                FROM execution_authority_leases AS newer_candidate
                WHERE newer_candidate.tournament_id = candidate.tournament_id
                    AND newer_candidate.holder_id = candidate.holder_id
                    AND newer_candidate.lease_id = candidate.lease_id
                    AND newer_candidate.epoch = candidate.epoch
                    AND newer_candidate.revision > candidate.revision
            )
    )
    AND EXISTS (
        SELECT 1
        FROM execution_authority_leases AS current_auth
        WHERE current_auth.tournament_id = lease.tournament_id
            AND current_auth.holder_id = $12
            AND current_auth.lease_id = $13
            AND current_auth.epoch = $14
            AND current_auth.process_kind = 'authority'
            AND current_auth.renewed_at <= clock_timestamp()
            AND clock_timestamp() < current_auth.expires_at
            AND (
                current_auth.holder_id IS DISTINCT FROM $9
                OR current_auth.lease_id IS DISTINCT FROM $10
                OR current_auth.epoch IS DISTINCT FROM $11
            )
            AND NOT EXISTS (
                SELECT 1
                FROM execution_authority_leases AS newer_current
                WHERE newer_current.tournament_id = current_auth.tournament_id
                    AND newer_current.revision > current_auth.revision
            )
    )
    AND lease.state = 'active'
RETURNING lease.id,
    lease.tournament_id,
    lease.roster_id,
    lease.participant_id,
    lease.player_id,
    lease.connection_id,
    lease.connection_generation,
    lease.assignment_id,
    lease.series_id,
    lease.game_attempt_id,
    lease.state,
    lease.revision,
    lease.connected_at,
    lease.disconnected_at,
    lease.updated_at,
    lease.authority_holder_id,
    lease.authority_lease_id,
    lease.authority_epoch
`

type CloseExpiredParticipantConnectionLeaseParams struct {
	TournamentID             uuid.UUID
	RosterID                 uuid.UUID
	ParticipantID            uuid.UUID
	PlayerID                 uuid.UUID
	ID                       uuid.UUID
	ExpectedRevision         int64
	ConnectionID             uuid.UUID
	ConnectionGeneration     int64
	AuthorityHolderID        uuid.UUID
	AuthorityLeaseID         uuid.UUID
	AuthorityEpoch           int64
	CurrentAuthorityHolderID uuid.UUID
	CurrentAuthorityLeaseID  uuid.UUID
	CurrentAuthorityEpoch    int64
}

// A recovery close is a second CAS fence: the exact candidate revision and
// socket fence must still be active, its stamped authority must have expired,
// and the caller must now own a different live execution authority.  The
// participant identity and active lease set are locked by the adapter before
// this statement is executed.
func (q *Queries) CloseExpiredParticipantConnectionLease(ctx context.Context, arg CloseExpiredParticipantConnectionLeaseParams) (ParticipantConnectionLease, error) {
	row := q.db.QueryRow(ctx, closeExpiredParticipantConnectionLease,
		arg.TournamentID,
		arg.RosterID,
		arg.ParticipantID,
		arg.PlayerID,
		arg.ID,
		arg.ExpectedRevision,
		arg.ConnectionID,
		arg.ConnectionGeneration,
		arg.AuthorityHolderID,
		arg.AuthorityLeaseID,
		arg.AuthorityEpoch,
		arg.CurrentAuthorityHolderID,
		arg.CurrentAuthorityLeaseID,
		arg.CurrentAuthorityEpoch,
	)
	var i ParticipantConnectionLease
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.ParticipantID,
		&i.PlayerID,
		&i.ConnectionID,
		&i.ConnectionGeneration,
		&i.AssignmentID,
		&i.SeriesID,
		&i.GameAttemptID,
		&i.State,
		&i.Revision,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.UpdatedAt,
		&i.AuthorityHolderID,
		&i.AuthorityLeaseID,
		&i.AuthorityEpoch,
	)
	return i, err
}

const closeParticipantConnectionLease = `-- name: CloseParticipantConnectionLease :one
UPDATE participant_connection_leases AS lease
SET state = 'disconnected',
    disconnected_at = GREATEST(clock_timestamp(), lease.connected_at),
    updated_at = GREATEST(clock_timestamp(), lease.updated_at + INTERVAL '1 microsecond'),
    revision = lease.revision + 1
WHERE lease.tournament_id = $1
    AND lease.roster_id = $2
    AND lease.participant_id = $3
    AND lease.player_id = $4
    AND lease.connection_id = $5
    AND lease.connection_generation = $6
    AND lease.authority_holder_id = $7
    AND lease.authority_lease_id = $8
    AND lease.authority_epoch = $9
    AND lease.state = 'active'
RETURNING lease.id,
    lease.tournament_id,
    lease.roster_id,
    lease.participant_id,
    lease.player_id,
    lease.connection_id,
    lease.connection_generation,
    lease.assignment_id,
    lease.series_id,
    lease.game_attempt_id,
    lease.state,
    lease.revision,
    lease.connected_at,
    lease.disconnected_at,
    lease.updated_at,
    lease.authority_holder_id,
    lease.authority_lease_id,
    lease.authority_epoch
`

type CloseParticipantConnectionLeaseParams struct {
	TournamentID         uuid.UUID
	RosterID             uuid.UUID
	ParticipantID        uuid.UUID
	PlayerID             uuid.UUID
	ConnectionID         uuid.UUID
	ConnectionGeneration int64
	AuthorityHolderID    uuid.NullUUID
	AuthorityLeaseID     uuid.NullUUID
	AuthorityEpoch       *int64
}

// The update is deliberately fenced by the complete server-resolved
// identity.  A stale generation or wrong participant updates no row.
func (q *Queries) CloseParticipantConnectionLease(ctx context.Context, arg CloseParticipantConnectionLeaseParams) (ParticipantConnectionLease, error) {
	row := q.db.QueryRow(ctx, closeParticipantConnectionLease,
		arg.TournamentID,
		arg.RosterID,
		arg.ParticipantID,
		arg.PlayerID,
		arg.ConnectionID,
		arg.ConnectionGeneration,
		arg.AuthorityHolderID,
		arg.AuthorityLeaseID,
		arg.AuthorityEpoch,
	)
	var i ParticipantConnectionLease
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.ParticipantID,
		&i.PlayerID,
		&i.ConnectionID,
		&i.ConnectionGeneration,
		&i.AssignmentID,
		&i.SeriesID,
		&i.GameAttemptID,
		&i.State,
		&i.Revision,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.UpdatedAt,
		&i.AuthorityHolderID,
		&i.AuthorityLeaseID,
		&i.AuthorityEpoch,
	)
	return i, err
}

const countParticipantConnectionLeases = `-- name: CountParticipantConnectionLeases :one
SELECT COUNT(*)::BIGINT AS active_lease_count
FROM participant_connection_leases AS lease
WHERE lease.tournament_id = $1
    AND lease.roster_id = $2
    AND lease.participant_id = $3
    AND lease.state = 'active'
    AND EXISTS (
        SELECT 1
        FROM realtime_subscribers AS subscriber
        WHERE subscriber.tournament_id = lease.tournament_id
            AND subscriber.role = 'participant'
            AND subscriber.principal_id = lease.player_id
            AND subscriber.connection_id = lease.connection_id
            AND subscriber.connection_generation = lease.connection_generation
            AND subscriber.closed_at IS NULL
    )
`

type CountParticipantConnectionLeasesParams struct {
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) CountParticipantConnectionLeases(ctx context.Context, arg CountParticipantConnectionLeasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipantConnectionLeases, arg.TournamentID, arg.RosterID, arg.ParticipantID)
	var active_lease_count int64
	err := row.Scan(&active_lease_count)
	return active_lease_count, err
}

const findParticipantConnectionLeaseByFence = `-- name: FindParticipantConnectionLeaseByFence :one
SELECT lease.id,
    lease.tournament_id,
    lease.roster_id,
    lease.participant_id,
    lease.player_id,
    lease.connection_id,
    lease.connection_generation,
    lease.assignment_id,
    lease.series_id,
    lease.game_attempt_id,
    lease.state,
    lease.revision,
    lease.connected_at,
    lease.disconnected_at,
    lease.updated_at,
    lease.authority_holder_id,
    lease.authority_lease_id,
    lease.authority_epoch
FROM participant_connection_leases AS lease
WHERE lease.connection_id = $1
    AND lease.connection_generation = $2
FOR UPDATE
`

type FindParticipantConnectionLeaseByFenceParams struct {
	ConnectionID         uuid.UUID
	ConnectionGeneration int64
}

func (q *Queries) FindParticipantConnectionLeaseByFence(ctx context.Context, arg FindParticipantConnectionLeaseByFenceParams) (ParticipantConnectionLease, error) {
	row := q.db.QueryRow(ctx, findParticipantConnectionLeaseByFence, arg.ConnectionID, arg.ConnectionGeneration)
	var i ParticipantConnectionLease
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.ParticipantID,
		&i.PlayerID,
		&i.ConnectionID,
		&i.ConnectionGeneration,
		&i.AssignmentID,
		&i.SeriesID,
		&i.GameAttemptID,
		&i.State,
		&i.Revision,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.UpdatedAt,
		&i.AuthorityHolderID,
		&i.AuthorityLeaseID,
		&i.AuthorityEpoch,
	)
	return i, err
}

const insertParticipantConnectionLease = `-- name: InsertParticipantConnectionLease :one
INSERT INTO participant_connection_leases (
    id,
    tournament_id,
    roster_id,
    participant_id,
    player_id,
    connection_id,
    connection_generation,
    assignment_id,
    series_id,
    game_attempt_id,
    authority_holder_id,
    authority_lease_id,
    authority_epoch,
    state,
    revision,
    connected_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::UUID,
    $9::UUID,
    $10::UUID,
    $11,
    $12,
    $13,
    'active',
    1,
    transaction_timestamp(),
    transaction_timestamp()
)
ON CONFLICT (connection_id, connection_generation) DO NOTHING
RETURNING id,
    tournament_id,
    roster_id,
    participant_id,
    player_id,
    connection_id,
    connection_generation,
    assignment_id,
    series_id,
    game_attempt_id,
    state,
    revision,
    connected_at,
    disconnected_at,
    updated_at,
    authority_holder_id,
    authority_lease_id,
    authority_epoch
`

type InsertParticipantConnectionLeaseParams struct {
	ID                   uuid.UUID
	TournamentID         uuid.UUID
	RosterID             uuid.UUID
	ParticipantID        uuid.UUID
	PlayerID             uuid.UUID
	ConnectionID         uuid.UUID
	ConnectionGeneration int64
	AssignmentID         uuid.NullUUID
	SeriesID             uuid.NullUUID
	GameAttemptID        uuid.NullUUID
	AuthorityHolderID    uuid.NullUUID
	AuthorityLeaseID     uuid.NullUUID
	AuthorityEpoch       *int64
}

func (q *Queries) InsertParticipantConnectionLease(ctx context.Context, arg InsertParticipantConnectionLeaseParams) (ParticipantConnectionLease, error) {
	row := q.db.QueryRow(ctx, insertParticipantConnectionLease,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.ParticipantID,
		arg.PlayerID,
		arg.ConnectionID,
		arg.ConnectionGeneration,
		arg.AssignmentID,
		arg.SeriesID,
		arg.GameAttemptID,
		arg.AuthorityHolderID,
		arg.AuthorityLeaseID,
		arg.AuthorityEpoch,
	)
	var i ParticipantConnectionLease
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.ParticipantID,
		&i.PlayerID,
		&i.ConnectionID,
		&i.ConnectionGeneration,
		&i.AssignmentID,
		&i.SeriesID,
		&i.GameAttemptID,
		&i.State,
		&i.Revision,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.UpdatedAt,
		&i.AuthorityHolderID,
		&i.AuthorityLeaseID,
		&i.AuthorityEpoch,
	)
	return i, err
}

const listParticipantConnectionLeaseTournaments = `-- name: ListParticipantConnectionLeaseTournaments :many
SELECT DISTINCT lease.tournament_id
FROM participant_connection_leases AS lease
WHERE lease.state = 'active'
    AND lease.authority_holder_id IS NOT NULL
    AND lease.authority_lease_id IS NOT NULL
    AND lease.authority_epoch IS NOT NULL
ORDER BY lease.tournament_id
`

// The reaper renews locally owned authorities before checking expiry.  This
// keeps a quiet but live process from orphaning its own long-lived sockets.
func (q *Queries) ListParticipantConnectionLeaseTournaments(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listParticipantConnectionLeaseTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var tournament_id uuid.UUID
		if err := rows.Scan(&tournament_id); err != nil {
			return nil, err
		}
		items = append(items, tournament_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantConnectionRecoveryCandidates = `-- name: ListParticipantConnectionRecoveryCandidates :many
WITH owner_authority AS (
    SELECT DISTINCT ON (authority.tournament_id, authority.holder_id, authority.lease_id, authority.epoch)
        authority.tournament_id,
        authority.holder_id,
        authority.lease_id,
        authority.epoch,
        authority.expires_at
    FROM execution_authority_leases AS authority
    WHERE authority.process_kind = 'authority'
    ORDER BY authority.tournament_id,
        authority.holder_id,
        authority.lease_id,
        authority.epoch,
        authority.revision DESC
)
SELECT lease.id,
    lease.tournament_id,
    lease.roster_id,
    lease.participant_id,
    lease.player_id,
    lease.connection_id,
    lease.connection_generation,
    lease.assignment_id,
    lease.series_id,
    lease.game_attempt_id,
    lease.state,
    lease.revision,
    lease.connected_at,
    lease.disconnected_at,
    lease.updated_at,
    lease.authority_holder_id,
    lease.authority_lease_id,
    lease.authority_epoch
FROM participant_connection_leases AS lease
JOIN owner_authority
    ON owner_authority.tournament_id = lease.tournament_id
    AND owner_authority.holder_id = lease.authority_holder_id
    AND owner_authority.lease_id = lease.authority_lease_id
    AND owner_authority.epoch = lease.authority_epoch
WHERE lease.state = 'active'
    AND lease.authority_holder_id IS NOT NULL
    AND lease.authority_lease_id IS NOT NULL
    AND lease.authority_epoch IS NOT NULL
    AND owner_authority.expires_at <= clock_timestamp()
ORDER BY lease.tournament_id,
    lease.roster_id,
    lease.participant_id,
    lease.id
LIMIT $1::INT
`

// Recovery discovery is deliberately owner-bound.  The migration backfills
// v21 rows and rejects future ownerless writes, while these predicates keep
// the query fail-closed if storage invariants are ever violated.
func (q *Queries) ListParticipantConnectionRecoveryCandidates(ctx context.Context, limitCount int32) ([]ParticipantConnectionLease, error) {
	rows, err := q.db.Query(ctx, listParticipantConnectionRecoveryCandidates, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParticipantConnectionLease{}
	for rows.Next() {
		var i ParticipantConnectionLease
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RosterID,
			&i.ParticipantID,
			&i.PlayerID,
			&i.ConnectionID,
			&i.ConnectionGeneration,
			&i.AssignmentID,
			&i.SeriesID,
			&i.GameAttemptID,
			&i.State,
			&i.Revision,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.UpdatedAt,
			&i.AuthorityHolderID,
			&i.AuthorityLeaseID,
			&i.AuthorityEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipantConnectionActiveGame = `-- name: LockParticipantConnectionActiveGame :many
SELECT assignment.id AS assignment_id,
    assignment.attempt_id AS game_attempt_id,
    assignment.series_id,
    series.state AS series_state,
    attempt.state AS game_state,
    snapshot.kind AS task_kind,
    presence.id AS presence_id,
    presence.state AS presence_state,
    presence.presence_epoch,
    presence.revision AS presence_revision
FROM wave_series AS membership
JOIN series
    ON series.id = membership.series_id
    AND series.tournament_id = membership.tournament_id
    AND series.roster_id = membership.roster_id
JOIN game_attempts AS attempt
    ON attempt.series_id = series.id
    AND attempt.roster_id = series.roster_id
JOIN assignments AS assignment
    ON assignment.attempt_id = attempt.id
    AND assignment.series_id = series.id
    AND assignment.roster_id = series.roster_id
    AND assignment.state = 'active'
JOIN task_snapshots AS snapshot
    ON snapshot.id = assignment.snapshot_id
    AND snapshot.reservation_id = assignment.reservation_id
    AND snapshot.task_id = assignment.task_id
    AND snapshot.task_version = assignment.task_version
JOIN task_delivery_receipts AS receipt
    ON receipt.assignment_id = assignment.id
    AND receipt.attempt_id = assignment.attempt_id
    AND receipt.roster_id = assignment.roster_id
    AND receipt.participant_id = $1
    AND receipt.snapshot_id = assignment.snapshot_id
JOIN presence_states AS presence
    ON presence.tournament_id = membership.tournament_id
    AND presence.roster_id = membership.roster_id
    AND presence.series_id = series.id
    AND presence.participant_id = $1
WHERE membership.wave_id = $2
    AND membership.tournament_id = $3
    AND membership.roster_id = $4
    AND $1 IN (series.first_participant_id, series.second_participant_id)
    AND series.state = 'active'
    AND attempt.state = 'active'
    AND snapshot.kind = 'normal'
    AND presence.state = 'connected'
ORDER BY assignment.series_id, assignment.attempt_id, assignment.id, presence.id
FOR UPDATE OF membership, series, attempt, assignment, snapshot, receipt, presence
`

type LockParticipantConnectionActiveGameParams struct {
	ParticipantID uuid.UUID
	WaveID        uuid.UUID
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
}

type LockParticipantConnectionActiveGameRow struct {
	AssignmentID     uuid.UUID
	GameAttemptID    uuid.UUID
	SeriesID         uuid.UUID
	SeriesState      string
	GameState        string
	TaskKind         string
	PresenceID       uuid.UUID
	PresenceState    string
	PresenceEpoch    int64
	PresenceRevision int64
}

// Only a delivered, normal task in an active game can produce ordinary game
// disconnect.  All joins are identity-bound and locked in graph order.
func (q *Queries) LockParticipantConnectionActiveGame(ctx context.Context, arg LockParticipantConnectionActiveGameParams) ([]LockParticipantConnectionActiveGameRow, error) {
	rows, err := q.db.Query(ctx, lockParticipantConnectionActiveGame,
		arg.ParticipantID,
		arg.WaveID,
		arg.TournamentID,
		arg.RosterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockParticipantConnectionActiveGameRow{}
	for rows.Next() {
		var i LockParticipantConnectionActiveGameRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.GameAttemptID,
			&i.SeriesID,
			&i.SeriesState,
			&i.GameState,
			&i.TaskKind,
			&i.PresenceID,
			&i.PresenceState,
			&i.PresenceEpoch,
			&i.PresenceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipantConnectionCurrentSubscriber = `-- name: LockParticipantConnectionCurrentSubscriber :many
SELECT subscriber.id
FROM realtime_subscribers AS subscriber
WHERE subscriber.tournament_id = $1
    AND subscriber.role = 'participant'
    AND subscriber.principal_id = $2
    AND subscriber.connection_id = $3
    AND subscriber.connection_generation = $4
    AND subscriber.closed_at IS NULL
FOR UPDATE OF subscriber
`

type LockParticipantConnectionCurrentSubscriberParams struct {
	TournamentID         uuid.UUID
	PlayerID             uuid.NullUUID
	ConnectionID         uuid.UUID
	ConnectionGeneration int64
}

// A realtime subscriber row is the mutable head of one participant socket
// fence.  Locking the exact open row before a lease close prevents a resume
// takeover from changing the fence between the stale check and the action
// decision.  The durable lease is still closed even when this query returns
// no row, preserving historical close evidence without allowing a superseded
// socket to mutate current tournament state.
func (q *Queries) LockParticipantConnectionCurrentSubscriber(ctx context.Context, arg LockParticipantConnectionCurrentSubscriberParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockParticipantConnectionCurrentSubscriber,
		arg.TournamentID,
		arg.PlayerID,
		arg.ConnectionID,
		arg.ConnectionGeneration,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipantConnectionIdentity = `-- name: LockParticipantConnectionIdentity :one

SELECT tournament.id AS tournament_id,
    tournament.state AS tournament_state,
    roster.id AS roster_id,
    participant.id AS participant_id,
    participant.player_id AS player_id
FROM tournaments AS tournament
JOIN rosters AS roster
    ON roster.tournament_id = tournament.id
JOIN participants AS participant
    ON participant.roster_id = roster.id
    AND participant.player_id = $1
WHERE tournament.id = $2
FOR UPDATE OF tournament, roster, participant
`

type LockParticipantConnectionIdentityParams struct {
	PlayerID     uuid.UUID
	TournamentID uuid.UUID
}

type LockParticipantConnectionIdentityRow struct {
	TournamentID    uuid.UUID
	TournamentState string
	RosterID        uuid.UUID
	ParticipantID   uuid.UUID
	PlayerID        uuid.UUID
}

// The connection lifecycle always locks the participant identity first.  Every
// subsequent query is scoped by that identity so a socket can never select a
// different roster, wave, assignment, or game by accident.
func (q *Queries) LockParticipantConnectionIdentity(ctx context.Context, arg LockParticipantConnectionIdentityParams) (LockParticipantConnectionIdentityRow, error) {
	row := q.db.QueryRow(ctx, lockParticipantConnectionIdentity, arg.PlayerID, arg.TournamentID)
	var i LockParticipantConnectionIdentityRow
	err := row.Scan(
		&i.TournamentID,
		&i.TournamentState,
		&i.RosterID,
		&i.ParticipantID,
		&i.PlayerID,
	)
	return i, err
}

const lockParticipantConnectionLeases = `-- name: LockParticipantConnectionLeases :many
SELECT lease.id,
    lease.tournament_id,
    lease.roster_id,
    lease.participant_id,
    lease.player_id,
    lease.connection_id,
    lease.connection_generation,
    lease.assignment_id,
    lease.series_id,
    lease.game_attempt_id,
    lease.state,
    lease.revision,
    lease.connected_at,
    lease.disconnected_at,
    lease.updated_at,
    lease.authority_holder_id,
    lease.authority_lease_id,
    lease.authority_epoch
FROM participant_connection_leases AS lease
WHERE lease.tournament_id = $1
    AND lease.roster_id = $2
    AND lease.participant_id = $3
    AND lease.state = 'active'
ORDER BY lease.connection_id, lease.connection_generation, lease.id
FOR UPDATE OF lease
`

type LockParticipantConnectionLeasesParams struct {
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
	ParticipantID uuid.UUID
}

// Locks are ordered by the immutable connection fence.  The participant row
// is already locked by the identity query, making this lock set the stable
// serialization point for multi-tab open/close and active-count decisions.
func (q *Queries) LockParticipantConnectionLeases(ctx context.Context, arg LockParticipantConnectionLeasesParams) ([]ParticipantConnectionLease, error) {
	rows, err := q.db.Query(ctx, lockParticipantConnectionLeases, arg.TournamentID, arg.RosterID, arg.ParticipantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParticipantConnectionLease{}
	for rows.Next() {
		var i ParticipantConnectionLease
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RosterID,
			&i.ParticipantID,
			&i.PlayerID,
			&i.ConnectionID,
			&i.ConnectionGeneration,
			&i.AssignmentID,
			&i.SeriesID,
			&i.GameAttemptID,
			&i.State,
			&i.Revision,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.UpdatedAt,
			&i.AuthorityHolderID,
			&i.AuthorityLeaseID,
			&i.AuthorityEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipantConnectionOperatorPause = `-- name: LockParticipantConnectionOperatorPause :many
SELECT pause.id AS pause_id,
    pause.tournament_id,
    pause.roster_id,
    pause.scope_id AS wave_id,
    pause.revision AS pause_revision,
    command.result_document AS pause_document,
    assignment.id AS assignment_id,
    assignment.attempt_id AS game_attempt_id,
    assignment.series_id,
    presence.id AS presence_id,
    presence.series_id AS presence_series_id,
    presence.participant_id,
    presence.state AS presence_state,
    presence.presence_epoch,
    presence.revision AS presence_revision
FROM pauses AS pause
LEFT JOIN wave_control_commands AS command
    ON command.tournament_id = pause.tournament_id
    AND command.roster_id = pause.roster_id
    AND command.wave_id = pause.wave_id
    AND command.action = 'pause'
    AND command.executed_at = pause.started_at
JOIN wave_series AS membership
    ON membership.wave_id = pause.wave_id
    AND membership.tournament_id = pause.tournament_id
    AND membership.roster_id = pause.roster_id
JOIN series
    ON series.id = membership.series_id
    AND series.tournament_id = membership.tournament_id
    AND series.roster_id = membership.roster_id
JOIN game_attempts AS attempt
    ON attempt.series_id = series.id
    AND attempt.roster_id = series.roster_id
JOIN assignments AS assignment
    ON assignment.attempt_id = attempt.id
    AND assignment.series_id = series.id
    AND assignment.roster_id = series.roster_id
    AND assignment.state = 'active'
JOIN task_snapshots AS snapshot
    ON snapshot.id = assignment.snapshot_id
    AND snapshot.reservation_id = assignment.reservation_id
    AND snapshot.task_id = assignment.task_id
    AND snapshot.task_version = assignment.task_version
    AND snapshot.kind = 'normal'
JOIN task_delivery_receipts AS receipt
    ON receipt.assignment_id = assignment.id
    AND receipt.attempt_id = assignment.attempt_id
    AND receipt.roster_id = assignment.roster_id
    AND receipt.participant_id = $1
    AND receipt.snapshot_id = assignment.snapshot_id
JOIN presence_states AS presence
    ON presence.tournament_id = pause.tournament_id
    AND presence.roster_id = pause.roster_id
    AND presence.series_id = membership.series_id
    AND presence.participant_id = $1
WHERE pause.tournament_id = $2
    AND pause.roster_id = $3
    AND pause.wave_id = $4
    AND pause.scope_kind = 'wave'
    AND pause.reason = 'operator'
    AND pause.state = 'active'
    AND (series.state = 'technical_pause' OR (
        series.state = 'active'
        AND EXISTS (
            SELECT 1 FROM pauses AS source_pause
            WHERE source_pause.tournament_id = series.tournament_id
                AND source_pause.roster_id = series.roster_id
                AND source_pause.series_id = series.id
                AND source_pause.game_attempt_id = attempt.id
                AND source_pause.scope_kind = 'game_attempt'
                AND source_pause.scope_id = attempt.id
                AND source_pause.parent_pause_id IS NULL
                AND source_pause.depth = 0
                AND source_pause.reason = 'disconnect'
                AND source_pause.state = 'active'
        )
    ))
    AND attempt.state = 'paused'
ORDER BY pause.id, assignment.series_id, assignment.attempt_id, presence.id
FOR UPDATE OF pause, membership, series, attempt, assignment, snapshot, receipt, presence
`

type LockParticipantConnectionOperatorPauseParams struct {
	ParticipantID uuid.UUID
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
	WaveID        uuid.NullUUID
}

type LockParticipantConnectionOperatorPauseRow struct {
	PauseID          uuid.UUID
	TournamentID     uuid.UUID
	RosterID         uuid.UUID
	WaveID           uuid.UUID
	PauseRevision    int64
	PauseDocument    []byte
	AssignmentID     uuid.UUID
	GameAttemptID    uuid.UUID
	SeriesID         uuid.UUID
	PresenceID       uuid.UUID
	PresenceSeriesID uuid.UUID
	ParticipantID    uuid.UUID
	PresenceState    string
	PresenceEpoch    int64
	PresenceRevision int64
}

// The operator pause is wave-scoped and joins the exact participant presence
// row.  Returning more than one row is a repository conflict, never a reason
// to choose one pause or one series arbitrarily.
func (q *Queries) LockParticipantConnectionOperatorPause(ctx context.Context, arg LockParticipantConnectionOperatorPauseParams) ([]LockParticipantConnectionOperatorPauseRow, error) {
	rows, err := q.db.Query(ctx, lockParticipantConnectionOperatorPause,
		arg.ParticipantID,
		arg.TournamentID,
		arg.RosterID,
		arg.WaveID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockParticipantConnectionOperatorPauseRow{}
	for rows.Next() {
		var i LockParticipantConnectionOperatorPauseRow
		if err := rows.Scan(
			&i.PauseID,
			&i.TournamentID,
			&i.RosterID,
			&i.WaveID,
			&i.PauseRevision,
			&i.PauseDocument,
			&i.AssignmentID,
			&i.GameAttemptID,
			&i.SeriesID,
			&i.PresenceID,
			&i.PresenceSeriesID,
			&i.ParticipantID,
			&i.PresenceState,
			&i.PresenceEpoch,
			&i.PresenceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipantConnectionReadiness = `-- name: LockParticipantConnectionReadiness :one
SELECT readiness.wave_id,
    readiness.ready_window_id,
    readiness.roster_id,
    readiness.participant_id,
    readiness.ready,
    readiness.revision AS readiness_revision
FROM wave_readiness AS readiness
JOIN wave_members AS member
    ON member.wave_id = readiness.wave_id
    AND member.roster_id = readiness.roster_id
    AND member.participant_id = readiness.participant_id
WHERE readiness.wave_id = $1
    AND readiness.ready_window_id = $2
    AND readiness.roster_id = $3
    AND readiness.participant_id = $4
FOR UPDATE OF member, readiness
`

type LockParticipantConnectionReadinessParams struct {
	WaveID        uuid.UUID
	ReadyWindowID uuid.NullUUID
	RosterID      uuid.UUID
	ParticipantID uuid.UUID
}

type LockParticipantConnectionReadinessRow struct {
	WaveID            uuid.UUID
	ReadyWindowID     uuid.NullUUID
	RosterID          uuid.UUID
	ParticipantID     uuid.UUID
	Ready             bool
	ReadinessRevision int64
}

func (q *Queries) LockParticipantConnectionReadiness(ctx context.Context, arg LockParticipantConnectionReadinessParams) (LockParticipantConnectionReadinessRow, error) {
	row := q.db.QueryRow(ctx, lockParticipantConnectionReadiness,
		arg.WaveID,
		arg.ReadyWindowID,
		arg.RosterID,
		arg.ParticipantID,
	)
	var i LockParticipantConnectionReadinessRow
	err := row.Scan(
		&i.WaveID,
		&i.ReadyWindowID,
		&i.RosterID,
		&i.ParticipantID,
		&i.Ready,
		&i.ReadinessRevision,
	)
	return i, err
}

const lockParticipantConnectionReadyWindow = `-- name: LockParticipantConnectionReadyWindow :one
SELECT ready_window.id AS ready_window_id,
    ready_window.wave_id,
    ready_window.roster_id,
    ready_window.revision_id AS ready_window_revision_id,
    ready_window.state AS ready_window_state,
    ready_window.opened_at AS ready_window_opened_at,
    ready_window.deadline AS ready_window_deadline
FROM ready_windows AS ready_window
WHERE ready_window.wave_id = $1
    AND ready_window.roster_id = $2
ORDER BY ready_window.created_at DESC, ready_window.id DESC
LIMIT 1
FOR UPDATE
`

type LockParticipantConnectionReadyWindowParams struct {
	WaveID   uuid.UUID
	RosterID uuid.UUID
}

type LockParticipantConnectionReadyWindowRow struct {
	ReadyWindowID         uuid.UUID
	WaveID                uuid.UUID
	RosterID              uuid.UUID
	ReadyWindowRevisionID uuid.UUID
	ReadyWindowState      string
	ReadyWindowOpenedAt   pgtype.Timestamptz
	ReadyWindowDeadline   pgtype.Timestamptz
}

func (q *Queries) LockParticipantConnectionReadyWindow(ctx context.Context, arg LockParticipantConnectionReadyWindowParams) (LockParticipantConnectionReadyWindowRow, error) {
	row := q.db.QueryRow(ctx, lockParticipantConnectionReadyWindow, arg.WaveID, arg.RosterID)
	var i LockParticipantConnectionReadyWindowRow
	err := row.Scan(
		&i.ReadyWindowID,
		&i.WaveID,
		&i.RosterID,
		&i.ReadyWindowRevisionID,
		&i.ReadyWindowState,
		&i.ReadyWindowOpenedAt,
		&i.ReadyWindowDeadline,
	)
	return i, err
}

const lockParticipantConnectionReconnect = `-- name: LockParticipantConnectionReconnect :many
SELECT assignment.id AS assignment_id,
    assignment.attempt_id AS game_attempt_id,
    assignment.series_id,
    series.state AS series_state,
    attempt.state AS game_state,
    snapshot.kind AS task_kind,
    reconnect.id AS interval_id,
    reconnect.deadline_at AS interval_deadline,
    reconnect.presence_epoch AS interval_presence_epoch,
    presence.id AS presence_id,
    presence.state AS presence_state,
    presence.presence_epoch,
    presence.revision AS presence_revision
FROM wave_series AS membership
JOIN series
    ON series.id = membership.series_id
    AND series.tournament_id = membership.tournament_id
    AND series.roster_id = membership.roster_id
JOIN game_attempts AS attempt
    ON attempt.series_id = series.id
    AND attempt.roster_id = series.roster_id
JOIN assignments AS assignment
    ON assignment.attempt_id = attempt.id
    AND assignment.series_id = series.id
    AND assignment.roster_id = series.roster_id
    AND assignment.state = 'active'
JOIN task_snapshots AS snapshot
    ON snapshot.id = assignment.snapshot_id
    AND snapshot.reservation_id = assignment.reservation_id
    AND snapshot.task_id = assignment.task_id
    AND snapshot.task_version = assignment.task_version
JOIN task_delivery_receipts AS receipt
    ON receipt.assignment_id = assignment.id
    AND receipt.attempt_id = assignment.attempt_id
    AND receipt.roster_id = assignment.roster_id
    AND receipt.participant_id = $1
    AND receipt.snapshot_id = assignment.snapshot_id
JOIN presence_states AS presence
    ON presence.tournament_id = membership.tournament_id
    AND presence.roster_id = membership.roster_id
    AND presence.series_id = series.id
    AND presence.participant_id = $1
JOIN reconnect_intervals AS reconnect
    ON reconnect.roster_id = assignment.roster_id
    AND reconnect.series_id = assignment.series_id
    AND reconnect.game_attempt_id = assignment.attempt_id
    AND reconnect.participant_id = $1
    AND reconnect.state = 'open'
    AND reconnect.presence_epoch = presence.presence_epoch
    AND reconnect.deadline_at > transaction_timestamp()
WHERE membership.wave_id = $2
    AND membership.tournament_id = $3
    AND membership.roster_id = $4
    AND $1 IN (series.first_participant_id, series.second_participant_id)
    AND series.state = 'active'
    AND attempt.state = 'paused'
    AND snapshot.kind = 'normal'
    AND presence.state = 'disconnected'
ORDER BY assignment.series_id, assignment.attempt_id, assignment.id, reconnect.id, presence.id
FOR UPDATE OF membership, series, attempt, assignment, snapshot, receipt, presence, reconnect
`

type LockParticipantConnectionReconnectParams struct {
	ParticipantID uuid.UUID
	WaveID        uuid.UUID
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
}

type LockParticipantConnectionReconnectRow struct {
	AssignmentID          uuid.UUID
	GameAttemptID         uuid.UUID
	SeriesID              uuid.UUID
	SeriesState           string
	GameState             string
	TaskKind              string
	IntervalID            uuid.UUID
	IntervalDeadline      pgtype.Timestamptz
	IntervalPresenceEpoch int64
	PresenceID            uuid.UUID
	PresenceState         string
	PresenceEpoch         int64
	PresenceRevision      int64
}

// A paused attempt with one open reconnect interval is the only ordinary
// reconnect action.  The deadline is returned so the coordinator can fence it
// against its injected clock before entering the nested game usecase.
func (q *Queries) LockParticipantConnectionReconnect(ctx context.Context, arg LockParticipantConnectionReconnectParams) ([]LockParticipantConnectionReconnectRow, error) {
	rows, err := q.db.Query(ctx, lockParticipantConnectionReconnect,
		arg.ParticipantID,
		arg.WaveID,
		arg.TournamentID,
		arg.RosterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockParticipantConnectionReconnectRow{}
	for rows.Next() {
		var i LockParticipantConnectionReconnectRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.GameAttemptID,
			&i.SeriesID,
			&i.SeriesState,
			&i.GameState,
			&i.TaskKind,
			&i.IntervalID,
			&i.IntervalDeadline,
			&i.IntervalPresenceEpoch,
			&i.PresenceID,
			&i.PresenceState,
			&i.PresenceEpoch,
			&i.PresenceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipantConnectionWave = `-- name: LockParticipantConnectionWave :one
SELECT wave.id AS wave_id,
    wave.tournament_id,
    wave.roster_id,
    wave.revision_id AS wave_revision_id,
    wave.revision AS wave_revision,
    wave.state AS wave_state,
    wave.started_at AS wave_started_at,
    member.participant_id
FROM waves AS wave
JOIN wave_members AS member
    ON member.wave_id = wave.id
    AND member.roster_id = wave.roster_id
    AND member.participant_id = $1
WHERE wave.tournament_id = $2
    AND wave.roster_id = $3
    AND wave.state <> 'superseded'
ORDER BY CASE
        WHEN wave.state IN ('planned', 'ready_window_open', 'ready', 'active', 'paused') THEN 0
        ELSE 1
    END,
    wave.updated_at DESC,
    wave.revision DESC,
    wave.id DESC
LIMIT 1
FOR UPDATE OF wave, member
`

type LockParticipantConnectionWaveParams struct {
	ParticipantID uuid.UUID
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
}

type LockParticipantConnectionWaveRow struct {
	WaveID         uuid.UUID
	TournamentID   uuid.UUID
	RosterID       uuid.UUID
	WaveRevisionID uuid.UUID
	WaveRevision   int64
	WaveState      string
	WaveStartedAt  pgtype.Timestamptz
	ParticipantID  uuid.UUID
}

// A participant can have completed historical waves.  Prefer the one current
// execution states use, then fall back to the latest immutable wave so Golden
// and terminal participants still have a durable scope for their lease.
func (q *Queries) LockParticipantConnectionWave(ctx context.Context, arg LockParticipantConnectionWaveParams) (LockParticipantConnectionWaveRow, error) {
	row := q.db.QueryRow(ctx, lockParticipantConnectionWave, arg.ParticipantID, arg.TournamentID, arg.RosterID)
	var i LockParticipantConnectionWaveRow
	err := row.Scan(
		&i.WaveID,
		&i.TournamentID,
		&i.RosterID,
		&i.WaveRevisionID,
		&i.WaveRevision,
		&i.WaveState,
		&i.WaveStartedAt,
		&i.ParticipantID,
	)
	return i, err
}
