// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddSolvedTask(ctx context.Context, arg AddSolvedTaskParams) error
	CountSolvedTasksByDifficulty(ctx context.Context, arg CountSolvedTasksByDifficultyParams) (int64, error)
	CountTasksByDifficulty(ctx context.Context, difficulty string) (int64, error)
	CreateAdminPlayerAuditEvent(ctx context.Context, arg CreateAdminPlayerAuditEventParams) error
	CreateDuel(ctx context.Context, arg CreateDuelParams) (Duel, error)
	CreateDuelPlayerTask(ctx context.Context, arg CreateDuelPlayerTaskParams) error
	CreatePlayer(ctx context.Context, username string) (Player, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id uuid.UUID) error
	FinishDuel(ctx context.Context, arg FinishDuelParams) (Duel, error)
	GetActiveDuelByPlayerID(ctx context.Context, player1ID uuid.UUID) (Duel, error)
	GetAdminPlayer(ctx context.Context, id uuid.UUID) (GetAdminPlayerRow, error)
	GetAdminPlayerIncludingDeleted(ctx context.Context, id uuid.UUID) (GetAdminPlayerIncludingDeletedRow, error)
	GetDuelByID(ctx context.Context, id uuid.UUID) (Duel, error)
	GetDuelPlayerTask(ctx context.Context, arg GetDuelPlayerTaskParams) (DuelPlayerTask, error)
	GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error)
	GetPlayerBySessionToken(ctx context.Context, sessionToken uuid.NullUUID) (Player, error)
	GetPlayerByUsername(ctx context.Context, username string) (Player, error)
	GetPlayerTask(ctx context.Context, arg GetPlayerTaskParams) (Task, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	ListActiveDuels(ctx context.Context) ([]Duel, error)
	ListAdminPlayerAuditEventsByPlayer(ctx context.Context, arg ListAdminPlayerAuditEventsByPlayerParams) ([]AdminPlayerAuditEvent, error)
	ListAdminPlayers(ctx context.Context, dollar_1 bool) ([]ListAdminPlayersRow, error)
	ListSolvedTaskIDs(ctx context.Context, playerID uuid.UUID) ([]uuid.UUID, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByDifficulty(ctx context.Context, difficulty string) ([]Task, error)
	MarkDuelPlayerTaskSolved(ctx context.Context, arg MarkDuelPlayerTaskSolvedParams) error
	ResetQueuedPlayers(ctx context.Context) (int64, error)
	SelectAnyTaskByDifficulty(ctx context.Context, difficulty string) (Task, error)
	SelectUnsolvedTaskByDifficulty(ctx context.Context, arg SelectUnsolvedTaskByDifficultyParams) (Task, error)
	SoftDeleteIdlePlayer(ctx context.Context, arg SoftDeleteIdlePlayerParams) (Player, error)
	TaskInActiveDuel(ctx context.Context, taskID uuid.UUID) (bool, error)
	TopLeaderboardStats(ctx context.Context, limit int32) ([]TopLeaderboardStatsRow, error)
	UpdateDuelDeadline(ctx context.Context, arg UpdateDuelDeadlineParams) (Duel, error)
	UpdatePlayerSessionToken(ctx context.Context, arg UpdatePlayerSessionTokenParams) (Player, error)
	UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) (Player, error)
	UpdatePlayerStatusIfCurrent(ctx context.Context, arg UpdatePlayerStatusIfCurrentParams) (Player, error)
	UpdatePlayerUsername(ctx context.Context, arg UpdatePlayerUsernameParams) (Player, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpsertPlayerLeaderboardOverride(ctx context.Context, arg UpsertPlayerLeaderboardOverrideParams) (PlayerLeaderboardOverride, error)
	UpsertPlayerSessionByUsername(ctx context.Context, arg UpsertPlayerSessionByUsernameParams) (Player, error)
}

var _ Querier = (*Queries)(nil)
