// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: swiss.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAutomaticSwissRound = `-- name: CreateAutomaticSwissRound :one
INSERT INTO swiss_rounds (
    id,
    tournament_id,
    roster_id,
    round_number,
    revision,
    source_roster_revision,
    source_history_revision,
    generation_kind,
    pairing_inputs,
    decision_evidence_id,
    decision_algorithm_version,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    generated_at,
    lock_revision,
    locked_at,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    1,
    $5,
    $6,
    'automatic',
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15::BIGINT,
    $16::TIMESTAMPTZ,
    $17,
    $17
)
RETURNING id, roster_id, round_number, revision, source_roster_revision, source_history_revision, generation_kind, pairing_inputs, decision_evidence_id, decision_algorithm_version, decision_seed, decision_result, decision_replay_digest, decision_owner_id, generated_at, lock_revision, locked_at, created_at, updated_at, tournament_id, content_configuration_id, content_configuration_revision, category_mode, effective_categories
`

type CreateAutomaticSwissRoundParams struct {
	ID                       uuid.UUID
	TournamentID             uuid.UUID
	RosterID                 uuid.UUID
	RoundNumber              int16
	SourceRosterRevision     int64
	SourceHistoryRevision    int64
	PairingInputs            []byte
	DecisionEvidenceID       uuid.NullUUID
	DecisionAlgorithmVersion *string
	DecisionSeed             []byte
	DecisionResult           []byte
	DecisionReplayDigest     []byte
	DecisionOwnerID          uuid.NullUUID
	GeneratedAt              pgtype.Timestamptz
	LockRevision             *int64
	LockedAt                 pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) CreateAutomaticSwissRound(ctx context.Context, arg CreateAutomaticSwissRoundParams) (SwissRound, error) {
	row := q.db.QueryRow(ctx, createAutomaticSwissRound,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.RoundNumber,
		arg.SourceRosterRevision,
		arg.SourceHistoryRevision,
		arg.PairingInputs,
		arg.DecisionEvidenceID,
		arg.DecisionAlgorithmVersion,
		arg.DecisionSeed,
		arg.DecisionResult,
		arg.DecisionReplayDigest,
		arg.DecisionOwnerID,
		arg.GeneratedAt,
		arg.LockRevision,
		arg.LockedAt,
		arg.CreatedAt,
	)
	var i SwissRound
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.RoundNumber,
		&i.Revision,
		&i.SourceRosterRevision,
		&i.SourceHistoryRevision,
		&i.GenerationKind,
		&i.PairingInputs,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.GeneratedAt,
		&i.LockRevision,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TournamentID,
		&i.ContentConfigurationID,
		&i.ContentConfigurationRevision,
		&i.CategoryMode,
		&i.EffectiveCategories,
	)
	return i, err
}

const createManualSwissRound = `-- name: CreateManualSwissRound :one
INSERT INTO swiss_rounds (
    id,
    tournament_id,
    roster_id,
    round_number,
    revision,
    source_roster_revision,
    source_history_revision,
    generation_kind,
    pairing_inputs,
    generated_at,
    lock_revision,
    locked_at,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    1,
    $5,
    $6,
    'manual',
    $7,
    $8,
    $9::BIGINT,
    $10::TIMESTAMPTZ,
    $11,
    $11
)
RETURNING id, roster_id, round_number, revision, source_roster_revision, source_history_revision, generation_kind, pairing_inputs, decision_evidence_id, decision_algorithm_version, decision_seed, decision_result, decision_replay_digest, decision_owner_id, generated_at, lock_revision, locked_at, created_at, updated_at, tournament_id, content_configuration_id, content_configuration_revision, category_mode, effective_categories
`

type CreateManualSwissRoundParams struct {
	ID                    uuid.UUID
	TournamentID          uuid.UUID
	RosterID              uuid.UUID
	RoundNumber           int16
	SourceRosterRevision  int64
	SourceHistoryRevision int64
	PairingInputs         []byte
	GeneratedAt           pgtype.Timestamptz
	LockRevision          *int64
	LockedAt              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateManualSwissRound(ctx context.Context, arg CreateManualSwissRoundParams) (SwissRound, error) {
	row := q.db.QueryRow(ctx, createManualSwissRound,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.RoundNumber,
		arg.SourceRosterRevision,
		arg.SourceHistoryRevision,
		arg.PairingInputs,
		arg.GeneratedAt,
		arg.LockRevision,
		arg.LockedAt,
		arg.CreatedAt,
	)
	var i SwissRound
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.RoundNumber,
		&i.Revision,
		&i.SourceRosterRevision,
		&i.SourceHistoryRevision,
		&i.GenerationKind,
		&i.PairingInputs,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.GeneratedAt,
		&i.LockRevision,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TournamentID,
		&i.ContentConfigurationID,
		&i.ContentConfigurationRevision,
		&i.CategoryMode,
		&i.EffectiveCategories,
	)
	return i, err
}

const createSwissBye = `-- name: CreateSwissBye :exec
INSERT INTO swiss_byes (
    round_id,
    roster_id,
    participant_id,
    points_awarded,
    decision_evidence_id,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
`

type CreateSwissByeParams struct {
	RoundID                  uuid.UUID
	RosterID                 uuid.UUID
	ParticipantID            uuid.UUID
	PointsAwarded            int16
	DecisionEvidenceID       uuid.UUID
	DecisionAlgorithmVersion string
	DecisionInputs           []byte
	DecisionSeed             []byte
	DecisionResult           []byte
	DecisionReplayDigest     []byte
	DecisionOwnerID          uuid.UUID
	DecidedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) CreateSwissBye(ctx context.Context, arg CreateSwissByeParams) error {
	_, err := q.db.Exec(ctx, createSwissBye,
		arg.RoundID,
		arg.RosterID,
		arg.ParticipantID,
		arg.PointsAwarded,
		arg.DecisionEvidenceID,
		arg.DecisionAlgorithmVersion,
		arg.DecisionInputs,
		arg.DecisionSeed,
		arg.DecisionResult,
		arg.DecisionReplayDigest,
		arg.DecisionOwnerID,
		arg.DecidedAt,
		arg.CreatedAt,
	)
	return err
}

const createSwissOpponentHistory = `-- name: CreateSwissOpponentHistory :exec
INSERT INTO swiss_opponent_history (
    pairing_id,
    round_id,
    roster_id,
    prior_meeting_count,
    repeat_override_id,
    recorded_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::UUID,
    $6
)
`

type CreateSwissOpponentHistoryParams struct {
	PairingID         uuid.UUID
	RoundID           uuid.UUID
	RosterID          uuid.UUID
	PriorMeetingCount int16
	RepeatOverrideID  uuid.NullUUID
	RecordedAt        pgtype.Timestamptz
}

func (q *Queries) CreateSwissOpponentHistory(ctx context.Context, arg CreateSwissOpponentHistoryParams) error {
	_, err := q.db.Exec(ctx, createSwissOpponentHistory,
		arg.PairingID,
		arg.RoundID,
		arg.RosterID,
		arg.PriorMeetingCount,
		arg.RepeatOverrideID,
		arg.RecordedAt,
	)
	return err
}

const createSwissPairing = `-- name: CreateSwissPairing :exec
INSERT INTO swiss_pairings (
    id,
    round_id,
    roster_id,
    slot_number,
    repeat_override_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::UUID,
    $6
)
`

type CreateSwissPairingParams struct {
	ID               uuid.UUID
	RoundID          uuid.UUID
	RosterID         uuid.UUID
	SlotNumber       int16
	RepeatOverrideID uuid.NullUUID
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateSwissPairing(ctx context.Context, arg CreateSwissPairingParams) error {
	_, err := q.db.Exec(ctx, createSwissPairing,
		arg.ID,
		arg.RoundID,
		arg.RosterID,
		arg.SlotNumber,
		arg.RepeatOverrideID,
		arg.CreatedAt,
	)
	return err
}

const createSwissPairingMember = `-- name: CreateSwissPairingMember :exec
INSERT INTO swiss_pairing_members (
    pairing_id,
    round_id,
    roster_id,
    seat,
    participant_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateSwissPairingMemberParams struct {
	PairingID     uuid.UUID
	RoundID       uuid.UUID
	RosterID      uuid.UUID
	Seat          int16
	ParticipantID uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateSwissPairingMember(ctx context.Context, arg CreateSwissPairingMemberParams) error {
	_, err := q.db.Exec(ctx, createSwissPairingMember,
		arg.PairingID,
		arg.RoundID,
		arg.RosterID,
		arg.Seat,
		arg.ParticipantID,
		arg.CreatedAt,
	)
	return err
}

const createSwissRepeatOverride = `-- name: CreateSwissRepeatOverride :exec
INSERT INTO swiss_repeat_overrides (
    id,
    round_id,
    roster_id,
    actor_id,
    reason,
    confirmed_at,
    roster_participant_ids,
    proposed_pairings,
    bye_participant_id,
    previous_meetings,
    repeated_pairings,
    alternative_algorithm_version,
    alternative_search_complete,
    alternative_pairings,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9::UUID,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
`

type CreateSwissRepeatOverrideParams struct {
	ID                          uuid.UUID
	RoundID                     uuid.UUID
	RosterID                    uuid.UUID
	ActorID                     uuid.UUID
	Reason                      string
	ConfirmedAt                 pgtype.Timestamptz
	RosterParticipantIds        []byte
	ProposedPairings            []byte
	ByeParticipantID            uuid.NullUUID
	PreviousMeetings            []byte
	RepeatedPairings            []byte
	AlternativeAlgorithmVersion string
	AlternativeSearchComplete   bool
	AlternativePairings         []byte
	CreatedAt                   pgtype.Timestamptz
}

func (q *Queries) CreateSwissRepeatOverride(ctx context.Context, arg CreateSwissRepeatOverrideParams) error {
	_, err := q.db.Exec(ctx, createSwissRepeatOverride,
		arg.ID,
		arg.RoundID,
		arg.RosterID,
		arg.ActorID,
		arg.Reason,
		arg.ConfirmedAt,
		arg.RosterParticipantIds,
		arg.ProposedPairings,
		arg.ByeParticipantID,
		arg.PreviousMeetings,
		arg.RepeatedPairings,
		arg.AlternativeAlgorithmVersion,
		arg.AlternativeSearchComplete,
		arg.AlternativePairings,
		arg.CreatedAt,
	)
	return err
}

const createSwissRoundLockProof = `-- name: CreateSwissRoundLockProof :exec
INSERT INTO swiss_round_lock_proofs (
    round_id,
    tournament_id,
    roster_id,
    preset,
    round_number,
    source_projection_revision_id,
    preflight_revision_id,
    normal_pool_revision_id,
    wave_id,
    wave_revision_id,
    round_revision,
    source_projection_revision,
    roster_revision,
    history_revision,
    normal_pool_revision,
    wave_revision,
    bye_participant_id,
    proof_hash,
    proof_mode,
    terminal_command_id,
    locked_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17::UUID,
    $18,
    COALESCE($19::text, 'wave_start'),
    $20::uuid,
    $21,
    $22
)
`

type CreateSwissRoundLockProofParams struct {
	RoundID                    uuid.UUID
	TournamentID               uuid.UUID
	RosterID                   uuid.UUID
	Preset                     string
	RoundNumber                int16
	SourceProjectionRevisionID uuid.UUID
	PreflightRevisionID        uuid.UUID
	NormalPoolRevisionID       uuid.UUID
	WaveID                     uuid.UUID
	WaveRevisionID             uuid.UUID
	RoundRevision              int64
	SourceProjectionRevision   int64
	RosterRevision             int64
	HistoryRevision            int64
	NormalPoolRevision         int64
	WaveRevision               int64
	ByeParticipantID           uuid.NullUUID
	ProofHash                  []byte
	ProofMode                  *string
	TerminalCommandID          uuid.NullUUID
	LockedAt                   pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
}

func (q *Queries) CreateSwissRoundLockProof(ctx context.Context, arg CreateSwissRoundLockProofParams) error {
	_, err := q.db.Exec(ctx, createSwissRoundLockProof,
		arg.RoundID,
		arg.TournamentID,
		arg.RosterID,
		arg.Preset,
		arg.RoundNumber,
		arg.SourceProjectionRevisionID,
		arg.PreflightRevisionID,
		arg.NormalPoolRevisionID,
		arg.WaveID,
		arg.WaveRevisionID,
		arg.RoundRevision,
		arg.SourceProjectionRevision,
		arg.RosterRevision,
		arg.HistoryRevision,
		arg.NormalPoolRevision,
		arg.WaveRevision,
		arg.ByeParticipantID,
		arg.ProofHash,
		arg.ProofMode,
		arg.TerminalCommandID,
		arg.LockedAt,
		arg.CreatedAt,
	)
	return err
}

const createSwissRoundLockProofMember = `-- name: CreateSwissRoundLockProofMember :exec
INSERT INTO swiss_round_lock_proof_members (
    round_id,
    roster_id,
    participant_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateSwissRoundLockProofMemberParams struct {
	RoundID       uuid.UUID
	RosterID      uuid.UUID
	ParticipantID uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateSwissRoundLockProofMember(ctx context.Context, arg CreateSwissRoundLockProofMemberParams) error {
	_, err := q.db.Exec(ctx, createSwissRoundLockProofMember,
		arg.RoundID,
		arg.RosterID,
		arg.ParticipantID,
		arg.CreatedAt,
	)
	return err
}

const createSwissRoundLockProofSeries = `-- name: CreateSwissRoundLockProofSeries :exec
INSERT INTO swiss_round_lock_proof_series (
    round_id,
    roster_id,
    pairing_id,
    series_id,
    first_participant_id,
    second_participant_id,
    category_revision_id,
    category_revision,
    assignment_id,
    assignment_revision,
    assignment_plan_id,
    assignment_plan_revision_id,
    reservation_id,
    reservation_revision,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
`

type CreateSwissRoundLockProofSeriesParams struct {
	RoundID                  uuid.UUID
	RosterID                 uuid.UUID
	PairingID                uuid.UUID
	SeriesID                 uuid.UUID
	FirstParticipantID       uuid.UUID
	SecondParticipantID      uuid.UUID
	CategoryRevisionID       uuid.UUID
	CategoryRevision         int64
	AssignmentID             uuid.UUID
	AssignmentRevision       int64
	AssignmentPlanID         uuid.UUID
	AssignmentPlanRevisionID uuid.UUID
	ReservationID            uuid.UUID
	ReservationRevision      int64
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) CreateSwissRoundLockProofSeries(ctx context.Context, arg CreateSwissRoundLockProofSeriesParams) error {
	_, err := q.db.Exec(ctx, createSwissRoundLockProofSeries,
		arg.RoundID,
		arg.RosterID,
		arg.PairingID,
		arg.SeriesID,
		arg.FirstParticipantID,
		arg.SecondParticipantID,
		arg.CategoryRevisionID,
		arg.CategoryRevision,
		arg.AssignmentID,
		arg.AssignmentRevision,
		arg.AssignmentPlanID,
		arg.AssignmentPlanRevisionID,
		arg.ReservationID,
		arg.ReservationRevision,
		arg.CreatedAt,
	)
	return err
}

const deleteSwissBye = `-- name: DeleteSwissBye :exec
DELETE FROM swiss_byes
WHERE round_id = $1
`

func (q *Queries) DeleteSwissBye(ctx context.Context, roundID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSwissBye, roundID)
	return err
}

const deleteSwissOpponentHistory = `-- name: DeleteSwissOpponentHistory :exec
DELETE FROM swiss_opponent_history
WHERE round_id = $1
`

func (q *Queries) DeleteSwissOpponentHistory(ctx context.Context, roundID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSwissOpponentHistory, roundID)
	return err
}

const deleteSwissPairingMembers = `-- name: DeleteSwissPairingMembers :exec
DELETE FROM swiss_pairing_members
WHERE round_id = $1
`

func (q *Queries) DeleteSwissPairingMembers(ctx context.Context, roundID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSwissPairingMembers, roundID)
	return err
}

const deleteSwissPairings = `-- name: DeleteSwissPairings :exec
DELETE FROM swiss_pairings
WHERE round_id = $1
`

func (q *Queries) DeleteSwissPairings(ctx context.Context, roundID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSwissPairings, roundID)
	return err
}

const deleteSwissRepeatOverride = `-- name: DeleteSwissRepeatOverride :exec
DELETE FROM swiss_repeat_overrides
WHERE round_id = $1
`

func (q *Queries) DeleteSwissRepeatOverride(ctx context.Context, roundID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSwissRepeatOverride, roundID)
	return err
}

const getSwissBye = `-- name: GetSwissBye :one
SELECT round_id,
    roster_id,
    participant_id,
    points_awarded,
    decision_evidence_id,
    decision_algorithm_version,
    decision_inputs,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    decided_at,
    created_at
FROM swiss_byes
WHERE round_id = $1
`

func (q *Queries) GetSwissBye(ctx context.Context, roundID uuid.UUID) (SwissBye, error) {
	row := q.db.QueryRow(ctx, getSwissBye, roundID)
	var i SwissBye
	err := row.Scan(
		&i.RoundID,
		&i.RosterID,
		&i.ParticipantID,
		&i.PointsAwarded,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionInputs,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSwissRepeatOverride = `-- name: GetSwissRepeatOverride :one
SELECT id,
    round_id,
    roster_id,
    actor_id,
    reason,
    confirmed_at,
    roster_participant_ids,
    proposed_pairings,
    bye_participant_id,
    previous_meetings,
    repeated_pairings,
    alternative_algorithm_version,
    alternative_search_complete,
    alternative_pairings,
    created_at
FROM swiss_repeat_overrides
WHERE round_id = $1
`

func (q *Queries) GetSwissRepeatOverride(ctx context.Context, roundID uuid.UUID) (SwissRepeatOverride, error) {
	row := q.db.QueryRow(ctx, getSwissRepeatOverride, roundID)
	var i SwissRepeatOverride
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.RosterID,
		&i.ActorID,
		&i.Reason,
		&i.ConfirmedAt,
		&i.RosterParticipantIds,
		&i.ProposedPairings,
		&i.ByeParticipantID,
		&i.PreviousMeetings,
		&i.RepeatedPairings,
		&i.AlternativeAlgorithmVersion,
		&i.AlternativeSearchComplete,
		&i.AlternativePairings,
		&i.CreatedAt,
	)
	return i, err
}

const getSwissRound = `-- name: GetSwissRound :one
SELECT id,
    roster_id,
    round_number,
    revision,
    source_roster_revision,
    source_history_revision,
    generation_kind,
    pairing_inputs,
    decision_evidence_id,
    decision_algorithm_version,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    generated_at,
    lock_revision,
    locked_at,
    created_at,
    updated_at,
    tournament_id,
    content_configuration_id,
    content_configuration_revision,
    category_mode,
    effective_categories
FROM swiss_rounds
WHERE id = $1
`

func (q *Queries) GetSwissRound(ctx context.Context, id uuid.UUID) (SwissRound, error) {
	row := q.db.QueryRow(ctx, getSwissRound, id)
	var i SwissRound
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.RoundNumber,
		&i.Revision,
		&i.SourceRosterRevision,
		&i.SourceHistoryRevision,
		&i.GenerationKind,
		&i.PairingInputs,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.GeneratedAt,
		&i.LockRevision,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TournamentID,
		&i.ContentConfigurationID,
		&i.ContentConfigurationRevision,
		&i.CategoryMode,
		&i.EffectiveCategories,
	)
	return i, err
}

const listSwissOpponentHistory = `-- name: ListSwissOpponentHistory :many
SELECT history.pairing_id,
    history.round_id,
    history.roster_id,
    pairing.slot_number,
    first_member.participant_id AS first_participant_id,
    second_member.participant_id AS second_participant_id,
    history.prior_meeting_count,
    history.repeat_override_id,
    history.recorded_at
FROM swiss_opponent_history AS history
JOIN swiss_pairings AS pairing ON pairing.id = history.pairing_id
JOIN swiss_rounds AS round ON round.id = history.round_id
JOIN swiss_pairing_members AS first_member
    ON first_member.pairing_id = history.pairing_id
    AND first_member.seat = 1
JOIN swiss_pairing_members AS second_member
    ON second_member.pairing_id = history.pairing_id
    AND second_member.seat = 2
WHERE history.roster_id = $1
ORDER BY round.round_number,
    pairing.slot_number
`

type ListSwissOpponentHistoryRow struct {
	PairingID           uuid.UUID
	RoundID             uuid.UUID
	RosterID            uuid.UUID
	SlotNumber          int16
	FirstParticipantID  uuid.UUID
	SecondParticipantID uuid.UUID
	PriorMeetingCount   int16
	RepeatOverrideID    uuid.NullUUID
	RecordedAt          pgtype.Timestamptz
}

func (q *Queries) ListSwissOpponentHistory(ctx context.Context, rosterID uuid.UUID) ([]ListSwissOpponentHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSwissOpponentHistory, rosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSwissOpponentHistoryRow{}
	for rows.Next() {
		var i ListSwissOpponentHistoryRow
		if err := rows.Scan(
			&i.PairingID,
			&i.RoundID,
			&i.RosterID,
			&i.SlotNumber,
			&i.FirstParticipantID,
			&i.SecondParticipantID,
			&i.PriorMeetingCount,
			&i.RepeatOverrideID,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwissRounds = `-- name: ListSwissRounds :many
SELECT id,
    roster_id,
    round_number,
    revision,
    source_roster_revision,
    source_history_revision,
    generation_kind,
    pairing_inputs,
    decision_evidence_id,
    decision_algorithm_version,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    generated_at,
    lock_revision,
    locked_at,
    created_at,
    updated_at,
    tournament_id,
    content_configuration_id,
    content_configuration_revision,
    category_mode,
    effective_categories
FROM swiss_rounds
WHERE roster_id = $1
ORDER BY round_number
`

func (q *Queries) ListSwissRounds(ctx context.Context, rosterID uuid.UUID) ([]SwissRound, error) {
	rows, err := q.db.Query(ctx, listSwissRounds, rosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwissRound{}
	for rows.Next() {
		var i SwissRound
		if err := rows.Scan(
			&i.ID,
			&i.RosterID,
			&i.RoundNumber,
			&i.Revision,
			&i.SourceRosterRevision,
			&i.SourceHistoryRevision,
			&i.GenerationKind,
			&i.PairingInputs,
			&i.DecisionEvidenceID,
			&i.DecisionAlgorithmVersion,
			&i.DecisionSeed,
			&i.DecisionResult,
			&i.DecisionReplayDigest,
			&i.DecisionOwnerID,
			&i.GeneratedAt,
			&i.LockRevision,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TournamentID,
			&i.ContentConfigurationID,
			&i.ContentConfigurationRevision,
			&i.CategoryMode,
			&i.EffectiveCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSwissRoundCAS = `-- name: LockSwissRoundCAS :one
UPDATE swiss_rounds
SET lock_revision = revision,
    locked_at = $1,
    updated_at = $1
WHERE id = $2
    AND revision = $3
    AND locked_at IS NULL
RETURNING id, roster_id, round_number, revision, source_roster_revision, source_history_revision, generation_kind, pairing_inputs, decision_evidence_id, decision_algorithm_version, decision_seed, decision_result, decision_replay_digest, decision_owner_id, generated_at, lock_revision, locked_at, created_at, updated_at, tournament_id, content_configuration_id, content_configuration_revision, category_mode, effective_categories
`

type LockSwissRoundCASParams struct {
	LockedAt         pgtype.Timestamptz
	ID               uuid.UUID
	ExpectedRevision int64
}

func (q *Queries) LockSwissRoundCAS(ctx context.Context, arg LockSwissRoundCASParams) (SwissRound, error) {
	row := q.db.QueryRow(ctx, lockSwissRoundCAS, arg.LockedAt, arg.ID, arg.ExpectedRevision)
	var i SwissRound
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.RoundNumber,
		&i.Revision,
		&i.SourceRosterRevision,
		&i.SourceHistoryRevision,
		&i.GenerationKind,
		&i.PairingInputs,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.GeneratedAt,
		&i.LockRevision,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TournamentID,
		&i.ContentConfigurationID,
		&i.ContentConfigurationRevision,
		&i.CategoryMode,
		&i.EffectiveCategories,
	)
	return i, err
}

const lockSwissRoundForUpdate = `-- name: LockSwissRoundForUpdate :one
SELECT id,
    roster_id,
    round_number,
    revision,
    source_roster_revision,
    source_history_revision,
    generation_kind,
    pairing_inputs,
    decision_evidence_id,
    decision_algorithm_version,
    decision_seed,
    decision_result,
    decision_replay_digest,
    decision_owner_id,
    generated_at,
    lock_revision,
    locked_at,
    created_at,
    updated_at,
    tournament_id,
    content_configuration_id,
    content_configuration_revision,
    category_mode,
    effective_categories
FROM swiss_rounds
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockSwissRoundForUpdate(ctx context.Context, id uuid.UUID) (SwissRound, error) {
	row := q.db.QueryRow(ctx, lockSwissRoundForUpdate, id)
	var i SwissRound
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.RoundNumber,
		&i.Revision,
		&i.SourceRosterRevision,
		&i.SourceHistoryRevision,
		&i.GenerationKind,
		&i.PairingInputs,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.GeneratedAt,
		&i.LockRevision,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TournamentID,
		&i.ContentConfigurationID,
		&i.ContentConfigurationRevision,
		&i.CategoryMode,
		&i.EffectiveCategories,
	)
	return i, err
}

const updateAutomaticSwissRoundCAS = `-- name: UpdateAutomaticSwissRoundCAS :one
UPDATE swiss_rounds
SET revision = revision + 1,
    source_roster_revision = $1,
    source_history_revision = $2,
    generation_kind = 'automatic',
    pairing_inputs = $3,
    decision_evidence_id = $4,
    decision_algorithm_version = $5,
    decision_seed = $6,
    decision_result = $7,
    decision_replay_digest = $8,
    decision_owner_id = $9,
    generated_at = $10,
    updated_at = $11
WHERE id = $12
    AND revision = $13
    AND locked_at IS NULL
RETURNING id, roster_id, round_number, revision, source_roster_revision, source_history_revision, generation_kind, pairing_inputs, decision_evidence_id, decision_algorithm_version, decision_seed, decision_result, decision_replay_digest, decision_owner_id, generated_at, lock_revision, locked_at, created_at, updated_at, tournament_id, content_configuration_id, content_configuration_revision, category_mode, effective_categories
`

type UpdateAutomaticSwissRoundCASParams struct {
	SourceRosterRevision     int64
	SourceHistoryRevision    int64
	PairingInputs            []byte
	DecisionEvidenceID       uuid.NullUUID
	DecisionAlgorithmVersion *string
	DecisionSeed             []byte
	DecisionResult           []byte
	DecisionReplayDigest     []byte
	DecisionOwnerID          uuid.NullUUID
	GeneratedAt              pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	ID                       uuid.UUID
	ExpectedRevision         int64
}

func (q *Queries) UpdateAutomaticSwissRoundCAS(ctx context.Context, arg UpdateAutomaticSwissRoundCASParams) (SwissRound, error) {
	row := q.db.QueryRow(ctx, updateAutomaticSwissRoundCAS,
		arg.SourceRosterRevision,
		arg.SourceHistoryRevision,
		arg.PairingInputs,
		arg.DecisionEvidenceID,
		arg.DecisionAlgorithmVersion,
		arg.DecisionSeed,
		arg.DecisionResult,
		arg.DecisionReplayDigest,
		arg.DecisionOwnerID,
		arg.GeneratedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i SwissRound
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.RoundNumber,
		&i.Revision,
		&i.SourceRosterRevision,
		&i.SourceHistoryRevision,
		&i.GenerationKind,
		&i.PairingInputs,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.GeneratedAt,
		&i.LockRevision,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TournamentID,
		&i.ContentConfigurationID,
		&i.ContentConfigurationRevision,
		&i.CategoryMode,
		&i.EffectiveCategories,
	)
	return i, err
}

const updateManualSwissRoundCAS = `-- name: UpdateManualSwissRoundCAS :one
UPDATE swiss_rounds
SET revision = revision + 1,
    source_roster_revision = $1,
    source_history_revision = $2,
    generation_kind = 'manual',
    pairing_inputs = $3,
    decision_evidence_id = NULL,
    decision_algorithm_version = NULL,
    decision_seed = NULL,
    decision_result = NULL,
    decision_replay_digest = NULL,
    decision_owner_id = NULL,
    generated_at = $4,
    updated_at = $5
WHERE id = $6
    AND revision = $7
    AND locked_at IS NULL
RETURNING id, roster_id, round_number, revision, source_roster_revision, source_history_revision, generation_kind, pairing_inputs, decision_evidence_id, decision_algorithm_version, decision_seed, decision_result, decision_replay_digest, decision_owner_id, generated_at, lock_revision, locked_at, created_at, updated_at, tournament_id, content_configuration_id, content_configuration_revision, category_mode, effective_categories
`

type UpdateManualSwissRoundCASParams struct {
	SourceRosterRevision  int64
	SourceHistoryRevision int64
	PairingInputs         []byte
	GeneratedAt           pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ID                    uuid.UUID
	ExpectedRevision      int64
}

func (q *Queries) UpdateManualSwissRoundCAS(ctx context.Context, arg UpdateManualSwissRoundCASParams) (SwissRound, error) {
	row := q.db.QueryRow(ctx, updateManualSwissRoundCAS,
		arg.SourceRosterRevision,
		arg.SourceHistoryRevision,
		arg.PairingInputs,
		arg.GeneratedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i SwissRound
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.RoundNumber,
		&i.Revision,
		&i.SourceRosterRevision,
		&i.SourceHistoryRevision,
		&i.GenerationKind,
		&i.PairingInputs,
		&i.DecisionEvidenceID,
		&i.DecisionAlgorithmVersion,
		&i.DecisionSeed,
		&i.DecisionResult,
		&i.DecisionReplayDigest,
		&i.DecisionOwnerID,
		&i.GeneratedAt,
		&i.LockRevision,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TournamentID,
		&i.ContentConfigurationID,
		&i.ContentConfigurationRevision,
		&i.CategoryMode,
		&i.EffectiveCategories,
	)
	return i, err
}
