// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament_cancellation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTournamentForCancellationCAS = `-- name: CancelTournamentForCancellationCAS :one
UPDATE tournaments
SET state = 'cancelled',
    paused_from_state = NULL,
    revision = revision + 1,
    updated_at = $1,
    finished_at = $1
WHERE id = $2
    AND revision = $3
    AND state = $4
    AND state NOT IN ('completed', 'cancelled')
RETURNING id,
    preset,
    state,
    paused_from_state,
    revision,
    created_at,
    updated_at,
    started_at,
    finished_at,
    name,
    public_id,
    planned_roster_size,
    content_revision
`

type CancelTournamentForCancellationCASParams struct {
	CancelledAt      pgtype.Timestamptz
	TournamentID     uuid.UUID
	ExpectedRevision int64
	ExpectedState    string
}

func (q *Queries) CancelTournamentForCancellationCAS(ctx context.Context, arg CancelTournamentForCancellationCASParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, cancelTournamentForCancellationCAS,
		arg.CancelledAt,
		arg.TournamentID,
		arg.ExpectedRevision,
		arg.ExpectedState,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Preset,
		&i.State,
		&i.PausedFromState,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Name,
		&i.PublicID,
		&i.PlannedRosterSize,
		&i.ContentRevision,
	)
	return i, err
}

const createTournamentCancellation = `-- name: CreateTournamentCancellation :one
WITH created AS (
    INSERT INTO tournament_cancellations (
    command_id,
    tournament_id,
    roster_id,
    source_revision,
    resulting_revision,
    source_state,
    actor_id,
    reason,
    audit_event_id,
    outbox_event_id,
    cancelled_at,
    created_at
    )
    VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $11
    )
    RETURNING command_id,
    tournament_id,
    roster_id,
    source_revision,
    resulting_revision,
    source_state,
    actor_id,
    reason,
    audit_event_id,
    outbox_event_id,
    cancelled_at,
    created_at
),
source AS (
    INSERT INTO outbox_tournament_cancellation_sources (
        outbox_event_id,
        tournament_id,
        roster_id,
        cancellation_command_id,
        projection_revision_id,
        projection_revision,
        projection_ordinal,
        created_at
    )
    SELECT outbox_event_id,
        tournament_id,
        roster_id,
        command_id,
        $12,
        $13,
        $14,
        created_at
    FROM created
    RETURNING outbox_event_id
)
SELECT created.command_id,
    created.tournament_id,
    created.roster_id,
    created.source_revision,
    created.resulting_revision,
    created.source_state,
    created.actor_id,
    created.reason,
    created.audit_event_id,
    created.outbox_event_id,
    created.cancelled_at,
    created.created_at
FROM created
CROSS JOIN source
`

type CreateTournamentCancellationParams struct {
	CommandID            uuid.UUID
	TournamentID         uuid.UUID
	RosterID             uuid.UUID
	SourceRevision       int64
	ResultingRevision    int64
	SourceState          string
	ActorID              uuid.UUID
	Reason               string
	AuditEventID         uuid.UUID
	OutboxEventID        uuid.UUID
	CancelledAt          pgtype.Timestamptz
	ProjectionRevisionID uuid.UUID
	ProjectionRevision   int64
	ProjectionOrdinal    int16
}

type CreateTournamentCancellationRow struct {
	CommandID         uuid.UUID
	TournamentID      uuid.UUID
	RosterID          uuid.UUID
	SourceRevision    int64
	ResultingRevision int64
	SourceState       string
	ActorID           uuid.UUID
	Reason            string
	AuditEventID      uuid.UUID
	OutboxEventID     uuid.UUID
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateTournamentCancellation(ctx context.Context, arg CreateTournamentCancellationParams) (CreateTournamentCancellationRow, error) {
	row := q.db.QueryRow(ctx, createTournamentCancellation,
		arg.CommandID,
		arg.TournamentID,
		arg.RosterID,
		arg.SourceRevision,
		arg.ResultingRevision,
		arg.SourceState,
		arg.ActorID,
		arg.Reason,
		arg.AuditEventID,
		arg.OutboxEventID,
		arg.CancelledAt,
		arg.ProjectionRevisionID,
		arg.ProjectionRevision,
		arg.ProjectionOrdinal,
	)
	var i CreateTournamentCancellationRow
	err := row.Scan(
		&i.CommandID,
		&i.TournamentID,
		&i.RosterID,
		&i.SourceRevision,
		&i.ResultingRevision,
		&i.SourceState,
		&i.ActorID,
		&i.Reason,
		&i.AuditEventID,
		&i.OutboxEventID,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTournamentCancellationAuditEvent = `-- name: CreateTournamentCancellationAuditEvent :one
INSERT INTO audit_events (
    id,
    tournament_id,
    roster_id,
    series_id,
    result_event_id,
    actor_kind,
    actor_id,
    action,
    payload,
    occurred_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    NULL,
    NULL,
    'operator',
    $4,
    'tournament.cancelled',
    jsonb_build_object(
        'reason', $5::TEXT,
        'source_revision', $6::BIGINT,
        'resulting_revision', $7::BIGINT,
        'source_projection_revision_id', $8::UUID,
        'source_projection_revision', $9::BIGINT
    ),
    $10,
    $10
)
RETURNING id
`

type CreateTournamentCancellationAuditEventParams struct {
	ID                         uuid.UUID
	TournamentID               uuid.UUID
	RosterID                   uuid.UUID
	ActorID                    uuid.NullUUID
	Reason                     string
	SourceRevision             int64
	ResultingRevision          int64
	SourceProjectionRevisionID uuid.UUID
	SourceProjectionRevision   int64
	CancelledAt                pgtype.Timestamptz
}

func (q *Queries) CreateTournamentCancellationAuditEvent(ctx context.Context, arg CreateTournamentCancellationAuditEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTournamentCancellationAuditEvent,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.ActorID,
		arg.Reason,
		arg.SourceRevision,
		arg.ResultingRevision,
		arg.SourceProjectionRevisionID,
		arg.SourceProjectionRevision,
		arg.CancelledAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTournamentCancellationOutboxEvent = `-- name: CreateTournamentCancellationOutboxEvent :one
WITH existing AS MATERIALIZED (
    SELECT outbox_event.id,
        outbox_event.tournament_id,
        outbox_event.roster_id,
        outbox_event.sequence,
        outbox_event.projection_revision_id,
        outbox_event.projection_revision,
        outbox_event.projection_ordinal,
        outbox_event.terminal,
        outbox_event.audience,
        outbox_event.principal_id,
        outbox_event.topic,
        outbox_event.payload,
        outbox_event.created_at,
        outbox_event.available_at
    FROM outbox_events AS outbox_event
    WHERE outbox_event.idempotency_key = $1
),
authoritative_projection AS MATERIALIZED (
    SELECT projection_revision.id,
        projection_revision.tournament_id,
        projection_revision.roster_id,
        projection_revision.revision_number
    FROM projection_revisions AS projection_revision
    WHERE projection_revision.id = $2
        AND projection_revision.tournament_id = $3
        AND projection_revision.roster_id = $4
        AND projection_revision.revision_number = $5
        AND projection_revision.state = 'published'
    FOR SHARE
),
allocated_sequence AS (
    INSERT INTO tournament_outbox_cursors (
        tournament_id,
        next_sequence,
        updated_at
    )
    SELECT authoritative_projection.tournament_id,
        2,
        $6
    FROM authoritative_projection
    WHERE NOT EXISTS (SELECT 1 FROM existing)
    ON CONFLICT (tournament_id) DO UPDATE
    SET next_sequence = tournament_outbox_cursors.next_sequence + 1,
        updated_at = EXCLUDED.updated_at
    RETURNING next_sequence - 1 AS sequence
),
allocated_ordinal AS (
    INSERT INTO projection_outbox_cursors (
        projection_revision_id,
        tournament_id,
        roster_id,
        next_ordinal,
        updated_at
    )
    SELECT authoritative_projection.id,
        authoritative_projection.tournament_id,
        authoritative_projection.roster_id,
        2,
        $6
    FROM authoritative_projection
    INNER JOIN allocated_sequence ON true
    ON CONFLICT (projection_revision_id) DO UPDATE
    SET next_ordinal = projection_outbox_cursors.next_ordinal + 1,
        updated_at = EXCLUDED.updated_at
    WHERE projection_outbox_cursors.tournament_id = EXCLUDED.tournament_id
        AND projection_outbox_cursors.roster_id = EXCLUDED.roster_id
        AND projection_outbox_cursors.next_ordinal < 32768
    RETURNING next_ordinal - 1 AS projection_ordinal
),
created AS (
    INSERT INTO outbox_events (
        id,
        tournament_id,
        roster_id,
        projection_revision_id,
        projection_revision,
        sequence,
        projection_ordinal,
        terminal,
        idempotency_key,
        audience,
        principal_id,
        topic,
        payload,
        created_at,
        available_at
    )
    SELECT
        $7,
        authoritative_projection.tournament_id,
        authoritative_projection.roster_id,
        authoritative_projection.id,
        authoritative_projection.revision_number,
        allocated_sequence.sequence,
        allocated_ordinal.projection_ordinal,
        true,
        $1,
        'all',
        NULL,
        'tournament.cancelled',
        jsonb_build_object('state', 'cancelled'),
        $6,
        $6
    FROM authoritative_projection
    INNER JOIN allocated_sequence ON true
    INNER JOIN allocated_ordinal ON true
    ON CONFLICT (idempotency_key) DO NOTHING
    RETURNING id,
        tournament_id,
        roster_id,
        sequence,
        projection_revision_id,
        projection_revision,
        projection_ordinal
),
existing_verified AS MATERIALIZED (
    SELECT existing.id,
        existing.tournament_id,
        existing.roster_id,
        existing.sequence,
        existing.projection_revision_id,
        existing.projection_revision,
        existing.projection_ordinal
    FROM existing
    INNER JOIN authoritative_projection
        ON authoritative_projection.id = existing.projection_revision_id
        AND authoritative_projection.tournament_id = existing.tournament_id
        AND authoritative_projection.roster_id = existing.roster_id
        AND authoritative_projection.revision_number = existing.projection_revision
    INNER JOIN outbox_tournament_cancellation_sources AS source
        ON source.outbox_event_id = existing.id
        AND source.tournament_id = existing.tournament_id
        AND source.roster_id = existing.roster_id
        AND source.cancellation_command_id = $8
        AND source.projection_revision_id = existing.projection_revision_id
        AND source.projection_revision = existing.projection_revision
        AND source.projection_ordinal = existing.projection_ordinal
        AND source.created_at = existing.created_at
    WHERE existing.id = $7
        AND existing.tournament_id = $3
        AND existing.roster_id = $4
        AND existing.terminal
        AND existing.audience = 'all'
        AND existing.principal_id IS NULL
        AND existing.topic = 'tournament.cancelled'
        AND existing.payload = jsonb_build_object('state', 'cancelled')
        AND existing.created_at = $6
        AND existing.available_at = $6
),
resolved AS MATERIALIZED (
    SELECT created.id,
        created.tournament_id,
        created.roster_id,
        created.sequence,
        created.projection_revision_id,
        created.projection_revision,
        created.projection_ordinal
    FROM created
    UNION ALL
    SELECT existing_verified.id,
        existing_verified.tournament_id,
        existing_verified.roster_id,
        existing_verified.sequence,
        existing_verified.projection_revision_id,
        existing_verified.projection_revision,
        existing_verified.projection_ordinal
    FROM existing_verified
    WHERE NOT EXISTS (SELECT 1 FROM created)
)
SELECT outbox_event.id,
    outbox_event.sequence,
    outbox_event.projection_revision_id,
    outbox_event.projection_revision,
    outbox_event.projection_ordinal
FROM resolved AS outbox_event
`

type CreateTournamentCancellationOutboxEventParams struct {
	IdempotencyKey        uuid.UUID
	ProjectionRevisionID  uuid.UUID
	TournamentID          uuid.UUID
	RosterID              uuid.UUID
	ProjectionRevision    int64
	CancelledAt           pgtype.Timestamptz
	ID                    uuid.UUID
	CancellationCommandID uuid.UUID
}

type CreateTournamentCancellationOutboxEventRow struct {
	ID                   uuid.UUID
	Sequence             int64
	ProjectionRevisionID uuid.UUID
	ProjectionRevision   int64
	ProjectionOrdinal    int16
}

func (q *Queries) CreateTournamentCancellationOutboxEvent(ctx context.Context, arg CreateTournamentCancellationOutboxEventParams) (CreateTournamentCancellationOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, createTournamentCancellationOutboxEvent,
		arg.IdempotencyKey,
		arg.ProjectionRevisionID,
		arg.TournamentID,
		arg.RosterID,
		arg.ProjectionRevision,
		arg.CancelledAt,
		arg.ID,
		arg.CancellationCommandID,
	)
	var i CreateTournamentCancellationOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.ProjectionRevisionID,
		&i.ProjectionRevision,
		&i.ProjectionOrdinal,
	)
	return i, err
}

const findTournamentCancellation = `-- name: FindTournamentCancellation :one
SELECT cancellation.command_id,
    cancellation.tournament_id,
    cancellation.roster_id,
    cancellation.source_revision,
    cancellation.resulting_revision,
    cancellation.source_state,
    cancellation.actor_id,
    cancellation.reason,
    cancellation.audit_event_id,
    cancellation.outbox_event_id,
    cancellation.cancelled_at,
    cancellation.created_at,
    tournament.state AS tournament_state,
    tournament.paused_from_state,
    tournament.revision AS tournament_revision,
    tournament.updated_at AS tournament_updated_at,
    tournament.finished_at AS tournament_finished_at
FROM tournament_cancellations AS cancellation
INNER JOIN tournaments AS tournament ON tournament.id = cancellation.tournament_id
WHERE cancellation.tournament_id = $1
    AND cancellation.command_id = $2
`

type FindTournamentCancellationParams struct {
	TournamentID uuid.UUID
	CommandID    uuid.UUID
}

type FindTournamentCancellationRow struct {
	CommandID            uuid.UUID
	TournamentID         uuid.UUID
	RosterID             uuid.UUID
	SourceRevision       int64
	ResultingRevision    int64
	SourceState          string
	ActorID              uuid.UUID
	Reason               string
	AuditEventID         uuid.UUID
	OutboxEventID        uuid.UUID
	CancelledAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	TournamentState      string
	PausedFromState      *string
	TournamentRevision   int64
	TournamentUpdatedAt  pgtype.Timestamptz
	TournamentFinishedAt pgtype.Timestamptz
}

func (q *Queries) FindTournamentCancellation(ctx context.Context, arg FindTournamentCancellationParams) (FindTournamentCancellationRow, error) {
	row := q.db.QueryRow(ctx, findTournamentCancellation, arg.TournamentID, arg.CommandID)
	var i FindTournamentCancellationRow
	err := row.Scan(
		&i.CommandID,
		&i.TournamentID,
		&i.RosterID,
		&i.SourceRevision,
		&i.ResultingRevision,
		&i.SourceState,
		&i.ActorID,
		&i.Reason,
		&i.AuditEventID,
		&i.OutboxEventID,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.TournamentState,
		&i.PausedFromState,
		&i.TournamentRevision,
		&i.TournamentUpdatedAt,
		&i.TournamentFinishedAt,
	)
	return i, err
}

const getTournamentCancellationAudit = `-- name: GetTournamentCancellationAudit :one
SELECT cancellation.command_id,
    cancellation.tournament_id,
    cancellation.roster_id,
    cancellation.source_revision,
    cancellation.resulting_revision,
    cancellation.actor_id,
    cancellation.reason,
    cancellation.audit_event_id,
    cancellation.cancelled_at,
    source.projection_revision_id AS source_projection_revision_id,
    source.projection_revision AS source_projection_revision
FROM tournament_cancellations AS cancellation
INNER JOIN outbox_tournament_cancellation_sources AS source
    ON source.cancellation_command_id = cancellation.command_id
    AND source.tournament_id = cancellation.tournament_id
    AND source.roster_id = cancellation.roster_id
    AND source.outbox_event_id = cancellation.outbox_event_id
WHERE cancellation.tournament_id = $1
`

type GetTournamentCancellationAuditRow struct {
	CommandID                  uuid.UUID
	TournamentID               uuid.UUID
	RosterID                   uuid.UUID
	SourceRevision             int64
	ResultingRevision          int64
	ActorID                    uuid.UUID
	Reason                     string
	AuditEventID               uuid.UUID
	CancelledAt                pgtype.Timestamptz
	SourceProjectionRevisionID uuid.UUID
	SourceProjectionRevision   int64
}

func (q *Queries) GetTournamentCancellationAudit(ctx context.Context, tournamentID uuid.UUID) (GetTournamentCancellationAuditRow, error) {
	row := q.db.QueryRow(ctx, getTournamentCancellationAudit, tournamentID)
	var i GetTournamentCancellationAuditRow
	err := row.Scan(
		&i.CommandID,
		&i.TournamentID,
		&i.RosterID,
		&i.SourceRevision,
		&i.ResultingRevision,
		&i.ActorID,
		&i.Reason,
		&i.AuditEventID,
		&i.CancelledAt,
		&i.SourceProjectionRevisionID,
		&i.SourceProjectionRevision,
	)
	return i, err
}

const lockTournamentCancellationAuthority = `-- name: LockTournamentCancellationAuthority :one
SELECT tournament.id,
    tournament.state,
    tournament.paused_from_state,
    tournament.revision,
    tournament.updated_at,
    tournament.finished_at,
    roster.id AS roster_id,
    projection_revision.id AS projection_revision_id,
    projection_revision.revision_number AS projection_revision
FROM tournaments AS tournament
INNER JOIN rosters AS roster ON roster.tournament_id = tournament.id
INNER JOIN projection_revisions AS projection_revision
    ON projection_revision.tournament_id = tournament.id
    AND projection_revision.roster_id = roster.id
    AND projection_revision.state = 'published'
WHERE tournament.id = $1
FOR UPDATE OF tournament, projection_revision
`

type LockTournamentCancellationAuthorityRow struct {
	ID                   uuid.UUID
	State                string
	PausedFromState      *string
	Revision             int64
	UpdatedAt            pgtype.Timestamptz
	FinishedAt           pgtype.Timestamptz
	RosterID             uuid.UUID
	ProjectionRevisionID uuid.UUID
	ProjectionRevision   int64
}

func (q *Queries) LockTournamentCancellationAuthority(ctx context.Context, tournamentID uuid.UUID) (LockTournamentCancellationAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockTournamentCancellationAuthority, tournamentID)
	var i LockTournamentCancellationAuthorityRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.PausedFromState,
		&i.Revision,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.RosterID,
		&i.ProjectionRevisionID,
		&i.ProjectionRevision,
	)
	return i, err
}

const lockTournamentCancellationOutboxIdempotency = `-- name: LockTournamentCancellationOutboxIdempotency :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::TEXT, 0)
)
`

func (q *Queries) LockTournamentCancellationOutboxIdempotency(ctx context.Context, idempotencyKey string) error {
	_, err := q.db.Exec(ctx, lockTournamentCancellationOutboxIdempotency, idempotencyKey)
	return err
}
