// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament_admin_snapshot.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTournamentAdminSnapshotHeader = `-- name: GetTournamentAdminSnapshotHeader :one
SELECT tournament.id,
    roster.id AS roster_id,
    tournament.preset,
    tournament.name,
    tournament.public_id,
    tournament.planned_roster_size,
    tournament.content_revision,
    tournament.state,
    tournament.paused_from_state,
    tournament.revision AS tournament_revision,
    tournament.created_at AS tournament_created_at,
    tournament.updated_at AS tournament_updated_at,
    tournament.started_at AS tournament_started_at,
    tournament.finished_at AS tournament_finished_at,
    COALESCE(roster_size.participant_count, 0)::INTEGER AS roster_size,
    COALESCE(projection.revision_number, 0)::BIGINT AS projection_revision,
    COALESCE(authority.revision, tournament.revision)::BIGINT AS authority_revision,
    COALESCE(audit.event_count, 0)::BIGINT AS audit_sequence,
    COALESCE(authority.holder_id, '00000000-0000-0000-0000-000000000000'::UUID) AS authority_holder_id,
    COALESCE(authority.lease_id, '00000000-0000-0000-0000-000000000000'::UUID) AS authority_lease_id,
    COALESCE(authority.epoch, 0)::BIGINT AS authority_epoch,
    COALESCE(authority.process_kind, '')::TEXT AS authority_process_kind
FROM tournaments AS tournament
LEFT JOIN rosters AS roster ON roster.tournament_id = tournament.id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::INTEGER AS participant_count
    FROM participants AS participant
    WHERE participant.roster_id = roster.id
        AND participant.attendance <> 'withdrawn'
) AS roster_size ON TRUE
LEFT JOIN LATERAL (
    SELECT revision.revision_number
    FROM projection_revisions AS revision
    WHERE revision.tournament_id = tournament.id
        AND revision.roster_id = roster.id
        AND revision.state = 'published'
    ORDER BY revision.revision_number DESC, revision.id DESC
    LIMIT 1
) AS projection ON TRUE
LEFT JOIN LATERAL (
    SELECT lease.holder_id,
        lease.lease_id,
        lease.epoch,
        lease.process_kind,
        lease.revision
    FROM execution_authority_leases AS lease
    WHERE lease.tournament_id = tournament.id
    ORDER BY lease.revision DESC, lease.created_at DESC, lease.command_id DESC
    LIMIT 1
) AS authority ON TRUE
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS event_count
    FROM audit_events AS event
    WHERE event.tournament_id = tournament.id
) AS audit ON TRUE
WHERE tournament.id = $1
    AND tournament.deleted_at IS NULL
`

type GetTournamentAdminSnapshotHeaderRow struct {
	ID                   uuid.UUID
	RosterID             uuid.NullUUID
	Preset               string
	Name                 string
	PublicID             string
	PlannedRosterSize    int32
	ContentRevision      int64
	State                string
	PausedFromState      *string
	TournamentRevision   int64
	TournamentCreatedAt  pgtype.Timestamptz
	TournamentUpdatedAt  pgtype.Timestamptz
	TournamentStartedAt  pgtype.Timestamptz
	TournamentFinishedAt pgtype.Timestamptz
	RosterSize           int32
	ProjectionRevision   int64
	AuthorityRevision    int64
	AuditSequence        int64
	AuthorityHolderID    uuid.UUID
	AuthorityLeaseID     uuid.UUID
	AuthorityEpoch       int64
	AuthorityProcessKind string
}

func (q *Queries) GetTournamentAdminSnapshotHeader(ctx context.Context, tournamentID uuid.UUID) (GetTournamentAdminSnapshotHeaderRow, error) {
	row := q.db.QueryRow(ctx, getTournamentAdminSnapshotHeader, tournamentID)
	var i GetTournamentAdminSnapshotHeaderRow
	err := row.Scan(
		&i.ID,
		&i.RosterID,
		&i.Preset,
		&i.Name,
		&i.PublicID,
		&i.PlannedRosterSize,
		&i.ContentRevision,
		&i.State,
		&i.PausedFromState,
		&i.TournamentRevision,
		&i.TournamentCreatedAt,
		&i.TournamentUpdatedAt,
		&i.TournamentStartedAt,
		&i.TournamentFinishedAt,
		&i.RosterSize,
		&i.ProjectionRevision,
		&i.AuthorityRevision,
		&i.AuditSequence,
		&i.AuthorityHolderID,
		&i.AuthorityLeaseID,
		&i.AuthorityEpoch,
		&i.AuthorityProcessKind,
	)
	return i, err
}

const listTournamentAdminSnapshotActiveDraftIDs = `-- name: ListTournamentAdminSnapshotActiveDraftIDs :many
SELECT draft.id
FROM drafts AS draft
JOIN series
    ON series.id = draft.series_id
    AND series.roster_id = draft.roster_id
JOIN LATERAL (
    SELECT revision.state
    FROM draft_revisions AS revision
    WHERE revision.draft_id = draft.id
    ORDER BY revision.revision DESC, revision.id DESC
    LIMIT 1
) AS current_revision ON TRUE
JOIN wave_series AS membership ON membership.series_id = series.id
WHERE membership.wave_id = $1
    AND current_revision.state IN ('active', 'paused', 'recovery_required')
ORDER BY draft.created_at, draft.id
`

func (q *Queries) ListTournamentAdminSnapshotActiveDraftIDs(ctx context.Context, waveID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotActiveDraftIDs, waveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotGameAttempts = `-- name: ListTournamentAdminSnapshotGameAttempts :many
SELECT attempt.id,
    attempt.slot_id,
    attempt.series_id,
    attempt.roster_id,
    attempt.attempt_number,
    attempt.state,
    attempt.result_reason,
    attempt.winner_id,
    attempt.result_revision_id,
    attempt.revision,
    attempt.created_at,
    attempt.updated_at,
    attempt.started_at,
    attempt.finished_at
FROM game_attempts AS attempt
JOIN series ON series.id = attempt.series_id
    AND series.roster_id = attempt.roster_id
WHERE series.tournament_id = $1
    AND attempt.roster_id = $2
    AND series.state <> 'superseded'
ORDER BY attempt.series_id, attempt.slot_id, attempt.attempt_number, attempt.id
`

type ListTournamentAdminSnapshotGameAttemptsParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

type ListTournamentAdminSnapshotGameAttemptsRow struct {
	ID               uuid.UUID
	SlotID           uuid.UUID
	SeriesID         uuid.UUID
	RosterID         uuid.UUID
	AttemptNumber    int32
	State            string
	ResultReason     *string
	WinnerID         uuid.NullUUID
	ResultRevisionID uuid.NullUUID
	Revision         int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
}

func (q *Queries) ListTournamentAdminSnapshotGameAttempts(ctx context.Context, arg ListTournamentAdminSnapshotGameAttemptsParams) ([]ListTournamentAdminSnapshotGameAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotGameAttempts, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentAdminSnapshotGameAttemptsRow{}
	for rows.Next() {
		var i ListTournamentAdminSnapshotGameAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.SeriesID,
			&i.RosterID,
			&i.AttemptNumber,
			&i.State,
			&i.ResultReason,
			&i.WinnerID,
			&i.ResultRevisionID,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotGameSlots = `-- name: ListTournamentAdminSnapshotGameSlots :many
SELECT slot.id,
    slot.series_id,
    slot.roster_id,
    slot.slot_number,
    slot.category,
    slot.first_participant_wins_before,
    slot.second_participant_wins_before,
    slot.revision,
    slot.created_at,
    slot.updated_at
FROM game_slots AS slot
JOIN series ON series.id = slot.series_id
    AND series.roster_id = slot.roster_id
WHERE series.tournament_id = $1
    AND slot.roster_id = $2
    AND series.state <> 'superseded'
ORDER BY slot.series_id, slot.slot_number, slot.id
`

type ListTournamentAdminSnapshotGameSlotsParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotGameSlots(ctx context.Context, arg ListTournamentAdminSnapshotGameSlotsParams) ([]GameSlot, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotGameSlots, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameSlot{}
	for rows.Next() {
		var i GameSlot
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.RosterID,
			&i.SlotNumber,
			&i.Category,
			&i.FirstParticipantWinsBefore,
			&i.SecondParticipantWinsBefore,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotPauseClocks = `-- name: ListTournamentAdminSnapshotPauseClocks :many
SELECT clock.pause_id,
    clock.game_attempt_id,
    clock.original_deadline,
    clock.frozen_at,
    clock.frozen_remaining_ms,
    clock.resumed_at,
    clock.resumed_deadline,
    clock.revision,
    clock.created_at,
    clock.updated_at
FROM pause_clocks AS clock
JOIN pauses AS pause ON pause.id = clock.pause_id
WHERE pause.tournament_id = $1
    AND pause.roster_id = $2
ORDER BY clock.game_attempt_id, clock.pause_id
`

type ListTournamentAdminSnapshotPauseClocksParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotPauseClocks(ctx context.Context, arg ListTournamentAdminSnapshotPauseClocksParams) ([]PauseClock, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotPauseClocks, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PauseClock{}
	for rows.Next() {
		var i PauseClock
		if err := rows.Scan(
			&i.PauseID,
			&i.GameAttemptID,
			&i.OriginalDeadline,
			&i.FrozenAt,
			&i.FrozenRemainingMs,
			&i.ResumedAt,
			&i.ResumedDeadline,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotPauses = `-- name: ListTournamentAdminSnapshotPauses :many
SELECT pause.id,
    pause.tournament_id,
    pause.roster_id,
    pause.scope_kind,
    pause.scope_id,
    pause.wave_id,
    pause.series_id,
    pause.game_attempt_id,
    pause.parent_pause_id,
    pause.depth,
    pause.reason,
    pause.paused_from_state,
    pause.state,
    pause.current_revision_id,
    pause.revision,
    pause.started_at,
    pause.resolved_at,
    pause.created_at,
    pause.updated_at
FROM pauses AS pause
WHERE pause.tournament_id = $1
    AND pause.roster_id = $2
ORDER BY pause.depth, pause.started_at, pause.id
`

type ListTournamentAdminSnapshotPausesParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotPauses(ctx context.Context, arg ListTournamentAdminSnapshotPausesParams) ([]Pause, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotPauses, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pause{}
	for rows.Next() {
		var i Pause
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RosterID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.WaveID,
			&i.SeriesID,
			&i.GameAttemptID,
			&i.ParentPauseID,
			&i.Depth,
			&i.Reason,
			&i.PausedFromState,
			&i.State,
			&i.CurrentRevisionID,
			&i.Revision,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotPresence = `-- name: ListTournamentAdminSnapshotPresence :many
SELECT presence.id,
    presence.tournament_id,
    presence.roster_id,
    presence.series_id,
    presence.participant_id,
    presence.state,
    presence.presence_epoch,
    presence.revision,
    presence.connected_at,
    presence.disconnected_at,
    presence.updated_at
FROM presence_states AS presence
JOIN pause_presence_snapshots AS snapshot
    ON snapshot.roster_id = presence.roster_id
    AND snapshot.series_id = presence.series_id
    AND snapshot.participant_id = presence.participant_id
    AND snapshot.presence_state = presence.state
    AND snapshot.presence_epoch = presence.presence_epoch
    AND snapshot.presence_revision = presence.revision
JOIN pauses AS pause ON pause.id = snapshot.pause_id
WHERE snapshot.pause_id = $1
    AND pause.tournament_id = $2
    AND pause.roster_id = $3
    AND snapshot.captured_at = pause.started_at
ORDER BY presence.series_id, presence.participant_id
`

type ListTournamentAdminSnapshotPresenceParams struct {
	PauseID      uuid.UUID
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotPresence(ctx context.Context, arg ListTournamentAdminSnapshotPresenceParams) ([]PresenceState, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotPresence, arg.PauseID, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresenceState{}
	for rows.Next() {
		var i PresenceState
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RosterID,
			&i.SeriesID,
			&i.ParticipantID,
			&i.State,
			&i.PresenceEpoch,
			&i.Revision,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotReconnectCounters = `-- name: ListTournamentAdminSnapshotReconnectCounters :many
SELECT counter.pause_id,
    counter.roster_id,
    counter.participant_id,
    counter.slot_limit,
    counter.slots_used,
    counter.revision,
    counter.created_at,
    counter.updated_at
FROM reconnect_slot_counters AS counter
JOIN pauses AS pause ON pause.id = counter.pause_id
WHERE pause.tournament_id = $1
    AND counter.roster_id = $2
ORDER BY counter.pause_id, counter.participant_id
`

type ListTournamentAdminSnapshotReconnectCountersParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotReconnectCounters(ctx context.Context, arg ListTournamentAdminSnapshotReconnectCountersParams) ([]ReconnectSlotCounter, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotReconnectCounters, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconnectSlotCounter{}
	for rows.Next() {
		var i ReconnectSlotCounter
		if err := rows.Scan(
			&i.PauseID,
			&i.RosterID,
			&i.ParticipantID,
			&i.SlotLimit,
			&i.SlotsUsed,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotReconnectIntervals = `-- name: ListTournamentAdminSnapshotReconnectIntervals :many
SELECT reconnect.id,
    reconnect.pause_id,
    reconnect.roster_id,
    reconnect.series_id,
    reconnect.game_attempt_id,
    reconnect.participant_id,
    reconnect.presence_epoch,
    reconnect.interval_number,
    reconnect.state,
    reconnect.opened_at,
    reconnect.deadline_at,
    reconnect.closed_at,
    reconnect.revision,
    reconnect.created_at,
    reconnect.updated_at,
    reconnect.continuation_number,
    reconnect.continued_from_id,
    reconnect.suspended_by_pause_id
FROM reconnect_intervals AS reconnect
JOIN series
    ON series.id = reconnect.series_id
    AND series.roster_id = reconnect.roster_id
WHERE series.tournament_id = $1
    AND reconnect.roster_id = $2
ORDER BY reconnect.series_id,
    reconnect.participant_id,
    reconnect.interval_number,
    reconnect.continuation_number,
    reconnect.id
`

type ListTournamentAdminSnapshotReconnectIntervalsParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotReconnectIntervals(ctx context.Context, arg ListTournamentAdminSnapshotReconnectIntervalsParams) ([]ReconnectInterval, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotReconnectIntervals, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconnectInterval{}
	for rows.Next() {
		var i ReconnectInterval
		if err := rows.Scan(
			&i.ID,
			&i.PauseID,
			&i.RosterID,
			&i.SeriesID,
			&i.GameAttemptID,
			&i.ParticipantID,
			&i.PresenceEpoch,
			&i.IntervalNumber,
			&i.State,
			&i.OpenedAt,
			&i.DeadlineAt,
			&i.ClosedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContinuationNumber,
			&i.ContinuedFromID,
			&i.SuspendedByPauseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotSeries = `-- name: ListTournamentAdminSnapshotSeries :many
SELECT id,
    tournament_id,
    roster_id,
    first_participant_id,
    second_participant_id,
    format,
    state,
    first_participant_wins,
    second_participant_wins,
    winner_id,
    current_score_revision_id,
    current_result_revision_id,
    revision,
    created_at,
    updated_at,
    started_at,
    finished_at,
    supersedes_series_id,
    superseded_by_series_id,
    superseded_at,
    supersession_reason,
    content_configuration_id,
    content_configuration_revision,
    category_mode,
    effective_categories
FROM series
WHERE tournament_id = $1
    AND roster_id = $2
    AND state <> 'superseded'
ORDER BY created_at, id
`

type ListTournamentAdminSnapshotSeriesParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotSeries(ctx context.Context, arg ListTournamentAdminSnapshotSeriesParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotSeries, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RosterID,
			&i.FirstParticipantID,
			&i.SecondParticipantID,
			&i.Format,
			&i.State,
			&i.FirstParticipantWins,
			&i.SecondParticipantWins,
			&i.WinnerID,
			&i.CurrentScoreRevisionID,
			&i.CurrentResultRevisionID,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SupersedesSeriesID,
			&i.SupersededBySeriesID,
			&i.SupersededAt,
			&i.SupersessionReason,
			&i.ContentConfigurationID,
			&i.ContentConfigurationRevision,
			&i.CategoryMode,
			&i.EffectiveCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotWaveMembers = `-- name: ListTournamentAdminSnapshotWaveMembers :many
SELECT member.wave_id,
    member.participant_id,
    readiness.ready,
    readiness.revision AS readiness_revision,
    series.id AS series_id
FROM wave_members AS member
JOIN waves AS wave
    ON wave.id = member.wave_id
    AND wave.roster_id = member.roster_id
LEFT JOIN wave_readiness AS readiness
    ON readiness.wave_id = member.wave_id
    AND readiness.roster_id = member.roster_id
    AND readiness.participant_id = member.participant_id
LEFT JOIN LATERAL (
    SELECT series.id
    FROM wave_series AS membership
    JOIN series
        ON series.id = membership.series_id
        AND series.tournament_id = membership.tournament_id
        AND series.roster_id = membership.roster_id
    WHERE membership.wave_id = member.wave_id
        AND membership.roster_id = member.roster_id
        AND series.state <> 'superseded'
        AND member.participant_id IN (
            series.first_participant_id,
            series.second_participant_id
        )
    ORDER BY series.id
) AS series ON TRUE
WHERE wave.tournament_id = $1
    AND member.roster_id = $2
ORDER BY member.wave_id, member.participant_id, series.id
`

type ListTournamentAdminSnapshotWaveMembersParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

type ListTournamentAdminSnapshotWaveMembersRow struct {
	WaveID            uuid.UUID
	ParticipantID     uuid.UUID
	Ready             *bool
	ReadinessRevision *int64
	SeriesID          uuid.UUID
}

func (q *Queries) ListTournamentAdminSnapshotWaveMembers(ctx context.Context, arg ListTournamentAdminSnapshotWaveMembersParams) ([]ListTournamentAdminSnapshotWaveMembersRow, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotWaveMembers, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentAdminSnapshotWaveMembersRow{}
	for rows.Next() {
		var i ListTournamentAdminSnapshotWaveMembersRow
		if err := rows.Scan(
			&i.WaveID,
			&i.ParticipantID,
			&i.Ready,
			&i.ReadinessRevision,
			&i.SeriesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentAdminSnapshotWaves = `-- name: ListTournamentAdminSnapshotWaves :many
SELECT wave.id,
    wave.tournament_id,
    wave.revision_id,
    wave.revision,
    wave.state,
    wave.created_at,
    wave.updated_at,
    wave.started_at,
    wave.paused_at,
    wave.closed_at,
    ready_window.id AS ready_window_id,
    ready_window.revision_id AS ready_window_revision_id,
    ready_window.state AS ready_window_state,
    ready_window.opened_at AS ready_window_opened_at,
    ready_window.deadline AS ready_window_deadline,
    ready_window.consumed_at AS ready_window_consumed_at,
    link.bye_participant_id
FROM waves AS wave
LEFT JOIN ready_windows AS ready_window ON ready_window.wave_id = wave.id
LEFT JOIN swiss_wave_links AS link ON link.wave_id = wave.id
WHERE wave.tournament_id = $1
    AND wave.roster_id = $2
ORDER BY wave.created_at, wave.id
`

type ListTournamentAdminSnapshotWavesParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
}

type ListTournamentAdminSnapshotWavesRow struct {
	ID                    uuid.UUID
	TournamentID          uuid.UUID
	RevisionID            uuid.UUID
	Revision              int64
	State                 string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	PausedAt              pgtype.Timestamptz
	ClosedAt              pgtype.Timestamptz
	ReadyWindowID         uuid.NullUUID
	ReadyWindowRevisionID uuid.NullUUID
	ReadyWindowState      *string
	ReadyWindowOpenedAt   pgtype.Timestamptz
	ReadyWindowDeadline   pgtype.Timestamptz
	ReadyWindowConsumedAt pgtype.Timestamptz
	ByeParticipantID      uuid.NullUUID
}

func (q *Queries) ListTournamentAdminSnapshotWaves(ctx context.Context, arg ListTournamentAdminSnapshotWavesParams) ([]ListTournamentAdminSnapshotWavesRow, error) {
	rows, err := q.db.Query(ctx, listTournamentAdminSnapshotWaves, arg.TournamentID, arg.RosterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTournamentAdminSnapshotWavesRow{}
	for rows.Next() {
		var i ListTournamentAdminSnapshotWavesRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.RevisionID,
			&i.Revision,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.PausedAt,
			&i.ClosedAt,
			&i.ReadyWindowID,
			&i.ReadyWindowRevisionID,
			&i.ReadyWindowState,
			&i.ReadyWindowOpenedAt,
			&i.ReadyWindowDeadline,
			&i.ReadyWindowConsumedAt,
			&i.ByeParticipantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
