// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament_reconnect.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceTournamentReconnectSeriesCAS = `-- name: AdvanceTournamentReconnectSeriesCAS :one
UPDATE series
SET revision = revision + 1,
    updated_at = $1
WHERE id = $2
    AND tournament_id = $3
    AND roster_id = $4
    AND revision = $5
    AND state = $6
RETURNING id
`

type AdvanceTournamentReconnectSeriesCASParams struct {
	UpdatedAt        pgtype.Timestamptz
	SeriesID         uuid.UUID
	TournamentID     uuid.UUID
	RosterID         uuid.UUID
	ExpectedRevision int64
	ExpectedState    string
}

// Series is part of the reconnect authority graph.  Every state-preserving
// reconnect mutation still advances its revision when its game advances.
func (q *Queries) AdvanceTournamentReconnectSeriesCAS(ctx context.Context, arg AdvanceTournamentReconnectSeriesCASParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, advanceTournamentReconnectSeriesCAS,
		arg.UpdatedAt,
		arg.SeriesID,
		arg.TournamentID,
		arg.RosterID,
		arg.ExpectedRevision,
		arg.ExpectedState,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const cancelTournamentReconnectIntervalCAS = `-- name: CancelTournamentReconnectIntervalCAS :one
UPDATE reconnect_intervals
SET state = 'cancelled',
    closed_at = $1,
    revision = revision + 1,
    updated_at = $1
WHERE id = $2
    AND pause_id = $3
    AND roster_id = $4
    AND series_id = $5
    AND game_attempt_id = $6
    AND participant_id = $7
    AND presence_epoch = $8
    AND state = 'open'
    AND revision = $9
    AND suspended_by_pause_id IS NULL
RETURNING id,
    pause_id,
    roster_id,
    series_id,
    game_attempt_id,
    participant_id,
    presence_epoch,
    interval_number,
    state,
    opened_at,
    deadline_at,
    closed_at,
    revision,
    created_at,
    updated_at,
    continuation_number,
    continued_from_id,
    suspended_by_pause_id
`

type CancelTournamentReconnectIntervalCASParams struct {
	ClosedAt         pgtype.Timestamptz
	ID               uuid.UUID
	PauseID          uuid.UUID
	RosterID         uuid.UUID
	SeriesID         uuid.UUID
	GameAttemptID    uuid.UUID
	ParticipantID    uuid.UUID
	PresenceEpoch    int64
	ExpectedRevision int64
}

// Terminal cancellation is separate so a continuation predecessor can never
// accidentally gain suspension provenance from this game-level writer.
// Normal Wave pause suspension remains owned by the normal-pause adapter.
func (q *Queries) CancelTournamentReconnectIntervalCAS(ctx context.Context, arg CancelTournamentReconnectIntervalCASParams) (ReconnectInterval, error) {
	row := q.db.QueryRow(ctx, cancelTournamentReconnectIntervalCAS,
		arg.ClosedAt,
		arg.ID,
		arg.PauseID,
		arg.RosterID,
		arg.SeriesID,
		arg.GameAttemptID,
		arg.ParticipantID,
		arg.PresenceEpoch,
		arg.ExpectedRevision,
	)
	var i ReconnectInterval
	err := row.Scan(
		&i.ID,
		&i.PauseID,
		&i.RosterID,
		&i.SeriesID,
		&i.GameAttemptID,
		&i.ParticipantID,
		&i.PresenceEpoch,
		&i.IntervalNumber,
		&i.State,
		&i.OpenedAt,
		&i.DeadlineAt,
		&i.ClosedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContinuationNumber,
		&i.ContinuedFromID,
		&i.SuspendedByPauseID,
	)
	return i, err
}

const closeTournamentReconnectIntervalCAS = `-- name: CloseTournamentReconnectIntervalCAS :one
UPDATE reconnect_intervals
SET state = $1,
    closed_at = $2,
    revision = revision + 1,
    updated_at = $2
WHERE id = $3
    AND pause_id = $4
    AND roster_id = $5
    AND series_id = $6
    AND game_attempt_id = $7
    AND participant_id = $8
    AND presence_epoch = $9
    AND state = 'open'
    AND revision = $10
    AND $1::VARCHAR IN ('reconnected', 'expired')
    AND $2::TIMESTAMPTZ >= opened_at
    AND (
        ($1::VARCHAR = 'reconnected'
            AND $2::TIMESTAMPTZ <= deadline_at)
        OR ($1::VARCHAR = 'expired'
            AND $2::TIMESTAMPTZ >= deadline_at)
    )
RETURNING id,
    pause_id,
    roster_id,
    series_id,
    game_attempt_id,
    participant_id,
    presence_epoch,
    interval_number,
    state,
    opened_at,
    deadline_at,
    closed_at,
    revision,
    created_at,
    updated_at,
    continuation_number,
    continued_from_id,
    suspended_by_pause_id
`

type CloseTournamentReconnectIntervalCASParams struct {
	NextState        string
	ClosedAt         pgtype.Timestamptz
	ID               uuid.UUID
	PauseID          uuid.UUID
	RosterID         uuid.UUID
	SeriesID         uuid.UUID
	GameAttemptID    uuid.UUID
	ParticipantID    uuid.UUID
	PresenceEpoch    int64
	ExpectedRevision int64
}

// Close an open interval as reconnected or expired.  The live presence CAS is
// performed before this statement, satisfying the deferred interval guard.
func (q *Queries) CloseTournamentReconnectIntervalCAS(ctx context.Context, arg CloseTournamentReconnectIntervalCASParams) (ReconnectInterval, error) {
	row := q.db.QueryRow(ctx, closeTournamentReconnectIntervalCAS,
		arg.NextState,
		arg.ClosedAt,
		arg.ID,
		arg.PauseID,
		arg.RosterID,
		arg.SeriesID,
		arg.GameAttemptID,
		arg.ParticipantID,
		arg.PresenceEpoch,
		arg.ExpectedRevision,
	)
	var i ReconnectInterval
	err := row.Scan(
		&i.ID,
		&i.PauseID,
		&i.RosterID,
		&i.SeriesID,
		&i.GameAttemptID,
		&i.ParticipantID,
		&i.PresenceEpoch,
		&i.IntervalNumber,
		&i.State,
		&i.OpenedAt,
		&i.DeadlineAt,
		&i.ClosedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContinuationNumber,
		&i.ContinuedFromID,
		&i.SuspendedByPauseID,
	)
	return i, err
}

const createTournamentReconnectPauseClock = `-- name: CreateTournamentReconnectPauseClock :one
INSERT INTO pause_clocks (pause_id, game_attempt_id, original_deadline, frozen_at,
    frozen_remaining_ms, revision, created_at, updated_at)
VALUES ($1, $2, $3,
    $4, $5, $6,
    $4, $4)
RETURNING pause_id
`

type CreateTournamentReconnectPauseClockParams struct {
	PauseID           uuid.UUID
	GameAttemptID     uuid.UUID
	OriginalDeadline  pgtype.Timestamptz
	FrozenAt          pgtype.Timestamptz
	FrozenRemainingMs int64
	Revision          int64
}

// Read the frozen clock belonging to an active game pause.
// Reconnect freeze advances the domain clock revision together with the game
// authority.  Keep that revision in the durable clock instead of using the
// normal pause helper's fixed initial revision.
func (q *Queries) CreateTournamentReconnectPauseClock(ctx context.Context, arg CreateTournamentReconnectPauseClockParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTournamentReconnectPauseClock,
		arg.PauseID,
		arg.GameAttemptID,
		arg.OriginalDeadline,
		arg.FrozenAt,
		arg.FrozenRemainingMs,
		arg.Revision,
	)
	var pause_id uuid.UUID
	err := row.Scan(&pause_id)
	return pause_id, err
}

const getLatestTournamentReconnectCommandReceipt = `-- name: GetLatestTournamentReconnectCommandReceipt :one
SELECT command_id,
    tournament_id,
    roster_id,
    wave_id,
    mutation_kind,
    participant_id,
    interval_id,
    expected_authority_revision,
    result_authority_revision,
    schema_version,
    record_document,
    recorded_at,
    created_at
FROM reconnect_command_receipts
WHERE tournament_id = $1
    AND roster_id = $2
    AND wave_id = $3
    AND participant_id = $4
ORDER BY created_at DESC, command_id DESC
LIMIT 1
`

type GetLatestTournamentReconnectCommandReceiptParams struct {
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
	WaveID        uuid.UUID
	ParticipantID uuid.UUID
}

// The latest receipt supplies the durable aggregate revision for this
// participant when the current game has already resumed.  The command id is
// a deterministic tie breaker for timestamps supplied by one authoritative
// transaction.
func (q *Queries) GetLatestTournamentReconnectCommandReceipt(ctx context.Context, arg GetLatestTournamentReconnectCommandReceiptParams) (ReconnectCommandReceipt, error) {
	row := q.db.QueryRow(ctx, getLatestTournamentReconnectCommandReceipt,
		arg.TournamentID,
		arg.RosterID,
		arg.WaveID,
		arg.ParticipantID,
	)
	var i ReconnectCommandReceipt
	err := row.Scan(
		&i.CommandID,
		&i.TournamentID,
		&i.RosterID,
		&i.WaveID,
		&i.MutationKind,
		&i.ParticipantID,
		&i.IntervalID,
		&i.ExpectedAuthorityRevision,
		&i.ResultAuthorityRevision,
		&i.SchemaVersion,
		&i.RecordDocument,
		&i.RecordedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestTournamentReconnectResumedClock = `-- name: GetLatestTournamentReconnectResumedClock :one
SELECT pause_clock.pause_id, pause_clock.game_attempt_id, pause_clock.original_deadline, pause_clock.frozen_at, pause_clock.frozen_remaining_ms, pause_clock.resumed_at, pause_clock.resumed_deadline, pause_clock.revision, pause_clock.created_at, pause_clock.updated_at
FROM pause_clocks AS pause_clock
JOIN pauses AS pause
    ON pause.id = pause_clock.pause_id
    AND pause.tournament_id = $1
    AND pause.roster_id = $2
    AND pause.game_attempt_id = $3
JOIN series AS series
    ON series.id = pause.series_id
    AND series.tournament_id = pause.tournament_id
    AND series.roster_id = pause.roster_id
JOIN wave_series AS membership
    ON membership.series_id = series.id
    AND membership.wave_id = $4
    AND membership.roster_id = pause.roster_id
WHERE pause_clock.game_attempt_id = $3
    AND pause_clock.resumed_at IS NOT NULL
    AND pause_clock.resumed_deadline IS NOT NULL
ORDER BY pause_clock.resumed_at DESC, pause_clock.pause_id DESC
LIMIT 1
`

type GetLatestTournamentReconnectResumedClockParams struct {
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
	GameAttemptID uuid.NullUUID
	WaveID        uuid.UUID
}

type GetLatestTournamentReconnectResumedClockRow struct {
	PauseClock PauseClock
}

// After a prior reconnect/resume, the current game clock is the most recent
// resumed clock.  The query is also used as a consistency check for an active
// game that has no currently active pause.
func (q *Queries) GetLatestTournamentReconnectResumedClock(ctx context.Context, arg GetLatestTournamentReconnectResumedClockParams) (GetLatestTournamentReconnectResumedClockRow, error) {
	row := q.db.QueryRow(ctx, getLatestTournamentReconnectResumedClock,
		arg.TournamentID,
		arg.RosterID,
		arg.GameAttemptID,
		arg.WaveID,
	)
	var i GetLatestTournamentReconnectResumedClockRow
	err := row.Scan(
		&i.PauseClock.PauseID,
		&i.PauseClock.GameAttemptID,
		&i.PauseClock.OriginalDeadline,
		&i.PauseClock.FrozenAt,
		&i.PauseClock.FrozenRemainingMs,
		&i.PauseClock.ResumedAt,
		&i.PauseClock.ResumedDeadline,
		&i.PauseClock.Revision,
		&i.PauseClock.CreatedAt,
		&i.PauseClock.UpdatedAt,
	)
	return i, err
}

const getTournamentReconnectCommandReceipt = `-- name: GetTournamentReconnectCommandReceipt :one
SELECT command_id,
    tournament_id,
    roster_id,
    wave_id,
    mutation_kind,
    participant_id,
    interval_id,
    expected_authority_revision,
    result_authority_revision,
    schema_version,
    record_document,
    recorded_at,
    created_at
FROM reconnect_command_receipts
WHERE tournament_id = $1
    AND command_id = $2
`

type GetTournamentReconnectCommandReceiptParams struct {
	TournamentID uuid.UUID
	CommandID    uuid.UUID
}

// Reconnect command receipts are the domain idempotency boundary.  The
// complete record is retained in record_document so a retry can return the
// exact result without re-running a settlement or selecting a lease.
func (q *Queries) GetTournamentReconnectCommandReceipt(ctx context.Context, arg GetTournamentReconnectCommandReceiptParams) (ReconnectCommandReceipt, error) {
	row := q.db.QueryRow(ctx, getTournamentReconnectCommandReceipt, arg.TournamentID, arg.CommandID)
	var i ReconnectCommandReceipt
	err := row.Scan(
		&i.CommandID,
		&i.TournamentID,
		&i.RosterID,
		&i.WaveID,
		&i.MutationKind,
		&i.ParticipantID,
		&i.IntervalID,
		&i.ExpectedAuthorityRevision,
		&i.ResultAuthorityRevision,
		&i.SchemaVersion,
		&i.RecordDocument,
		&i.RecordedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertTournamentReconnectCommandReceipt = `-- name: InsertTournamentReconnectCommandReceipt :one
INSERT INTO reconnect_command_receipts (
    command_id,
    tournament_id,
    roster_id,
    wave_id,
    mutation_kind,
    participant_id,
    interval_id,
    expected_authority_revision,
    result_authority_revision,
    schema_version,
    record_document,
    recorded_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::UUID,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING command_id
`

type InsertTournamentReconnectCommandReceiptParams struct {
	CommandID                 uuid.UUID
	TournamentID              uuid.UUID
	RosterID                  uuid.UUID
	WaveID                    uuid.UUID
	MutationKind              string
	ParticipantID             uuid.UUID
	IntervalID                uuid.NullUUID
	ExpectedAuthorityRevision int64
	ResultAuthorityRevision   int64
	SchemaVersion             int16
	RecordDocument            []byte
	RecordedAt                pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
}

// Receipt persistence is intentionally last in CommitMutation.  The primary
// key makes a concurrent command with the same identity fail atomically; the
// caller maps that unique violation to a retry conflict.
func (q *Queries) InsertTournamentReconnectCommandReceipt(ctx context.Context, arg InsertTournamentReconnectCommandReceiptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTournamentReconnectCommandReceipt,
		arg.CommandID,
		arg.TournamentID,
		arg.RosterID,
		arg.WaveID,
		arg.MutationKind,
		arg.ParticipantID,
		arg.IntervalID,
		arg.ExpectedAuthorityRevision,
		arg.ResultAuthorityRevision,
		arg.SchemaVersion,
		arg.RecordDocument,
		arg.RecordedAt,
		arg.CreatedAt,
	)
	var command_id uuid.UUID
	err := row.Scan(&command_id)
	return command_id, err
}

const listTournamentReconnectCommandReceipts = `-- name: ListTournamentReconnectCommandReceipts :many
SELECT command_id,
    tournament_id,
    roster_id,
    wave_id,
    mutation_kind,
    participant_id,
    interval_id,
    expected_authority_revision,
    result_authority_revision,
    schema_version,
    record_document,
    recorded_at,
    created_at
FROM reconnect_command_receipts
WHERE tournament_id = $1
    AND roster_id = $2
    AND wave_id = $3
ORDER BY created_at DESC, command_id DESC
`

type ListTournamentReconnectCommandReceiptsParams struct {
	TournamentID uuid.UUID
	RosterID     uuid.UUID
	WaveID       uuid.UUID
}

// Receipt persistence is intentionally last in CommitMutation.  The primary
// key makes a concurrent command with the same identity fail atomically; the
// caller maps that unique violation to a retry conflict.
func (q *Queries) ListTournamentReconnectCommandReceipts(ctx context.Context, arg ListTournamentReconnectCommandReceiptsParams) ([]ReconnectCommandReceipt, error) {
	rows, err := q.db.Query(ctx, listTournamentReconnectCommandReceipts, arg.TournamentID, arg.RosterID, arg.WaveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconnectCommandReceipt{}
	for rows.Next() {
		var i ReconnectCommandReceipt
		if err := rows.Scan(
			&i.CommandID,
			&i.TournamentID,
			&i.RosterID,
			&i.WaveID,
			&i.MutationKind,
			&i.ParticipantID,
			&i.IntervalID,
			&i.ExpectedAuthorityRevision,
			&i.ResultAuthorityRevision,
			&i.SchemaVersion,
			&i.RecordDocument,
			&i.RecordedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTournamentReconnectGamePause = `-- name: LockTournamentReconnectGamePause :one
SELECT pause.id, pause.tournament_id, pause.roster_id, pause.scope_kind, pause.scope_id, pause.wave_id, pause.series_id, pause.game_attempt_id, pause.parent_pause_id, pause.depth, pause.reason, pause.paused_from_state, pause.state, pause.current_revision_id, pause.revision, pause.started_at, pause.resolved_at, pause.created_at, pause.updated_at
FROM pauses AS pause
JOIN series AS series
    ON series.id = pause.series_id
    AND series.tournament_id = pause.tournament_id
    AND series.roster_id = pause.roster_id
JOIN wave_series AS membership
    ON membership.series_id = series.id
    AND membership.wave_id = $1
    AND membership.roster_id = pause.roster_id
WHERE pause.tournament_id = $2
    AND pause.roster_id = $3
    AND pause.game_attempt_id = $4
    AND pause.scope_kind = 'game_attempt'
    AND pause.parent_pause_id IS NULL
    AND pause.state = 'active'
ORDER BY pause.started_at DESC, pause.id DESC
LIMIT 1
FOR UPDATE
`

type LockTournamentReconnectGamePauseParams struct {
	WaveID        uuid.UUID
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
	GameAttemptID uuid.NullUUID
}

type LockTournamentReconnectGamePauseRow struct {
	Pause Pause
}

// Load the one game pause that can own reconnect intervals.  A graph scope
// may contain several games; the adapter rejects that ambiguity before using
// this row, so no arbitrary active pause is ever selected.
func (q *Queries) LockTournamentReconnectGamePause(ctx context.Context, arg LockTournamentReconnectGamePauseParams) (LockTournamentReconnectGamePauseRow, error) {
	row := q.db.QueryRow(ctx, lockTournamentReconnectGamePause,
		arg.WaveID,
		arg.TournamentID,
		arg.RosterID,
		arg.GameAttemptID,
	)
	var i LockTournamentReconnectGamePauseRow
	err := row.Scan(
		&i.Pause.ID,
		&i.Pause.TournamentID,
		&i.Pause.RosterID,
		&i.Pause.ScopeKind,
		&i.Pause.ScopeID,
		&i.Pause.WaveID,
		&i.Pause.SeriesID,
		&i.Pause.GameAttemptID,
		&i.Pause.ParentPauseID,
		&i.Pause.Depth,
		&i.Pause.Reason,
		&i.Pause.PausedFromState,
		&i.Pause.State,
		&i.Pause.CurrentRevisionID,
		&i.Pause.Revision,
		&i.Pause.StartedAt,
		&i.Pause.ResolvedAt,
		&i.Pause.CreatedAt,
		&i.Pause.UpdatedAt,
	)
	return i, err
}

const lockTournamentReconnectPauseClock = `-- name: LockTournamentReconnectPauseClock :one
SELECT pause_clock.pause_id, pause_clock.game_attempt_id, pause_clock.original_deadline, pause_clock.frozen_at, pause_clock.frozen_remaining_ms, pause_clock.resumed_at, pause_clock.resumed_deadline, pause_clock.revision, pause_clock.created_at, pause_clock.updated_at
FROM pause_clocks AS pause_clock
JOIN pauses AS pause
    ON pause.id = pause_clock.pause_id
    AND pause.tournament_id = $1
    AND pause.roster_id = $2
    AND pause.game_attempt_id = $3
JOIN series AS series
    ON series.id = pause.series_id
    AND series.tournament_id = pause.tournament_id
    AND series.roster_id = pause.roster_id
JOIN wave_series AS membership
    ON membership.series_id = series.id
    AND membership.wave_id = $4
    AND membership.roster_id = pause.roster_id
WHERE pause_clock.pause_id = $5
    AND pause_clock.game_attempt_id = $3
FOR UPDATE OF pause_clock
`

type LockTournamentReconnectPauseClockParams struct {
	TournamentID  uuid.UUID
	RosterID      uuid.UUID
	GameAttemptID uuid.NullUUID
	WaveID        uuid.UUID
	PauseID       uuid.UUID
}

type LockTournamentReconnectPauseClockRow struct {
	PauseClock PauseClock
}

// Read the frozen clock belonging to an active game pause.
func (q *Queries) LockTournamentReconnectPauseClock(ctx context.Context, arg LockTournamentReconnectPauseClockParams) (LockTournamentReconnectPauseClockRow, error) {
	row := q.db.QueryRow(ctx, lockTournamentReconnectPauseClock,
		arg.TournamentID,
		arg.RosterID,
		arg.GameAttemptID,
		arg.WaveID,
		arg.PauseID,
	)
	var i LockTournamentReconnectPauseClockRow
	err := row.Scan(
		&i.PauseClock.PauseID,
		&i.PauseClock.GameAttemptID,
		&i.PauseClock.OriginalDeadline,
		&i.PauseClock.FrozenAt,
		&i.PauseClock.FrozenRemainingMs,
		&i.PauseClock.ResumedAt,
		&i.PauseClock.ResumedDeadline,
		&i.PauseClock.Revision,
		&i.PauseClock.CreatedAt,
		&i.PauseClock.UpdatedAt,
	)
	return i, err
}

const lockTournamentReconnectPausePresenceSnapshots = `-- name: LockTournamentReconnectPausePresenceSnapshots :many
SELECT snapshot.pause_id,
    snapshot.roster_id,
    snapshot.series_id,
    snapshot.participant_id,
    snapshot.presence_state,
    snapshot.presence_epoch,
    snapshot.presence_revision,
    snapshot.captured_at,
    snapshot.created_at
FROM pause_presence_snapshots AS snapshot
WHERE snapshot.pause_id = $1
    AND snapshot.roster_id = $2
    AND snapshot.series_id = $3
ORDER BY snapshot.participant_id
FOR UPDATE OF snapshot
`

type LockTournamentReconnectPausePresenceSnapshotsParams struct {
	PauseID  uuid.UUID
	RosterID uuid.UUID
	SeriesID uuid.UUID
}

// Resume decisions must cite immutable pre-mutation presence evidence.  The
// live rows have already advanced to the reconnecting state by the time the
// decision is appended.
func (q *Queries) LockTournamentReconnectPausePresenceSnapshots(ctx context.Context, arg LockTournamentReconnectPausePresenceSnapshotsParams) ([]PausePresenceSnapshot, error) {
	rows, err := q.db.Query(ctx, lockTournamentReconnectPausePresenceSnapshots, arg.PauseID, arg.RosterID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PausePresenceSnapshot{}
	for rows.Next() {
		var i PausePresenceSnapshot
		if err := rows.Scan(
			&i.PauseID,
			&i.RosterID,
			&i.SeriesID,
			&i.ParticipantID,
			&i.PresenceState,
			&i.PresenceEpoch,
			&i.PresenceRevision,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTournamentReconnectPresenceCAS = `-- name: UpdateTournamentReconnectPresenceCAS :one
UPDATE presence_states
SET state = $1,
    connected_at = CASE
        WHEN $1::VARCHAR = 'connected' THEN $2::TIMESTAMPTZ
        ELSE connected_at
    END,
    presence_epoch = presence_epoch + 1,
    revision = revision + 1,
    disconnected_at = CASE
        WHEN $1::VARCHAR = 'connected' THEN NULL
        ELSE $2::TIMESTAMPTZ
    END,
    updated_at = $2
WHERE id = $3
    AND tournament_id = $4
    AND roster_id = $5
    AND series_id = $6
    AND participant_id = $7
    AND state = $8
    AND presence_epoch = $9
    AND revision = $10
    AND $1::VARCHAR IN ('connected', 'disconnected')
RETURNING id,
    tournament_id,
    roster_id,
    series_id,
    participant_id,
    state,
    presence_epoch,
    revision,
    connected_at,
    disconnected_at,
    updated_at
`

type UpdateTournamentReconnectPresenceCASParams struct {
	NextState        string
	UpdatedAt        pgtype.Timestamptz
	ID               uuid.UUID
	TournamentID     uuid.UUID
	RosterID         uuid.UUID
	SeriesID         uuid.UUID
	ParticipantID    uuid.UUID
	ExpectedState    string
	ExpectedEpoch    int64
	ExpectedRevision int64
}

// Presence updates are guarded by the identity, epoch, revision, and prior
// state.  The trigger on presence_states enforces the same transition shape;
// this predicate is the application-visible CAS result.
func (q *Queries) UpdateTournamentReconnectPresenceCAS(ctx context.Context, arg UpdateTournamentReconnectPresenceCASParams) (PresenceState, error) {
	row := q.db.QueryRow(ctx, updateTournamentReconnectPresenceCAS,
		arg.NextState,
		arg.UpdatedAt,
		arg.ID,
		arg.TournamentID,
		arg.RosterID,
		arg.SeriesID,
		arg.ParticipantID,
		arg.ExpectedState,
		arg.ExpectedEpoch,
		arg.ExpectedRevision,
	)
	var i PresenceState
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RosterID,
		&i.SeriesID,
		&i.ParticipantID,
		&i.State,
		&i.PresenceEpoch,
		&i.Revision,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}
